### ISSUE TITLE
Fatal error when deleting field via the API that doesn't exist

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1007]
```
Catchable fatal error: Argument 1 passed to Fields::___delete() must implement interface Saveable, null given in /wire/core/Fields.php on line 265
Recoverable Fatal Error: Argument 1 passed to Fields::___delete() must implement interface Saveable, null given (line 265 of /wire/core/Fields.php) 
This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged.
```

At least I think that is the reason I got this error. I went to uninstall the SchedulPages module, but I had previously already uninstalled the field that it is trying the delete with these lines:
```
$field = wire('fields')->get('publish_from');
wire('fields')->delete($field);
```

I think perhaps the PW core should handle this and proceed with a simple warning: "Field does not exist", rather than giving a fatal error.

**Comment by ryancramerdesign** [comment]
I don't think we can change that error message because that's coming from passing the wrong argument type to a method where PHP is enforcing the type rather than PW (Saveable interface is type hinted in the method declaration, which is a good thing).

**Comment by adrianbj** [comment]
Right - gotcha! 

It's a shame you couldn't return an empty field object from the 
```
$fields->get('fieldname'); 
```
if it doesn't exist, but that would cause multiple other problems throughout PW, so I guess there isn't really a solution other than checking if it exists before trying to delete.

I guess I should file a bug with SchedulePages asking them to do that check.
