### ISSUE TITLE
ProcessPageAdd descriptions put template label lowercase

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1008]
The descriptions when you can add page to multiple parents and there's a select to select the parent.

I wish this lines L81 L82 would not have strtolower on the template label 

```
$f->label = sprintf($this->_('Where do you want to add the new %s?'), strtolower($templateLabel)); 
$f->description = sprintf($this->_('Please select a parent %s page below:'), strtolower($parentTemplateLabel)); 
```

instead maybe also while at it, make the template label in the translation string bold/emphasis/quotes to better understand it's a label of a template?

```
$f->label = sprintf($this->_('Where do you want to add the new "%s"?'), $templateLabel); 
$f->description = sprintf($this->_('Please select a parent "%s" page below:'), $parentTemplateLabel); 
```

**Comment by somatonic** [comment]
Maybe one can add quotes like

$f->label = sprintf($this->_('Where do you want to add the new %s?'), "'$templateLabel'");
		$f->description = sprintf($this->_('Please select a parent %s page below:'), "'$parentTemplateLabel'");

To avoid the need for translation packs to update that string?

**Comment by ryancramerdesign** [comment]
I actually have no idea why that strtolower() call is on those two lines, it doesn't seem to make any sense.  I must have had some reason, but it escapes me now. I'm removing that. and quoting them as you suggested. This will appear in this week's commits.
