### ISSUE TITLE
image warnings for long deleted pages

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1010]
Since the last dev updates and after activating image management for textareas I get this sort of error messages. 
 Original image file on /trash/1495_block-37/ no longer exists, unable to create new variation (123.png)
 Original image file on /blocks-storage/block-37/ no longer exists, unable to create new variation (123.png) 
The pages they refer to are long gone (trashed+emptied trash). They were originally "child" pages of a pagetable field. I have no idea what PW wants me to do to fix it. - Since the pages are gone there obviously is no orignal image and definitely no need for resizing it.

**Comment by tbba** [comment]
...switching image handling off, saving the field and then switching image handling back on worked as a workaround, by the way.

**Comment by ryancramerdesign** [comment]
What it's telling you is that you've got a page still active in the system that is referring to an image that no longer exists (in in your case, the page no longer exists either). If you look in your Setup > Logs > markup-aa-errors you may be able to narrow in on which page is referring to the image that no longer exists.
