### ISSUE TITLE
Autocomplete Page field doesn't work since update

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1012]
It doesn't find pages when entering. It was working fine and last I did update the core from .19 or .20 to .22.

I get this error in the console:

ncaught TypeError: Cannot read property 'length' of undefinedJqueryCore.js?v=183:2 v.extend.mapInputfieldPageAutocomplete.js?v=104:87 (anonymous function)JqueryCore.js?v=183:2 v.Callbacks.lJqueryCore.js?v=183:2 v.Callbacks.c.fireWithJqueryCore.js?v=183:2 TJqueryCore.js?v=183:2 v.support.ajax.v.ajaxTransport.send.rXMLHttpRequest.send (async)JqueryCore.js?v=183:2 v.support.ajax.v.ajaxTransport.sendJqueryCore.js?v=183:2 v.extend.ajaxJqueryCore.js?v=183:2 v.each.v.(anonymous function)JqueryCore.js?v=183:2 v.extend.getJSONInputfieldPageAutocomplete.js?v=104:71 $input.autocomplete.sourceJqueryUI.js?v=194:6 e.widget._searchJqueryUI.js?v=194:6 (anonymous function)JqueryUI.js?v=194:6 e.widget.searchJqueryUI.js?v=194:6 (anonymous function)JqueryUI.js?v=194:6 (anonymous function)JqueryUI.js?v=194:6 isetTimeout (async)JqueryUI.js?v=194:6 t.Widget._delayJqueryUI.js?v=194:6 e.widget._searchTimeoutJqueryUI.js?v=194:6 (anonymous function)JqueryUI.js?v=194:6 e.widget._create._on.inputJqueryUI.js?v=194:6 hJqueryCore.js?v=183:2 v.event.dispatchJqueryCore.js?v=183:2 v.event.add.o.handle.u

**Comment by somatonic** [comment]
The error returned is {"error":true,"message":"Field does not exist: it"}

What could this be... it?

**Comment by adrianbj** [comment]
The error returned is {"error":true,"message":"Field does not exist: it"}

I got this exact same error the other day, but I can't remember for what and I can't find where I reported it. I haven't used an autocomplete field in a while though. Anyway, maybe someone else will see where I reported and connect the dots :)

**Comment by ryancramerdesign** [comment]
Since this is the second time this one has been reported, I've gone ahead and added it to our exclusion list (in last commit). I believe it's occurring because some autoload module must be accessing $input->get() before ProcessPageView does, because ProcessPageView removes/unsets that variable. Of course, it should be fine for an autoload module to access $input->get(), which is why the exclusion is necessary.

**Comment by somatonic** [comment]
Great thanks for the quick fix, I just upgraded a site that gone live 5 min ago. WOrked perfectly.

http://www.1815.ch ;)
