### ISSUE TITLE
I suddenly get an error on creating .PagefilesManager dirs

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1013]
I'm getting lots of errors 
Error: Exception: Kann temporäres Verzeichnis nicht erstellen - /home/www-data/1815.ch/site/assets/cache/WireTempDir/.PagefilesManager120115/1/ (in /home/www-data/1815.ch/wire/core/WireTempDir.php line 111)

**Comment by somatonic** [comment]
There's nothing changed server side with permissions, but I updgraded PW a couple hours ago when it started appearing.

This is from the trace, it can't create dirs but when I look on server there's dirs created and deleted all the time.

Error: Exception: Kann temporäres Verzeichnis nicht erstellen - /home/www-data/1815.ch/site/assets/cache/WireTempDir/.PagefilesManager120115/1/ (in /home/www-data/1815.ch/wire/core/WireTempDir.php line 111) #0 /home/www-data/1815.ch/wire/core/PagefilesManager.php(473): WireTempDir->get() #1 /home/www-data/1815.ch/wire/core/Pageimage.php(355): PagefilesManager->getTempPath() #2 /home/www-data/1815.ch/wire/core/Pageimage.php(245): Pageimage->___size(320, 170, Array) #3 /home/www-data/1815.ch/site/templates/sidebar-element.php(34): Pageimage->size(320, 170) #4 /home/www-data/1815.ch/wire/core/TemplateFile.php(169): require('/home/www-data/...') #5 [internal function]: TemplateFile->___render() #6 /home/www-data/1815.ch/wire/core/Wire.php(366): call_user_func_array(Array, Array) #7 /home/www-data/1815.ch/wire/core/Wire.php(321): Wire->runHooks('render', Array) #8 /home/www-data/1815.ch/wire/modules/PageRender.module(356): Wire->__call('render', Array) #9 /home/www-data/1815.ch/wire/modules/PageRender.module(356): Temp

and on another page

Error: Exception: Kann temporäres Verzeichnis nicht erstellen - /home/www-data/1815.ch/site/assets/cache/WireTempDir/.PagefilesManager128228/2/ (in /home/www-data/1815.ch/wire/core/WireTempDir.php line 111) #0 /home/www-data/1815.ch/wire/core/PagefilesManager.php(473): WireTempDir->get() #1 /home/www-data/1815.ch/wire/core/Pageimage.php(355): PagefilesManager->getTempPath() #2 /home/www-data/1815.ch/wire/core/Pageimage.php(245): Pageimage->___size(650, 0, Array) #3 /home/www-data/1815.ch/site/templates/views/article/article-topstory.php(29): Pageimage->size(650, 0, Array) #4 /home/www-data/1815.ch/site/templates/common-article.php(12): include('/home/www-data/...') #5 /home/www-data/1815.ch/site/templates/news-article.php(15): include('/home/www-data/...') #6 /home/www-data/1815.ch/wire/core/TemplateFile.php(169): require('/home/www-data/...') #7 [internal function]: TemplateFile->___render() #8 /home/www-data/1815.ch/wire/core/Wire.php(366): call_user_func_array(Array, Array) #9 /home/www-data/1815.ch/wire/core/W

**Comment by processwired** [comment]
I'm facing the same on some of my sites for a while now. If I remember correctly, the errors appear since approximately 2.5.8. My observations are that is has something to do with the setting `$config->pagefileSecure = true` in config.php.

**Comment by ryancramerdesign** [comment]
Is this on a live site with lots of traffic and needing to create a lot of images in a short period of time? The exception looks like a potential race condition where two requests executed at the some time are trying to do the same thing. This probably does not need to be a fatal exception, so I should update this to make it retry a few times before it gives up and throws an exception. Are you continuing to observe it a lot, or has it slowed down (or even stopped appearing) in your logs? Have you observed it during any live requests, or is it happening with API side code separately from web requests?

**Comment by somatonic** [comment]
Yes on a a live site with lot of traffic there was like 1500 active sessions, and there's also pagefileSecure enabled. But it looks like it is better now and only occuring like 10-20 times an hours maybe, before it was worse.

**Comment by somatonic** [comment]
This project is also using the $config->pagefileExtendedPaths = true;

**Comment by ryancramerdesign** [comment]
Does the issue on those pages resolve itself, or are you seeing broken images anywhere?

**Comment by tbba** [comment]
I also have funny errors with a client's site. This site has medium traffic (600 visitors a day condensed to working hours). Maybe the error is related:

Error: 
Exception: Kann temporäres Verzeichnis nicht erstellen - /clientwebsite/site/assets/cache/WireTempDir/.PagefilesManager1088/2/ 
(in /clientwebsite/wire/core/WireTempDir.php line 111)

Maybe that information is important:
If I remember I had activated during launch I had $config->pagefileExtendedPaths = true; and deactivated it later for the newer pages when I found it makes more trouble than it solves for me. 
There might be a side effect now.

So in case you need samples to investigate further, here is another candidate for testing :-)

**Comment by somatonic** [comment]
I'm running pageFileExtendedPaths without problems.

And I can't see any corrupt images. But I'm asking why does it need to create temp dirs on each request/view?

**Comment by somatonic** [comment]
We now have 1815.ch online and we get this error every couple minutes. While opening a front-end page, the page exits with the error. I sent you a screenshot to your email with the error I seen the first time for myself on the front-end.

$config->pagefileSecure = true;
$config->pageFileExtendedPaths = true;

What more infos do you need?

**Comment by somatonic** [comment]
The images on that site are done via reference. So adding images to an article is done through a Fieldtype I developed (similar as Page field) to select an Page that has the image stored. The image field on those pages are Croppable Images field.

**Comment by ryancramerdesign** [comment]
I'm not sure I know enough about your custom Fieldtype or CroppableImage to say whether those are possibly involved in the issue. But we do have enough info to test something out. Though since I'm not seeing the issue here, I think we need you to test it out. Based on the error message, I think that we're seeing a race condition, possibly combined with a file system cache giving the wrong result (and the reason for PHP's clearstatcache() function to exist). If you look at /wire/core/WireTempDir.php you'll see the following:
````````
// create temp dir
if(!wireMkdir($tempDir, true)) {
    throw new WireException($this->_('Unable to create temp dir') . " - $tempDir");
}
``````````
Try replacing that with the following, which goes in for another try after clearing the stat cache, before throwing an exception. If my guess is right, this could fix it. 
````````````
// create temp dir
if(!wireMkdir($tempDir, true)) {
	clearstatcache();
	if(!is_dir($tempDir) && !wireMkdir($tempDir, true)) {
		throw new WireException($this->_('Unable to create temp dir') . " - $tempDir");
	}
}
``````````
Btw, I don't currently think that pagefileSecure or pageFileExtendedPaths is the cause for this issue. I can see looking at the debug trace in your screenshot that the requester of the temp dir is Pageimage::size(), and tracking through all the code involved in the debug trace doesn't seem to be connected with the pagefileSecure or pageFileExtendedPaths.

**Comment by somatonic** [comment]
My custom field type is here https://github.com/somatonic/FieldtypeImagesSelect

Thanks so much for the code. I tried different thing yesterday. Some other problems I solved first and thought that might be involved, but it isn’t.

So after changing the WireTempDir with the code you sent, it seems to make a difference in that i doesn’t happen every minute but like 1-2 times an hour. So it seems that it works in some cases and some not.

The site has 200-600, and even more at times, users browsing the site. On the dev install on same server this never happens.

I’m not sure what to try next. Anything that would help you, I can give you access to the site if you want.

Thanks so much!

Soma

Am 18.03.2015 um 22:28 schrieb Ryan Cramer <notifications@github.com>:

**Comment by ryancramerdesign** [comment]
If it's gone from occurring every second to occurring only 1-2 times an
hour, it sounds like we're on the right track. Do the instances where it
occurs seem to coincide with new images being added to the system? Here's
what I think is going on:

1. User uploads image to site (or image gets added by some other means)
2. Two page views (or more) occur to the page the image was added to, at
the same time. (or some other page that happens to use the image)
3. The page being viewed by multiple people at the same time contains an
image size() call, which creates an image at an alternate size.
4. Each of the 2+ requests races to see who can create the resized images
first.
5. The loser(s) are beat in the race condition, causing them to error out.

Does this sound like what's occurring on the site? If so, I think the
answer is that the exception needs to be caught in Pageimage::size or
somewhere in that process, and it needs to make multiple attempts (rather
than one) before it gives up.

**Comment by somatonic** [comment]
Thanks. But the element in question is are pages with images that are created long time ago. They aren't edited at all. There's no size happening as the image is already there.


Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Ryan Cramer <notifications@github.com> 
Datum:19.03.2015  17:40  (GMT+01:00) 
An: ryancramerdesign/ProcessWire <ProcessWire@noreply.github.com> 
Cc: Philipp Urlich <philipp@urlich.ch> 
Betreff: Re: [ProcessWire] I suddenly get an error on creating
  .PagefilesManager dirs (#1013) 

If it's gone from occurring every second to occurring only 1-2 times an
hour, it sounds like we're on the right track. Do the instances where it
occurs seem to coincide with new images being added to the system? Here's
what I think is going on:

1. User uploads image to site (or image gets added by some other means)
2. Two page views (or more) occur to the page the image was added to, at
the same time. (or some other page that happens to use the image)
3. The page being viewed by multiple people at the same time contains an
image size() call, which creates an image at an alternate size.
4. Each of the 2+ requests races to see who can create the resized images
first.
5. The loser(s) are beat in the race condition, causing them to error out.

Does this sound like what's occurring on the site? If so, I think the
answer is that the exception needs to be caught in Pageimage::size or
somewhere in that process, and it needs to make multiple attempts (rather
than one) before it gives up.

**Comment by ryancramerdesign** [comment]
That's interesting that that are images that have been there awhile. That
led me to look in some other places and I think I may have isolated the
issue now. I'll commit some updates to GitHub shortly.

**Comment by ryancramerdesign** [comment]
I just pushed an update that includes a potential fix. However, the dev branch updates were pretty broad in scope (outside of this issue), so if this is that live/busy site you've been working on, you may want to test the new version on a staging server before going live. Or for a quick fix, just replace the one file that affects this issue, which is /wire/core/Pageimage.php

**Comment by somatonic** [comment]
Thanks Ryan. I haven't come to test this out as I first have to test the dev. As the complexity demand a whole lot of testing this will take a while. I will consider the option to replace the file so thanks for the mention!

Currently the hot fix reduced the occurrence a lot, 1-2 an hour.

**Comment by somatonic** [comment]
I went ahead an tested with latest dev. It's currently on live and there was no error anymore since 12 hours. Looks like it's fixed. Thanks!

**Comment by ryancramerdesign** [comment]
Good to hear, thanks!

**Comment by processwired** [comment]
Yes, I can confirm that it doesn't throw any of these error messages for a few days now. Great! Thanks, Ryan :-)
