### ISSUE TITLE
Installation fails on latest dev

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1014]
Error: Call to a member function execute() on null (line 240 of /xxxxx/xxxx/xx/xxxxxxxx/xxxxxxx/xxxxx/index.php) 
This error message was shown because /install.php still exists. Error has been logged.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate, so need to ask questions. When did the error occur during the install process? What screen did you see immediately before you saw the error?

**Comment by ryancramerdesign** [comment]
If anyone else sees this error please reply here too.

**Comment by kalmarlansmuseum** [comment]
Just after i filled out the intallation settings.

**Comment by cstevensjr** [comment]
What version of PHP and profile did you install with?  I ask because I will attempt to use the same profile and do a test install.

**Comment by kalmarlansmuseum** [comment]
PHP Version 5.4.38
Blank profile

I installed the master branch and every thing installed as normal.

**Comment by cstevensjr** [comment]
I was able to recreate the issue using PHP 5.4.37 and latest Dev (2.5.22)

![dev22-install](https://cloud.githubusercontent.com/assets/7488817/6617951/58a9f358-c87b-11e4-86fd-e14cb9eb6df1.png)

**Comment by mike-anthony** [comment]
Same thing for me with blank profile... PHP 5.5.11, MySQL 5.0.11-dev.

**Comment by ryancramerdesign** [comment]
The blank profile was the thing I missed before. Installed default profile fine, but blank profile got me the same error message. Thanks, I've got enough to go on now and should be able to get this figured out today.

**Comment by ryancramerdesign** [comment]
Thanks guys, I think I got this one fixed.

**Comment by cstevensjr** [comment]
Confirmed. I just tested again (blank profile) and everything installed without any issues.

**Comment by ryancramerdesign** [comment]
Thanks! Glad that seems to fix it.
