### ISSUE TITLE
Undefined variable: blankIsObject in PageFinder due to missing isset()

### ISSUE THREAD

**Issue by Deltanic** [ryancramerdesign/ProcessWire#1016]
~~ProcessWire throws a notice in PageFinder when the $blankValue is not an object. I'm not exactly sure what causes this notice to appear for us, but it's easily fixable by simply adding an isset(). It's certainly one of our modules, but ProcessWire clearly made a mistake here for not ensuring the variable exists.~~

~~The first time the error gets thrown at line 752 of PageFinder.php @ dev. Line 788 throws the notice again, for the same reason.~~

~~We are running ProcessWire 2.5.21 dev.~~

```php
750: $blankValue = $field->type->getBlankValue(new NullPage(), $field, $value);
751: if(is_object($blankValue)) $blankIsObject = true; 
752: if($blankIsObject) $blankValue = '';
[...]
788: } else if($blankIsObject) {
```

Edit: Oh hey, I just noticed this was fixed a few days ago. Our installation is a little older. Nevermind then!

**Comment by ryancramerdesign** [comment]
You must have grabbed the dev branch sometime in the brief period where that issue was there. Glad you found the updated version. Thanks for reporting it though.
