### ISSUE TITLE
Option to render InputfieldButton as modal opening link

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1022]
We do have a great way to enable modal window usage with `$this->wire('modules')->get('JqueryUI')->use('modal');`, but InputfieldButton does not play well for opening these.

**Comment by ryancramerdesign** [comment]
I have updated it to support `<button>` in addition to `<a>`, and this will appear in this weeks commits. To use, just give the button a `pw-modal` class. When using a button, it will pull the href attribute from an `<a>` that wraps the button. If no `<a>` wraps the button, it will pull from a `data-href` attribute on the button itself.

**Comment by LostKobrakai** [comment]
Great. At least for me this seems more intuitive than using a link.
