### ISSUE TITLE
CKE button maximise

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1024]
I have a pagetable field which opens a page in a modal view.
I edit a CKE text field.
If I use the button Maximise (which is available if CKE is not inline mode) and then
click LINK, the link modal is behind the Maximise view and is not visible until I shrink down the maximized view to normal.

This is probably just a to low z-index?

**Comment by ryancramerdesign** [comment]
Thanks, I can reproduce that too after adding a Maximize button to my toolbar. Though we're not actually setting the values for any z-indexes here. CKEditor and jQuery UI are doing that themselves. But I'm pretty sure I can find a way to make the jQuery UI modals up their z-index somehow or another. I will look into it.
