### ISSUE TITLE
WireHttp: Options aren't parsed when using downloadCURL

### ISSUE THREAD

**Issue by felixwahner** [ryancramerdesign/ProcessWire#1027]
Hey ryan,

I'm trying to use WireHttp through a proxy to download some images from akamai/facebook. The problem is: The options array isn't parsed and therefore the proxy set for the stream_context_create have no effect:
```				
				$domain 		= parse_url($news['image'], PHP_URL_HOST);
				$proxy_string 	= "http://xyz.net:3128";
				$httpReq 		= new WireHttp();
				$imageResult 	= 	$httpReq->download(
										$news['image'], 
										$upload_path . $p->id . '.jpg', 
										array( 
											'http' => array(
	                                        	'proxy'   => $proxy_string
	                                		),
	                                		'ssl' => array(
	                                			'SNI_enabled' => true, 
	                                			'SNI_server_name' => $domain
	                                		)
                                		)
                                	);
```
I fixed this by adding the following to WireHttp->downloadCurl : 
```
		if(isset($options['http']) && isset( $options['http']['proxy']) && !is_null($options['http']['proxy']) ) {
			curl_setopt($curl, CURLOPT_PROXY, $options['http']['proxy']);
		}
```
It would be nice if you could add proxy support as this is something we do need quite regularly in "large scale" enviroments (enterprise server architectures with firewalls).

**Comment by ryancramerdesign** [comment]
Thanks Felix. I'm not sure I've got a good scenario to test this one out, but your suggestion makes sense and I'll add the code you provided exactly as-is, and will appear in this weeks commits.

**Comment by isellsoap** [comment]
@felixwahner Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
