### ISSUE TITLE
Image in RTE not saved

### ISSUE THREAD

**Issue by m-artin** [ryancramerdesign/ProcessWire#1028]
I'm working with CKeditor with inline mode. When I insert an image and do nothing else afterwards, except pressing directly the Save page button, then the image isn't inserted in the RTE. 
The image is only inserted/saved, when I type something after inserting the image or deselecting the editor.

PW Dev 2.5.22
Mac Yosemite, Safari

**Comment by ryancramerdesign** [comment]
Interesting, I was able to duplicate that too (in Chrome) though only in Inline editor mode. I was able to fix it by manually triggering a CKE change event `editor.fire('change')`, which they don't like us to do, but seems like the only way around it. I'll include this update in the next commit.

**Comment by m-artin** [comment]
Sounds great, thanks so much for all your work ryan!
