### ISSUE TITLE
Render bug when using a field named 'label'

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1029]
Adding an InputfieldText field with the name 'label' to a template results is the below image.
![screen shot 2015-03-20 at 15 41 02](https://cloud.githubusercontent.com/assets/2760993/6753669/06133278-cf18-11e4-8359-162a5b91cac3.png)

both dev 2.5.22 and dev 2.5.22

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed and will appear in this weeks commits.

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
