### ISSUE TITLE
has_parent broken

### ISSUE THREAD

**Issue by kongondo** [ryancramerdesign/ProcessWire#1032]
Works fine in 2.5.20 but not in 2.5.22. This selector won't work. It returns admin pages including **'page', 'module', 'setup' and 'access'**.

````php
//ignores has_parent
$pagesSelector = "has_parent!=2, parent!=7, id!=27, limit=50";
$items = $pages->find("{$pagesSelector}");
````
Adding template!=admin works though...so the issue is has_parent

````php
//works due to template!=admin
$pagesSelector = "has_parent!=2, template!=admin, parent!=7, id!=27, limit=50";
$items = $pages->find("{$pagesSelector}");
````

This breaks ProcessModules like MenuBuilder :-)

**Comment by ryancramerdesign** [comment]
Thanks @kongondo, just pushed a fix. That was broken by a PR that at first I thought looked like a good optimization, but turns out there was a reason why I had it the way it was the first time. So I've switched it back and will add this scenario to Nik's tests.

**Comment by isellsoap** [comment]
@kongondo Can this issue be closed?

**Comment by kongondo** [comment]
Yes, thanks, Francesco. Done...
