### ISSUE TITLE
Can't set comment status via API

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1034]
https://processwire.com/talk/topic/9181-set-comment-status/

I have been having the same trouble - the moderation settings override what you try to set.

**Comment by CanRau** [comment]
is this one fixed? doesn't seem to be merged to new issue tracker, should I?

**Comment by adrianbj** [comment]
Hi @CanRau - as far as I know it isn't fixed, so yes please post in the new Issues repo.

Thanks,
Adrian

**Comment by adrianbj** [comment]
Thanks for reposting @CanRau - I'll close this one.
