### ISSUE TITLE
Bootstrap script overwriting static user setFuel(name, value, true)

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1035]
https://processwire.com/talk/topic/9447-set-created-and-modified-user-on-cron-scripts/

I'm using this script to set user in scripts I call manuall in the browser or are run via cronjob to avoid having "guest" as the created modified user.

```
$importerUser = wire("users")->get("importer");
if($importerUser->id) wire()->setFuel("user", $importerUser, $lock = true);
```

I noticed while testing that the other new way to set fuel variables doesn't work and the user still gets set as the current user logged in while calling the script:

```
$importerUser = wire("users")->get("importer");
if($importerUser->id) wire("user", $importerUser, $lock = true);
```
Doesn't work for me. If I call the script and I'm logged in as "philipp" the created pages still have "philipp" and not "importer", the first script using wire()->setFuel() works.

**Comment by ryancramerdesign** [comment]
The function-based wire() does not support setting API values. Only the method based version in objects supports it. Reason is that the function based wire() is for front-end and intended for use in template files and such, whereas the method based version is within Wire objects and intended more for module developer (and core) use. However, if you want to access it from the function based version, you still can, like this: `wire()->wire('key', 'value');`
