### ISSUE TITLE
New modal sizing not working with Inputfield Selector Show Matches

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1039]
Create a field that use InputfieldSelector. Go to a page with this, enter a filter that returns some matches. Click the "show" link. The bottom of the modal is chopped off.

It used to work fine before the new core modal stuff.

**Comment by ryancramerdesign** [comment]
I'm not seeing that issue here. Have you changed your modal settings? If so, what values should I use? I'm currently just using the defaults. Also if you think it has anything to do with browser, let me know which you tested in? Thanks.

**Comment by adrianbj** [comment]
Sorry, not sure what's going on - it is still happening in an old PW test install (no matter how hard I try to clear caches), but it's working fine on a brand new PW install. Let's not worry about it for now unless I come across it again in another install.
