### ISSUE TITLE
make string translatable in ProcessLogger.module

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1041]
just cosmetics: make string translatable in ProcessLogger.module

line 20:
```json
'summary' => __('View and manage system logs.', __FILE__),
```

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
