### ISSUE TITLE
InputfieldPage validates parentID for "Custom PHP code" option

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1046]
InputfieldPage does validate based on the parentID even though it shouldn't if one uses the "Custom PHP code" option. 

More here: https://processwire.com/talk/topic/9492-bug-and-possible-cause-page-id-is-not-valid-for-field/

**Comment by ryancramerdesign** [comment]
Validating for parent ID or template ID is intended even if findPagesCode is used. The same goes for findPagesSelector. But of course it can be disabled by unselecting the parent/template options.

**Comment by LostKobrakai** [comment]
Then I don't see what this line is supposed to say: `Using this is optional, and if used, it overrides the parent/template/selector fields above.`

**Comment by LostKobrakai** [comment]
Also, please have a look a the last two commits on the pull-request, these are not fully related to this issue.

**Comment by teppokoivula** [comment]
I had a vague memory that this could've been intentional, and was going to point that out earlier, but since the description text clearly states that this shouldn't happen I thought that perhaps it was a bug after all. The description text should definitely be corrected to avoid further confusion.. :)

**Comment by LostKobrakai** [comment]
Just want to note, that the description of the "Custom PHP code …" field is still wrong. It states it overrides the selector field, but it doesn't. So either the first two commits I added to the PR need to be added, or the description needs to change.

Also the third commit of the PR adds a sentence about returning a Page from the "Custom PHP code …" to set a parent instead of the whole select. This feature seems to be added for quite some time, but didn't find it's way into the description, e.g. the users.
