### ISSUE TITLE
Can't save page 1074: /about//: It has an empty 'name' field

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1048]
This happens if you are using Name Format for Children together with noSettings=1 (or some other way of hiding the settings tab).

**Comment by adrianbj** [comment]
I am not sure the best way to fix this, but I wonder if it might be ok to conditionally add _pw_page_name to ProcessPageEdit as an InputfieldHidden field when noSettings is set, but nameContentTab is not.

Maybe something like this? It seems to work great when noSettings is on, but nameContenTab is not. The other thing I did it move the position of the name field to be after the title - I found it confusing the way it was - I think users would have started filling it out before the title, not realizing it is automatic.

```
if($this->page->template->nameContentTab || $this->page->template->noSettings) {
    // name
    $field = $this->page->template->noSettings && !$this->page->template->nameContentTab ? $this->modules->get('InputfieldHidden') : $this->modules->get('InputfieldPageName');
    $field->attr('name', '_pw_page_name');
    $field->attr('value', $this->page->name);
    $field->required = $this->page->id != 1;
    $field->slashUrls = $this->page->template->slashUrls;
    if(!$this->page->editable('name')) {
        $field->attr('disabled', 'disabled');
        $field->required = false;
    }
    if($this->page->parent) $field->parentPage = $this->page->parent;
    $fields->insertAfter($field, $fields->get("title"));
}
```

The one issue that remains is when the Settings tab is removed by other means, like the new removeTab method. Because this is part of building the content tab, I don't see any way of knowing at this point whether the Settings tab will be removed with removeTab or not. Any ideas?

**Comment by adrianbj** [comment]
Just a little more info about other possible interactions. My new RestrictTableView module was affected by this, but I put together a full workaround for it. 

Unfortunately it will also impact my PageRenameOptions module here: https://github.com/adrianbj/PageRenameOptions/blob/master/PageRenameOptions.module#L77

The problem here is that it relies on checking the template's noSettings status, but it also needs to consider when the Settings tab has been hidden with removeTab.

I think it would be possible to solve all these issues if you could define a page property ($page->settingsTab or similar) that returns true/false based on whether the tab is included or not. Do you think that would be a reasonable approach?

**Comment by adrianbj** [comment]
I know this is getting a little OT, but obviously the big downside to removing the Settings tab in general is that there is no longer a way to unpublish a page once it has been published. Do you think that it was be a reasonable idea to add an Unpublish button next to the save button when editing a page? Either in all situations, or maybe just when the Settings tab has been removed. I think there have been a lot of requests about simplifying the page edit options by remove the Settings tab - it is unnecessarily complex for some users, and I think the addition of an unpublish button could be the only important thing that is missing.

**Comment by teppokoivula** [comment]
@adrianbj: for the record, one of the reasons I've chosen to hide the Settings tab in the past has been making it impossible to unpublish, hide, etc. the page. Thus, for us, current situation is *preferable*.

In our case only actual issue with the Settings tab itself has been page name, which users very often forget, resulting in rather weird page names. This is, of course, in some ways intentional, and can be "fixed" by moving the name field to content tab, so.. not complaining, just saying :)

**Comment by adrianbj** [comment]
Thanks for your thoughts @teppokoivula - I hadn't considered wanting to remove the unpublish option completely. If I expand Restrict Tab View as is being discussed in the forum, I would make an option for adding an Unpublish button to the Content tab - that way you could choose whether this appropriate for your needs or not.

As for the page name field - there is of course the advanced template relative nameContentTab setting. Restrict Tab View now currently adds a hidden page name field to the Content tab if the Settings tab is hidden - maybe I should provide an option to make it visible/hidden.

I guess I am wondering how much of this should be handled by the core vs Restrict Tab View. I think the key thing from my initial issue here is the "can't save" error because that can happen with the right combination of core settings.

**Comment by adrianbj** [comment]
Thanks Ryan!
