### ISSUE TITLE
Sanitizer::nameFilter does not remove leading or trailing dashes, underscores, dots

### ISSUE THREAD

**Issue by marc1n** [ryancramerdesign/ProcessWire#1049]
ProcessWire: 2.5.24
Code: $sanitizer->nameFilter('abc:', ['-'], '-', Sanitizer::translate)
Result: 'abc-'
Expected result: 'abc'

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed and will appear in this weeks commits.

**Comment by isellsoap** [comment]
@marc1n Can this issue be closed?

**Comment by isellsoap** [comment]
@ryancramerdesign Can you close this issue?
