### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by harikt** [ryancramerdesign/ProcessWire#1054]
Hi Ryan, 

It will be great help if you can tag each release. Like 2.4.0 , 2.4.1 , 2.5.0 etc.

The idea is to download different versions.

Working on wireshell installer .

Thanks

**Comment by peterfoeng** [comment]
:+1:

**Comment by isellsoap** [comment]
@harikt Great suggestion! @ryancramerdesign started tagging releases in the new repository, [starting with 3.0.34](https://github.com/processwire/processwire/releases/tag/3.0.34).

**Comment by harikt** [comment]
Thank you :) .
