### ISSUE TITLE
Link Attributes don't apply in TinyMCE

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1057]
I've upgraded several older PW sites that used TinyMCE to PW dev 2.5.23 and downloaded the latest version of the TinyMCE module. On two of the sites I've tested, neither of them work with the new Attributes tab in the link editor modal window. If I try to add target="_blank", for example, and then check the html code in TinyMCE, the attribute has not been applied (even before saving the page).

Troubleshooting steps taken so far:
1. Refreshed module cache
2. Hard refresh and cleared cache on browser
3. Set valid_elements to accept all elements
4. Asked on PW forums :)

Edit: Perhaps this belongs in the TinyMCE module issues rather than on the core. I apologize if I posted in the wrong spot.

**Comment by ryancramerdesign** [comment]
The new RTE image and link features are built for use with CKEditor. Much of the code exists in CKEditor plugins. I would recommend using TinyMCE only for pre-2.5 installations. At some point we may update that module as bandwidth allows, but for the moment it does not support these new features.
