### ISSUE TITLE
Template context field visibility settings not overriding main settings is breaking image upload

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1064]
Maybe not a great title :)

Set an images field to be "hidden, not shown in the editor" (I think collapsed also works). Now go to the template context settings for this field and set it to "always open".

Now try to upload an image to that field on the template you just edited. The image will upload, but then immediately disappear.

**Comment by isellsoap** [comment]
@adrianbj I followed your steps but can’t reproduce the issue. Everything works like expected. I close the issue, but if you think the issue requires additional work to do, please add a comment to this issue and I re-open it.

**Comment by adrianbj** [comment]
Agreed, it seems to be fine now since the image upgrades in PW 3.x
