### ISSUE TITLE
Cropping images in repeater fields

### ISSUE THREAD

**Issue by typhoon2099** [ryancramerdesign/ProcessWire#1068]
Hi, I cannot seem to crop images properly when they are contained in repeater fields. I have hunted through the code and it appears to be something to do the with the field name in the link to the cropper popup.

When the link is created (InputfieldImage.module:257) the reference to $this->name pulls back a field name with appended data about the repeater field it resides in. If this repeater data is removed then the image can be cropped properly.

**Comment by ryancramerdesign** [comment]
Thanks, I had actually meant to disable the feature within repeaters but looks like I forgot to, as I can duplicate that here too. I have corrected that so it will appear in this week's commits.

**Comment by isellsoap** [comment]
@typhoon2099 What’s the status of the issue? Can it be closed?

**Comment by typhoon2099** [comment]
I haven't had a chance to check, unfortunately. It probably can be closed now, though.
