### ISSUE TITLE
Error on installing Languages Support on fresh 2.5.25 installation

### ISSUE THREAD

**Issue by blynx** [ryancramerdesign/ProcessWire#1074]
Hej,

I get this Error when I install Languages Support on a fresh 2.5.25 installation ... The whole site is broken afterwards.

Error: Call to a member function setIsDefaultLanguage() on a non-object (line 152 of /Users/lynx/Arbeitsordner/___htdocs/cival/wire/modules/LanguageSupport/LanguageSupport.module) 
This error message was shown because you are logged in as a Superuser. Error has been logged.

**Comment by ryancramerdesign** [comment]
I pushed an attempted fix for this issue to the dev branch. If you have a chance would you mind trying it out to see if it resolves the errors you were seeing? If you initially see an error or something not working, try reloading the page a few times, as it will attempt to correct missing language columns, but may not be able to do more than one at a time. Thanks.

**Comment by blynx** [comment]
Hi,
I just tested it and it works now - great!

**Comment by ryancramerdesign** [comment]
Great! Glad to hear it. Thanks for testing it out.
