### ISSUE TITLE
File name truncation after 128 chars on upload with preservation of file name extension

### ISSUE THREAD

**Issue by bfncs** [ryancramerdesign/ProcessWire#1077]
If files with names longer than 128 characters are uploaded, the names are just truncated. The file name extension is not treated specially and can be lost in the process without notice. This is error-prone and incovenient, especially for image uploads.

To replicate upload a file with a name longer than 128 characters, e.g. `xepeZoocohBeb3phohnu0Biethah6doa_Tue6raex0ijee4dooPh6eene4Igh7Saa_daes1cuokoon9Lazoo4iu3Hoh6chew6O_foohaipheiweush0Hiegaaloop4xei.jpg`. On upload, the file name will be truncated to `xepeZoocohBeb3phohnu0Biethah6doa_Tue6raex0ijee4dooPh6eene4Igh7Saa_daes1cuokoon9Lazoo4iu3Hoh6chew6O_foohaipheiweush0Hiegaaloop.jp` and therefore be virtually unusable.

Clearly having filenames this long isn't advisable anyway, but when giving backend access to technically non-inclined editors, Processwire is needed to gracefully handle these cases. Long filenames should:

a) be truncated with preservance of the file name, and
b) a warning should be given about the filename change.

**Comment by ryancramerdesign** [comment]
Makes sense to me, thanks, I will update. I think we'll skip "b" though since PW always sanitizes uploaded filenames and that's part of normal/expected behavior.

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed and will appear in this weeks commits.

**Comment by isellsoap** [comment]
@bfncs Can this issue be closed?

**Comment by bfncs** [comment]
@isellsoap Thanks, this has already been fixed (at least on `dev`).
