### ISSUE TITLE
Update via uploading a zip seems to not trigger a refresh

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1079]
If I update a module by uploading a zip file the "Recently found and installed modules" section still shows the old version number. I think it would be nice to do a refresh after the upload, so it prevents confusion.

**Comment by ryancramerdesign** [comment]
Thanks, this has been updated and will appear in today's commits.

**Comment by LostKobrakai** [comment]
I just checked it on a fresh installation and it seems not to be fixed.
I installed the Helloworld module and then uploaded a update with a higher version number. After the upload the version number in "Recently found and installed modules" was still the old one.

**Comment by isellsoap** [comment]
@LostKobrakai Is this still an issue?
