### ISSUE TITLE
Little wish for InputfieldPageAutocomplete.

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1083]
It would be nice when InputfieldPageAutocomplete will re-focus the inputfield after an item is added. This way you don't need to use the mouse at all to add multiple items.

**Comment by ryancramerdesign** [comment]
No problem. This was an easy one. It'll appear in today's commits.

**Comment by Da-Fecto** [comment]
Great, the editors will love it :+1:

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
