### ISSUE TITLE
Lack of check for configurable module interface causes db module configuration errors

### ISSUE THREAD

**Issue by kongondo** [ryancramerdesign/ProcessWire#1085]
Ryan, this [commit](https://github.com/ryancramerdesign/ProcessWire/commit/2126cb8e266ca157cc4de241eea63ebb28a93d3e#diff-54569eb5f135c3049cc00c94f210b667) to ProcessModule.module is breaking/preventing fresh installs of modules that leverage the 'configurable module interface' such as Blog. You seem to have removed a big chunk of code that does that check. In the case of Blog, all initially empty config indices are not saved to the database and zero values converted to '' (empty strings). The result is that Blog cannot be installed and ProcessWire throws errors.

**Comment by ryancramerdesign** [comment]
Actually all that code was just moved into a function, so it's all being covered by this call (shown as the added code above).
`````````
$fields = $this->wire('modules')->getModuleConfigInputfields($moduleName);
`````````
I think I need a test case to see what you are talking about. I've tried installing a couple ConfigurableModule modules that I have locally, but everything is working normally. I will try installing the Blog module next. But if there's anything specific I should look for during installation, please let me know.

I just installed ProcessBlog, but can't detect any errors. Maybe I just don't know what to look for, but it appears like it installed normally to me?

**Comment by kongondo** [comment]
Blog has a two-step installer. The first step of the module will install fine but you won't be able to run the second step. In your test, visit the Blog ProcessModule page itself (Admin > Blog) and you will get the error **'Field does not exist: blog_date'.** The reason that is happening is the following:

When Blog is first installed, the following default configurations are written to its data column in the module table in the db as expected.

```json
{
"blogFullyInstalled":0,
"blogStyle":"",
"schedulePages":0,
"commentsUse":1,
"templateFilesInstall":1,
"tagTemplatesFields":"blog",
"blog":"",
"blog-posts":"",
"blog-categories":"",
"blog-tags":"",
"blog-comments":"",
"blog-widgets":"",
"blog-authors":"",
"blog-archives":"",
"blog-settings":"",
"blog-asc":"",
"blog-dnc":"",
"blog-dc":"",
"blog-rposts":"",
"blog-rcomments":"",
"blog-broll":"",
"blog-tweets":"",
"blog-pauthor":""
}
```
At this point, the user then has to select a blog style within the module config screen in admin. Instead of the above config values getting updated,  the below happens in the db. As you can see, quite a number of the now saved configurations disappear, specifically all those with empty values. The zero value for 'schedulePages' is also replaced by an empty string.

```json
{
"blogStyle":"1",
"schedulePages":"",
"commentsUse":1,
"templateFilesInstall":"2",
"tagTemplatesFields":"blog"
}
```
In the second step of installing Blog, the user has to visit the Blog page itself (in Admin > Blog) and there they will see the above error because Blog will check for "blogFullyInstalled":0, and will not find it and hence will bypass installation and try to load the dashboard, which will try to access posts, sorting them by 'blog_date' and of course such a field (indeed everything blog :-)) does not exist yet since the installer did not run.

The normal flow is that once Blog is fully installed (the 2nd step of the installer), the configurations should resemble the following, where our default empty values are all populated: 

```json
{
"blogFullyInstalled":1,
"blogStyle":"1",
"schedulePages":"",
"commentsUse":1,
"templateFilesInstall":"2",
"tagTemplatesFields":"blog",
"blog":1156,
"blog-posts":1157,
"blog-categories":1158,
"blog-tags":1159,
"blog-comments":1160,
"blog-widgets":1161,
"blog-authors":1162,
"blog-archives":1163,
"blog-settings":1164,
"blog-asc":1168,
"blog-dnc":1169,
"blog-dc":1170,
"blog-rposts":1171,
"blog-rcomments":1172,
"blog-broll":1173,
"blog-tweets":1175,
"blog-pauthor":1176
}
```
I have tested in 2.5.24 and it works fine. I will set up a test case for you at lightning.pw if that helps. Sorry for the verbosity, just wanted to be clear.

Thanks.

**Comment by ryancramerdesign** [comment]
I still can't seem to figure this one out. I'm now looking in ProcessBlog and the results when configuring the module, but I only see 5 inputs, and likewise 5 fields accounted for in the module config json. So from what I can gather, you are wanting to store stuff in the module config separately from what's being defined with Inputfields? Usually when I do this, I create InputfieldHidden inputs in the module config to store the values. But I can see a lot of the variable names you are using have hyphens in them, which PHP doesn't allow as variable names, so that wouldn't work. 

My best guess based on what I can see so far is that somehow we previously supported independent config values in the module outside of them being specifically defined in the form returned by getModuleConfigInputfields(). You are listing a bunch of field names for which there aren't associated Inputfields. If it was doing that, it wasn't supposed to. But if you think it sounds like I'm on the right track (?), I think I can figure out how to add that behavior. Does this sound right?

**Comment by ryancramerdesign** [comment]
I think I found an easy fix, which you'll see in the latest commit. I'm just letting the $data array start as what's pulled from Modules::getModuleConfigData() rather than as a blank array. That way any values in there that don't have associated Inputfields should remain. I just tested by re-installing ProcessBlog, and the longer list of values you mentioned now remains. Can you confirm?

**Comment by kongondo** [comment]
Edit: This is a response to your comment above the last one...

Those are not variable names :-)...They are array indices that are used to hold the IDs of the main Blog pages (i.e. parent pages). That allows users to call their Blog pages anything they want, since Blog will reference them by their IDs rather than titles/names. So, the Author page can be renamed to 'Writer', Blog can be renamed to 'Mumblings', etc, etc....Renaming can occur at both the 2nd  step of the install or even after Blog has been fully installed. The following code block from ProcessBlog explains it:

```php
	public static function configDefaults () {
		
		return array(
						'blogFullyInstalled' => 0, // boolean 0=false {new install}; 1=true {blog fully installed - i.e. including template files and pages}
						'blogStyle' => '', // 1='see example 1'
						'schedulePages' => 0,//boolean 0=false; 1=true: Whether to use auto-publish/unpublish feature {needs SchedulePages module}
						'commentsUse' => 1, //boolean 0=false; 1=true
						'templateFilesInstall' => 1,//int 1=blank template files; 2=demo template files; 3=no template files
						/*'prefixTemplatesFields' => 'blog',*///string default='blog'. Will be used to prefix templates, fields and template files. E.g. blog-post, blog_date, blog-post.php. Blank = no prefix
						'tagTemplatesFields' => 'blog',//string default='blog'. Will be used to tag templates and fields in the admin. Blank = no tag						
					
						/* BLOG PARENT PAGES IDs */
						//changed to below for convenience in coding - to use array index as both an identifier and identifier storage (id) AS well as related template name
						'blog' => '',//ID of the page 'Blog' - if used
						'blog-posts' => '',//ID of the page 'Posts' - if used
						'blog-categories' => '',//ID of the page 'Categories'
						'blog-tags' => '',//ID of the page 'Tags'
						'blog-comments' => '',//ID of the page 'Comments' - if used
						'blog-widgets' => '',//ID of the page 'Widgets'
						'blog-authors' => '',//ID of the page 'Authors'
						'blog-archives' => '',//ID of the page 'Archives'
						'blog-settings' => '',	//ID of the page 'Settings'
						'blog-asc' => '',//ID of the page 'Always Show Comments'
						'blog-dnc' => '',//ID of the page 'Disable New Comments'
						'blog-dc' => '',//ID of the page 'Disable Comments'
						'blog-rposts' => '',//ID of the page 'Recent Posts' - widget
						'blog-rcomments' => '',//ID of the page 'Recent Comments' - widget
						'blog-broll' => '',//ID of the page 'Blogroll' - widget
						'blog-tweets' => '',//ID of the page 'Recent Tweets' - widget
						'blog-pauthor' => '',//ID of the page 'Post Author' - widget
		);

	}
```
I thought it superfluous to have hidden inputfields to hold the values for the parent pages since those were only created during the 2nd step of the install rather than at the module config stage (1st  step). Hope this makes sense. 

OK, off of to test, thanks.

**Comment by kongondo** [comment]
[Fix](https://github.com/ryancramerdesign/ProcessWire/commit/0d3d06c8ec6b7cda4abe2aea14b8b1629a7cfcbe) works, thanks!

**Comment by ryancramerdesign** [comment]
Great! Glad that did it. As a side note, I'm also glad I no longer have to
use hidden inputs for these types of config vars. :)
