### ISSUE TITLE
Unable To Delete An Entry Using A PageTable or PageTableExtended (2.5.25 Dev)

### ISSUE THREAD

**Issue by cstevensjr** [ryancramerdesign/ProcessWire#1086]
I ran into an issue that took me a few hours to realize what was going on.

I have a couple of fields that use the PageTable or PageTableExtended.  I updated to PW 2.5.25 Dev and from then on I couldn't directly mark the PageTable or PageTableExtended entry for deletion.  I had to go to the actual page were it was stored and then I could delete the page.  

Whenever you created a new PageTable or PageTableExtended entry, it would create a blank entry along with the one you created.

This was for an Account that has SuperUser role assigned.

Once I reverted back to 2.5.23 Dev, everything worked as it should.

**Comment by ryancramerdesign** [comment]
I don't have any experience with PageTableExtended, so am testing with PageTable here. But I can't seem to duplicate the issue. I tried both modes: items as children of page being edited, and items in a specified container page, but am able to delete them as expected in both. I'm also not seeing the blank entry that you mentioned either. I think we probably need to look at what other modules are installed in /site/ to see if one of them is potentially conflicting.

Also, there haven't been any code changes to PageTable (Fieldtype or Inputfield) for the last two months, except for adding a minified version of the JS file that comes into play if debug mode is off. Meaning, the only difference in PageTable between 2.5.23 and 2.5.25 is that it has the option of using a minified JS file. As a result, it might be worth testing with debug mode on (to force use of the old, non-minified JS file) just in case that makes any difference? Also, I would do a hard refresh in your browser just in case. Please let me know what you find.

**Comment by cstevensjr** [comment]
I will update the site later today to 2.5.25 again (whenever I have some free time). If I run into the issue again, I will look at uninstalling modules I know I have recently installed.  I will also look at the other factors you mentioned and test in debug mode.

**Comment by ryancramerdesign** [comment]
Before you go uninstalling modules, you may want to list what they are
here. I might be able to identify if any are worth uninstalling to test. If
the modules aren't hooking into any Pages class hooks then they are
unlikely to interfere at least with the server side of it. And if something
is interfering with the client side, you'll likely see a JS error in your
console. Also, just to confirm, you are seeing this behavior in regular
PageTable? I know you mentioned PageTableExtended, so if that's where you
are seeing it, we probably need to loop that module's author (Marc?) into
the conversation since I didn't develop that one. However, if you've only
seen the issue in PageTableExtended, you may want to view the source and
see if the InputfieldPageTable.js and/or InputfieldPageTable.min.js file
might potentially getting loaded twice?

**Comment by cstevensjr** [comment]
I understand what you are saying.  Here are a couple of screencasts that go over the issue.

Using a PageTable Field on PW 2.5.23
https://vimeo.com/cstevensjr/review/124647098/24c7acf4ae

Using a PageTable Field on PW 2.5.25
https://vimeo.com/cstevensjr/review/124647100/c6e74215b9

Reverting Back to using PW 2.5.23
https://vimeo.com/cstevensjr/review/124647099/7b9f5e47cd

Modules In-use (Site and Core)
https://vimeo.com/cstevensjr/review/124640907/b115b04cb9

**Comment by cstevensjr** [comment]
Okay, I decided to test this on a complete different website installation with the exact same PageTable configuration (I imported them from the troubled installation).  I was able to update to 2.5.26 Dev with no problems and could continue to delete the PageTable entries.

This eliminates any possible problem as stated earlier regarding PageTable field and indicates that I need to do some more cleanup and troubleshooting on the problem website.

Closing this issue.

**Comment by cstevensjr** [comment]
Follow-up:

When I put the problem website in Debug mode, there were numerous errors popping up in different places.  After an extensive cleanup of Site Modules on the problem website (I physically removed and reinstalled all Site modules) I was able to update from Pw 2.5.23 to 2.5.26.
