### ISSUE TITLE
"has" not working with object, but fine with key

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1088]
This is weird, but I have been using the following script in admin.php for a little while now to automatically add and delete child pages to/from pagetable fields
```
wire()->addHookBefore('InputfieldPageTable::render', function($event) {
    $pp = wire('pages')->get(wire('input')->get->id);
    $ptf = $event->object;

    //remove pages from pagetable field if they were externally trashed
    foreach($pp->{$ptf->name} as $item) {
        if($item->is(Page::statusTrash)) $pp->{$ptf->name}->remove($item);
    }

    //add pages to pagetable field if they were created externally
    foreach($pp->children as $child) {
        if(!$ptf->has($child)) {
            $pp->{$ptf->name}->add($child);
            $pp->of(false);
            $pp->save($ptf->name);
        }
    }

    //reset orphans property so that we don't get a message asking to add new pages that are now already automatically added
    $ptf->setOrphans(new pageArray());
});
```

Everything has been working great but I just started getting the following errors
```
Warning: array_key_exists() [function.array-key-exists]: The first argument should be either a string or an integer in /wire/core/Inputfield.php on line 246

Warning: Illegal offset type in isset or empty in /wire/core/Inputfield.php on line 866
```

Doesn't seem to matter what version of PW I use I get the same error. However, if I change:
```
if(!$ptf->has($child)) $pp->{$ptf->name}->add($child);
```
to
```
if(!$ptf->has($child->id)) $pp->{$ptf->name}->add($child);
```
ie from the child object to the id of the child page, then the errors go away.

Can you think of why it wouldn't be working and why it used to work?

**Comment by adrianbj** [comment]
Ok, I think the error may have always been there - probably a debug mode issue. Anyway, the code works either way (object or id), but I am still not sure why there is that error when using the object - maybe the way PageTable stores the references to its connected pages?

**Comment by ryancramerdesign** [comment]
You have code there that is passing an object to an Inputfield::has() method, and it's expecting a string. See the definition for Inputfield::has() in /wire/core/Inputfield.php. It looks to me like maybe you intended for it to be `$ptf->attr('value')->has($child)`.

**Comment by adrianbj** [comment]
Thanks Ryan - I was just going with the description in the cheatsheet in regards to has() being able to accept an object. I didn't think about it being different with an inputfield. It's not the value I am looking at, it's whether or not the page exists in the page table field, but it doesn't matter because $child->id works fine.
