### ISSUE TITLE
Issues with saving page having comments enabled

### ISSUE THREAD

**Issue by websharp** [ryancramerdesign/ProcessWire#1090]
Hi guys,

I have a little issue I debugged as far as I could for the moment.

I have a simple page (title, a checkbox, a textarea and the comments field) working as a guestbook page. Initially there were no problems with creating the page and setting the content of title and the textarea field. Currently some comments have been made on the page.

Now I want to change the content of the textarea field, but sadly nothing is happening in the administration area. The green bar saying "successful saved" (or something like that) does not appear.

I checked the mysql log file, and also reassured my of the normal behavior on a different page without comments, how the log must be look like. So I found, that really nothing is happening. No insert statement.

I don't think this is the expected behaviour, but I'm not sure how to fix this issue or debug this some more. Hope you can help me out here.

My environment installation looks like the following:

ProcessWire Core (Stable/Master) 2.5.3
JqueryDataTables 1.9.4
ModulesManager 2.1.6
ProcessDatabaseBackups 0.0.3
ProcessLatestComments 0.0.3
ProcessWireUpgrade 0.0.3
TemplateDataProviders 1.1.0
TemplateTwigReplace 1.0.9

**Comment by ryancramerdesign** [comment]
Just to confirm, it only happens on pages with a 'comments' field? I've not heard of this particular issue before, but two modules you listed I don't have experience with: TemplateDataProviders and TemplateTwigReplace. It might be worth uninstalling those temporarily, just to see if it makes a difference. You might also want to upgrade to the dev branch (currently 2.5.26) as it contains a lot of fixes. Nothing specific to this that I'm aware of, but I'd be worth trying.

**Comment by websharp** [comment]
Hi!
Yes, I can confirm, this happens only if a field type "comments" is added to the template. If I remove it from the template, the changes on the page can be saved.

I removed the two modules, but it made no difference. I also upgraded to the 2.5.26, but this has not solved the issue too.

**Comment by websharp** [comment]
I just readded the fieldtype "comments" to my template. Everything is working fine with no data, and also after I added some simple test comments.

So there might be some issues with the exisiting data I had in the comments, so this seems to be no real issue originating from process wire itself.

**Comment by websharp** [comment]
So now I finally got the answer:

[17-Apr-2015 18:18:15 UTC] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0

Seems to be a problem, if to much comments are applied on a page. All comments are listed in the current page and will be send on the save request.

**Comment by NicoKnoll** [comment]
@websharp Try this: https://github.com/ryancramerdesign/ProcessWire/issues/920

**Comment by isellsoap** [comment]
@websharp This issue doesn’t seem to be a bug or cannot be reproduced, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
