### ISSUE TITLE
Markdown and code blocks in field description

### ISSUE THREAD

**Issue by raphaelbastide** [ryancramerdesign/ProcessWire#1092]
Fields descriptions doesn’t output correctly code blocks: the four spaces seams to be ignored.
To reproduce this bug, test the following markdown text in a field description:

    Link list in markdown. Example:

         - [Link 1](http://foo.bar)
         - [Link 2](http://bar.foo)

This should output:

Link list in markdown. Example:

     - [Link 1](http://foo.bar)
     - [Link 2](http://bar.foo)

But it actually outputs:

Link list in markdown. Example:

 - [Link 1](http://foo.bar)
 - [Link 2](http://bar.foo)

**Comment by ryancramerdesign** [comment]
Field descriptions actually don't support any block level markdown. Supported is limited to the following at present: 
```````
[link](url)
**strong**
*em*
~~s~~
`code`
```````
There actually isn't a real markdown parser involved here, just a small and fast homegrown search/replace of a few recognized tags.

**Comment by raphaelbastide** [comment]
Ok. Is it supposed to be changed to a full markdown support?

**Comment by ryancramerdesign** [comment]
Full markdown support isn't intended here just because an inputfield `$description` is actually a block level `<p>` element already, so we have to format within that. So we're just providing the inline markdown options (and may add more of those too if there's demand for it).

**Comment by mike-anthony** [comment]
My humble opinion: I think that the feature-set should remain as-is, unless there's demand for it, sure. 

To me, adding full markdown support (or just code block support) opens up the opportunity to clutter admin pages, which could get quite messy. That said, ProcessWire is all about letting the developer choose what he/she wants (flexibility) and, thus, this is one of those topics that's open to discussion.

**Comment by raphaelbastide** [comment]
I think my case is not isolated: As the field support markdown, I want to show users how to make a link list in markdown, for that I need the block code support. Do you see an alternative to solve my problem? Is there a way to put some HTML there?

**Comment by LostKobrakai** [comment]
If you need that much information I doubt the description field is the right place. Have a look at this http://modules.processwire.com/modules/template-notes/ if you need a space for documentation. No matter where you put the docs you can always link to it from the description (like it's done by pw for example for the inputfield dependencies).

**Comment by raphaelbastide** [comment]
Ok, thank you @LostKobrakai for this tip. I guess this issue can be closed in this case.

**Comment by LostKobrakai** [comment]
Please do close this on your own if it's resolved for you.

**Comment by ryancramerdesign** [comment]
I do understand the need, and I've had it before too, so will keep more ideas on this in mind for the future. One idea is that the `<p class='description'>` could become a `<div class='description'>` and then it could support block level elements within it (and thus more markdown). But this would no doubt break the current styling in admin themes, so probably not the right time for this change.

**Comment by isellsoap** [comment]
@raphaelbastide This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
