### ISSUE TITLE
Inputfields without a label are rendered strangely

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1093]
There seems to be the whole wrapper styling missing as long as the repeater doesn't have a label. Version is 2.5.25.

![screenshot 2015-04-12 16 09 26](https://cloud.githubusercontent.com/assets/2489835/7105872/6956ce6c-e12e-11e4-8cc7-ef0343dbe199.png)

**Comment by adrianbj** [comment]
Same with PageTable fields - the issue is still there in 2.5.26

![screen shot 2015-04-12 at 7 15 02 am](https://cloud.githubusercontent.com/assets/871211/7105892/c51e4b62-e0e3-11e4-82c7-94187f24ce13.png)

**Comment by LostKobrakai** [comment]
Seems to be a more global issue. Noticed this for a an asmSelect field inside the mentioned repeater, too.

**Comment by LostKobrakai** [comment]
Seems to be working here.
