### ISSUE TITLE
Bug with concat fields with multiple parent level labels

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1096]
Set up a Concat field and set the "Name of fields to concatenate" to include more than one parent level.

Here is the path to the page that contains this concat field:
http://pwtest.dev/about-two/test-one/

```
parent.parent.title - parent.title - title
```
returns: Home - parent.Test One - Test One (WRONG)

but:
```
parent.title - title
```
returns: About Two - Test One (CORRECT)

and:
```
parent.parent.title - title
```
returns: Home - Test One (CORRECT)

Why can't I combine parent.parent.title and parent.title together, but they both work separately?

**Comment by ryancramerdesign** [comment]
Adrian I've updated FieldtypeConcat to support this. Previously it didn't support using subfields on the same property more than once. Now it does. Since it's not core, you'll need to grab that one from the FieldtypeConcat repo.

**Comment by adrianbj** [comment]
Brilliant - thank you!

Sorry for posting this issue in the wrong place!
