### ISSUE TITLE
Reno MarkupAdminDataTables styles

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1100]
AdminDataTables are missing the border-left styles for `.content .AdminDataList tfoot td(:first-child)` in AdminThemeReno.

**Comment by ryancramerdesign** [comment]
Sounds like an easy fix. But are there any examples you are aware of where I can see this in the admin? If not, I can setup an example myself. I'm not sure I've seen `tfoot` in use with MarkupAdminDataTable before (though I know it supports it), so likely the default admin theme is missing the styles as well.

**Comment by LostKobrakai** [comment]
Here's a part of the module I'm building and you're right, it's missing in the default theme as well. Just adding the selector posted before to the place where `.content .AdminDataList tboy td(:first-child)` is should be sufficient.
![screenshot 2015-04-17 12 30 18](https://cloud.githubusercontent.com/assets/2489835/7200468/8de75e36-e4fd-11e4-8efa-685754da7d23.png)

**Comment by LostKobrakai** [comment]
It's working now for `<td>` elements, but not for `<th>`. So if someone wants to duplicate the headers to the bottom (not my case) it'll still look like above.
