### ISSUE TITLE
Pages::executeQuery not throwing exception

### ISSUE THREAD

**Issue by marc1n** [ryancramerdesign/ProcessWire#1103]
PW dev 2.5.26

Throw state is not restored when tryAgain variable is set to 0:

1921: } else {
		// some other error that we don't have retry plans for
		// tryAgain=0 will force the loop to stop
		$tryAgain = 0;
}

This cause a problem with not auto-numbering new-page name if page with such name already exists (see forum: https://processwire.com/talk/topic/9686-integrity-constraint-violation-while-saving-new-page-with-non-uniqe-name/)

**Comment by marc1n** [comment]
PW 2.5.27 is now OK.

**Comment by LostKobrakai** [comment]
Please also close the issue, if it's fully fixed.
