### ISSUE TITLE
Duplicate a Set field

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1107]
When creating a Set field through duplication of an existing one, the accompanying set_END field does not get created as well. Is this a bug or intended?

**Comment by mike-anthony** [comment]
Just noticed this as well. Having to manually duplicate the _END variant as well.

**Comment by tbba** [comment]
in case it is not worth the trouble to add the feature (duplicating 2 fields at the same time is not used anywhere else) a simple reminder/notification instead ("_END" field missing / field needs to be duplicated as well) might be all that's needed?

**Comment by mike-anthony** [comment]
To me, this is like a 'gap' that should be filled. It slightly relates to #917, which was also a 'gap', if you know what I mean...

**Comment by tbba** [comment]
too old (still unsolved? -but there are a lot of newer threads already)
