### ISSUE TITLE
Page::path not hookable

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1108]
There seems to be an issue with the hookability of Page::path in 2.5.27.

**Comment by ryancramerdesign** [comment]
Need a little more to go on than that. :) This seems to work fine:
````````
wire()->addHookAfter('Page::path', function($e) {
        $e->return .= 'test';
}); 

foreach($pages->find("limit=5, sort=random") as $item) {
        echo "<li>" . $item->path . "</li>";
}
````````

**Comment by LostKobrakai** [comment]
I'm dynamically assigning hooking some pages like this. They are selected as part of my modules logic.
`$this->page->addHookAfter('path', $this, 'modifyPath');`

But it didn't work, so I commented out `public function path(){}` in Page.php and made the hookable function public and it worked.

The error without my changes (version 2.5.27)
```
Fatal error: Exception: Method Page::path is not hookable (in …/wire/core/Wire.php line 582)

#0 …/wire/core/Wire.php(671): Wire->addHook('path', Object(PagePathMaskFolder), 'modifyPath', Array)
#1 …/site/modules/PagePathMaskFolder/PagePathMaskFolder.module(101): Wire->addHookAfter('path', Object(PagePathMaskFolder), 'modifyPath')
#2 …/wire/core/Wire.php(405): PagePathMaskFolder->searchMaskedFolder(Object(HookEvent))
#3 …/wire/core/Wire.php(321): Wire->runHooks('ready', Array)
#4 …/wire/modules/Process/ProcessPageView.module(152): Wire->__call('ready', Array)
#5 …/wire/modules/Process/ProcessPageView.module(152): ProcessPageView->ready()
#6 [internal function]: ProcessPageView->___execute(true)
#7 …/wire/core/Wire.php(383): call_user_func_array(Array, Array)
```

**Comment by ryancramerdesign** [comment]
Page::path does not support instance-level hooks. You can't hook individual pages, only Page objects in general. The reason for this is that path() is a high traffic method that might be called thousands of times in a request, so overhead is reduced here by not supporting instance level hooks. However, you can accomplish the same thing just by hooking Page::path, and performing your "should I modify the return value" code in your hooked method/function.

**Comment by LostKobrakai** [comment]
Thanks, will do this then.
