### ISSUE TITLE
Temp pages not being automatically removed

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1114]
Based on your statement: "Pages that remain statusTemp will be automatically moved to the trash after having that status for 1+ days.", my understanding is that temporary "untitled" pages should be deleted after a day. I have several now that are more than a week old.

I am running 2.5.27 but not sure if this is a new bug or if it has never worked properly.

**Comment by adrianbj** [comment]
Just noticed that all the older ones have now gone. I thought maybe the trigger to delete them is the saving of a new page, but testing on another site that doesn't seem to work.

**Comment by ryancramerdesign** [comment]
Temp pages are handled entirely by ProcessPageAdd. Maintenance is performed when ProcessPageAdd runs. So the "after 1+ days" means exactly that, in that the temp page will last no less than 1 day.

**Comment by adrianbj** [comment]
Understood - I am still not convinced the cleanup is always working on Page Add when pages are older than one day, but I'll close this and keep an eye out.
