### ISSUE TITLE
WireArray explode() subfield selectors to multidimensional arrays instead of plain text keys

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1123]
What a topic headline. So let me explain: 

Since 2.5.27 there's the ability to use explode() with an array of fieldnames. E. g.
```php
$page->explode(array("id", "pagefield.title"));

// Output
array(
  "id" => 1111,
  "pagefield.title" => "Some title"
)
```

Now I'm using mustache, which can't handle dots in keys, as it's using dotnotation to traverse arrays. So it would be really nice to have subfields parsed to arrays, like this:

```php
$page->explode(array("id", "pagefield.title", "pagefield.id"));

// Output
array(
  "id" => 1111,
  "pagefield" => array(
    "title" => "Some title",
    "id" => 1112
  )
)
```

I'm not sure what the best option would be to implement a switch to enable something like this, but I've just wildly build this into my WireArray to test this out.

```php
	public function explode($property, $splitSubselectors = false) {
		$isArray = is_array($property);
		$isFunction = !$isArray && !is_string($property) && is_callable($property); 
		$values = array();
		foreach($this as $key => $item) {
			if($isFunction) {
				$values[$key] = $property($item, $key);
			} else if($isArray) {
				$values[$key] = array();
				foreach($property as $p) {
					if(strpos($p, '.') !== false && $splitSubselectors){
						$fields = explode(".", $p);
						$result = array(array_pop($fields) => $item->get($p));
						while($field = array_pop($fields)){
							$result = array($field => $result);
						}
						$values[$key] = array_merge_recursive($values[$key], $result);
					}else{
						$values[$key][$p] = $item->get($p);
					}
				}
			} else {
				$values[$key] = $item->get($property);
			}
		}
		return $values; 
	}
```

**Comment by ryancramerdesign** [comment]
As a general thing, I'm not sure I want functions like this returning properties in a different format than they were requested. But I understand your use case here, and to me it looks like a good reason to make the explode method hookable? 

Here's some code that you could run on the $event->return to convert the array to the format that you want for Mustache: 
``````
function explodeForMustache(array $items) {
        foreach($items as $key => $value) {
                if(!strpos($key, '.')) continue;
                unset($items[$key]);
                list($k, $rest) = explode('.', $key, 2); 
                $a = explodeForMustache(array($rest => $value));
                $items[$k] = isset($items[$k]) ? array_merge($items[$k], $a) : $a;
        }
        return $items;
}
`````````
input array:
````
Array
(
    [id] => 1111
    [pagefield.title] => Some title
    [pagefield.name] => Some name
    [pagefield.blah.title] => Blah title
)
```````
output array:
```````
Array
(
    [id] => 1111
    [pagefield] => Array
        (
            [title] => Some title
            [name] => Some name
            [blah] => Array
                (
                    [title] => Blah title
                )

        )

)
````````

**Comment by LostKobrakai** [comment]
I understand you're concern and hooking would be a acceptable way around the issue. But there's also the option to build it like this `$modules->getModule($key, array $options = array()){}`. The return values are still both arrays with the same values, it's just hierarchical. 
Also if someone writes something like this: 
`$page->explode(array("page.title", "page.id"), array("nestSubfields" => true))`,
 then it should be obvious what's happening.
