### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1126]
When i activate cache, i am getting this error for page using cached template

Warning: file_put_contents(/path_to_site/site/assets/cache/Page/1032/0d414f538b11822bee0d75d251bc4aad.cache): failed to open stream: No such file or directory in /path_to_site/wire/core/CacheFile.php on line 178

Warning: chmod(): No such file or directory in /path_to_site/wire/core/CacheFile.php on line 179

When i check folder, no folder exist about this page, i think before we cache, need to check folder exist there? if not create folder after we can try to create cache file.

![screen shot 2015-04-24 at 13 58 20](https://cloud.githubusercontent.com/assets/455983/7317487/0a2fe8e6-ea8a-11e4-859e-977c14e79541.png)

**Comment by ryancramerdesign** [comment]
This check is already performed in CacheFile.php (in the constructor), and it throws an exception if it is unable to create the directory. It seems like it shouldn't be able to occur without an exception getting thrown first. I'm wondering if maybe there's something about the directory permissions? Which version of PW?

**Comment by trk** [comment]
Latest from dev, permission is 755 for page folder

![screen shot 2015-04-25 at 03 43 52](https://cloud.githubusercontent.com/assets/455983/7330753/627576c4-eafd-11e4-81cd-d9b01981f77d.png)

**Comment by wanze** [comment]
Does the folder belong to the user running the webserver? Otherwise you must change the owner so that the user gets write permission.

**Comment by trk** [comment]
@wanze Tested on local mamp server with virtual host spec. and get this issue, but when i upload website to online server its look like ok. Normally with virtual host spec. all things must work like online server.. is it?

**Comment by trk** [comment]
@ryancramerdesign your last commit also fixed cache folder and file creation.
