### ISSUE TITLE
2.5.28: new WireCache throws fatal error

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#1127]
I'm experimenting with the new WireCache features and tried the last code example from http://processwire.com/blog/posts/processwire-core-updates-2.5.28/ in a template:

    $template = $templates->get("product");
    $products = $cache->get("new-products", $template, function($pages) {
        return $pages->find("template=product, sort=-created, limit=100");
    });

which throws an error:
`Catchable fatal error: Closure object cannot have properties in /web/wire/core/WireCache.php on line 332`
Seems I can't use a template object as second parameter in $cache->get(). 
PHP version is  5.4.39

**Comment by FlipZoomMedia** [comment]
I can confirm this bug also under PHP 5.5.12.

```php
$templateTrigger = $templates->get("menus");
echo $cache->get("main-navigation", $templateTrigger, function($modules) use($options) {
        return $modules->get("MarkupMenuBuilder")->render("main", $options);
});
```

throws 

```Recoverable Fatal Error: Closure object cannot have properties (line 332 of C:\wamp\www\testing\pw-module-tests\wire\core\WireCache.php)```

**Comment by FlipZoomMedia** [comment]
Thanks Ryan, The problem has been fixed. Can it be that I can not define multible templates? e.g. 

```php
$templateTrigger = $templates->find("name=news|archive");
echo $cache->get("news-content", $templateTrigger, function() use($content) {
        return $content;
});
```

i got the following notice in debug mode: 

```
Notice: Object of class TemplatesArray could not be converted to int in C:\wamp\www\testing\pw-module-tests\wire\core\WireCache.php on line 416
```

**Comment by ryancramerdesign** [comment]
No you can't define multiple templates in that way at least. If given an
object, it expects either a Page or Template object. But you can give it a
selector string that matches pages, and this should work:

`````````
$cache->get("news-content", "template=news|archive", function() { ... }
`````````

**Comment by FlipZoomMedia** [comment]
True, works. Excellent Ryan. Thank you.
