### ISSUE TITLE
2.5.28 Method Template::getFormatted does not exist or is not callable in this context

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1130]
Pagelist fails after upgrade to 2.5.28. I get an error in the JSON response. (See this title)
Same exception for InputfieldPageListSelect.

```php
// this one is thrown (line 350 Wire.php)
throw new WireException("Method " . $this->className() . "::$method does not exist or is not callable in this context");
```

**Comment by ryancramerdesign** [comment]
Need more information to reproduce this one. If you can identify the page where it's throwing the exception, check that page's template under Setup > Templates > Advanced > Page List Label Field(s). What do you have populated there?

**Comment by Da-Fecto** [comment]
Setup > Templates > Advanced > Page List Label Field(s) was the right direction. For 'List of fields to display in the admin Page List' I had specified **template.label**. Removing template.label and everything works fine again.

**Comment by Da-Fecto** [comment]
The problem still exists in 2.6. 
When ProcessPageList try to create a label for the PageListItem(s) an Exception is throw when template.label is filled in in **Name of page field to display**. (Method Template::getFormatted does not exist or is not callable in this context)

This is the third install where I see this issue.

**Comment by Da-Fecto** [comment]
Latest update for dev fixed the issue. Thanks Ryan !
