### ISSUE TITLE
Datetime cannot handle "Y" format

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1131]
A minor issue, but still annoying to find out. Somehow the input seems to not be converted from a raw year to a timestamp.

**Comment by ryancramerdesign** [comment]
Are you talking about the FieldtypeDatetime? If so, do you have "Y" as the setting for the "input format"? Or are you seeing the result only in the "output format"? Just want to make sure I know what you are talking about.

**Comment by LostKobrakai** [comment]
```json
{
    "year": {
        "id": 204,
        "type": "FieldtypeDatetime",
        "flags": 0,
        "name": "year",
        "label": "Year",
        "dateOutputFormat": "Y",
        "collapsed": 0,
        "size": 25,
        "datepicker": 0,
        "dateInputFormat": "Y",
        "defaultToday": 1,
        "showIf": "",
        "columnWidth": 100,
        "required": "",
        "requiredIf": "",
        "yearRange": "",
        "timeInputFormat": "",
        "placeholder": ""
    }
}
```

This field won't save itself properly. A short try to debug this showed, that the input is recieved as plain text (e.g. 2015) and not as timestamp.

**Comment by LostKobrakai** [comment]
I just checked (out of curiosity) what would be lost of one would just convert timestamps up to 4 digits via strtotime and it's not even 3 hours: 01.01.1970 00:00:00 to 01.01.1970 02:46:39 (0-9999).
Maybe that could be an option (+ warning about this) if one uses a datefield which consists only of an integer value.

**Comment by ryancramerdesign** [comment]
One question though, why bother with using a Date field if you only need to
store a year? Wouldn't an integer be more efficient for that use case?

**Comment by ryancramerdesign** [comment]
As much as I like the 1970s, I'm good with this. I will update. :)

**Comment by LostKobrakai** [comment]
Mostly just consistency and because of having the default option.

**Comment by LostKobrakai** [comment]
Just noticed `datetime::createfromformat($format, $dateString);` would be the better bet instead of `strtotime()`.
