### ISSUE TITLE
Long words breaks out of description

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1132]
Long words like URLs do break out of the boundaries of the description of fields if the `p` element not wide enough. I assume just giving it `word-wrap: break-word` should work, but I don't know if that would be a backdraw for other people.

**Comment by teppokoivula** [comment]
That would definitely be better than allowing them to overflow.. and also much better than `overflow: hidden` :)

**Comment by LostKobrakai** [comment]
I'll close this one here.

**Comment by isellsoap** [comment]
Issue has been reopened here: https://github.com/processwire/processwire-issues/issues/14
