### ISSUE TITLE
Fieldcreation loses all inputs on error

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1133]
If the fieldname in the creation form isn't applicable all other data one entered is lost.

**Comment by ryancramerdesign** [comment]
Are you talking about Setup > Fields > add new? It is true that if the field creation failed, then the label and description won't live on the following page because there was nowhere to store the information (i.e. no field to store it in). Later on I'll add an ajax check to the name field.
