### ISSUE TITLE
PageTable should use Fieldtype::markupValue

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1134]
Same reasons as for ListerPro, which lead to the introduction of this function.

**Comment by LostKobrakai** [comment]
Any news on this?

**Comment by isellsoap** [comment]
I would also be very interested in this. Would be an awesome addition to ProcessWire.

**Comment by isellsoap** [comment]
@LostKobrakai This can be closed, right?

**Comment by LostKobrakai** [comment]
Seems like it. Didn't notice it, as it was in a commit, where Github couldn't serve the whole diff.
