### ISSUE TITLE
Template/Field export textarea should be readonly

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1135]
Minor thing, but would be nice, so that one can't accidentally delete the exported json.

**Comment by ryancramerdesign** [comment]
Hmm, I actually like to be able to edit these things on the spot, which is one of the reasons I like to use JSON and textarea fields. But I suppose I could edit it anywhere... in a separate text editor, or even after pasting. If folks accidentally deleting JSON is a regular issue, I suppose we could make it read only.
