### ISSUE TITLE
Cache: expire time not effecting for stored data

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1136]
I you set a cache data with an expire time example : 3600
and after this data cached, if you change this expire time as 0 its not effecting to stored data. When you call data always getting old stored data.

@ryancramerdesign also when you have time, can you check this post please : https://processwire.com/talk/topic/9789-cache-and-to-be-updated-always/

For cleaning cache i wrote a little function, if core have this specification, could be better.

My little function for deleting cache items from caches table

```
/**
 * Clear Cache DB Data for given prefix name if like or not like
 *
 * @param string $prefix
 * @param bool $prefixDelete
 */
function clearCache($prefix="Modules", $prefixDelete=false) {
    if($prefix != "") {
        $where = ($prefixDelete) ? "LIKE" : "NOT LIKE";
        wire('db')->query("DELETE FROM caches where Name {$where} '{$prefix}%'");
    }
    return;
}
```

**Comment by ryancramerdesign** [comment]
You mentioned changing the expiration time, but how are you changing the expiration time? You would need to change it when writing the cache, i.e. during `$cache->save()` and not during `$cache->get()`. The get() function doesn't make modifications to the DB unless you also provide a function for writing the cache (as the 3rd argument). But of course, a typical use of get() would be to follow it up with a save() if it returned null. i.e. 
```````
$out = $cache->get('my-cache'); 
if(!$out) {
  $out = "some cached data";
  $cache->save($out, 3600); 
}
```````
or this:
```````
echo $cache->get('my-cache', 3600, function() {
  echo "some cached data";
}); 
```````1

**Comment by trk** [comment]
I have a field added to home template and changing expire time from template directly.

**Comment by trk** [comment]
Using cache like this :
```
$output = $cache->get('my-cache', $cacheExpireValue, function($pages or $page) use(if need some variables need) {
  echo "some cached data";
}); 
```
