### ISSUE TITLE
Delete FIGURE and FIGCAPTION tags when deleting image

### ISSUE THREAD

**Issue by gsbelarus** [ryancramerdesign/ProcessWire#1147]
It is possible to insert image with caption. As a result a set of nested tags figure-img-figcaption will be added to source code of a page. If later one would try to delete image then only IMG tag will be deleted leaving empty and useless figure and figcaption tags.

**Comment by ryancramerdesign** [comment]
As far as I know, there isn't a provision in CKEditor to automatically select parent tags when an img tag is selected. It makes sense though, as one may want to delete an image while leaving the caption to insert another image. But if you want to delete both the image and the figure/caption, you'll need to select both and then delete. In the regular editor mode (as opposed to inline) you can also click the image, then in the status bar at the bottom, click "figure", then delete.
