### ISSUE TITLE
Skip width attributes on image tags not honored

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1151]
When "Skip width attributes on image tags" is checked, the expected result is:

img alt="" src="/site/assets/files/1237/image.jpg"

but the result is 

img alt="" src="/site/assets/files/1237image.jpg" width="96"

**Comment by ryancramerdesign** [comment]
When using hidpi mode, it has to use a width attribute. That "skip width attributions" option is an older holdout that's no longer applicable so likely to be removed soon, but since some are still using TinyMCE we're keeping it there for a bit longer.

**Comment by matjazpotocnik** [comment]
I'm not using hidpi (HiDPI/Retina is not checked), but width is still there...

**Comment by matjazpotocnik** [comment]
Also, when viewing variations, if you check top right checkbox (id=delete_all), nothing happen, I would expect that all images would get checked so that all variations could be deleted.

**Comment by matjazpotocnik** [comment]
Fixed in PW 3.0.79 https://github.com/processwire/processwire/commit/47b87d283bcc2efcc7cd085b1c828799ea773694
