### ISSUE TITLE
Image field with grid option

### ISSUE THREAD

**Issue by jacmaes** [ryancramerdesign/ProcessWire#1152]
I have an image field whose default view is grid. As you can in the screenshot below, the toggle icon is duplicated. If I click on it once, one disappears, but the toggle doesn't work. No JS error in the console. This means that I can't reorder or delete these images.

![double](https://cloud.githubusercontent.com/assets/1206842/7517231/19bf3a9c-f4d4-11e4-9af5-97a141747cd3.png)

I don't know if it makes any difference, but the pages that contain this field are automatically generated by FormBuilder when someone submits a form. Happens in Chrome and Safari on 2.5.29. 

<b>Edit</b>: same behavior with a new page that I created manually. Published or unpublished, same issue.

**Comment by ryancramerdesign** [comment]
I'm not seeing that here in Chrome or Safari (anyone else?). I think we have to look at what 3rd party modules you've got installed in case one of them might be causing the issue.

**Comment by isellsoap** [comment]
@jacmaes Please provide more information to your issue. Is it still one? I close this for now, but if you think the issue requires additional work to do, please add a comment to this issue and I re-open it.

**Comment by jacmaes** [comment]
The issue is still present on various sites using 2.7. I believe it's related to the old Thumbnails module because it's gone if I upgrade to the brand new CropModule3 with PW 3x. Since it only affects legacy sites, I think you can keep this issue closed.
