### ISSUE TITLE
DateTime parsing post php 5.3

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1153]
DateTimes are parsed with `date_parse_from_format` if available ([here](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Fieldtype/FieldtypeDatetime.module#L179)). Now while working on an import script I noticed this behavior from php's date parser:
```php
$date = date_create_from_format("d.m.Y", "04.16.2015");
echo $date->format("d.m.Y");
// Output: 04.04.2016
```
While `date_create_from_format` won't care, the function used by FieldtypeDateTime at least includes a warning:
```php
  ["warning_count"]=>
  int(1)
  ["warnings"]=>
  array(1) {
    [10]=>
    string(27) "The parsed date was invalid"
  } 
```
Wouldn't is be favorable to check for the warning count. At least for me this is not the expected behavior. I would expect this to not work.

**Comment by ryancramerdesign** [comment]
Makes sense to me for it to at least pass along the warnings to the user. I have added this and it will appear in this week's commits.

**Comment by LostKobrakai** [comment]
I've seen your commit. Is there any way I could check for this warning(s) from the api? I'd like to use this to validate dates before importing them.
