### ISSUE TITLE
var_dump notifications field

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1156]
I was just taking a look at the SystemNotifications, when I got this error:
```php
var_dump($users->get("name=benni")->notifications);
```
```
Notice: Trying to get property of non-object in …/wire/core/WireArray.php on line 1715

Fatal error: Call to a member function className() on null in …/wire/core/WireArray.php on line 1716
```
It's a fresh 2.6.0 dev installation with only Reno / SystemNotifications and SessionHandlerDB installed.

**Comment by ryancramerdesign** [comment]
I think your `$users->get("name=benni");` may have returned a NullPage object, so you'd usually need to check the 'id' property of an object like that to make sure you've got something before you attempt to access properties on it. But __debugInfo() in WireArray (which is being triggered by your var_dump) should be able to handle a NullPage without that error, so I have corrected that and it'll appear in this week's commits. Thanks.

**Comment by LostKobrakai** [comment]
I did originally check for the id, but shortened it here for readability. I get the error even when it's a valid user.

**Comment by LostKobrakai** [comment]
Seems to be fixed in the dev branch
