### ISSUE TITLE
Pagetree "move" speedup

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1159]
It would be nice if clicking the "move" action would just halt/abort the ajax request, which retrieves the children. No matter what you'll hit after the moving is started, the children will never be visible and a new ajax request is started regardless, if one wants to see the children again. It's just useless unresponsiveness, that you've to wait for the ajax request to finish.

**Comment by LostKobrakai** [comment]
I'll add this here, because it's not very important, but another "speed" issue.
When clicking the breadcrump of a page, it'll open the pagetree until the clicked page is visible. If the tree is quite deeply nested (> 4/5 levels) this takes quite a lot of time to open. It would be great if the animation would be faster for the parent levels and only slow for the last one, or something equivalent.

**Comment by ryancramerdesign** [comment]
I don't think we can cancel a request already in progress per your first message. Besides, that list is typically already loaded before one could even mouseover to a move link. But I do think we can speed or cancel the animation for a multi-tree open. The animation speed is something we already have configurable in ProcessPageList module settings, so it's relatively easy for us to adjust it on the fly. I haven't noticed any significant speed difference even if I turn off the animation in those settings, but even if it just feels faster it can't hurt.

**Comment by ryancramerdesign** [comment]
Also, you may want to use one of the new $config->pageList settings that lets you see the action links before opening children, as that lets you perform a move without any children loading.

**Comment by LostKobrakai** [comment]
Yeah, didn't think of the setting, as I mostly use Reno, where it's default. 
Aborting AJAX requests should work with this: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#abort%28%29

**Comment by LostKobrakai** [comment]
I just had a look at the change you made. I see now what you meant by no noticeable difference, as the ajax requests still take their time, whereas before the animation kinda hit a sweet spot. Didn't check with the animation-speed setting before. Also I think that disabling the animation completely is to rough, a speedup, maybe even like plain 40–50% of the setting, would be more likely to hit what I meant.
