### ISSUE TITLE
PagePathHistory->getPage($page) public?

### ISSUE THREAD

**Issue by hagcin** [ryancramerdesign/ProcessWire#1163]
I wonder if it would be beneficial if: PagePathHistory->getPage($page) was a public method. If it was you could port the features of PagePathHistory over to other none HTML  mediums such as JSON page APIs. I just copied the method into my JSON pages module for now....super low priority issue, just something to think about.

**Comment by ryancramerdesign** [comment]
I'm not sure I fully understand about the use case, but it sounds good so far, and I'm happy to make it public. I've gone ahead and made it public, so it'll appear in this weeks commits.

**Comment by isellsoap** [comment]
@hagcin Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
