### ISSUE TITLE
Login Fails Using SSL

### ISSUE THREAD

**Issue by wllkle** [ryancramerdesign/ProcessWire#1167]
I have tried both forcing the site to use HTTPS using apache and also from setting it for each template, however every time I try to log in using HTTPS it fails. How can I correct this?

**Comment by cstevensjr** [comment]
Can you provide information about your environment (PW, PHP, MySQL, Apache version) and a little more detail about your situation?

**Comment by isellsoap** [comment]
@wllkle Please provide more information for this issue (if it still is an issue). I close the issue, but if you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
