### ISSUE TITLE
Comments notification email Edit Url is root relative, not full http

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1171]
https://processwire.com/talk/topic/9970-comments-edit-link/

https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Fieldtype/FieldtypeComments/CommentNotifications.php#L114

In general, would it be nice to have a: $page->httpEditUrl

**Comment by gingebaker** [comment]
Just stumbled across this problem...

Changed this Line:
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Fieldtype/FieldtypeComments/CommentNotifications.php#L120

to
```php
$pageEditUrl = strpos($page->editUrl,'http') === 0 ? $page->editUrl : 'http://'.$this->config->httpHost.$page->editUrl;
$value = "<a href='$info[value]'>$page->title</a> (<a href='$pageEditUrl'>" . $this->_('Edit') . ")";
```
editUrl() function could possibly give back an full URL so I did that check for http at the beginning.

**Comment by gebeer** [comment]
This issue still persists for PW 2.7.2 stable.
We should add https check to @gingebaker 's solution:
```php
$protocol = $config->https ? 'https' : 'http';  
$pageEditUrl = strpos($page->editUrl,'http') === 0 ? $page->editUrl : 'http://'.$this->config->httpHost.$page->editUrl;
$value = "<a href='$info[value]'>$page->title</a> (<a href='$pageEditUrl'>" . $this->_('Edit') . ")";
```

**Comment by adrianbj** [comment]
@ryancramerdesign - any chance of fixing this please - it is still a problem in PW 3.

Thanks!
