### ISSUE TITLE
Language Translation: don't remove double content

### ISSUE THREAD

**Issue by NicoKnoll** [ryancramerdesign/ProcessWire#1172]
Issue following this post: https://processwire.com/talk/topic/9854-language-translation-dont-remove-double-content/

> Hey,
if I'm using the Language Translation Tool strings automatically get deleted if they match the original string. This is really annoying because it shows those strings as "blank" in the overview but you can't fix them.
> Why not just let them be as you type them in?

**Comment by jacmaes** [comment]
+1. This is indeed annoying. You never know whether your translation is complete because of this.

**Comment by plauclair** [comment]
:+1: It's confusing when translating.

**Comment by ryancramerdesign** [comment]
This is an intentional behavior not to store duplicate copies of content unnecessarily. It helps the translation tool to be more memory efficient. But I understand what you are saying. I'll see if there is some way around it next time working in here.

**Comment by NicoKnoll** [comment]
I think that small amount of double content is acceptable if it makes it easier for translators to keep their language repos up-to-date.

**Comment by plauclair** [comment]
Some stats to go with this :
Out of 2422 translatable strings, 103 were empty (same as original language). This represents 4%. I would say this is negligible compared to the significant amount of work it adds tracking these.

![trans-vs-unstranslated](https://cloud.githubusercontent.com/assets/171120/8392037/5dfac53a-1ca9-11e5-9f0d-324f7bd0eade.png)

**Comment by NicoKnoll** [comment]
I think German and English have even more same words than French and English. But there are a lot of other languages out there which have no overlap with english at all (like hebrew, russian, thai, japanese, turkey, ...)

So I still think it's a good addition for translators and won't create a huge efficiency gap :)

**Comment by plauclair** [comment]
@NicoKnoll This has been added, can be closed. https://processwire.com/blog/posts/processwire-2.6.23-2.7-rc2-translation-features-license-discussion/#ability-to-specify-does-not-need-translation
