### ISSUE TITLE
FieldAction send_templates sort by "checked"

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1176]
With lots of templates it would be nice if checked templates would be sorted to top. Finding the single checked template out of ~100 templates is not the nicest/fastest thing to do.

**Comment by ryancramerdesign** [comment]
Having ~100 templates is not the nicest/fastest thing to do in general. :) That exceeds the most I've ever used by about a factor of 3. But regardless, I think having a consistent a-z sort is important for anything like this, especially as the quantities grow.

**Comment by LostKobrakai** [comment]
Yeah it's quite some project I'm working on. Maybe it could just be a sortable table with a-z default sort.

**Comment by LostKobrakai** [comment]
Sorting by "populated pages" does exactly what I needed, because it shows 0 even for currently unused templates, while all the other templates without the field in it are blank.
