### ISSUE TITLE
feature request: changelog for module (required)

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1178]
I would appreciate, if every PW module would carry a required changelog file (like WordPress has it) where module authors put some rough information what they changed from version to version.

This info should be easily accessible from the PW website, github, and (as modals like WP?) from the Update module and ModuleManager module, or other places that carry information about modules.

This makes it easier for normal admins to evaluate whether and when to update, and whether this update is security related and/or urgent or maybe raised minimum requirements - without the need to dig into github commit infos.

**Comment by teppokoivula** [comment]
Not sure about *required*, but depending on the implementation I'd be very happy to see some kind of native support for this and perhaps even a few other new module details. For an example, it would be great if ProcessWire could display the license info in Admin (and perhaps even full LICENSE file, if it exists), and being able to view included README file would be neat too.

In a nutshell this could be as simple as checking if certain pre-defined files exist and displaying them, probably in modal windows as suggested above: LICENSE, README, CHANGELOG, etc. (with or without .md extension).

**Comment by tbba** [comment]
*required* I suggested, because it is not so much trouble to pin down some rough hints like "small fixes", "security fix",  "can talk to the washing machine now" but has great benefits to average site maintainers.
But that is only my personal view.

**Comment by tbba** [comment]
too old
