### ISSUE TITLE
Old description in htaccess.txt

### ISSUE THREAD

**Issue by DV-JF** [ryancramerdesign/ProcessWire#1185]
The head of the htaccess.txt file hasn't been updated to newest version. This confused me while updating.

![htaccess-2 6 0 txt -](https://cloud.githubusercontent.com/assets/3637410/7727077/c94ca04e-ff06-11e4-9d25-162531427183.jpg)

Many greets

**Comment by LostKobrakai** [comment]
Old but correct: https://github.com/ryancramerdesign/ProcessWire/issues/1155

**Comment by ryancramerdesign** [comment]
The .htaccess file hasn't changed, so if we update the version number in there then it will ask people to replace it unnecessarily. Basically PW 2.6 uses .htaccess version 2.5 (250). I can add a note about this to our upgrade instructions.

**Comment by tbba** [comment]
I think it would be less confusion if the htaccess and index would be treated like a module with it's own version number that looks different from the PW version number. So no one compares but only let the updater decide if the htaccess and index files are up-to.date.

**Comment by LostKobrakai** [comment]
This would mean that somewhere there needs to be a list which links htaccess / index.php versions to pw version, which is in my eyes only an additional point of failure.

**Comment by tbba** [comment]
For that we have a software :-)
