### ISSUE TITLE
Disabling cache for *any* GET or POST params, not just specific ones

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1189]
In most (might even say "all") cases I'd prefer to skip the template / page level cache if GET or POST params are present. Currently I have to make changes to caching settings if I add a new feature that requires either of these, naming all possible params specifically, and this gets worse if it's a site-wide feature.

I'd really prefer the cache to go away (don't cache content, don't serve cached content) if said params are present -- current behaviour seems counterintuitive, to be honest -- but since that would be a pretty big change to how this works, a wildcard setting would be nice.

**Comment by ryancramerdesign** [comment]
I completely agree, and not sure why we didn't have this before. I have updated it to support an asterisk (*) as a way to specify "any", and it will appear in this weeks commits. Thanks for letting me know.

**Comment by teppokoivula** [comment]
Sounds good to me, thanks! :)
