### ISSUE TITLE
CKEditor PWLink not honouring trailing slashes

### ISSUE THREAD

**Issue by mikerockett** [ryancramerdesign/ProcessWire#1192]
This seems to be a recent change, as it wasn't happening a few months ago on a site I've been building in my spare time.

When inserting a link, using "Select Page", it doesn't honour the trailing slash setting assigned to the template.

As a result, this could increase server load in terms of 301s to remove the slashes.

At the moment, I'm having to manually remove the slash for each link that I insert using "Select Page".

Haven't checked, but could this be in relation to #961, where the `path` is used, not the `url`?

**Comment by ryancramerdesign** [comment]
Looks like you are right! I was able to duplicate and fix the issue, and it will appear in this weeks commits. Thanks!

**Comment by mikerockett** [comment]
:+1:

**Comment by isellsoap** [comment]
@mikerockett Can this issue be closed?

**Comment by mikerockett** [comment]
@isellsoap - indeed, thanks for the reminder. :wink:
