### ISSUE TITLE
Entity encoding issue in breadcrumb

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1194]
![screenshot 2015-05-22 16 31 40](https://cloud.githubusercontent.com/assets/2489835/7772711/212949da-00a0-11e5-93a8-5f0af84ff18b.png)
Version 2.5.29

**Comment by ryancramerdesign** [comment]
I'm not seeing that issue here. Tried with both single language and multi-language just in case there was something there, but not getting double encoding of the breadcrumb the way your screenshot shows. Any idea how to reproduce it on a blank/default install?

**Comment by LostKobrakai** [comment]
Sadly not. Did only notice it on this exact page. Will see what I can find out about it.

-- 
www.kobrakai.de | Bauernstraße 5B | 86508 Rehling | 015221616149

**Comment by isellsoap** [comment]
@LostKobrakai Can this issue be closed?
