### ISSUE TITLE
has_parent buggy

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1195]
```php
var_dump($pages->find("has_parent=7438, id=8383, include=all, check_access=0")->implode(", ", "id"), $pages->get(8383)->parent("id=7438")->id);
// Output:
// string(0) "" int(7438)
```
This is somehow not the case for all pages, but only some of them won't be found with `has_parent`.

**Comment by LostKobrakai** [comment]
I just found some time to debug this further. The problem was, that cloning a page didn't update the `pages_parents` table. Just after moving a child of the newly cloned page to the "was cloned" page and moving it back the table was updated and resolved the issue.

**Comment by ryancramerdesign** [comment]
That's some excellent debugging work there. We've known there is some issue
where pages occasionally go missing from pages_parents, and this has been
the case since the beginning... but haven't known the source. I'm not near
the code to look closer at it now, but this sounds like it's got to be it.
Thanks!

**Comment by LostKobrakai** [comment]
No problem. I get to know the core better and it's always easier to work on the error at sight instead of letting you search in the dark.

**Comment by somatonic** [comment]
This was known for a long time and that is had to do with pages_parents and most likely clone https://processwire.com/talk/topic/8585-issue-with-has-parent-selector/ only one of the many threads about that issue.

I even reported the issue and with the info that it happend on page clone https://github.com/ryancramerdesign/ProcessWire/issues/404
