### ISSUE TITLE
Admin:Users: Can't save page fields of logged in user (since 2.6)

### ISSUE THREAD

**Issue by hagcin** [ryancramerdesign/ProcessWire#1196]
Unable to save custom page fields such as radios, and selects of the user that is logged in. My test account is superuser,and is un-able to  change custom values of own user profile.  I can however change built-in fields such as admin theme.  I can also change the fields of other user accounts. Just not the fields of the account that is logged in. 

After user save, values to not change for custom page select boxes or radios in user account of logged in user.

Just tested this on another install and can verify it seems to effect all my 2.6 installs. This was not an issue on 2.57

**Comment by ryancramerdesign** [comment]
So far I can't reproduce this one. Can you confirm if it is literally only "select" and "radio" fields that you can't save, or is it any extra field that you add to the user template? (like text and other fields?). Also, can you double check that you have these fields allowed in your Profile module configuration (Modules > Core > Process > Profile).

**Comment by ryancramerdesign** [comment]
Also, we'd next want to look at what 3rd party modules you have installed, in case one of them might be interfering. Please list all modules you have installed in Modules > Site.

**Comment by hagcin** [comment]
Thanks for the help Ryan.  When I changed modules > core > profile  settings and allowed the fields everything works great. i've been wondering where I could change what shows up in the user profile...Anyway, I think the problem is when you try to edit your user account through: access > users, you see all fields, can change them, but there is no warning as to why you can not save changes to them (only for the logged in user account, all fields unselected in Modules >core>process>profile). 

Modules
Admin Page Hider, ColorPicker, FieldtypeCroppableImage, ProFields: Table, ProFields: Textareas, Hanna Code Helper, LDAP Authentication, jQuery DataTables Plugin, Modules Manager, SEO, Page List Better Labels, Page Path History Manager, Database Backups,  Hanna Code, Page Delete, Version Control. + 5-6 custom modules that Hook Page save, and Page Tree Listings and actions.

Note: your fix worked great, id consider it closed if you can't reproduce any of it, ill see if I can find the offending module maker (maybe it's me) and let them know about the bug.

**Comment by madebymats** [comment]
I have the same issue in a URL-field. When trying to save, field is empty. Everything was working fine until 2.6 upgrade. Let me know If you would like to get access to the site.
