### ISSUE TITLE
2.6.0 Translate file in admin picks up only first translateable string in line?

### ISSUE THREAD

**Issue by roterkater** [ryancramerdesign/ProcessWire#1198]
`$out .= __("String1") . __("String2");`

Will only pick up "String1".
New line will work.

thanks & cheers

**Comment by ryancramerdesign** [comment]
This is the proper behavior. This is how it supports meta data related to
the translation within PHP comments. More info here:
https://processwire.com/api/multi-language-support/code-i18n/#there-may-only-be-one-translation-function-call-per-line

**Comment by roterkater** [comment]
oh ok, thanks.
