### ISSUE TITLE
Module auto uninstall from API fails with "You do not have permission to execute this module"

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1199]
ProcessVersionControl requires VersionControl and VersionControl installs ProcessVersionControl, so the Process module should be automatically uninstalled with the main module. From the Modules page this works as expected, but when VersionControl is uninstalled via API, ProcessVersionControl remains intact.

Everything else works as expected (`getUninstalls()` returns the Process module, PW tries to uninstall it, etc.) but the problem seems to be that the Process module defines a permission (`'permission' => 'version-control'`), and because of that the API user can't access the module at all.

I'm assuming that this isn't expected behaviour; shouldn't the API user be able to access all modules, regardless of permissions? At least the built-in auto-install procedure shouldn't fail because of this.. :)

I'm getting this with 2.6.1 dev, and the easiest way to reproduce it is as simple as installing the VersionControl module manually, and then running a script that bootstraps PW and executes `wire('modules')->uninstall('VersionControl')`.

**Comment by ryancramerdesign** [comment]
Thanks Teppo, this issue has been fixed.

**Comment by teppokoivula** [comment]
Confirmed, works as expected now. Thanks!
