### ISSUE TITLE
Negated selector in OR group not recognized 

### ISSUE THREAD

**Issue by tuomassalo** [ryancramerdesign/ProcessWire#1200]
I'm building a combination of selectors programmatically and I'd like to use arbitrary selector operators within a named OR group. It seems I can't use the generalized form of selector negation there. This doesn't work:

    my_named_or_group=(!body*=sushi tobiko)

Is it just a bug in the selector parser?

For now, I think I can work around it by detecting the situation and then adding an additional `id>0` hack, eg.:

    my_named_or_group=(id>0, !body*=sushi tobiko)

But that's an ugly hack. :)

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed in the latest commit.
