### ISSUE TITLE
SQL Errors from new System Notifications module following upgrade from 2.4 to 2.5 dev/2.6

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1203]
I posted about this in the forums a while ago and now think I've narrowed the issue down to the System Notifications module. See the forum thread for more details.

https://processwire.com/talk/topic/9526-strange-errors-following-upgrade/

**Comment by ryancramerdesign** [comment]
I can't duplicate this one yet. Anyone else see similar errors or know how to reproduce them?

**Comment by thetuningspoon** [comment]
This has now received confirmation from another user (chriswthomson) https://processwire.com/talk/topic/9526-strange-errors-following-upgrade/
