### ISSUE TITLE
New Image cropping tool, manually entered data breaks it.

### ISSUE THREAD

**Issue by hagcin** [ryancramerdesign/ProcessWire#1205]
When using the amazing new image tool, if you go to crop an image, and try to manually enter any kind of data into the text boxes you get all kinds of investing things but not what you would expect. 

![brokencropsettings](https://cloud.githubusercontent.com/assets/6478273/7873856/9c0bc702-0575-11e5-8069-f7fb579e8dff.png)

(the arrows just indicate things that are strange the minute you start entering numbers into the text fields)

Google Chrome Browser, OSX.
Processwire 2.6.0
Themes: Reno and Default

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this issue.

**Comment by isellsoap** [comment]
@hagcin Can this issue be closed?

**Comment by hagcin** [comment]
Yes, please close this one out

**Comment by isellsoap** [comment]
You can do it, I can’t. ;-)

**Comment by isellsoap** [comment]
@hagcin Can you please close this issue? Only you or @ryancramerdesign can do it.

**Comment by hagcin** [comment]
Sure.....no internet last couple weeks, makes keeping on top of this stuff tricky. closing out...
