### ISSUE TITLE
ignore global field on template problem with title

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1206]
When I create a new page where the template has ignore global fields, the title field isn't populated after page is added. It only takes global fields into account.

**Comment by ryancramerdesign** [comment]
Not sure I totally follow, so going to ask more questions. You've got a template with the noGlobal option set, but this template still has a "title" field. You populated a "title" field when adding a new page (?), and the value you entered was lost after clicking submit?

**Comment by somatonic** [comment]
Exactly.

**Comment by ryancramerdesign** [comment]
Okay thanks, I was able to duplicate and fix and it's now committed.

**Comment by isellsoap** [comment]
@somatonic Can this issue be closed?
