### ISSUE TITLE
New clone field doesn't respect compatible field types

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1207]
Just noticed when I went to change a field from one type to another even though I couldn't select the type I wanted (from image to text - yes weird, but actually logical) I could choose an existing text field from the list of fields to clone from.

Personally I prefer this as I never really liked the restriction, but it isn't consistent so should be changed.

**Comment by adrianbj** [comment]
PS It won't actually change it the type, but it suggests that I can change it because the clone list includes these options.

**Comment by ryancramerdesign** [comment]
Thanks, I have fixed this and it will appearing this weeks commits.
