### ISSUE TITLE
cannot create new field with PW 2.6.2

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1208]
On creating a new field I see this brand new error:
"Field name may not be the same as a Language name"

example field name "ddddddddd"
type "text"
Label not set.

With PW 2.6.1, that works.

**Comment by ryancramerdesign** [comment]
Sorry, small mistake on my part, I forgot to add an "->id". It's there now, so should be working if you grab the latest dev commit. Thanks.

**Comment by tbba** [comment]
Yes, fixed. - Thank you for those great new features with this update!!!!
