### ISSUE TITLE
Add support for partial match selectors for templates (^=, $=, %=)

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1210]
Currently, it gives the error `Error: Exception: Operator '^=' is not supported for 'templates_id'`. 

I'm trying to load different templates dynamically when their template name begins with something, for example _newsTwitter, newsRSS, newsLocal_. I'm loading their view/controller files dynamically as well. Right now I need to hardcode all of them, but I'd rather just throw a partial selector at them and not have to worry about it anymore. That would be very helpful. Cheers.

**Comment by somatonic** [comment]
That's already possible

```
$tpls = $templates->find("name^=news");
```

**Comment by ryancramerdesign** [comment]
Assuming this is going into a $pages->find() selector, you'd take Soma's code above and do this:

``````````
$tpls = $templates->find("name^=news");
$items = $pages->find("template=$tpls"); 
``````````

**Comment by plauclair** [comment]
Oh, didn't think of doing that, I was under the assumption that $templates->find and $pages->find were both using PageFinder so the result would be the same.

**Comment by LostKobrakai** [comment]
This would still be useful as for example the lister / inputfieldselector cannot use additional logic. I just tried this to allow page addition of a set of templates via the dynamic roles module. I don't want to add them all manually (big page, lots of templates) because it's not handling changes well this way.

**Comment by tbba** [comment]
I run into this when tryingto set up page-field settings - I got the same error.
All my templates I want to catch start with "p-" but that sort of thing does not work there:
template^=p-
and I wished it was.

**Comment by somatonic** [comment]
"template.name^=p-" works fine

'template' isn't a text you can search but and object.

**Comment by LostKobrakai** [comment]
That doesn’t work here. It’s throwing an internal server error on 
the frontend and the lister shows the same error message as without the 
name.

**Comment by tbba** [comment]
@soma: I still get: Operator '^=' is not supported for 'templates_id'.

**Comment by somatonic** [comment]
Don't know for lister but for pagefield selector it works fine here.

**Comment by somatonic** [comment]
template.name^=

Not 

template^=

**Comment by tbba** [comment]
input in page-field/settings/selector:
template.name^=p-, include=hidden, sort=alpha
->error on page that uses this field:
Operator '^=' is not supported for 'templates_id'. 
Interesting. What are you doing differently...

**Comment by somatonic** [comment]
Nothing different. What PW Version?

**Comment by somatonic** [comment]
I think I see why. The page field I'm using is a PageListSelect+. Only after saving it's checking the selector and in my PW2.5.22 version, it's using $page->matches($selector) only for when saving selected pages, which seems to work fine. In my case It's not using the selector to find pages.

However in PW.2.6.1 there a different new code in there that does a $this->page->find($selector), which may even throw an error in my case, but haven't tested.
