### ISSUE TITLE
FieldtypeOptions allow for manually set ids

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1211]
I just wanted to create some radio buttons to "replace" a checkbox, but the fieldtype doesn't allow me to set my id's to match the ones provided by a checkbox.
```
1=Yes
0=No
```
I had another issue with this before, where I used it to set some statuses. Further down the road I needed to fit a new status between the existing ones, where the automatic assigning broke the order of the statuses.
```
1=First Status
2=Second Status
4=Third Status (new one)
3=Fourth Status
```
This denies any use of `status>=3`. I needed to recreate the whole field.

I understand that it's nice to have this automatic assignment, but it can be quite annoying as well, so maybe a "override" option for these times would be nice.

**Comment by ryancramerdesign** [comment]
You can assign your own values if you want to. But once assigned and in use, they can't be changed because they are relational references in the database. Changing them would break those relations. It's like changing the ID of a page–anything else that was pointing to it would no longer be. You could attempt to change the IDs directly in the DB, but be very careful.

**Comment by LostKobrakai** [comment]
I'm aware of that, but sometimes in the course of development this wouldn't matter. But if you don't want to change this I'm ok with it. I just would really like the ability to assign the id's myself at creation time, like for the first example.

**Comment by ryancramerdesign** [comment]
You can already assign the IDs yourself at creation time, at least that's the intention. However, I don't think MySQL would accept 0 as an ID (as in your first example).

**Comment by LostKobrakai** [comment]
Ok as this is probably the case because of the zeroEqualsEmpty topic I should just accept it. If this https://github.com/ryancramerdesign/ProcessWire/issues/1212 can be resolved I can build an inputfield to replace the checkbox with Yes/No Radios.
