### ISSUE TITLE
Show in the add-page shortcut menu? = Yes. Doesn't work for templates with parent assigned as home

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1213]
Might me a difficult one to hunt down but here goes.

Assigned to my home page
Template = home
May pages using this template have children? = Yes
Can this template be used for new pages? = No
Allowed template(s) for children = page

Template = page
May pages using this template have children? = No
Can this template be used for new pages? = Yes
Allowed template(s) for parents = home

This will not appear in the 'Add New' dropdown for my editors, but it will for me as a superuser. There is a template which does appear in the dropdown for my editors and me as a superuser with exactly the same setup, however the page is not the root.

If you would like a login (superuser/editor) to check this just let me know.

**Comment by ryancramerdesign** [comment]
The conditions for something to appear in the "Add New" box also are connected to access control. On your "home" template "Access" tab, your "editor" role user would need "add" permission. On the "page" template, your editor role user would need "create" permission.

**Comment by cb2004** [comment]
Yeah, was my misunderstanding early on using Processwire. Closing this issue.
