### ISSUE TITLE
FieldtypeOptions Error using API getOptions()

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1214]
$field = $fields->get(164); // instance of FieldtypeOptions
$module = $modules->get('FieldtypeOptions');
var_dump($module->getOptions($field));

Error: Call to a member function className() on null (line 1716 of .../wire/core/WireArray.php)

**Comment by ryancramerdesign** [comment]
Just looking in the code for this one, I think this issue may have already been fixed. At least I can see that we confirm the value is a WireData object before attempting to access className() from it, so the error mentioned doesn't seem possible, at least not any longer… I seem to recall adjusting this a few weeks back.

**Comment by kixe** [comment]
confirmed. no errors.
