### ISSUE TITLE
Error on adding a page with 2.6.3 

### ISSUE THREAD

**Issue by madebymats** [ryancramerdesign/ProcessWire#1220]
Error: Call to a member function isAlternateField() on a non-object (line 478 of /home/xxxx/xxxx/wire/modules/LanguageSupport/LanguageSupport.module)

**Comment by ryancramerdesign** [comment]
Thanks, is this on an installation with or without the
LanguageSupportFields module installed?

**Comment by madebymats** [comment]
LanguageSupportFields is not installed.

**Comment by ryancramerdesign** [comment]
Okay thanks, I've added an extra check in there that should fix it.

**Comment by madebymats** [comment]
Thanks!
