### ISSUE TITLE
Editing inserted image in CKeditor when using pagefileExtendedPaths gives error

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1222]
I have a body field and an images field on a template added to a page table. Inserting the image works fine, but as soon as I want to edit the image I get error in the modal:

TemplateFile: Unknown page
#0 /home/www-update/verband.update.ch/wire/core/Modules.php(441): ProcessPageEditImageSelect->init() #1 /home/www-update/verband.update.ch/wire/core/Modules.php(1012): Modules->initModule(Object(ProcessPageEditImageSelect), false) #2 /home/www-update/verband.update.ch/wire/core/Modules.php(919): Modules->getModule('ProcessPageEdit...') #3 /home/www-update/verband.update.ch/wire/core/ProcessController.php(155): Modules->get('ProcessPageEdit...') #4 /home/www-update/verband.update.ch/wire/core/ProcessController.php(232): ProcessController->getProcess() #5 [internal function]: ProcessController->___execute() #6 /home/www-update/verband.update.ch/wire/core/Wire.php(387): call_user_func_array(Array, Array) #7 /home/www-update/verband.update.ch/wire/core/Wire.php(325): Wire->runHooks('execute', Array) #8 /home/www-update/verband.update.ch/wire/core/admin.php(93): Wire->__call('execute', Array) #9 /home/www-update/verband.update.ch/wire/core/admin.php(93): ProcessController->execute() #10 /home/www-update/verband.update.ch/wire/modules/AdminTheme/AdminThemeDefault/controller.php(13): require('/home/www-updat...') #11 /home/www-update/verband.update.ch/site/templates/admin.php(15): require('/home/www-updat...') #12 /home/www-update/verband.update.ch/wire/core/TemplateFile.php(169): require('/home/www-updat...') #13 [internal function]: TemplateFile->___render() #14 /home/www-update/verband.update.ch/wire/core/Wire.php(387): call_user_func_array(Array, Array) #15 /home/www-update/verband.update.ch/wire/core/Wire.php(325): Wire->runHooks('render', Array) #16 /home/www-update/verband.update.ch/wire/modules/PageRender.module(393): Wire->__call('render', Array) #17 /home/www-update/verband.update.ch/wire/modules/PageRender.module(393): TemplateFile->render() #18 [internal function]: PageRender->___renderPage(Object(HookEvent)) #19 /home/www-update/verband.update.ch/wire/core/Wire.php(387): call_user_func_array(Array, Array) #20 /home/www-update/verband.update.ch/wire/core/Wire.php(325): Wire->runHooks('renderPage', Array) #21 /home/www-update/verband.update.ch/wire/core/Wire.php(409): Wire->__call('renderPage', Array) #22 /home/www-update/verband.update.ch/wire/core/Wire.php(409): PageRender->renderPage(Object(HookEvent)) #23 /home/www-update/verband.update.ch/wire/core/Wire.php(325): Wire->runHooks('render', Array) #24 /home/www-update/verband.update.ch/wire/modules/Process/ProcessPageView.module(187): Wire->__call('render', Array) #25 /home/www-update/verband.update.ch/wire/modules/Process/ProcessPageView.module(187): Page->render() #26 [internal function]: ProcessPageView->___execute(true) #27 /home/www-update/verband.update.ch/wire/core/Wire.php(387): call_user_func_array(Array, Array) #28 /home/www-update/verband.update.ch/wire/core/Wire.php(325): Wire->runHooks('execute', Array) #29 /home/www-update/verband.update.ch/index.php(241): Wire->__call('execute', Array) #30 /home/www-update/verband.update.ch/index.php(241): ProcessPageView->execute(true) #31 {main}

Page table is setup to add page to a parent inside /admin/ with automated page name and they have no title.

**Comment by somatonic** [comment]
Just tried to edit the page not through page table modal but directly and it's same error.

I also tried to move the page table parent outside the /admin/ and still same error.

**Comment by somatonic** [comment]
I think it has to do with the 
$config->pagefileExtendedPaths = true;

**Comment by ryancramerdesign** [comment]
What version of PW? Can you tell what the full URL is (including all GET vars) when the error is thrown?

**Comment by somatonic** [comment]
I'm stumbling over this still and again. It's a bug.

<img alt="" src="/site/assets/files/0/05/534/logo_sig.jpg" width="601" />

The modal has this url which shows it's using 534 as the page id and not 5534...

http://domain.com/processwire/page/image/?id=534&edit_page_id=5534&modal=1&file=logo_sig.jpg&width=601&hidpi=0&winwidth=1893

**Comment by ryancramerdesign** [comment]
Thanks Soma, seeing the image tag and resulting modal URL answered all I needed to know–the rest was easy. I've pushed a fix to the dev branch.
