### ISSUE TITLE
Image alternate language fields doesn't get recognized when using $item->render()

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1227]
I have image fields

image
image_fr
image_en

Code in template is 
```
if($page->image) echo "<img src='{$page->image->size(500,0)->url}'>";
```

If use this directly in template to render image, it works fine. If the alternative image field isn't populated it takes the "image" field. As expected.

However, this isn't the case when I use $item->render(), where $item is a page with those image fields. When there's no "image_fr" image it won't output default "image".

**Comment by somatonic** [comment]
For whatever unexplainable reason, it suddenly works fine.

**Comment by ryancramerdesign** [comment]
Initially I'm thinking maybe your $item page had output formatting off? Glad to hear it's working now though. I'll close this out, but please re-open if you find a way to reproduce it.
