### ISSUE TITLE
Rendering using wireRenderFile() memory exhausted

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1228]
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in /Applications/MAMP/htdocs/verbandsnet/wire/core/WireData.php on line 90

When I'm using 

```
$content .= wireRenderFile("views/" . $block->template->name, array("page", $block));
```

using page->render works fine

```
$content .= $block->render();
```

I'm lost.

**Comment by somatonic** [comment]
I'm using this in other places, where it seems to work fine. The pages in question aren't big, just body field and image field.

**Comment by somatonic** [comment]
I have no idea why but after trying around now again since friday on this issue, it's working without memory error. On both, prod server and local install it suddenly works without changing something.

**Comment by LostKobrakai** [comment]
Maybe any php caching enabled?

**Comment by somatonic** [comment]
Could be most likely the reason, but don't know for sure.

**Comment by ryancramerdesign** [comment]
If something wasn't working before, and started working on its own, then most likely an opcode cache got cleared. Though please re-open if you find it to be something else. In particular, look for any nested wireRenderFile() calls that might be creating a circular reference, as that's the only scenario I can think of where this error might occur.
