### ISSUE TITLE
cloning templates and field overrides

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1230]
Not sure this has been mentioned before:
If I clone a template, the field overrides (labels, look and behavior) set in the source template get all lost in the template clone, so it is not a real clone. It can be a source for errors if I forget to fix the fields and it is a bit tedious to go through all the fields to update them manually sometimes.

**Comment by ryancramerdesign** [comment]
Those settings aren't actually part of the template (or field) per se, so they don't get inherited by the clone. But I agree they should and it would be nice to have it clone those too. I'll look into this.

**Comment by tbba** [comment]
I close my remaining "feature request" out of here...

**Comment by matjazpotocnik** [comment]
And don't forget to open a new feature request later on, I'm also interested in fixing that template cloning issue...
