### ISSUE TITLE
Orphaned Table Rows Issue

### ISSUE THREAD

**Issue by cstevensjr** [ryancramerdesign/ProcessWire#1231]
I have been having an issue with a client's internal website that showed up when I tried to display two page fields in a Page Table on the front-end.  My investigation over the last couple of days has led me to finally look at the PW title field.  When I checked it I got the following error:

![field-title-error](https://cloud.githubusercontent.com/assets/7488817/8131133/1701b072-10cd-11e5-9e2f-2ab5636e9ce3.png)

Versions are PW 2.6.3, PHP 5.5.21, MySql 5.0.11-dev on a shared hosting account.

Any guidance on how to correct/fix this is greatly appreciated.  Note:  I am currently working with the client's hosting provider to get the MySQL version updated.

**Comment by ryancramerdesign** [comment]
Any PW installation that began with one of the older versions will have those titles in there. They were incorrectly created in our install.sql in the original version of PW, and a few versions after (up to PW 2.4 I think). It's okay to remove them with the check field utility. There's also no harm in leaving them there either, but they don't need to be there.
