### ISSUE TITLE
InputfieldSelector parse issue

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1232]
I just tested the dynamic roles module and the selector fields do save the following selector the wrong way: `has_parent|id=1019|1024` will get `has_parent=1019|1024, id=1019|1024` after saving. The default lister in Pages > Find will get even more crazy:

![screenshot 2015-06-12 16 49 30](https://cloud.githubusercontent.com/assets/2489835/8132599/256dfc00-1123-11e5-9c36-127495292202.png)

From what I've seen it looks like the module was still saving what I wanted.

**Comment by ryancramerdesign** [comment]
has_parent is not actually a field, but a function. As a result, I'm pretty sure it can't be combined in an OR context, at least not in a way that would work reliably. I will take a closer look later to confirm.

**Comment by LostKobrakai** [comment]
It seems to do what I want it to do. It's just not showing it in a reasonable way after saving this selector.

**Comment by LostKobrakai** [comment]
Ah I've just now discovered what this means. I thought it's just an inconsistency with the way InputfieldSelector works. But it's not working at all. `has_parent=1100|1234, template=bp_trainer_invoice` seems to break after the first "has_parent" id and therefore just shows all the subpages of the first page. I'd really need OR support for the has_parent selector for situations like this:
```
project 1
    - jobs
        - job #1
        - …
project 2
    - jobs
        - job #1
```
Sometimes I need to call even deeper nested pages under multiple parents.

**Comment by LostKobrakai** [comment]
It's already trying to do it the right way, but it's missing the parenthesis. I'm not sure if this is still related to the InputfieldSelector issue, but now it's already here.

```sql
SELECT pages.id,pages.parent_id,pages.templates_id 
FROM `pages` 
WHERE 
	( # missing
	pages.parent_id IN (SELECT pages_id FROM pages_parents WHERE parents_id=10409 OR pages_id=10409) 
	OR pages.parent_id IN (SELECT pages_id FROM pages_parents WHERE parents_id=10522 OR pages_id=10522) 
	OR pages.parent_id IN (SELECT pages_id FROM pages_parents WHERE parents_id=11727 OR pages_id=11727) 
	) #missing
AND (pages.templates_id=129) 
AND (pages.status<1024) 
GROUP BY pages.id
```

**Comment by jlahijani** [comment]
I'm running into this issue as well.

On a code level, the following doesn't work correctly:
```
if( $page->is("id|has_parent=123") ):
```

Nor does this:
```
if( $page->is("id=123|has_parent=123") ):
```

However this does:
```
if( $page->is("id=123") || $page->is("has_parent=123") ):
```

**Comment by LostKobrakai** [comment]
It seems like `has_parent=1234|1235` does also not work. It al least just broke my OR-groups from working, without even being part of them.

**Comment by LostKobrakai** [comment]
@ryancramerdesign Could has_parent at least throw a big red error if it's used with multiple id's? This can cause serious memory leaks:
![screenshot 2016-02-22 16 25 19](https://cloud.githubusercontent.com/assets/2489835/13222612/feaab44c-d980-11e5-9d2a-1c5c0f345d97.png)
9 seconds off, just by fixing a wrong has_parent value.

**Comment by LostKobrakai** [comment]
Some additional info:
```php
$pages->find("has_parent=$projects, template=ap_address")->count(); // 1177 (Wrong)
$hasParents = $projects->implode(", ", "(has_parent={id})");
$pages->find($hasParents . ", template=ap_address")->count(); // 84 (Correct)
```
So maybe it could not only throw an error, but actually fallback to what the latter syntax does.

**Comment by LostKobrakai** [comment]
Closing here, the important issue is linked above.
