### ISSUE TITLE
Checking $page->addable() on homepage throws few notices

### ISSUE THREAD

**Issue by apeisa** [ryancramerdesign/ProcessWire#1233]
Running 2.6.1 and when checking $page->addable() where $page is homepage I get few notices:

Notice: Trying to get property of non-object in /.../wire/modules/PagePermissions.module on line 360 
Notice: Trying to get property of non-object in /.../wire/core/PageAccess.php on line 26 
Notice: Trying to get property of non-object in /.../wire/core/PageAccess.php on line 28

**Comment by ryancramerdesign** [comment]
I'm not seeing the same issue here. Maybe it's specific to some context? I'm testing by pasting the following code into my home.php template and then viewing it (with debug mode on). 
````````
if($page->addable()) $content = "<p>page is addable</p>";
  else $content = "<p>page is not addable</p>";
````````

**Comment by apeisa** [comment]
I went for further debugging today, and it was only bug on my code - I was checking the addable() against NullPage object (it came from $page->parent from homepage). Sorry for the false alarm.

All good here, closing!
