### ISSUE TITLE
WireCache character encoding problem

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1235]
I have character encoding problem when trying to cache website data. I have problem on "Turkish" side when i cache the page output.

PW site database charsets :
![screen shot 2015-06-15 at 17 19 24](https://cloud.githubusercontent.com/assets/455983/8161921/d73d5e2e-1382-11e5-854b-e999dba13aef.png)

Caches tables charsets :
![screen shot 2015-06-15 at 17 19 53](https://cloud.githubusercontent.com/assets/455983/8161932/e5bab690-1382-11e5-9979-888e5a2746da.png)

Before Cache :

![screen shot 2015-06-15 at 17 15 35](https://cloud.githubusercontent.com/assets/455983/8161847/59998efc-1382-11e5-928d-12a04d7c4677.png)

After Cache :
![screen shot 2015-06-15 at 17 15 45](https://cloud.githubusercontent.com/assets/455983/8161853/63f05dc2-1382-11e5-9601-f4ea66e85cba.png)

Tested on : v.2.5, v.2.6, v.2.6+
Local and online server
Osx Yosemite (virtual host) and Centos 6.6
PHP 5.5 and PHP 5.6.7

**Comment by ryancramerdesign** [comment]
I can't duplicate here. We might need to take a closer look at your API-side code for getting and saving your cached value. Here is the code I used to test:
````````
$testValue = "ᚠᛇᚻ᛫ᛒᛦᚦ᛫ᚠᚱᚩᚠᚢᚱ᛫ᚠᛁᚱᚪ᛫ᚷᛖᚻᚹᛦᛚᚳᚢᛗ";
$testCache = $cache->get('test');
if($testCache) {
  echo "from cache: " . $testCache;
} else {
  echo $testValue;
  $cache->save('test', $testValue);
}
````````

**Comment by trk** [comment]
For the moment i don't have this issue after update to last dev version and still checking it. I wrote a module https://github.com/trk/AvbFastCache also use other cache types. I will let you know when i have issue again.

**Comment by trk** [comment]
First load is ok, no encoding problem. Second load have character problem.

Here is link for site : http://admiralbeachselimiye.com/ its using my cache module (file) cache, if i turned cache method to WireCache i have character problem.

Also tried directly *$cache->get();* i have same result.

I will write some Turkish words, you can try them :

Tadı Damağımda
Ulaşım
İletişim
Kaptan Köşkü
Kayıkhane

These Turkish words have encoding problem when you try cache them by using *$cache->get()* or *wire('cache')->get()* methods. But fist load is ok, problem on second load. Because first load not getting from database.

**Comment by wanze** [comment]
@trk I just tested this locally with the turkish words you provided (Pw 2.6.6) and it works fine. If you lookup the cache directly in the database, is it stored correctly there? Also check that all the files involved (module, template etc.) are UTF-8 encoded.

**Comment by trk** [comment]
All words i wrote, all coming from database (page titles),

Cache record on database not correct :
<img width="1308" alt="screen shot 2015-07-04 at 17 07 40" src="https://cloud.githubusercontent.com/assets/455983/8508202/cfac0c04-226f-11e5-8fde-706650943609.png">
And i am using PhpStorm as IDE and its always creating files as UTF-8
![screen shot 2015-07-04 at 17 11 54](https://cloud.githubusercontent.com/assets/455983/8508203/cfb0a426-226f-11e5-9551-b07e35ab31b4.png)

**Comment by JanRomero** [comment]
I just noticed this same problem. The 'data' column in table 'caches' turned out to be latin1_swedish_ci. No idea how or when that happened, but since I set it to utf8_general_ci, it's been working fine.

**Comment by trk** [comment]
I have new website created and tested cache, cache look like working there, but on the website i send. There is an error, i checked all record encodings, and they look like true. Anyway i wrote my cache module now and i am using it. For the moment don't have headache, but like @JanRomero say there is an mysterious encoding error...
