### ISSUE TITLE
PageTitle shows "default" language title 

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1239]
![image](https://cloud.githubusercontent.com/assets/370148/8250724/95735448-1676-11e5-8e0a-b25f16a469b0.png)

Can we remove the default language TItle "Deutsch" if using PageTitle (not PageTitleLanguage)

**Comment by somatonic** [comment]
It seems it's because I chose "title_default" as the field name. I renamed the field to "title_neutral" and the "Deutsch" label is gone.

**Comment by LostKobrakai** [comment]
Maybe this should get on the blacklist for fieldnames.
