### ISSUE TITLE
Updating from 6.2.1 to 6.2.4 breaks admin

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1241]
I get this on every admin page, and on PageList it throws unknown error alert and PageList won't show

Notice: Use of undefined constant SORT_NATURAL - assumed 'SORT_NATURAL' in /home/www-data/dev.swissjews.ch/wire/core/Wire.php on line 698 Warning: ksort() expects parameter 2 to be long, string given in /home/www-data/dev.swissjews.ch/wire/core/Wire.php on line 698

**Comment by LostKobrakai** [comment]
The constant is only available since php 5.4, but as long as the official requirements are 5.3.8 this shouldn't happen.

**Comment by somatonic** [comment]
PHP version is 5.4.42

**Comment by ryancramerdesign** [comment]
I didn't realize SORT_NATURAL required PHP 5.4+ when I put it there (though see it now in the PHP docs). No idea why Soma's PHP 5.4 would be missing SORT_NATURAL unless there's something wrong with it, but regardless our requirement is PHP 5.3, not 5.4. So have updated it to use an alternate method when the SORT_NATURAL constant isn't defined. This should accommodate both PHP 5.3, and 5.4 installs that are missing it for whatever reason.
