### ISSUE TITLE
Page list pagination settings has no effect on page tree

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1251]
On 2.6.5 Page list settings doesn't effect the number of page items displayed in the Page tree

![page-list-settings](https://cloud.githubusercontent.com/assets/11423659/8304594/a19d5c6c-19a7-11e5-8bc5-e56975dcd25d.png)

![page-list](https://cloud.githubusercontent.com/assets/11423659/8304595/a1a09fd0-19a7-11e5-83d2-27405d2baf81.png)

.

**Comment by ryancramerdesign** [comment]
Thanks @kalmarlansmuseum I have fixed this and it will appear in this weeks commits.

**Comment by kalmarlansmuseum** [comment]
Thanks, Ryan!
