### ISSUE TITLE
Core Save Reminder doesn't work if CKeditor isn't blured

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1253]
When I enter a Text and leave cursor in CKeditor and then leave the page, it doesn't throw alert.
I have to click outside the editor to get it register. Inline modus.

It works in my FormSaveReminder module.

**Comment by ryancramerdesign** [comment]
This was fixed a couple of weeks ago, but please let me know if you continue to experience it. Thanks.

**Comment by somatonic** [comment]
I can't find where a fix for this was introduced. Using 2.6.1.

**Comment by ryancramerdesign** [comment]
It was fixed in 2.6.3 (dev), see this commit, file InputfieldCKEditor.js:
https://github.com/ryancramerdesign/ProcessWire/commit/1efe44ea81f165c470b9c5ddc61675ab272eea16

**Comment by somatonic** [comment]
Ok, I'm not updating to dev anymore. I'll use my FormSaveReminder then.
