### ISSUE TITLE
$pages->find("include=unpublished") returns hidden pages also

### ISSUE THREAD

**Issue by dadish** [ryancramerdesign/ProcessWire#1255]
The `$pages->find("include=unpublished")` returns pages with `hidden` status also. I'm not sure if this is a bug or proper behavior. Does hidden status means it is also unpublished?

The [API page](http://processwire.com/api/selectors/#access_control) does not mention the exact behavior for `include=unpublished`.

If this is not a bug then it should be documented in the API page.

**Comment by LostKobrakai** [comment]
The include flag does always return all pages up to the queried status. The order of these statuses is `hidden`, `unpublished`, `trash`, `all`. If you need only un-/published pages, without the hidden ones, then use `include=unpublished, status!=hidden`. While it's not laid out perfectly this behavior is implicitly stated in the description the status flag directly after the include part.

**Comment by dadish** [comment]
I see now. Thank you for clearing that out.
