### ISSUE TITLE
Page name length, doublicates with the adjustName option hangs up PW and possibly MySQL

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1260]
I had strange timeouts on a import script. After hours of debugging it turned out the problem lays in too long page name set and adjustName save option. It works the first time, but the second time, if the page already was created with that name, so adjustName would come into play it fails with a timeout.

Further more on our live server where this happened, there seemed to be a process running still for 15-20 minutes where it was trying to insert pages but failed, yet the pages autoincrement ID was filled up to millions. So a new page inserted after that happened it used a significant higher ID than the last entry. Like last page was ~140000 before that happened, and after that the next page id was ~30'000'000. We're now at 750'000'000.

You can reproduce this with a code like following. Execute it two times 
```
$p = new Page();
$p->template = "basic-page";
$p->title = "test";
$p->name = "akjssd dhakjadasdsh askldhalksdh aklshdalkdhlkasdoawiueopiudfiashudasiu dauishd aisuh daisuhd liasuhd liash dlaisdhalishd alishd alisdhu asd asd asd";
$p->parent = "/about/";
$p->save(array("adjustName" => true));
```

**Comment by ryancramerdesign** [comment]
Thanks Soma, I've tracked down the issue and will be included in this weeks commits.

**Comment by isellsoap** [comment]
@somatonic Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
