### ISSUE TITLE
Double 'notes' in Profields Textareas

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#1266]
Cosmetic: the 'Notes' field information of ~~ProTable~~ Textareas is displayed twice. Once underneath each table entry and once underneath the whole field. (latest Dev, ~~proTable 7~~ Textareas 5)

![double-note](https://cloud.githubusercontent.com/assets/5285663/8407949/ffc07e28-1e6b-11e5-8939-e31e4a5ada77.png)

**Comment by junofornow** [comment]
My mistake. I meant Profields Textareas instead of Table.

**Comment by ryancramerdesign** [comment]
Thanks–I have corrected this in the Textareas ProField and it will appear in the next Textareas ProFields version. I'll close this issue out since not PW core, but thank you for letting me know about it.
