### ISSUE TITLE
Auto-Link on processwire.com looks wrong

### ISSUE THREAD

**Issue by NicoKnoll** [ryancramerdesign/ProcessWire#1267]
![bildschirmfoto 2015-06-29 um 17 03 35](https://cloud.githubusercontent.com/assets/1143670/8410866/2294ca66-1e81-11e5-8dbc-685700240c3b.png)

**How to fix:**
Add "display: inline-block;" to "#main p>code".

**Comment by ryancramerdesign** [comment]
Thanks Nico. I'm actually not seeing that issue on the site (as shown in your screenshot), but went ahead and added the CSS rule anyway. Though did notice on that particular page, there was no space between the word and the URL (directly in CKEditor) so went ahead and added that.
