### ISSUE TITLE
Datetime field multilanguage inconsistancy

### ISSUE THREAD

**Issue by Rayden** [ryancramerdesign/ProcessWire#1268]
## Datetime Field

With a multilanguage set up the following two fields can each have an unique value per language:
- Date Input Format Code
- Time Input Format Code

Altough the Select boxes are not seperated per language
- Date Input Format
- Time Input Format

Is this an inconsistancy, where the select boxes should be multiple (per language) instead of single?

**Comment by ryancramerdesign** [comment]
You may be right, it might be helpful to have multiple select boxes there. But in this case, the select box is just a helpful way to pre-populate the input, and not the input itself. I figured one select was enough to show potential date options, while keeping it fairly simple from the code side. But I'll put this in as a future enhancement.

**Comment by Rayden** [comment]
I'm using the input fields to populate this manualy, which works fine. Altough it was mentioned by a new user on the forum. Whom had some difficulties using the select buttons with a multilanguage setup.
https://processwire.com/talk/topic/10312-problem-with-datetime-fieldtype/
