### ISSUE TITLE
Inputfield Page (PageListSelectMultiple) lost selected Pages after second save

### ISSUE THREAD

**Issue by FlipZoomMedia** [ryancramerdesign/ProcessWire#1271]
In the PW version 2.6.6 all values get lost after the second save in the Inputfield "page". Action: I have a Sidebar of the type "Page", I select the sidebar-pages over the add button and save the whole page. If I save the page now once more, all well-chosen sidebar-pages get lost.

**Comment by ryancramerdesign** [comment]
I think this issue was on the dev branch for a day or two, but was fixed in 2.6.7 or earlier. But please let me know if you are continuing to see the issue.

**Comment by isellsoap** [comment]
@FlipZoomMedia Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!

**Comment by ryancramerdesign** [comment]
@isellsoap thanks for your help with identifying issues that can be closed, it's much appreciated.
