### ISSUE TITLE
Options what happens when guest has no view access (redirect to url) multilanguage

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1272]
There needs to be a multilanguage option for the "redirect to a page" option, cause currently it's not usable as only one url can be entered.

**Comment by ryancramerdesign** [comment]
@somatonic for multi-language, you should just enter the page ID you want to redirect to, and multi-language should be retained in that case. I noticed that the field description didn't mention that option, so I am adding it and it will appear in this weeks commits.

**Comment by isellsoap** [comment]
@somatonic This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
