### ISSUE TITLE
Usability issue: Checkboxes labels are display block, which can cause troubles with accidently checked

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1274]
![image](https://cloud.githubusercontent.com/assets/370148/8496998/e27a20ba-2179-11e5-919b-23fb2c5ad1ce.png)

Labels have display: block, which makes the label span 100% in the container. So clicking far right inside white area toogles checkboxes or whatever inputs. See the  blue label box = click area.

It should better be display: inline-block, so it keeps width of label text.

Also single checkboxes have the same issue, even worse when they have no label.

**Comment by ryancramerdesign** [comment]
Thanks @somatonic, good point. I've pushed a fix for this.

**Comment by isellsoap** [comment]
@somatonic Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
