### ISSUE TITLE
this update 2.6.7 produced a https error on my local server

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1276]
I am running some websites under https on localhost with MAMP for Mac.

Backend died - no login possible: 
To many redirects

Frontend shows this:
Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

Have not discovered where this comes from....

UPDATE: it might be useful information:
My SSL Server Port on MAMP is not 443 (that one is blocked by the router) but something else
admin pages are set to "HTTPS only"

**Comment by tbba** [comment]
The LIVE website fontend is ok, the backend is also dead: loop of death

**Comment by ryancramerdesign** [comment]
Any idea what the source might be? The only change involving https this
week was adding PR #1264, so it must be related, but not sure how.
Basically we just make sure we use the secure option when setting the
session cookies. I've tested it out with https on processwire.com and all
seems to be working normally. I will test some more, but if you can think
of any other conditions required to duplicate, please let me know.

**Comment by ryancramerdesign** [comment]
Okay I was just able to duplicate it. If you upgrade just /wire/ without
upgrading also the /index.php, the redirect loop will occur. I don't like
to require an index.php upgrade, so am looking for an alternative.

**Comment by ryancramerdesign** [comment]
I just pushed an update that seemed to fix it for me, and enables me to use
the old index.php file. Though my browser apparently had the old behavior
cached for a bit, because I had to click around on the front-end of my site
for a bit before returning to the admin without the redirect loop. Can you
confirm that it also fixes it there too? Thanks.

**Comment by tbba** [comment]
(Sorry, I was not at my desk for some time.)
The last update fixed all those issues on all my systems (localhost and live).
I am glad you found the problem so fast.

**Comment by ryancramerdesign** [comment]
Great! Glad that did it. Thanks for testing it out.

**Comment by harikt** [comment]
:)
