### ISSUE TITLE
Options field with a multi-value inputfield breaks change tracking

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1277]
Options field with any of the multi-value inputfields selected refuses to work properly with the $page->isChanged() method. This always returns `true` whether or not the field value has actually changed.

One simple way to observe this is to prepend following snippet to /site/templates/admin.php:
```
wire('pages')->addHook('saveReady', function($event) {
    if ($event->arguments[0]->isChanged('options')) {
        $this->message("Field 'options' has changed");
    } else {
        $this->message("Field 'options' has NOT changed");
    }
});
```

... and then follow these steps:

- Create a new Options field called 'options'
- Select any multi-value inputfield for the field
- Add the field to template/fieldgroup 'basic-page'
- Edit any page using template 'basic-page', but don't make changes to the 'options' field

At this point you should see message "Field 'options' has changed", while the "Field 'options' has NOT changed" message is what one would expect to see.

Tested with 2.6.6 and 2.6.7 (latest version of the dev branch at the moment).

**Comment by ryancramerdesign** [comment]
Thanks Teppo, I was able to reproduce and fix this and it will appear in this weeks commits, after a little more testing locally.
