### ISSUE TITLE
User field edit restrictions for superusers

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1278]
PagePermissions.module method userFieldEditable() controls edit permission for user fields depending on the settings in ProcessProfile. Superusers should be excluded from this. Missing code line:
		// superuser can always do whatever they want
		if($user->isSuperuser()) return true;

**Comment by jlahijani** [comment]
+1.  Tested kixe's code and it worked.  Without the fix, as a superuser, I cannot edit my own user fields but am able to edit the user fields of others.

**Comment by ryancramerdesign** [comment]
Thanks guys. There should have been a fix for this in 2.6.7 or 2.6.8 (don't remember which), but please let me know if you still experience the issue.

**Comment by isellsoap** [comment]
@kixe Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!
