### ISSUE TITLE
CKEditor right click link inconsistency

### ISSUE THREAD

**Issue by Rayden** [ryancramerdesign/ProcessWire#1280]
With CKEditor linking some text can be done with the link button from the CKEditor menu bar. This will launch the PWLink module of CKEditor.

Altough right clicking an existing link and chosing "Edit Link" will launch an other (maybe the default) CKEditor link module. Right click link editing should also launch the PWLink module.

**Comment by ryancramerdesign** [comment]
Are you using a PW version prior to 2.6? I am aware that the issue existed in the 2.5 and some 2.5 dev versions, but it was fixed before the 2.6 master version. I can't duplicate the issue on the current PW version, though please let me know if you can.

**Comment by Rayden** [comment]
This issue relates to PW 2.4.1. I was'nt aware it was already fixed in 2.6.
