### ISSUE TITLE
New AdminThemeReno

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1282]
Got this error when opening the modules settings for the first time. After a reload it was gone. I've done a refresh before going to the settings.
`Notice:  Undefined index: notices in …/wire/modules/AdminTheme/AdminThemeReno/AdminThemeReno.module on line 142`

**Comment by ryancramerdesign** [comment]
Thanks, looks like he just had a small typo there and I just fixed it.

**Comment by LostKobrakai** [comment]
Great :)
