### ISSUE TITLE
Notifications not showing

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1285]
I'm not sure if this is just related to systemnotifications (as I'm currently not able to deinstall it) but I'm missing notifications. 

``` php
$this->warning("Shit");
$this->message("Test ".$activeProjects->count());
$this->message($this->pages->count($selector));

// shows
warn: Shit
message: Test 0
```

``` php
$this->warning("Shit");
$this->message($activeProjects->count());
$this->message($this->pages->count($selector));

// shows 
warn: Shit
```

It's really not helpful if you try to debug a module with these, when it's swallowing pure numbers.

**Comment by ryancramerdesign** [comment]
Notifications skip over anything that matches PHP's empty() method, which a "0" does. If there's a strong need to support notifications of "0" then I suppose we could change it to an strlen(), but for the moment I'd suggest prepending some text to at least indicate what the "0" notification means.

**Comment by LostKobrakai** [comment]
Would it be possible to remove this check only for Notice::debug? I think it's nice to have that check in place for all the other notices, but for debugging, without the intention to leave the notices in place, could benefit from showing even a potential 0.

-- 
www.kobrakai.de | Bauernstraße 5B | 86508 Rehling | 015221616149

**Comment by teppokoivula** [comment]
To be honest that sounds like a potential source of even more confusion if one type of notices displays '0', while others skip it entirely.

I haven't had this need yet, but in my opinion 0 and empty string are *not* the same thing, period. 0 has valid use cases, while it's (mostly) logical to skip empty strings. This isn't the only situation where empty() could result in weird issues either; as an example, empty() will consider boolean FALSE empty, while boolean TRUE is not empty, etc.

Admittedly without fully understanding the context, sounds like casting to string and strlen() check would be the safest / most logical thing to do here.
