### ISSUE TITLE
Count subfield not working in PageTables.

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1286]
https://github.com/ryancramerdesign/ProcessWire/blame/master/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.module#L378

This line doesn't support the count subfield. I changed it to this:
```php
if($property == 'count') $value = $object->$property;
else $value = $object->implode("\n", $property); 
```

**Comment by ryancramerdesign** [comment]
Thanks, I have updated and it'll appear in this weeks commits.

**Comment by isellsoap** [comment]
@LostKobrakai Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
