### ISSUE TITLE
InsertAfter on forms enhancement

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1287]
It's really unintuitive when editing a deeply nested form, like the one in ProcessPageEdit, that insertBefore and insertAfter do not work when `$existingitem` is not a direct child of the form, while you've to think the `$existingitem`should really be enough information to append/prepend things to. I'm constantly using the first returning line of this enhanced function. 

```php
public function insertAfter(Inputfield $item, Inputfield $existingItem) {
	// Use parent of $exisitingitem if it's not $this
	if(!$this->children->has($existingItem) && $this->getChildByName($exisitingitem->attr("name")))
		return $existingItem->parent->insertAfter($item, $existingItem);

	$item->setParent($this); 
	$this->children->insertAfter($item, $existingItem); 
	return $this; 
}
```

**Comment by ryancramerdesign** [comment]
You are dealing with a potential tree of items here, and insertAfter/InsertBefore are specific to the level that you are on. I can adjust that to consider the entire children tree rather than just direct children. But here's an easy way to accomplish what you are trying to do: 
`````
$existingItem = $form->getChildByName('field_name');
$existingItem->parent->insertAfter($newItem, $existingItem); 
````

**Comment by ryancramerdesign** [comment]
What you suggested was an easy addition–thanks. I went ahead and updated insertAfter(), insertBefore() and remove() to support it, and it'll appear in this weeks commits.

**Comment by Da-Fecto** [comment]
:-) Thanks Ryan!

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Da-Fecto** [comment]
@isellsoap, I can't close this issue...
