### ISSUE TITLE
Hide modules with only InputfieldHidden in settings

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1290]
Modules with an InputfieldHidden are still shown as "configurable", while technically it's not thought to be edited via the modules interface. Maybe they can be hidden from there.

**Comment by yckart** [comment]
Yeah, I've also had thought about that. It's quite confusing, because I always think "Ouh great, there's something new to configure"...

With *they can be hidden*, you mean the Settings button, right?

**Comment by LostKobrakai** [comment]
I meant the literal InputfieldHidden, but visibility settings should probably be included as well in such a feature.

**Comment by adrianbj** [comment]
Just for reference - similar issue?: https://github.com/ryancramerdesign/ProcessWire/issues/516#issuecomment-46083158 - read the second half of Ryan's response.

> The presence of the Settings button just means that the module implements the ConfigurableModule interface and has the potential to be configured. While in most cases that also means there are fields for you to populate, that's not always the case.

**Comment by yckart** [comment]
I have too much time 😆 

> that's not always the case

**Yepp**
- AdminThemeDefault
- AdminThemeReno
- CommentFilterAkismet
- FieldtypePage
- FileCompilerTags
- InputfieldPage
- InputfieldPageName
- InputfieldSelector
- JqueryWireTabs
- LanguageSupportPageNames
- MarkupCache
- MarkupRSS
- PageFrontEdit
- PageRender
- ProcessField
- ProcessForgotPassword
- ProcessLanguage
- ProcessPageAdd
- ProcessPageEdit
- ProcessPageEditImageSelect
- ProcessPageEditLink
- ProcessPageList
- ProcessPageSearch
- ProcessPageType
- ProcessPermission
- ProcessProfile
- ProcessRole
- ProcessUser
- SessionHandlerDB
- SessionLoginThrottle
- SystemNotifications
- SystemUpdater
- TextformatterMarkdownExtra
- TextformatterStripTags

**Nope**
- FieldtypeCache
- FieldtypeComments
- FieldtypeRepeater
- FieldtypeSelector
- LanguageSupport
- LanguageSupportFields
- LanguageTabs
- LazyCron
- MarkupPageFields
- PagePathHistory
- PagePaths
- ProcessCommentsManager
- ProcessPageClone
- ProcessPageLister
- TextformatterNewlineBR
- TextformatterNewlineUL
- TextformatterPstripper
- TextformatterSmartypants

**Comment by teppokoivula** [comment]
Checking if a module implements an interface is very simple and very fast, but wouldn't this essentially require that the system iterates through all it's config settings and only then figure out whether to show it or not? Unless, of course, we implement something else for this purpose, like a module info item or another interface ("Foo implements Module, ConfigurableModule, NotReallyConfigurableModule").

Not sure if that's worth it, but then again, I've never felt the need to tweak every possible configuration setting either ;)

**Comment by LostKobrakai** [comment]
I think just a interface (maybe rather HiddenConfigurationModule) is enough. Modules are only visible by superusers anyway, but the whole "configure" dropdown in the admin does loose it's value if 1/3 of the modules don't actually provide visible module settings.

**Comment by adrianbj** [comment]
> but the whole "configure" dropdown in the admin does loose it's value if 1/3 of the modules don't actually provide visible module settings.

My thoughts exactly - I never use this because the list is often longer than the separat Site and Core ones.

**Comment by teppokoivula** [comment]
For the record, I must say that those numbers kind of confuse me, and so does the list above. For an example, at least some of the modules under "Nope" are not configurable at all. Was the point just to list all modules or am I missing something here? :)

Checking on one of my own sites, I have exactly three core modules that implement ConfigurableModule but don't have configuration settings: Repeater, PageName and Lister. PageName would have settings, but since I'm using $config->pageNameCharset = UTF8 it doesn't.

If you guys say that the situation is really as bad as 1/3 of configurable modules not having any actual configuration settings then I absolutely believe you, but again: based on my experience so far I'm having some trouble seeing this as something that justifies a fix that adds a new (though admittedly pretty shallow) layer of complexity and still can't fix the issue completely.

**Comment by LostKobrakai** [comment]
Tbh I've not looked it up again by now :D, but @yckart's list seems to overlap with mine, even though I've fewer ones. The interface solution would be a nice optional addition for those modules, which really only hold a hidden field on purpose, but that's about it. I don't think this should get more attention than that.
