### ISSUE TITLE
some translation issues

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1291]
inside the user profile the heading 'Set Password' is not translatable.
Found the phrase in wire/core/install.sql, line 186

**Theme Reno**:
in the helper dropdown menu the translated strings don't show up (see image). 
They are translated from AdminThemeRenoHelpers.php
![pw-reno-dropdown](https://cloud.githubusercontent.com/assets/5367033/8619640/e69ba818-2718-11e5-9819-b6fd7d79cfe2.jpg)
 
in the sidebar under 'Modules' the last 3 strings don't fetch the translation (see image)
![pw-reno-sidebar](https://cloud.githubusercontent.com/assets/5367033/8619700/5db26d88-2719-11e5-9ef9-4a4e63362487.jpg)

wire/modules/AdminTheme/AdminThemeReno/AdminThemeReno.module:
the phrases from line 123 and 130 aren't translatable anymore?

**Comment by Manfred62** [comment]
>wire/modules/AdminTheme/AdminThemeReno/AdminThemeReno.module:
the phrases from line 123 and 130 aren't translatable anymore?

this is fixed. 

The other issues still exist.

**Comment by ivangretsky** [comment]
+1 for this issue. I got similar trouble with translating Reno theme (the details are here https://processwire.com/talk/topic/7625-reno-theme/?p=105224).

**Comment by ryancramerdesign** [comment]
I have just committed fixes for the issues outlined here. Please let me know if you come across any others. Thanks.

**Comment by Manfred62** [comment]
fixed!
