### ISSUE TITLE
Glitch when creating a new field via Edit Template

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1293]
There's a glitch in the "create a new field" feature in the Edit Template view that only seems to appear when you follow these steps:

- Click "create a new field"
- Close the modal window
- Click "create a new field"
- Add a field (name and type don't seem to matter)

Result is that a field is added to the fields list, but displayed only partially. After I save template settings, the field is not added to the template (the field itself is created correctly, though). At least for me this seems to happen every time. PW 2.6.8 dev, Chrome / Mac.

![create-field-glitch](https://cloud.githubusercontent.com/assets/1252021/8639400/8448a740-28e1-11e5-8166-0b13259b6a57.png)

**Comment by teppokoivula** [comment]
Just noticed that if I click existing field to open the modal edit window (context settings), close the modal, then add a new field, this happens too.

In this case the effect seems more profound, though. After seeing the "partial" field in the field list I hit "Save" button, and the field I opened for editing was moved to the end of the fields list (and out of the FieldsetTab it was within), and in the end the new field wasn't added to the template after all :)

**Comment by adrianbj** [comment]
@teppokoivula - thanks for reporting. I can confirm this. It looks like an easy fix (works for me anyway). In /wire/modules/Process/ProcessTemplate/ProcessTemplateFieldCreator.js 

please try moving:

```
$("iframe").remove();
```

from line 54 to line 3 and let me know if that fixes it for you too.

Thanks,
Adrian

**Comment by adrianbj** [comment]
Ok, seems like that doesn't always work - I am still investigating this along with Issue 1217 - I think they may be related - seems like they are PW installation dependent - I am having issues on one, and not another even though both the same version!

**Comment by adrianbj** [comment]
Ok, I think we are sorted now. Please try replacing with this version:
https://gist.github.com/adrianbj/38324a9a08fe1241a373

**Comment by teppokoivula** [comment]
@adrianbj Thanks, seems like the issue mentioned here is fixed with the new version of ProcessTemplateFieldCreator.js!

**Comment by adrianbj** [comment]
:+1:

**Comment by adrianbj** [comment]
@teppokoivula - latest dev has my fix for this - please close this issue if everything is working for you as expected in the new version.

**Comment by teppokoivula** [comment]
Haven't had a chance to test this properly with new dev, but I'll take your word for it. Mentioning issues in commits that fix them would tracking issues a lot easier (just saying) :) /cc @ryancramerdesign
