### ISSUE TITLE
Image gridview

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1295]
I noticed, that somehow the grid-view of images is kind bitchy with it's ghosting element. Sometimes I need to move an image nearly one "gap" further and then back to get the image in the place I want it to be. Though I'm not sure if there's any room with the jquery UI to improve that.

Edit: Got another improvement request for the grid-view. Like the "crop" overlay button there you'd be two buttons showing if there are tags or description given and maybe even show them on hover (simply via the title attribute). I order of keeping things out of the way they could just be invisible if no tags/descriptions are present.

**Comment by FlipZoomMedia** [comment]
I have floating problems in Grid View.

![Bug](https://picload.org/image/iipgaoc/screenshot-dev.bildarchiv-sinz.png)
