### ISSUE TITLE
Template Family Settings

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1296]
I often use very strict allowed parent/children settings for templates. Especially for the "Allowed parents" setting it would be nice to have the asm select link to the parent template. Most of the time when I create a new template I need to not only allow an exisiting template as potential parent, but also make this parent allow the new template as child.

**Comment by apeisa** [comment]
+1 for this. If I remember reading correctly, asmSelect supports links pretty nicely.

**Comment by LostKobrakai** [comment]
It does for sure.

**Comment by LostKobrakai** [comment]
I don't know about how much "learned" the placement of parent/child templates is, but I would think it's more logical to have allowed parent-templates before child-templates, even if it's just for the "parents come first in the pagetree" idea.

**Comment by ryancramerdesign** [comment]
Hey guys, this has been added in the latest commit.

**Comment by LostKobrakai** [comment]
:+1:
