### ISSUE TITLE
DL styling like AdminDataList

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1297]
While doing lots of backend stuff I had a few occasions, where I needed a list of key/value pairs instead of a full table. As I really like the UI consistency of the admin backend it would be nice if one could use a structure like this with the styling of AdminDataList.

``` html
<dl>
    <dt>Key</dt>
    <dd>Value<dd>
    <dt>Key</dt>
    <dd>Value<dd>
</dl>
```

![screenshot 2015-07-13 14 03 50](https://cloud.githubusercontent.com/assets/2489835/8649198/045afcc2-2968-11e5-8a3b-d4eca0189508.png)

**Comment by ryancramerdesign** [comment]
Makes sense to me. I'll put this on the @todo.
