### ISSUE TITLE
FieldtypeOptions required state not set

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1299]
I've a required options field in a template, which is used by a pagetable. Now if I miss to add the required field value via the api I'll get this php errors on editing the page holding the pagetable:
```txt
Warning:  Invalid argument supplied for foreach() in /wire/modules/Fieldtype/FieldtypeOptions/FieldtypeOptions.module on line 263
Notice:  Object of class SelectableOptionArray could not be converted to int in /wire/core/Page.php on line 604
```

Edit: This is the case even when there's a default value set.

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed. Note that a default value being set is required in order for it to auto-populate one, without it being specifically set by the api.

**Comment by LostKobrakai** [comment]
Sure. That's what I'm using and what I referred to.
