### ISSUE TITLE
2.6.9 - language translator in admin broken

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1301]
since last update the translation tool in the backend is broken.
It's not possible to translate the files. 
Only 'delete' button is available.
The filename is shortened. 
No more info for empty or abandoned phrases.

![pw-translation-backend](https://cloud.githubusercontent.com/assets/5367033/8761613/457e57d0-2d5a-11e5-8ee3-fc75cb1636f3.jpg)

**Comment by ryancramerdesign** [comment]
Thanks @Manfred62, sorry about that – this issue has been fixed.

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
