### ISSUE TITLE
Autocomplete field not working

### ISSUE THREAD

**Issue by madebymats** [ryancramerdesign/ProcessWire#1302]
Instead of showing titles id's are shown. PW 2.6.9 Dev.

<img width="333" alt="autocomplete-processwire" src="https://cloud.githubusercontent.com/assets/1630407/8762588/e9de47d6-2d7d-11e5-8098-782d57b24b9f.png">

**Comment by ryancramerdesign** [comment]
@madebymats I can't duplicate this one. It looks to me like a JS issue, and I can also observe a styling issue in your screenshot. That makes me think that older JS and CSS files are present. I would do a Modules > Refresh, then hit reload on the page once or twice where you see that issue. It should clear it up. Please let me know?

**Comment by madebymats** [comment]
Clearing the cache solved it. Thanks Ryan!
