### ISSUE TITLE
PageTable: use large modal window or make modal size configurable?

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1304]
After using PageTable quite extensively in one of my latest projects, I can't help feeling that the current modal size ("medium") is a bit too small for my needs.

Size is currently hardcoded into InputfieldPageTable.js, so I can't change that without forking the module or making core changes, neither of which I'm really comfortable in this case. Usability-wise large setting feels better to me, I don't see value in leaving that much empty space around the modal window here.

Would you consider either a) making the PageTable modals large by default (seems like a better choice to me, though that might just be my use case / opinion), or b) (preferably) making this setting configurable?

There's already a "modal window behaviour" section in PageTable settings, so perhaps changing that to more general "modal window settings" would make sense here?

**Comment by ryancramerdesign** [comment]
I actually can't see any drawback to just using the large modal window here. Seems to make sense, and not sure why I chose medium before, I will update it. Thanks.

**Comment by teppokoivula** [comment]
Looks like this was already changed by commit 86bf1a7ae6f78e12d04f396372e7f7cea4de84d1, the message just failed to mention it. Thanks, Ryan; I'm closing the issue now.
