### ISSUE TITLE
Translating multiple files doesn't show them as translated in the lost after sumbit

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1305]
PW 2.6.1 When I create new translation using the multiple select files tool, I select 2 files and click translate, it doesn't show them as "translated" in the list although they are created already. It seems it creates the list before the information is saved or so. Confusing.

**Comment by ryancramerdesign** [comment]
Good point, the latest commit should fix it.

**Comment by isellsoap** [comment]
@somatonic Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
