### ISSUE TITLE
ProcessWire > 2.6.4: SSL issues, session logouts

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#1307]
I'm used to protect the backends of my PW installations by HTTPS/SSL. In such a setup I noticed that  current ProcessWire (2.6.9 dev) has weird issues with HTTPS (SSL) and session logouts. I tried to debug to some point: I can say that it's all working ok up to ProcessWire 2.6.4. More recent versions show the following problems.

Test case:
- Install clean ProcessWire 2.6.9 (blank profile)
- Edit "admin" template. Set "Schema/Protocol" to "HTTPS only".
- Edit "home" template. Set "Schema/Protocol" to "HTTPS only".
- Log out, log in again.
- Select home page in tree and view the home page: Home page should be called with HTTPS in a new browser tab. Notice the "edit" link at the bottom.
- Call the home page manually without SSL by replacing "https://" with "http://" in URL browser bar. Page gets redirected to https again, which is fine. Problem is: PW session has been terminated. The edit link has disappeared.

As a result, my clients have problems with being logged out when editing and viewing pages.

**Comment by ryancramerdesign** [comment]
We recently switched to HTTPS only cookies. Based on what you've described, I'm guessing we may need to use a different cookie name for HTTPS vs. HTTP. 

In your /site/config.php can you test the following? Replace this (if there):
``````
$config->sessionName = 'wire';
``````
with this:
`````
$config->https = !empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on';
$config->sessionName = $config->https ? 'wirehttps' : 'wire';
``````
Does that resolve the issue? Thanks.

**Comment by processwired** [comment]
Thanks, Ryan. I have tried it with the two lines in config.php as you did describe. It doesn't resolve the issue completely, but it's a step in the right direction. This is what happens:

- My backend lives under https://mydomain.com/processwire/
- If I view the home page with SSL (https://mydomain.com/), all is well.
- If I call it without SSL, http://mydomain.com/, session is not available anymore :-(
- If I return to backend with https, session still works. (Before adding the two lines to config.php, session was destroyed with https as well at that last step.)

**Comment by teppokoivula** [comment]
@processwired Sorry if I'm getting something wrong here, but what you've described above sounds like the expected behaviour.. at least if what you mean by your third bullet point is that the session you used to log in isn't available, but a new one is, and the logged in session is again available when you visit the HTTPS URL after this :)

The session opened with SSL enabled *shouldn't* be available without SSL, this should always go back to using a new "non-SSL" session. This is what the secure cookies update was about, after all.

**Comment by ryancramerdesign** [comment]
That's correct, it sounds like the intended behavior. Though if this is undesirable for anyone, I suppose we could make it optional via a $config setting? But turning it off means the cookies aren't benefiting from https.

**Comment by processwired** [comment]
Well, if this is the intended behavior, then I wonder what is was before in older ProcessWire versions :-)
The problem is: in earlier versions, I was able to choose if a page should be called with https or http by setting the according options in the backend. That was quite handy, because I have a lot of sites which have forms (served by https) and normal info pages (served by http). Now my clients are irritated, because they get lost of their sessions if they are going to preview the pages they are editing if they use a backend with https and their frontend with http or vice versa, which was not a problem before.

If the way it is now is the desired behavior and if it should stay this way, I have no choice and have to set the whole site to https, even if it contains just one form. Then I don't see the benefit of these template settings anymore, because general use of https could be better set in .htaccess.

**Comment by ryancramerdesign** [comment]
Sounds like in your case the secure cookies option is not desirable. See the latest commit, which adds a `$config->sessionCookieSecure` option. Set this in your /site/config.php to disable the behavior, and you should get exactly the same behavior as before we supported the secure cookies option.

``````
$config->sessionCookieSecure = false;
``````

**Comment by processwired** [comment]
Awesome! Thanks a lot, Ryan!

**Comment by teppokoivula** [comment]
@processwired While this issue per se is solved, here's one more thing to consider:

> If the way it is now is the desired behavior and if it should stay this way, I have no choice and have to set the whole site to https, even if it contains just one form. 

I don't see any real drawbacks with this approach, it makes interacting with your site more secure, and with Google giving more value to HTTPS-enabled sites in search results I'd say that *in most cases you should go for full HTTPS support if you can*.

Just saying :)
