### ISSUE TITLE
Preparing for PHP 7 compatibility (removed features)

### ISSUE THREAD

**Issue by mestaritonttu** [ryancramerdesign/ProcessWire#1308]
https://wiki.php.net/rfc/remove_deprecated_functionality_in_php7

Assignment of new by reference
=&
found in:

wire\core\FieldSelectorInfo.php
wire\core\ImageSizer.php
wire\core\Modules.php
wire\core\Wire.php
wire\modules\LanguageSupport\ProcessLanguage.module
wire\modules\Markup\MarkupHTMLPurifier\htmlpurifier\HTMLPurifier.standalone.php
wire\modules\Markup\MarkupHTMLPurifier\htmlpurifier\standalone\HTMLPurifier\ConfigSchema\ValidatorAtom.php
wire\modules\Markup\MarkupHTMLPurifier\htmlpurifier\standalone\HTMLPurifier\Printer\HTMLDefinition.php
wire\modules\Process\ProcessPageEditImageSelect\ProcessPageEditImageSelect.module
wire\modules\Textformatter\TextformatterMarkdownExtra\markdown.php
wire\modules\Textformatter\TextformatterSmartypants\smartypants.php

**Comment by teppokoivula** [comment]
@mestaritonttu Just checking, but could there be some confusion here about the meaning of this particular change? From what I can tell, it's literally about assigning *new* by reference, not assigning by reference itself:

```
$obj =& new ClassName; // wrong, deprecated since PHP 5.3
$obj =& $otherObj; // correct, nothing wrong with this
```

.. and, for the record, I'm not seeing any "assignments of new by reference" in the ProcessWire codebase. Which is a good thing, of course :)
