### ISSUE TITLE
Inline CKEditor and AdminThemeReno: can't use arrow keys to move the pointer

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1312]
AdminThemeReno has this neat feature for collapsing the menu/sidebar with left arrow key, and restoring it with the right arrow key. This works fine with most fields enabled, but prevents moving the cursor with left/right arrow key in CKEditor fields with inline mode enabled.

The good thing here is that I wouldn't even know that this feature exists if this hadn't happened, but the bad thing is that at the moment it's kind of complicating my work.. :)

**Comment by Renobird** [comment]
Teppo,

This is fixed now, and I'll submit a PR to Ryan. In the meantime, you can replace main.js and main.min.js for a quick fix.

https://github.com/Renobird/AdminThemeReno/tree/master/scripts

**Comment by ryancramerdesign** [comment]
This is an awesome feature. I wasn't aware of it till mentioned here actually. Nice job @Renobird. Since it seems to be already fixed on the current dev, I'll close this one out.
