### ISSUE TITLE
OR groups in "expire" selector for WireCache not working.

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1315]
When I set a selector like:
```
has_parent=1111|1035
```
it is added to the data field for the entry in the cache DB table:
```
{"selector":"has_parent=1111|1035","WireCache"
```
 and it works fine in that it expires the cache when any child of those page IDs is saved.

But I need:
```
(has_parent=1111|1035),(id=1023)
```
This results in no selector at all being stored in cache table and the cache does not expire when any pages are saved.

Even manually editing the entry in the DB row to include the OR groups still doesn't seem to work.

Please let me know if I can provide any further info.

**Comment by adrianbj** [comment]
Also, just wanted to note that the blog post about WireCache doesn't actually mention the ability to use selectors or page objects as the trigger for expiring the cache:
http://processwire.com/blog/posts/processwire-core-updates-2.5.28/#wirecache-upgrades

I had to read the source code comments to find this.

**Comment by ryancramerdesign** [comment]
Adrian, OR-groups are a database-join operation rather than a in-memory
selector operation. Or to word it differently, they are a way to select
pages from the database, but not a means of matching pages already in
memory. The same goes for subselectors. This does seem like one case where
they might be useful in memory though, so will keep it in mind for future
support. For the case you mentioned, using `parents|id=1111|1035|1023`
might work though.

**Comment by adrianbj** [comment]
Thanks Ryan - I wasn't thinking about database vs in-memory issues. I ended up broadening my selector (a little like your suggestion) and it is working, but it clearing the cache more than needed because it is targeting many more pages than needed. Not ideal because the set of queries takes several seconds (building up a large json object for some interactive visualizations), but reality is that the content for the pages isn't changing very often either, so not really a big deal.

Feel free to close this if you want, or keep open as a reminder for possible future support.

**Comment by ryancramerdesign** [comment]
I do think it'll be possible support OR-groups with in-memory selectors, and I'm adding a @todo to the Selectors class, as there have been a few instances lately where people wanted in-memory selectors to support OR-groups. Subselectors will still be limited to database selectors, but ideally that would be the only one not supported by in-memory selectors.
