### ISSUE TITLE
ProcessPageEdit error

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1317]
[ProcessPageEdit.module#L733-L736](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L733-L736)

This part does throw an `Trying to get property of non-object` error. Should there first be checked if it's still an available user and then get the name.

**Comment by ryancramerdesign** [comment]
Thanks, I have updated and it will appear in this weeks commits.

**Comment by isellsoap** [comment]
@LostKobrakai Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
