### ISSUE TITLE
Fieldset tabs display regardless of Access settings

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1319]
On a project I'm working on I wanted to use a fieldsetTab to create a separate "Advanced" tab on the page edit screen that would only be visible to the superuser, so I turned on Access controls for that field and left all checkbox inputs blank. When testing this out as other users, I discovered that the tab still shows for them. Switching back to a standard fieldset caused it to hide again.

This is in dev 2.6.3. Please disregard if this has already been fixed :)

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed and will appear in this weeks commits.
