### ISSUE TITLE
parent_id doesn't work in field visibility settings

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1321]
In this post, I described how one could use 'parent_id=id-of-parent-page' in a field's visibility settings to make a field appear based on what the id of the parent page was:
https://processwire.com/talk/topic/10426-ability-to-add-field-to-page-instead-of-to-template/?p=98721

It worked at the time I made that post, however it now seems to be broken in 2.6.11.

**Comment by ryancramerdesign** [comment]
The parent_id property was converted to an AJAX-loaded field in 2.6.11, so it's not populated into the markup unless you click the parent ID field. We converted this to an AJAX loaded field because there was a little bit of overhead associated with it, so making it only load when needed for a change helps to speed up the page editor. However, if this is a common need (to use parent_id in a dependency) I can change it back.

**Comment by jlahijani** [comment]
I suppose whatever makes the most sense.

**Comment by ryancramerdesign** [comment]
I've added a setting in PW 2.6.12 that enables you to convert the parent_id field back to non-ajax, which should enable your selector to work again. See the /wire/config.php file for the $pageEdit['ajaxParent'] option.

**Comment by isellsoap** [comment]
@jlahijani Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by LostKobrakai** [comment]
@ryancramerdesign 
How about integrating this into ProcessPageEdit and let it run just before the end of buildForm(). Dependencies on external pages aren't supposed to dynamically update anyway in my opinion. This would at least let any single selectors like "page.field_name=value" work out of the box. 

```php
/**
 * Check for external page dependencies
 *
 * @param InputfieldForm $form
 * @return InputfieldForm
 *
 */
protected function checkExternalPageDependencies(InputfieldForm $form){
	$inputfields = $form->getAll();
	foreach ($inputfields as $inputfield) {
		if(strpos($inputfield->showIf, "parent") !== 0) continue;
		$input = $form->getChildByName($inputfield->name);

		if($this->page->is($inputfield->showIf)) {
			$input->showIf = "";
		}else{
			$input->parent->remove($input);
			$inputfields->remove($inputfield);
		}
	}

	foreach ($inputfields as $inputfield) {
		if(strpos($inputfield->requiredIf, "parent") !== 0) continue;
		$input = $form->getChildByName($inputfield->name);

		if($this->page->is($inputfield->requiredIf)) {
			$input->requiredIf = "";
			$input->required = true;
		}else{
			$input->requiredIf = "";
			$input->required = false;
		}
	}

	return $form;
}
```

Maybe later it could be improved to only strip off any "parent.something" parts of the selector and add back the form specific values to the showIf / requiredIf property if those are true, e.g.:
  
`parent.name=hello, parent.linkto=1034, field=hello` => `true, true, field=hello` => `field=hello`  
`parent.name=hello, parent.linkto=1035, field=hello` => `true, false, field=hello` => remove field

But that's would be a whole other level.
