### ISSUE TITLE
ListerPro spinner keeps spinning, hanging on delete

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1322]
PW 2.6.10
LP 1.0.5

Tested in Firefox and Chrome. I'm having an issue when using modal windows for editing. When I save a modal window, it closes and the record properly updates in the results. However, the spinner at the top of the screen keeps spinning, giving the impression that there is still processing going on.

When trashing a page from the modal window, the window closes and refresh does not occur. Spinner keeps spinning.

**Comment by ryancramerdesign** [comment]
I'm not seeing either of those issues here, and it sounds like potentially a older cached JS file. Though it could also be an issue with that version combination that I'm not aware of. I'm curious if you see the same issue in PW 2.6.12 + LP 1.0.6?
