### ISSUE TITLE
2.6.12 - refresh modules - long list of detected modules

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1324]
I get this alert after updating PW to 1.6.12 just now and then hitting refresh modules. The Note does not go away after hitting refresh again. Not sure this is a bug...

Detected 11 module version changes (will be applied the next time each module is... 11 Sek. 
Detected 11 module version changes (will be applied the next time each module is loaded):
ProcessRole: 1.0.1 => 1.0.2
ProcessUser: 1.0.5 => 1.0.6
ProcessPageAdd: 1.0.7 => 1.0.8
ProcessPageLister: 0.2.1 => 0.2.3
InputfieldCheckboxes: 1.0.6 => 1.0.7
InputfieldPageAutocomplete: 1.0.7 => 1.0.9
InputfieldRadios: 1.0.4 => 1.0.5
InputfieldImage: 1.1.5 => 1.1.6
InputfieldPageName: 1.0.5 => 1.0.6
InputfieldCKEditor: 1.5.0 => 1.5.1
InputfieldPageTable: 0.1.0 => 0.1.1

**Comment by ryancramerdesign** [comment]
No that's correct. The same modules will continue showing up there until
they are loaded at least once. So for instance,  if you go and click to
access > users, then it'll stop showing ProcessUser in the refresh. The
module stays in an update queue until the next time it is used. I may just
suppress that list except in debug mode, if it is causing confusion.

**Comment by tbba** [comment]
If Ryan decided, whether to suppress this output or not, the issue can be closed either way?

**Comment by tbba** [comment]
closed (conversation too old)
