### ISSUE TITLE
comment form : issue with cookie storage of notification value

### ISSUE THREAD

**Issue by er314** [ryancramerdesign/ProcessWire#1327]
In file comments.js, my understanding (and my observation !) is that,

- for storage of notification value, the jquery code will actually store the value of the 1st radio button (so always equals 0) :<br>
		var $notify = $form.find(".CommentFormNotify :input");<br>
		var notify = $notify.length > 0 ? $notify.val() : '';<br>
- then for populating the previously stored value, the jquery code will set all radio buttons values to this "0" value :<br>
		$form.find(".CommentFormNotify :input").val(values[3]);<br>

this is not the intended behaviour, obviously

cheers

**Comment by ryancramerdesign** [comment]
Thanks @er314, good find. I have corrected this and it will appear in this weeks commits. This CommentFormNotify originally started as a single checkbox, so looks like the JS didn't get updated when it switched to radios. Come to think of it, the current behavior is not undesirable (having to be clear about your choice with every comment–I'd forgotten that wasn't our intention), but nevertheless it's better for it to be fixed.

**Comment by isellsoap** [comment]
@er314 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by er314** [comment]
confirmed fixed, thanks
