### ISSUE TITLE
PageTable: allow showing image preview of image field with dot notation

### ISSUE THREAD

**Issue by isellsoap** [ryancramerdesign/ProcessWire#1328]
It is possible to get a preview of an image in a PageTable column by specifying the name of an image field. If I specify an image field with dot notation (say `page_field.image_field`) only the file name of the image is rendered in the PageTable. 

Why not allow the preview of an image also with the dot notation? That would be an awesome addition.

I think the code responsible for this behavior is [located exactly here](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.module#L348). If a subfield name is present, the `objectToString` method is called. Instead, images specified with dot notation should go in the `else` path.

**Comment by LostKobrakai** [comment]
It's not only about images, lots of fields could use a different representation in page-tables, which was already requested here: https://github.com/ryancramerdesign/ProcessWire/issues/1229.

**Comment by isellsoap** [comment]
+1

**Comment by ryancramerdesign** [comment]
Makes sense to me, thanks. I have updated the core to support this and it'll appear in this weeks commits.

**Comment by isellsoap** [comment]
Ryan, that is amazing. Can’t wait to try it out! :-)
