### ISSUE TITLE
Hooking Page::path, $event->return = $newurl doesn't alter page url

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1329]
I have a autoload module with a hook on Page::path to modify urls of certain pages.

I have done this in another project just fine but can't get it to work in any other install I have tried so far. 2.4, 2.5, 2.6 etc

In the init()
```
$this->addHookAfter("Page::path", $this, "hookPagePath");
```

The method where $event->return = $url; doesn't do anything.

```
public function hookPagePath(HookEvent $event) {
    $page = $event->object;
    if($page->template->name == "basic-page") {
          $event->return = "/test/";
    }
}
```

Such a hook works fine if I add it directly in the template, but not when in a autoload module.
Strange thing is I have this working in one project ever since.

**Comment by somatonic** [comment]
Hmm I think now after hours of trying I think I found the culprit. It's language support page names that does not let me alter the url if hooking in the init(). I have to use ready() to add the hook. Doh.

**Comment by wanze** [comment]
@somatonic You can pass a priority to your hook. There were some bugs regarding priorities not being respected, but ryan has fixed this some time ago. See https://github.com/ryancramerdesign/ProcessWire/issues/1218

**Comment by somatonic** [comment]
Thanks wanze, yes I'm aware of the prio settings. I tried and it seems to also solve the issue. I thought it wouldn't cause language page names hooks into page path in ready(), so at a later point. But obviously it works.

**Comment by isellsoap** [comment]
@somatonic Can be closed?
