### ISSUE TITLE
Cannot assign allowed parent template

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1330]
When the noParents setting is saved as "one" on the current dev one cannot save allowed parent templates, even if the page is not yet created.

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai this has been fixed and will appear in this weeks commits.

**Comment by isellsoap** [comment]
@LostKobrakai Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
