### ISSUE TITLE
Checkboxes not loaded via ajax

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1331]
When editing an field in current dev the "global" and "permanent" checkboxes do not load.

**Comment by zgjonbalaj** [comment]
Samething for me and a few other settings i just posted about it under issue AdminThemeReno

**Comment by ryancramerdesign** [comment]
This should already be fixed in 2.6.13, but please let me know if you continue to see it anywhere.

**Comment by LostKobrakai** [comment]
Seems to be working again.
