### ISSUE TITLE
Add New Enhancement

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1332]
The new "Add New" page is really great, but it's lacking a feature in my mind. One cannot chose from multiple valid parents. Maybe this could be related to the multi-language setup, but I'm not sure.

**Comment by LostKobrakai** [comment]
Ok it seems like one of my "noParent=one" settings might have thrown off the feature. After moving the pages to be children of users both the possible parents are visible.

**Comment by ryancramerdesign** [comment]
It sounds like you already found the resolution to this one, or does it still appear to be a bug? I can't tell for sure. :)

**Comment by LostKobrakai** [comment]
I restructured the page a bit so I had to removed those "noParent=one" settings from a few allowed parent pages. After that change the add-new page did show the correct pages, therefore I think there's still an issue when using a parent that uses "noParent=one".
