### ISSUE TITLE
Multilanguage pageLabelField value

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1333]
It might be nice, now with the added tag substitution feature, if the pageLabelField would be multi-language.

**Comment by ryancramerdesign** [comment]
Not sure I follow what you mean. Can you provide more details about the context?

**Comment by LostKobrakai** [comment]
The pageLabelField does have the new feature do work with strings like this: 
```
"Event#{id} ({registration.count} of {maxRegistrations} Registrations)"
"Event#1234 (199 of 350 Registrations)"
```
It would be nice if this could be multilanguage to also be able do translate it if needed. E.g. to german:
```
"Event#{id} ({registration.count} von {maxRegistrations} Anmeldungen)"
"Event#1234 (199 von 350 Anmeldungen)"
```
