### ISSUE TITLE
No "unsaved changes" warning when switching context

### ISSUE THREAD

**Issue by Philzen** [ryancramerdesign/ProcessWire#1337]
When editing a field and trying to leave the page, the user gets a nice warning about unsaved changes.

An event listener should be hooked up to the context select's `change` event to trigger likewise.

**Comment by ryancramerdesign** [comment]
It sounds like you are talking about the ProcessField module? (you mentioned editing a field and having a "context" select box). The core only monitors the PageEdit form with an unload/confirmation dialog. It doesn't monitor the ProcessField form. Given that, I'm thinking your request might instead be for @somatonic FormSaveReminder? (3rd party module)

**Comment by isellsoap** [comment]
@Philzen Can this issue be closed then?

**Comment by Philzen** [comment]
Thanks for pointing me in the right direction and sorry for getting back so late.

Keep up the great work on this awesome product!
