### ISSUE TITLE
Disappearing Fields

### ISSUE THREAD

**Issue by zgjonbalaj** [ryancramerdesign/ProcessWire#1339]
Many configuration settings for modules or even the AdminThemeReno have disappeared. 

Edit: Also noticed several other places like the checkbox for the global option in field settings. Seems to be an AJAX issue although not entirely sure.

![image](https://cloud.githubusercontent.com/assets/6172602/9234413/b9b6fbf6-4106-11e5-9a50-8aed8f3f1622.png)

![image](https://cloud.githubusercontent.com/assets/6172602/9234420/c2343ea6-4106-11e5-85e9-f0a7cc9eaf2d.png)

![image](https://cloud.githubusercontent.com/assets/6172602/9234449/e6bcea7a-4106-11e5-956f-3f88483893f6.png)

**Comment by isellsoap** [comment]
@zgjonbalaj Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by zgjonbalaj** [comment]
Sorry yes it has thank you!

*Zgjim (Jim) Gjonbalaj, Owner/Web Developer*
*Computer City Service L.L.C*
*computercityservice.com <http://computercityservice.com> |
info@computercityservice.com <info@computercityservice.com>*
*97 Myrtle Ave Ansonia, CT 06401*
*Office: (203) 516-0505 | Cell: (203) 893-3714*

On Thu, Aug 27, 2015 at 6:45 AM, Francesco Schwarz <notifications@github.com

**Comment by zgjonbalaj** [comment]
Sorry for the delay issue has been fixed!
