### ISSUE TITLE
Styling of unpublished pages in Admin Theme Reno

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1340]
Unpublished pages in the page tree of Admin Theme Reno don't seem to have any specific styling compared to published pages. This makes identifying unpublished pages difficult. Hidden pages are "faded out", so no problem there.

One of the "Test" pages in the screenshot is unpublished – could be a bit more obvious :)

![reno-page-tree](https://cloud.githubusercontent.com/assets/1252021/9244619/8e6231e2-41a5-11e5-80b7-3d5291deada6.png)

**Comment by LostKobrakai** [comment]
Maybe this http://fortawesome.github.io/Font-Awesome/icon/eye-slash/ as icon. I doubt using another faded / color variant would be a good choice.

**Comment by teppokoivula** [comment]
I'd prefer if it followed the example of the default admin theme here with line-through, for the sake of consistency. Especially for templates that already have an icon defined, additional ones appearing based on visibility settings etc. can make things even more confusing.

**Comment by LostKobrakai** [comment]
Sure, there you see how often I'm working with unpublished pages.

**Comment by ryancramerdesign** [comment]
I didn't realize this was missing from AdminThemeReno. Actually, I don't think it's missing specifically, but that some style in AdminThemeReno must be overriding it. I have corrected it and it'll appear in this weeks commits. Thanks for identifying it.

**Comment by teppokoivula** [comment]
Confirmed, closing this issue.
