### ISSUE TITLE
Lister not updating when ListerPro installed

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1341]
Doing a Modules > Refresh continues to say that ProcessPageLister will be updated the next time it is loaded. Going to Pages > Find to call Lister doesn't update it. As soon as I uninstall ListerPro, it updates.

**Comment by ryancramerdesign** [comment]
Adrian, you might need to use the search engine in the admin (top right corner) before ProcessLister will get called and have its upgrade status cleared. I will also make sure in the next version of ListerPro that its upgrade method loads ProcessPageLister, so that will also clear it.

**Comment by adrianbj** [comment]
Thanks for taking care of this in the next version of ListerPro!

**Comment by adrianbj** [comment]
I haven't seen this in a while, so assume it's fixed, but maybe it's just because there have been no Lister updates. Will reopen on the new issues repo if I see again.
