### ISSUE TITLE
Trailing slash on URL Segments redirects to default language

### ISSUE THREAD

**Issue by adamkiss** [ryancramerdesign/ProcessWire#1342]
When you have URL Segments and Trailing Slashes turned ON on a multilingual site, the addition of the trailing slash to the url segment doesn't honour the requested language, but redirects to default language.

Request: `example.com/nondefault/nd-pagename/urlsegment`
Redirect: `example.com/default/d-pagename/urlsegment/`

Did some debugging, I think it's this line: https://github.com/ryancramerdesign/ProcessWire/blob/53e4e3bfa8623163e0d6382e4a0cc8c58ee6a3a6/wire/modules/Process/ProcessPageView.module#L416

**Comment by ryancramerdesign** [comment]
Thanks Adam, I have corrected the issue and it will appear in this weeks commits.

**Comment by isellsoap** [comment]
@adamkiss Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
