### ISSUE TITLE
deleted items are activated when closing modal

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1345]
reproduction:
pagetable with several items
delete one item
open another item to edit (modal view)
close this modal without saving
the pagetable item that was marked for getting deleted is activated again

**Comment by ryancramerdesign** [comment]
Thanks Bernhard, I have corrected this and it will appear in this weeks commits.

**Comment by isellsoap** [comment]
@BernhardBaumrock Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by BernhardBaumrock** [comment]
sorry got no notifications! thanks for fixing :) :+1:
