### ISSUE TITLE
No more create new page from page field after upgrade 2.6.13

### ISSUE THREAD

**Issue by BFDCalendar** [ryancramerdesign/ProcessWire#1348]
Since upgrading from 2.6.1 dev to 2.6.13 I can't create new pages anymore from a page field.
Details: Single Page or empty page, input PageAutocomplete and advanced *= and 'Allow new pages' checked.
I can type and see the list of pages appear, but when I type in a new name it just disappears when hitting return of clicking outside the field.
I have same type of page fields on other pages, they don't work either. On my 'places' page I have one for city input PageAutocomplete, one for state input PageAutocomplete and one four country input AsmSelect. Both PageAutocomplete don't add new pages while AsmSelect does.
It worked fine before upgrading.

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate the issue and have put in a fix for this. Please let me know if it resolves the issue for you too.

**Comment by BFDCalendar** [comment]
Ryan,


I suppose it will be in the next dev upgrade. As soon as I upgrade I'll test and let you know.

Thanks.

And just adding that ProcessWire is really the best thing I've encountered since doing (Landrover style) websites for 20 years now.


DDV


>Thanks, I was able to duplicate the issue and have put in a fix for
>this. Please let me know if it resolves the issue for you too. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ryancramerdesign/ProcessWire/issues/
>1348#issuecomment-142289901



==== ===== > (+x-) < ===== ====

 Find out what happened today

 www.birthfactdeathcalendar.net

 Get inspired to fill your day

======= ===== > < ===== =======

**Comment by BFDCalendar** [comment]
Ryan,


It works. Hurray!


DDV

**Comment by LostKobrakai** [comment]
@BFDCalendar 
Please do close the issue here on github as well.

**Comment by BFDCalendar** [comment]
Thanks!
