### ISSUE TITLE
Insert Link > Link to URL: User-Interface

### ISSUE THREAD

**Issue by m-artin** [ryancramerdesign/ProcessWire#1351]
Inserting a Link (with CKedit) shows a little UI-inconsistency in the pw-dialog window for me. 
The Link to URL field has focus at first and everything is fine. Only after the focus is changed by clicking elsewhere (e.g. changing to attributes tab) and then coming back to the URL field seems to inactivate the URL field and it can't be edited anymore. 

P.s. Another tiny thing: The dialog close-button (x) is jumping a little bit to the right, after mouse hover.

PW 2.6.13 dev, Safari/Firefox

![pw_link_focus](https://cloud.githubusercontent.com/assets/1139221/9359465/8d2877c8-4691-11e5-9c7b-cef456e934c3.png)

**Comment by isellsoap** [comment]
I noticed the jumping of the close button too. Good catch!

**Comment by m-artin** [comment]
Also creating a new link (by writing the address into the 'Link to URL' field) leads to a disappearing URL text after clicking somewhere else without saving at first. 
So entering an URL and making a change in the Attributes tab afterwards for example removes the entered URL. Maybe someone else is able to reproduce that. 

PW 2.6.15 dev, Webkit/Mozilla

**Comment by ryancramerdesign** [comment]
I actually just fixed this one yesterday, and committed it to the dev
branch about 5 minutes ago, but please let me know if you run into any
other issues with it. Thanks.
