### ISSUE TITLE
Filefield Tag Styling

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1354]
How about using something like this https://github.com/bevacqua/insignia to have the tags for file/image fields styled more appropriately. As this is build to progressively enhance inputfields there should be much to change for making it work.

**Comment by plauclair** [comment]
I've used tags extensively in a project lately, and would tend to agree.

insignia doesn't seem too strong UX-wise (especially deleting behavior). It will still remain difficult to keep consistency across everything using tags. Select2 has a really nice tag functionality, that will allow adding new ones on the fly and re-use existing ones (ajax). https://select2.github.io/examples.html#tags

**Comment by LostKobrakai** [comment]
Yeah, but select2 is an enhancement to selectboxes, which is not what's used for tags right now. Insignia is supposed to work with simple text fields and would therefore work much easier with the existing code.

**Comment by plauclair** [comment]
True, probably an ok in-between.

**Comment by plauclair** [comment]
Just some usage notes, I've lately done extensive work with JavaScript selects. Chosen (no mobile support but easy to work with), Select2 (powerful but too complicated), insignia (too limited), even bsmSelect (mild feelings, seems unmaintained) an asmSelect fork. 

The one I like the most is https://brianreavis.github.io/selectize.js/, it also works on text fields, and I was even able to replicate (and improve upon) asm/bsmSelect vertical display with sorting, but with the additional search functionality (though it would still require some modifications for it to be 100% functional). Might be a good option.
