### ISSUE TITLE
function redeclaration in the beginner profile

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1355]
The beginner profile, does not include_once() the renderNav() and other functions, which leads to errors if _init.php is called a second time: https://processwire.com/talk/topic/10699-pagenotfoundexception-leads-to-redecleration-of-initphp-functions/

**Comment by ryancramerdesign** [comment]
I was really hoping to keep the beginner profile as absolutely simple as possible, but I think it's worth the tradeoff to move those functions to a separate include_once() file, as it'll reduce confusion down the road if people continue to use the beginner strategy with their templates. I've gone ahead and moved those functions to a separate include_once() file.

**Comment by LostKobrakai** [comment]
I can understand that, but as soon as people discover they can have easy partials by using $page->render() or wireRenderFile() they get in trouble. Therefore I think this is the better alternative.

**Comment by ryancramerdesign** [comment]
I completely agree. It's worth the slight tradeoff in simplicity.
