### ISSUE TITLE
documentation should state "$options" variable is reserved?

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1357]
I brought up the following topic on the forums a few weeks ago:
https://processwire.com/talk/topic/10547-is-options-a-reserved-variable/

I think it would be important to state in the documentation that one should not create their own $options variable since it could conflict with the $options variable created by the PageRender module.

The reason I hit this issue is because one of my boilerplate things to do with any project is to create a global variable called $options (in _init.php) that stores the value of the "/options/" page I always create, which stores options used globally throughout a site (site_name, phone, etc.).  I will most likely rename this to $settings and /settings/.

**Comment by plauclair** [comment]
A typical way of doing this in ProcessWire would be to add these to $config. See "Adding your own configuration options" in https://processwire.com/api/variables/config/. There is also a module (currently beta) to enabling these through the backend's UI, if these need to be configurable by the client, for example.

**Comment by ryancramerdesign** [comment]
It should be okay to overwrite the $options variable if you want to. It is just there to provide additional information, should you want it. But the truth is most don't make use of it. I don't think you need to worry about coming up with a different name for your own $options variable unless you have a specific need for the $options that PageRender provides to it. You could always move those $options to another variable first if you preferred too, like `$renderOptions = $options;` before you initialize your own $options.
