### ISSUE TITLE
LanguageParser::parseFile() multiple __( on one line

### ISSUE THREAD

**Issue by FdeQuillettes** [ryancramerdesign/ProcessWire#1360]
The regexes in parseFile() seem to assume only one translation per line should exist so the example below only finds the "text 1" translation.
```php
<?php echo __('text 1'); ?> - <?php echo __('text 2'); ?>
```
It should find both or at least give a warning (for instance trigger the warning if if __( is found in the tail part of the match).

I'm not that good with regexes unfortunately, so no accompanying pull request this time.

**Comment by LostKobrakai** [comment]
That's by design and mentioned in the docs: http://processwire.com/api/multi-language-support/code-i18n/#there-may-only-be-one-translation-function-call-per-line

**Comment by isellsoap** [comment]
@FdeQuillettes Can you please close this issue? Thank you!

**Comment by FdeQuillettes** [comment]
Actually I totally forgot about this issue. Now that I think of it again, this restriction could be removed altogether if ProcessWire used PHPs tokenizer instead of a regex. Even the comment descriptions would keep working then.

Anybody have input on this? I could even start a pull request but won't put in the effort if noone else thinks this will be useful.

**Comment by isellsoap** [comment]
@FdeQuillettes No input here for a while, I close this issue. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
