### ISSUE TITLE
FieldsetTabs not showing after upgrade to 2.6.14 (on templates that have no template file)

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1361]
I'm experiencing a very strange issue after upgrading to 2.6.14. Fieldset tabs are not showing on some of my templates, but are showing on others. There are no special access settings on the fieldset itself. I've tried removing any custom code that might be effecting this, but I haven't been able to narrow the issue down yet. 

I know this is probably not very helpful, but maybe this is an issue others are having? I will keep testing and try to narrow it down.

**Comment by thetuningspoon** [comment]
I've narrowed down the issue! The fieldset tabs are not showing when the template has no template file set.

**Comment by ryancramerdesign** [comment]
Thanks Michael! I've fixed it locally and will test things out and commit
on this weeks dev branch. If you want to fix it in your copy, locate line
479 in /wire/modules/PagePermissions.module, which says this:

$field = $arg0;

And add this line after it:

$checkFile = false;

**Comment by thetuningspoon** [comment]
That fixed it. Thanks Ryan!
