### ISSUE TITLE
Modal window close button jumping around in 2.6.14

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1362]
Since upgrading to 2.6.14, the "X" close button in the right hand corner of modal windows is jumping to the right several pixels when hovered over. This is on Chrome (Mac OS).

**Comment by ryancramerdesign** [comment]
I'm aware of it, and it's been driving me nuts for the last couple of
weeks... but thus far have not been able to figure it out. If anyone with
better front-end debugging skills manages to track it down, please let me
know. :)

**Comment by thetuningspoon** [comment]
Hi Ryan,
I did a little debugging. Inthe  main-modern.css file, .ui-button.ui-state-default has a right and left padding of 1.1em assigned. When the button gets hovered over the .ui-state-default class is removed and this value then gets superceded by the padding value from .ui-dialog-titlebar-close, which is 1px all around.

**Comment by ryancramerdesign** [comment]
Thanks Michael, that helped me track it down and fix it, and it will be in
this weeks commits.

**Comment by isellsoap** [comment]
Note: this bug is also mentioned in #1351.

**Comment by m-artin** [comment]
Thanks Michael and Ryan, the fix is working fine in the latest dev version.
