### ISSUE TITLE
Missing image tag only throws error when resized

### ISSUE THREAD

**Issue by eladnova** [ryancramerdesign/ProcessWire#1367]
The code below throws no error when one of the pages doesn't have an image with the specified tag.
<img src=\"{$post->blog_images->getTag('preview')->url}\">

It'll simply loop through the pages and display whatever images it can. I think that's desirable behaviour.

Adding a width onto the same image does presents an error
<img src=\"{$post->blog_images->getTag('preview')->width(720)->url}\" >

> Error: Call to a member function width() on a non-object (line 44 of ....

Would it be possible to simply display the echoed pages without an error? It's a little inconsistent but also means I have to manually track down the offending image from a large selection of pages.

**Comment by ryancramerdesign** [comment]
The getTag() method returns NULL if no files matched the tag you provided. Both of the examples you mentioned would throw an error (if no tag matched), but the first is considered non-fatal to PHP, so the actual error notice is likely in your "src=" tag, which you don't see (or may be suppressed completely if debug mode is off). In either case, calling an object property or a method on NULL is a code error, so not something you'd want to rely on the behavior of. I would suggest doing this instead:
`````
$preview = $page->blog_images->getTag('preview'); 
if($preview) {
  // output your image
} else {
  // output a placeholder image or skip
}
`````

**Comment by isellsoap** [comment]
@eladnova Can you please close this issue? Thank you!

**Comment by isellsoap** [comment]
@eladnova This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
