### ISSUE TITLE
"Contains Text" filter not working on name field

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1369]
I think these two screenshots show the issue quite well.

![screen shot 2015-08-28 at 10 18 45 pm](https://cloud.githubusercontent.com/assets/871211/9560616/ef6c83a0-4dd2-11e5-9c4e-b79dec2b7680.png)
![screen shot 2015-08-28 at 10 18 14 pm](https://cloud.githubusercontent.com/assets/871211/9560615/ef6a63fe-4dd2-11e5-8c5f-b993b91b7dd8.png)

**Comment by ryancramerdesign** [comment]
> I think these two screenshots show the issue quite well.

As far as I can tell the screenshots show the correct result. The name of the page you are trying to match is "background" but you are trying to match it with the term "new", which is in the title, not the name. Wouldn't "No Results" be the expected result? Do you need more coffee, or do I? :)

**Comment by adrianbj** [comment]
Wow - I am sorry Ryan - apparently I needed more coffee when I posted this. Very embarrassed - sorry for wasting your time!

**Comment by ryancramerdesign** [comment]
Don't be embarrassed, I'm usually the one that needs more coffee–you wouldn't believe how often I get caught up into trying to resolve some issue I find that turns out to not actually exist. It goes with the job. :)
