### ISSUE TITLE
"Add permissions by role" ASM should have sortable set to false

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1371]
Not a big deal, but I think it is slightly confusing having this new field sortable when the order of these permissions isn't actually relevant.

**Comment by ryancramerdesign** [comment]
While PW may not care what order the permissions are in, these are still intended to be sortable for visual/grouping purposes. If the admin is assigning lots of permissions here, they will likely want to have some control over the visual organization of them.

**Comment by adrianbj** [comment]
Fair enough :)
