### ISSUE TITLE
ProcessPageListActions Extra Action trash only for superuser? (2.6.15)

### ISSUE THREAD

**Issue by gingebaker** [ryancramerdesign/ProcessWire#1373]
Hi
Just wanted to ask why the extra Action "trash" in PageListActions is only viewable for superusers?
This If Statement on Line 161:
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessPageList/ProcessPageListActions.php#L161
excludes all normal users with delete permission.

But users with delete permission are able to delete/trash pages when the are on page edit.

Am i missing something here? Is there a reason for that?
on PW Dev 2.6.15
thanks

**Comment by LostKobrakai** [comment]
This is the case of precaution, because only superusers can restore pages (superusers are the only users even just seeing the trash).

**Comment by gingebaker** [comment]
Thx for the info. I just find it a little confusing to allow it on page edit (delete-tab) but not allow it on the ExtraActions. 
Since i can hook into the ___getExtraActions() I can change it anyway.
