### ISSUE TITLE
Sort order for "Add New" not applied to other roles

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1376]
The option of setting a non-default sort order for items in the "Add New" dropdown (introduced in 2.6.13) ~~works for the current superuser~~, but the sort order is not applied for other users.

Edit: it seems even for superusers the custom sort order does not survive a logout/login. Sort order is reset to default.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai this issue has been fixed in the latest commit.

**Comment by isellsoap** [comment]
@Toutouwai Can you close this issue please? Thank you!
