### ISSUE TITLE
ProcessLogger: Modified column sorted as string

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1381]
As the title says:

Modified column is sorted as string, would be nice if it will be sorted on time (unix timestamp). 
Maybe something linke this will do:
```
<span style='font-size: 0;'>1441458411</span>5 hours ago
```

**Comment by ryancramerdesign** [comment]
Actually, that table was not meant to be sortable since it may span multiple paginations, and the tablesorter result only spans one pagination. I have disabled the click-to-sort column headers to prevent confusion here. Thanks!

**Comment by ryancramerdesign** [comment]
Okay just realized after I wrote that, that you may be talking about the actual logs list table, rather than the log entries table. I will go ahead and add the span as you suggested to make the sort work properly there. :)
