### ISSUE TITLE
tel-links are being stripped

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#1382]
Linking a phone number that use the "tel" protocol in a Textarea field in ProcessWire (CK Editor) are being stripped on save. (This is most likely a CK Editor issue.) 

Example:

	<a href="tel:123456789">123 456 789</a> (correct syntax)

On saving and reloading the page in the editing interface, I get these results:

* Observed result: 123 456 789
* Expected result: <a href="tel:123456789">123 456 789</a>

The link works when using "//" after the protocol name -- however, this syntax is incorrect according to W3C (see below).

Exapmle:

	<a href="tel//:123456789">123 456 789</a> (incorrect syntax)

### Field Type

I use the standard Body field in ProcessWire with this configuration: ```Type: Textarea - Inputfield Type: CKEditor, Content Type: Markup/HTML with image management```.

### Documentation / Tutorials / Examples re. "tel"-links:

* http://www.w3.org/wiki/Introduction_to_mobile_web
* http://www.mobilexweb.com/blog/click-to-call-links-mobile-browsers
* http://stackoverflow.com/questions/1164004/how-to-mark-up-phone-numbers

**Comment by tbba** [comment]
Maybe a HTML Purifier issue?

**Comment by mestaritonttu** [comment]
This seems to be a solution: http://stackoverflow.com/a/10467098/3057764

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this.

**Comment by isellsoap** [comment]
@klor Can you close this issue please? Thank you!
