### ISSUE TITLE
Viewing bookmarks returns "The process returned no content."

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1385]
![admin-bookmarks](https://cloud.githubusercontent.com/assets/11423659/9807375/b9ed9c2a-5852-11e5-97e3-d6094e0be1ec.png)

**Comment by tbba** [comment]
I had this too, in several (not all) websites, but only on the first login attempt attempt after the update.
I clicked on the Admin Link then moved to the frontpage and clicked around there... 
After that to my surprise I was able to login normally and see the page tree as usual... 
So this could have been some temporary cache or cookie effect with a browser hick up?

**Comment by kalmarlansmuseum** [comment]
Logged out/in and now it returns the bookmark. Thanks for your help!

**Comment by mikerockett** [comment]
Yeah, I had the same thing... Think it has something to do with applying an update after login, not sure.
