### ISSUE TITLE
Additional noParents setting for templates

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1391]
It would be nice to have not only a "one" setting, but also a "one per parent". For example for structures like this:

```
- BMW Mini (car)
    - Spare Parts (spare_parts, one-per-parent)
        - Spare Part #1
        - Spare Part #2
    - Services (services, one-per-parent)
        - Service #1
        - Service #2
```

One wouldn't like to have multiple `spare_parts` or `services` folders in such a case.

**Comment by plauclair** [comment]
How about a 1-n constraint globally available for page relationships? That seems more versatile than limiting by one.

**Comment by LostKobrakai** [comment]
Yeah, maybe even hookable, so one could also set the limit dynamically, e.g. limit the number of reservations for an event.

**Comment by ryancramerdesign** [comment]
Sounds like an interesting idea, thanks. Will definitely give it future consideration.
