### ISSUE TITLE
wire/modules/Process/ProcessPageEditLink: URL gets lost when switching Tabs

### ISSUE THREAD

**Issue by MadeMyDay** [ryancramerdesign/ProcessWire#1393]
Hi,

if you try to enter a link in CKE and try to set a target in one go, the URL is lost (also the preview is empty). If you first define the target and then the URL, it works. It also works if you first enter the link, "insert link" in editor and edit the link again. Tested in version 2.6.15.

**Comment by teppokoivula** [comment]
Used to have this problem, but as of 2.6.16 (I think) it's now gone. I'd check if updating helps.

**Comment by ryancramerdesign** [comment]
Thanks, I thought I'd fixed this one already too, but just tried it and got the same non-working result. I've just pushed a fix.

**Comment by isellsoap** [comment]
@MadeMyDay Can you close this issue please? Thank you!
