### ISSUE TITLE
WireInput::previousRequestFormData

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1394]
It would be nice to have the ability to store request data (post/get) for an additional page request, so they are still available after a redirect. So one doesn't need to render a form on the same page as the validation does happen. While I'm using something different a Restful structure for example does need this:
- A form on /entity/create sends POST data to /entity
- /entity doesn't validate the request and redirects back to /entity/create
- /entity/create should still be able to pre-fill the form with the submitted data

As WireInput isn't hookable there's also no way to plug this functionality in by oneself.

**Comment by teppokoivula** [comment]
Sounds like a sensible use case for session data, though /entity *could* also send a POST request back to /entity/create. What you're suggesting here might make sense, so would you mind explaining a bit further why/how this is better than aforementioned options?

**Comment by LostKobrakai** [comment]
I'm now using the session to store and retrieve the data, but I'd really like to retrieve the data from the WireInput object, which is imho the more logical place for that. For storage the session is surely the best option. 

How would I send back POST data as part of an redirect?

**Comment by teppokoivula** [comment]
Yeah, looks like I didn't exactly think that one through. Redirect with POST data won't work without some weird tricks with auto-submitted forms, etc. :)

The remaining solutions are session, or the one you're suggesting here. This is starting to make more sense now, except that I still see session as a superior solution: it has more flexibility (need to store not just one but two sets of data? was there an extra redirect in-between those requests? no problem!) *and* it's also already there.

I'm a big fan of the "less is more" strategy, and in my opinion each new feature should either add something entirely new or make some common task a lot easier, and so far I'm seeing neither here.

Anyway, that's just my take on this.

**Comment by LostKobrakai** [comment]
This is what I'm currently using. It would need some additions to allow for multiple redirects / multiple saved dataset. I don't think that the storing part should be done different than with the session. Just the implementation of holding the lastData / retrieving it should in my opinion be part of WireInput.

```php
/**
 * Save request data in session over one redirect
 */
// This could be a function of WireInput
$wire->addHook("Session::previousRequestData", function(HookEvent $event){
	$key = $event->arguments(0);
	$event->return = $key ? wire('page')->previousRequestData->__get($key) : wire('page')->previousRequestData; 
});

// Here I'd like to store the data not in the page but as part of WireInput
if(is_array($session->saveRequestData)){
	$page->previousRequestData = new WireInputData($session->saveRequestData);
	$session->remove("saveRequestData");
}

if($input->post || $input->get){
	$data = array_merge($input->get->getArray(), $input->post->getArray()); //convenient
	$session->saveRequestData = $data;
}
```

**Comment by ryancramerdesign** [comment]
I like the idea in terms of potential convenience, but I'd have security concerns about PW handling this. It would have to just store all the unsanitized GET/POST data in session, and I don't think it's good security to use server-side storage for unsanitized user input. For instance, someone could start firing off giant POSTs to the server under a farm of IP addresses and consume huge amounts of resources, maybe even exhaust the drive space and halt the site. It would be far better I think for one to use $session to store specific (and sanitized) data that they want to use in a later request.

**Comment by LostKobrakai** [comment]
That's true. Maybe I should add some kind of sanitizer to my current implementation as well.

**Comment by plauclair** [comment]
How about a mix of a maximum form data size (stored in a specific part of $session and roughly evaluated as ```strlen(serialize($))```) in config and a destructor on each call unless a redirect has happened?

I very often store stuff in session but tracking their creation and destruction can sometimes be a bit messy.
