### ISSUE TITLE
New published field not working to sort in selector

### ISSUE THREAD

**Issue by tomfrit** [ryancramerdesign/ProcessWire#1395]
$pages->find("parent=/,sort=published) doesn't seem to work. Apparently $pages->find("parent=/")->sort("published") works but in many cases that's not a possible workaround.
Thanks.

**Comment by ryancramerdesign** [comment]
Thanks, the latest commit should fix this issue.

**Comment by isellsoap** [comment]
@tomfrit Can you close this issue please? Thank you!
