### ISSUE TITLE
Class WireDatabaseBackup, function getFileInfo() doesn't match footer in sql properly

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1402]
In some cases function getFileInfo() will find a curled bracket before the commented footer but within the last 278 characters of the sql file, which results in not displaying numTables in the AdminDataTable and FileInfo. I recommend to change Line 461 from
```
$pos = strpos($foot, '{');
```
to something like
```
$pos = strpos($foot, '{"numTables"');
```
or better
```
$pos = strpos($foot, self::fileFooter) + strlen(self::fileFooter);
```

**Comment by ryancramerdesign** [comment]
Thanks @kixe, great solution. This appears in the latest commit.
