### ISSUE TITLE
Too many tables; MySQL can only use 61 tables in a join

### ISSUE THREAD

**Issue by foobarlab** [ryancramerdesign/ProcessWire#1407]
I get the following error in PW 2.6.17:
```
Error: Exception: SQLSTATE[HY000]: General error: 1116 Too many tables; MySQL can only use 61 tables in a join (in <...path to my hosting ....>\htdocs\wire\core\PageFinder.php line 298)

#0 [internal function]: PageFinder->___find(Object(Selectors), Array)
#1 <...path to my hosting ....>\htdocs\wire\core\Wire.php(397): call_user_func_array(Array, Array)
#2 <...path to my hosting ....>\htdocs\wire\core\Wire.php(332): Wire->runHooks('find', Array)
#3 <...path to my hosting ....>\htdocs\wire\core\Pages.php(216): Wire->__call('find', Array)
#4 <...path to my hosting ....>\htdocs\wire\core\Pages.php(216): PageFinder->find(Object(Selectors), Array)
#5 [internal function]: Pages->___find('path=/a/a/a/a/a...', Array)
#6 <...path to my hosting ....>\htdocs\wire\core\Wire.php(397): call_user_func_array(Array, Array)
#7 <...path to my hosting ....>\htdocs\wire\core\Wire.php(332): Wire->run

This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged. Administrator has been notified. 
```

This error appears when the URL in the browser address bar contains more than 61 slashes. For example http://www.example.com/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/ will throw this error.

Any chance to limit the number of joins in PW?

**Comment by ryancramerdesign** [comment]
Thanks @foobarlab I have committed a fix for this so that it should now show a proper 404 rather than a 500. The exception you see would only appear if you were logged in as an admin or had debug mode enabled. The fix was to add a $config->maxUrlDepth setting (with default value of 30) to prevent PW from attempting to initiate a query an impossible path.
