### ISSUE TITLE
translation in bookmark menu

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1411]
Click in top menu: Pages > Edit. 
In the breadcrumb the "Page Edit > Bookmarks" isn't translated.

solution: add the 2 strings in wire/templates-admin/default.php
```
 * __("Bookmarks");
 * __("Page Edit");
```

Screenshots from default and Reno theme:
![pw-bookmark-default](https://cloud.githubusercontent.com/assets/5367033/10122037/8ac370d2-6509-11e5-870a-780fe347d528.jpg)
![pw-bookmark-reno](https://cloud.githubusercontent.com/assets/5367033/10122038/96741062-6509-11e5-956a-6335c73a483b.jpg)

**Comment by ryancramerdesign** [comment]
Thanks, this update has been pushed.

**Comment by Manfred62** [comment]
fixed!
