### ISSUE TITLE
ProcessTemplate.module adding non-minified version of ProcessTemplateFieldCreator.js

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1413]
See my comment from a while ago.

https://github.com/ryancramerdesign/ProcessWire/commit/1d3745944765842cb3a7d1aed02c9a83dcfd53a8#commitcomment-12364675

Looks like it is still the same in the latest dev version:
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessTemplate/ProcessTemplate.module#L543

**Comment by ryancramerdesign** [comment]
Thanks Adrian–fixed.

**Comment by adrianbj** [comment]
Thank you!
