### ISSUE TITLE
top nav in responsive view missing translation

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1415]
in mobile view (hamburger icon) the navigation isn't fully translated. 
The first 4 items from *id topnav* aren't translated.
Link to forum post: https://processwire.com/talk/topic/925-german-de-de/page-9#entry103203

screenshot:
![pw-responsive-nav](https://cloud.githubusercontent.com/assets/5367033/10139794/e69d7262-6604-11e5-9a22-47e42c9caf8a.jpg)

**Comment by ryancramerdesign** [comment]
Thanks @Manfred62 I've pushed a fix for this issue.

**Comment by Manfred62** [comment]
fixed
