### ISSUE TITLE
Editor unable to edit / view image and thumbnail (in repeater)

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#1418]
*Not sure if a bug or intended security:*
When the config setting "Secure page files" is on, an editor can upload images to an **unpublished** page, but not view them in the image field (also the admin thumbnail isn't shown). An expected 404 not found javascript error is thrown.
I know it's a security setting for 'guests', is it also intended for someone with 'edit' access to the unpublished page?

*Note: it only happens with an image field that is in a repeater field, not with image fields that are directly in the page template.*

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this issue. Please let me know if you run into any more problems with it.

**Comment by junofornow** [comment]
thanks.
