### ISSUE TITLE
An Exception after delete log file

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1422]
If i delete "messages" or "sessiong" log file i am getting  Exception Error log :
```
Unknown log (in /wire/modules/Process/ProcessLogger/ProcessLogger.module line 145)
```

**Comment by ryancramerdesign** [comment]
I'm not seeing that error message here. Just deleted both my messages and session logs. What version of PW? Also, does the log get deleted, or does it remain?

**Comment by trk** [comment]
I am using ProcessWire 2.6.18 dev version. After delete log file Exception log message is appearing.

![ekran resmi 2015-10-01 14 38 27](https://cloud.githubusercontent.com/assets/455983/10219798/bacf80b0-684a-11e5-98d0-768a39f6153e.png)
![ekran resmi 2015-10-01 14 39 06](https://cloud.githubusercontent.com/assets/455983/10219799/bad61952-684a-11e5-835e-07b34c7b932d.png)
![ekran resmi 2015-10-01 14 39 17](https://cloud.githubusercontent.com/assets/455983/10219800/bad7e96c-684a-11e5-92f1-8629fe52e816.png)
