### ISSUE TITLE
With noSettings on, page list trash action button is missing

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1424]
This might be intentional. I can understand why the unpub, hide, lock are not shown, but I feel like the trash button should maybe still be available since hiding the settings tab does not prevent page deletion.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks Ryan, but now I am seeing two trash buttons - trying to attach a screenshot, but Github is complaining :) There is one showing by default, and then another after using the expand arrow.

**Comment by adrianbj** [comment]
![screen shot 2015-10-02 at 4 31 29 am](https://cloud.githubusercontent.com/assets/871211/10230864/d9f55ad2-68c2-11e5-8bb2-0dd5987f798b.png)

**Comment by adrianbj** [comment]
Ignore me - I had Nico's Page Delete module installed on this pw test site.
