### ISSUE TITLE
ProcessModule fails to create page

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1427]
I don't know if this is intended or is a bug, never-the-less I'll report it.
When using an install() method in a ProcessModule the page assigned in the getModuleInfo() is ignored. 
(not created)

```php
/**
 * When using an install() method
 *
 */
public function ___install() { }



/**
 * The page to install from getModuleInfo() is ignored
 *
 */
public static function getModuleInfo() {
    return array(
        ... etc.
        'page' => array(
            'name' => 'my-page',
            'parent' => 'setup',
            'title' => 'Just a title'
        ),
    );
}
```
PW 2.6.18

**Comment by ryancramerdesign** [comment]
Your install method needs to call parent::install(), and the same approach
for an uninstall() method, if used.

**Comment by LostKobrakai** [comment]
Leaving it out should work as well, right?

**Comment by ryancramerdesign** [comment]
Yup, okay to leave it out if you don't need it, as that just calls the
Process::install() instead.

**Comment by Da-Fecto** [comment]
Good to know, I was a little confused about this one.
