### ISSUE TITLE
Inputfields in columns not collapsing correctly

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1428]
Inputfields in columns do not collapse correctly. Full-width fields seem to be okay. I tested in Firefox Windows, Chrome Windows, IE11. If you don't see the bug on the first toggle try toggling both columns a few times.

These issues occur in the latest dev and the current stable.

Note the "Body", "Images" and "Text 1" fields in the screenshot below.
![edit page1](https://cloud.githubusercontent.com/assets/1538852/10240202/8877a6e2-6935-11e5-9be9-45935650939c.png)

Not 100% sure the following is a bug, but when column fields are collapsed there are gaps in the form border.
![edit-page2](https://cloud.githubusercontent.com/assets/1538852/10240213/96db6372-6935-11e5-9912-e326e38d99d7.jpg)

**Comment by LostKobrakai** [comment]
The first one is a bug I noticed, too. The last one is how it's supposed to work.

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this. Also @lostKobrakai is correct that the last example mentioned there is the intended/correct behavior.

**Comment by isellsoap** [comment]
@Toutouwai Can you close this issue please? Thank you!
