### ISSUE TITLE
Pagetable doesn't use responsive table layout

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1430]
I just noticed that a page table under 2.6.17 doesn't use the responsive layout in AdminThemeReno.

**Comment by ryancramerdesign** [comment]
I hadn't really intended on supporting responsive table for this, but since it's just a matter of adding a class to the table now, we might as well – I have added this. Though I think PageTable is not a great candidate for mobile edits either way.

**Comment by LostKobrakai** [comment]
Maybe not for edits, but most of the time the table is rather to tell the user information, which can be consumed on mobile as well.
