### ISSUE TITLE
Warning when running actions in listerpro

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1434]
Warning: Invalid argument supplied for foreach() in /var/www/lager/wire/modules/Inputfield/InputfieldForm.module on line 364

Latest dev and lister.

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed.

**Comment by isellsoap** [comment]
@LostKobrakai Can you close this issue please? Thank you!
