### ISSUE TITLE
Warning when accessing users with non superuser

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1435]
When I access the users lister I get the following warning, as long as I'm not superuser and not using any filters:
```
strpos() expects parameter 1 to be string, array given in /var/www/lager/wire/modules/Process/ProcessPageLister/ProcessPageLister.module on line 1425
```
I wrapped the argument in quotes and now I get this instead, but at least the lister is working instead of erroring.
```
PHP Notice:  Array to string conversion in /var/www/lager/wire/modules/Process/ProcessPageLister/ProcessPageLister.module on line 1425
```

**Comment by plauclair** [comment]
What if you try strval() instead? This might force a __toString() on the object.

**Comment by LostKobrakai** [comment]
I'm not sure, but the variable should probably not be an array in the first place.

**Comment by plauclair** [comment]
Probably not but I've been calling some methods on other objects that would give me similar results if not wrapped in this function, even though they were called from smart quotes.

**Comment by ryancramerdesign** [comment]
Thanks, this issue has been fixed.
