### ISSUE TITLE
$sanitizer->text truncated

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#1441]
Although the cheatsheet mentions that $sanitizer->text truncates up to 1024 characters, only 254 characters are kept.

this one is on 2.6.17 dev

**Comment by teppokoivula** [comment]
Just checking, but did you notice that this value can be changed by providing text() with a config array? Default for max length seems to be 255, so I'd guess that documentation (and/or cheatsheet) are either plain wrong or just out of date.

**Comment by junofornow** [comment]
no I didn't know, thanks - never needed extra's before (and not always checking the inline source comments...)
So I guess the cheatsheet is out-of-date.

**Comment by ryancramerdesign** [comment]
That cheatsheet entry should be updated to be more clear. Technically it's correct in that it does truncate to 1024 characters by default, but it's talking about 1-byte characters (better termed "bytes"), which amounts to about 255 UTF-8 characters. So it should really say 1024 bytes or 255 UTF-8 encoded characters.

**Comment by junofornow** [comment]
Thanks Teppo and Ryan for the clarification.
Since it's not an actual issue, I'm closing it.
