### ISSUE TITLE
comments.js console error

### ISSUE THREAD

**Issue by Majini** [ryancramerdesign/ProcessWire#1443]
Hi Ryan
Having created and set up a comments field, the instructions that are visible within this fields "details" tab describe to us how to link comments.js should we be utilizing the threaded comments feature.

When doing this, I get a console error in Firebug.

Tracking it down, it turns out that comment.js has a missing semi-colon on line number 56:
var $form = $this.closest('form.CommentForm')

Adding a semi-colon to the end of the above said line eliminates the console error.

Hope that helps!

Zahari M.

**Comment by ryancramerdesign** [comment]
Thanks, I've submitted a fix.

**Comment by isellsoap** [comment]
@Majini Can you close this issue please? Thank you!

**Comment by Majini** [comment]
Hi Francesco

Done!

Thanks for the message :)

Cheers

On Thu, Mar 10, 2016 at 3:37 PM, Francesco Schwarz <notifications@github.com
