### ISSUE TITLE
CKEditor in Repeater has 3 lines of icons.

### ISSUE THREAD

**Issue by beatep** [ryancramerdesign/ProcessWire#1445]
I have a textarea in a repeater and a "normal" body field with the same configuration. The textarea in the repeater has 3 lines of icons, and the body one line. If I put the repeater textarea as a single fileld in the template, it also has 1 line. I think the configurations of PW get ignored on repeater fields.

PW 2.6.19
![bug_pw](https://cloud.githubusercontent.com/assets/1794446/10426269/bbd84a7c-70de-11e5-981c-d6f71bccda1b.png)

**Comment by ryancramerdesign** [comment]
Thanks for the report. So far I can't seem to duplicate this one though. I've setup a repeater that has 'title' and 'body' fields, while the template that it lives in also has the same fields. I'm just seeing the one line of icons. I tried both inline mode and regular mode. Can you think of any other factors that might affect it?

**Comment by isellsoap** [comment]
@beatep Is this still an issue with the latest ProcessWire issue? If not, I would like to close the issue. Please give us an update on this issue, thank you.

**Comment by beatep** [comment]
Works for me on 3.0.34 and 2.7.2.
