### ISSUE TITLE
ajax fileupload not working if filefield global settings set to hidden, not shown in editor

### ISSUE THREAD

**Issue by jriihi** [ryancramerdesign/ProcessWire#1450]
It seems ajax file upload does not work if filefield global settings set to hidden, not shown in editor. This "bug?" is in processwire 2.6.1. If it set template specific context for filefield to Always open (default) ajax file upload does not work if global settings is set to hidden.

**Comment by ryancramerdesign** [comment]
Thanks @jriihi I have pushed a fix for this.

**Comment by isellsoap** [comment]
@jriihi Can you close this issue please? Thank you!
