### ISSUE TITLE
Add support for IIS

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1453]
Supply web.config.txt and copy it to web.config when installing PW on Internet Information Services. Inform the user that he needs IIS URL Rewrite module. Inform the user that he can ignore the warning about "Unable to determine if Apache mod_rewrite (required by ProcessWire) is installed." (or better yet, don't display that warning at all).

**Comment by ryancramerdesign** [comment]
We don't officially support IIS right now, and don't have the server test environment to maintain it. But if what you've mentioned is all that's necessary to support it, maybe it's something we could do with PW 3.x. We are also looking to officially support nginx in 3.x as well. What is the contents of the web.config file? I'm assuming it would be significantly different from .htaccess?

**Comment by matjazpotocnik** [comment]
Yes, web.config is significantly different from .htaccess. See https://processwire.com/talk/topic/268-processwire-on-windows72008-server-with-iis-webserver/?p=99778

**Comment by matjazpotocnik** [comment]
I have tested:

PW 2.4.x, 2.5.4 dev, 2.5.26 dev, 2.6.0 dev, 2.6.21 dev on Windows Server 2008 R2, IIS 7.5, PHP 5.5.1, MySQL 5.6.15

PW 2.6.21 dev on Windows 8.1 Professional, IIS 8.5, PHP 5.6.0, MySQL 5.7.9

PW 2.5.4 dev, 2.5.7 dev on Windows Server 2012 R2, IIS 8.5, PHP 5.5.12, MariaDB 10.0.11 

I can provide instructions, web.config file and modified install.php if there is interes.

**Comment by BitPoet** [comment]
I can add that PW runs without hassle on IIS 10 (I've got PW versions 2.6, 2.7 and 3.0 running on it). Our intranet (>50k requests/day) has now been running without the slightest glitch on IIS 7.5 with PW 2.6 for the last four months. I'd be happy to help too.

Normally, getting things up and running should be straight forward. For installs in subdirectories, one substitution in the web.config template (to get all 404 errors redirected to PW) should be sufficient, as the rewrite rules are all parent path agnostic. The presence of the URL Rewrite module can be checked through ``$_SERVER["IIS_UrlRewriteModule"]``.

**Comment by matjazpotocnik** [comment]
BitPoet: Do you have manuals for installing PW on IIS? Should we provide info on installing prerequisites (IIS, UrlRewrite, mysql)? Please contact me on the forum (matjazp) if you would like to elaborate further (permissions, web.config, install.php etc).

**Comment by matjazpotocnik** [comment]
Closing this in favour of https://github.com/processwire/processwire-requests/issues/7
