### ISSUE TITLE
translation in bookmark menu #2

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1455]
clicking on Pages - *Tree* - Bookmarks:

![pw-page-list](https://cloud.githubusercontent.com/assets/5367033/10558759/6d25e22a-74dc-11e5-8c85-9b2dadef367f.jpg)
for the breadcrumb add the following to wire\templates-admin\default.php
```
 * __("Page List");
```

================================
clicking on Pages - *Edit* - Bookmarks:

![pw-page-edit](https://cloud.githubusercontent.com/assets/5367033/10558781/00fbe49a-74dd-11e5-83b8-18216248e1c4.jpg)

the translation in the heading (Page List/Page Edit) is missing

**Comment by ryancramerdesign** [comment]
Thanks @Manfred62 I have pushed a fix for this.

**Comment by Manfred62** [comment]
> the translation in the heading (Page List/Page Edit) is missing

the breadcrumb is ok now, but the headings ```<h2>``` aren't translated. Did I oversee something?

**Comment by ryancramerdesign** [comment]
You are right, my mistake. I've just pushed another update for this–thanks.

**Comment by Manfred62** [comment]
now fixed
