### ISSUE TITLE
If the admin credentials entered are not correct there is no way of knowing

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1459]
No error message is given if the admin credentials are incorrect.

**Comment by teppokoivula** [comment]
Can you clarify this a bit; what exactly are you referring to here? Do you mean the login screen, or something entirely different?

In case you're talking about the login screen, I'm currently seeing the "login failed" message for wrong credentials.

**Comment by cb2004** [comment]
@teppokoivula I have done a bit more testing, and if the SystemNotifications module is installed, there is no login failed message.

**Comment by mikerockett** [comment]
I can confirm this on my sites as well.

**Comment by teppokoivula** [comment]
Right, got the same problem here once I installed SystemNotifications.

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this.

**Comment by cb2004** [comment]
@ryancramerdesign I can now confirm a login failed notification if both inputs are populated, however if none or one is populated there is no notification. More of an enhancement now?

**Comment by isellsoap** [comment]
@ryancramerdesign Investigate more on this?

**Comment by isellsoap** [comment]
@cb2004 Can this issue be closed?

**Comment by isellsoap** [comment]
@cb2004 I close this issue as it seems fixed. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.

**Comment by cb2004** [comment]
@isellsoap this is probably an enhancement now. Earlier comment:

@ryancramerdesign I can now confirm a login failed notification if both inputs are populated, however if none or one is populated there is no notification. More of an enhancement now?

**Comment by isellsoap** [comment]
@cb2004 Ok, you a free to open an issue in the [new requests repository](https://github.com/processwire/processwire-requests). Thank you.
