### ISSUE TITLE
pages menu dropdown with different items

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1460]
When logging into PW (green bar on top), the "Add New - Bookmark" is also available in the Pages dropdown. After refreshing or other action the entry "Add New - Bookmark" isn't available anymore. Intentional?

![pw-login-bookmark](https://cloud.githubusercontent.com/assets/5367033/10584210/25b62380-7691-11e5-969b-b8ea349ca8a6.jpg)

after action/reload:

![pw-logged-bookmark](https://cloud.githubusercontent.com/assets/5367033/10584239/617ca01a-7691-11e5-9a1e-d0ea969296e2.jpg)

**Comment by ryancramerdesign** [comment]
I'm not seeing that here. What version of PW are you using? If 2.6.20, you might try doing a Modules > Refresh and trying again. Please let me know what you find.

**Comment by Manfred62** [comment]
hmm, refreshed the modules. But still the same. After login there's this menu entry.

PW 2.6.20 (the latest update from 10 min ago)
Win 7, local XAMPP 5.6.14
actual Firefox and Chrome

**Comment by ryancramerdesign** [comment]
Thanks @Manfred62, I still can't duplicate this one but will keep an eye out and lets see if anyone else runs into the same issue.

**Comment by isellsoap** [comment]
@Manfred62 I couldn’t reproduce your issue on a fresh 3.0.34 install even after several reloads and page actions, thus I close it. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
