### ISSUE TITLE
There is missing two double quotes on .htaccess file

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1462]
Line: 29 and Line: 33

```
<Files favicon.ico>
  ErrorDocument 404 "The requested file favicon.ico was not found.
</Files>

<Files robots.txt>
  ErrorDocument 404 "The requested file robots.txt was not found.
</Files>
```

**Comment by ryancramerdesign** [comment]
That's intentional. From what I understand not all versions of apache
understand ending quotes here, but all understand a single opening quote.

**Comment by trk** [comment]
Sorry PhpStorm showing error at that lines and i didn't read comment line. thanks for your quick reply !  :)
