### ISSUE TITLE
Multi-language: Settings > Name is showing /home/ for the direct children, Active checkbox is showing the translated version

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1465]
I have a multi-language setup with default and Deutsch. A direct parent of Home has the link /about-us/, however in the admin it is showing /home/about-us/ on the settings tab. The view link is showing correctly as /about-us/

Also I have installed the German language pack:

http://modules.processwire.com/modules/german/

You will see from the screenshot that the Active checkbox is showing in that installed language, but shouldnt this only display if I have selected that language in my profile?

![2015-10-21- 24](https://cloud.githubusercontent.com/assets/6205980/10642795/7a55d336-7817-11e5-97da-e75133fa64ca.png)

**Comment by ryancramerdesign** [comment]
> I have a multi-language setup with default and Deutsch. A direct parent of Home has the link /about-us/, however in the admin it is showing /home/about-us/ on the settings tab. The view link is showing correctly as /about-us/

Check your homepage by editing it. You likely have "home" entered as the page name for the default language. Remove that and make it blank. 

> You will see from the screenshot that the Active checkbox is showing in that installed language, but shouldnt this only display if I have selected that language in my profile?

This field should show checkboxes for all languages you have installed, which is what enables you to turn it on or off for specific languages. If you don't want that, you can install language permissions (added recently on dev branch, and covered in a recent blog post).

**Comment by cb2004** [comment]
Hey Ryan.

My default home name is blank:

![home](https://cloud.githubusercontent.com/assets/6205980/10663699/4c178a48-78b5-11e5-94ae-075e0155133e.png)

Here is my finding:

Home
>> About us | Name: /home/about-us/ | View link: /about-us/
>> About us >> Team | Name: /about-us/team/ | View link: /about-us/team/

So it looks like it is just adding the /home/ on direct children even though it shouldn't.

Should that checkbox show the words Aktiv though when my profile is set as Default and not Deutsch?

**Comment by ryancramerdesign** [comment]
I'm not sure where the "home" is coming from in your case, as I don't see that here. You might try editing the homepage and typing in something like "test" for the default homepage name, Save, then make it blank, and save again. Though if it's not interfering with anything else, you should be able to safely ignore it. I think much older versions of PW originally had "home" as the page name, even if it was ignored, so it may just be carrying over from that. 

> Should that checkbox show the words Aktiv though my profile is set as Default and not Deutsch? Shouldn't it be Active?

You are right–it was showing the wrong language for that. I have just pushed a fix, thanks.

**Comment by cb2004** [comment]
@ryancramerdesign ok so I changed the name to 'test', which then made the direct children have the url test/*, now I go to remove the test and make it blank again but it doesn't like it and 'test' wont go.

This was a 2.6.13 fresh install recently upgraded to 2.6.20 so not very old at all.

**Comment by cb2004** [comment]
@ryancramerdesign further findings. I deleted the name straight out of the database which works. I no longer got /home/ in my direct children. I then added a name again to the home page, all was fine, when I tried to make it blank again it would not change. Changing it to something else does work though. Very odd.

**Comment by cb2004** [comment]
@ryancramerdesign and even more findings. When i checked a fresh install of the dev it does have the 'home' name stored in the database. These settings do not appear on a site that does not have multilanguage for the home page. So I went back to my multilanguage site, put the name in as home and it changed it back to blank.

I will leave you alone now :)

**Comment by ryancramerdesign** [comment]
Thanks for your tests. As it turns out "home" (rather than blank) is the default name for the homepage, I had just forgotten this. PW requires all pages to have a name. So it just ignores the "home" when it appears on the homepage. I'm not certain why it was showing up in your URLs since it's supposed to be ignored, but I've attempted a fix which is now in the latest commit to the dev branch. I'm hoping this will make it really ignore "home" this time. :) It should also let you make it blank if you want to (and it'll substitute "home" behind the scenes, since it needs a name in the DB). Please let me know how it works.

**Comment by ryancramerdesign** [comment]
Btw, the fix just affects one file, so that's all you'd need: /wire/modules/Inputfield/InputfieldPageName/InputfieldPageName.module

**Comment by cb2004** [comment]
Good work, I can confirm fixes for all issues here :)
