### ISSUE TITLE
Request/Discussion: Page field label formats (plural)

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1466]
Hi there

Label formats in page fields are great, but when you use custom PHP to generate the page list you could be pulling from multiple templates. In that scenario, I might want some page labels to be {parent.title} - {title} and some just to be {title}.

What I'm wondering is if there would be merit in a way to allow multiple formats depending on criteria such as template, or page parent etc? So maybe have that single field as it is with an Add button next to it and when you click on the Add button, it adds another row. The first row is the default custom format to be used and additional rows have 2 fields - "selector" and "custom format" where selector is just a string like "template=news".

While on the subject - and I'm sure I've not thought about all use cases - couldn't the first 3 options under "Selectable pages" now be replaced with InputfieldSelector? Custom is still required as there are times when you need to throw in something much more complex, or combinations of selectors resulting in a single PageArray so that one definitely needs to stay but perhaps the others could be done with a single InputfieldSelector. That said, they are simple to use as they currently are!

**Comment by Notanotherdotcom** [comment]
Turns out you can already achieve this - see my example here: https://processwire.com/talk/topic/11258-advanced-page-field-labels/

My only concern with the approach I've taken is if there is any danger of the titles I've manipulated getting saved? I can't see how - using the Custom PHP Code option you can't add pages through the inputfield so they should never get saved with their temporary titles, but I'm wondering if this is safe?

**Comment by ryancramerdesign** [comment]
I think your strategy looks fine, and shouldn't be danger of those titles getting saved so long as they aren't the pages being edited. If you were worried about it, you could always populate a custom property at runtime, like "_title" or something, and then make that your pageLabelField.

**Comment by Notanotherdotcom** [comment]
Oh yes! Silly me - that custom property sounds a lot safer, thanks!
