### ISSUE TITLE
Select All not working for Images Variations modal

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1468]
![Images Variations  Modal](https://cloud.githubusercontent.com/assets/455983/10648995/3dc6cab4-784a-11e5-808a-ae7c2918c880.png)

**Comment by ryancramerdesign** [comment]
Thanks I have pushed a fix for this.

**Comment by trk** [comment]
It's ok not, thank for fix.

**Comment by trk** [comment]
Variation delete action is not working
