### ISSUE TITLE
PageTable autopublish item pages

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1469]
Seems like there is some interest from others in having this option:
https://processwire.com/talk/topic/11255-pagetable-autopublish-item-pages/

**Comment by isellsoap** [comment]
This would be very neat, indead!

**Comment by isellsoap** [comment]
I republished this feature request [in the new repository ](https://github.com/processwire/processwire-requests/issues/14) and close this one.
