### ISSUE TITLE
Api to get previous parent of trashed pages

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1472]
As outlined in this topic:
https://processwire.com/talk/topic/11123-get-previous-parent-for-trashed-page/

**Comment by ryancramerdesign** [comment]
For this you would have to extract it from the page name. I think you could do it like this:
``````
list($id, $parent_id, name) = explode('.', $page->name, 3); 
$parent = $pages->get($parent_id); 
```````

**Comment by LostKobrakai** [comment]
It would be nice to have that as api somewhere, as I wouldn't trust this solution to be very future proof.
