### ISSUE TITLE
Double Hooks

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1474]
When Hooking WireMail::send and one of the SMTP sending modules is installed. 
Hooks are attached for WireMail and for the other Module.

Is this intensional and should I try to figure out how to remove the double Hooks or just let it be?

**Comment by ryancramerdesign** [comment]
It's intentional but I'm guessing the wiremail module you mentioned is
calling parent::send() rather than parent::___send(). That would make the
hook get called twice. Which module is it?

**Comment by Da-Fecto** [comment]
It's a module I'm currently building to add Branding to wireMail.

I've put it on GitHub right now for you to see (look at Module configuration)
https://github.com/Da-Fecto/WireMailTemplates

```
// use it with:
$mail = wireMail();
$mail->to('user@other_domain.ext')->from('me@domain.ext'); // all calls can be chained
$mail->subject('Mail Subject');
$mail->bodyHTML('<p>Maecenas faucibus mollis interdum.</p>');
$mail->send();
```

**Comment by Da-Fecto** [comment]
Moving the hooks from init() to ready() solves the double hook issue.
In this repository it works fine. Thanks looking into it.
https://github.com/Da-Fecto/WireMailBranding

**Comment by ryancramerdesign** [comment]
Thanks Martijn, I've looked at your module and everything seems okay there.
I'm not exactly sure why switching from init() to ready() made the
difference here, but I'm thinking that your module must be getting loaded
twice somehow. I wanted to suggest adding `"singular" => true` to your
getModuleInfo() method to ensure that only once instance of it can be
active. I would also recommend implementing the ___send() method in your
WireMail class, even if it doesn't do anything. Like this:
````````
public function __send() {
  return parent::___send();
}
```````

On Sat, Oct 24, 2015 at 4:13 PM, Martijn Geerts <notifications@github.com>
wrote:

> Moving the hooks from init() to ready() solves the double hook issue.
> In this repository it works fine. Thanks looking into it.
> https://github.com/Da-Fecto/WireMailBranding
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryancramerdesign/ProcessWire/issues/1474#issuecomment-150847262>
> .
>

**Comment by Da-Fecto** [comment]
Cool... I do think the double calls come from the function call wireMail() in /core/functions.php. I think there is the (hidden) reason somehow but i'm not sure. I go test your implementations and probably release it to the public. 

Thanks again taking your time to look into it.

**Comment by Da-Fecto** [comment]
I've added ```'singular' => true``` moved to ```init()``` and added ```return parent::___send();``` + fixed a bug... All working great now, thanks again.

**Comment by ryancramerdesign** [comment]
Great! Glad that fixed it.
