### ISSUE TITLE
Class 'ProcessWire\WireHooks' not found 

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1478]
Installing PW 3.x alpha (devns branch) on IIS (I know, not supported), PHP 5.6.0, and I get:

Fatal error: Class 'ProcessWire\WireHooks' not found in C:\inetpub\wwwroot\wire\core\ProcessWire.php on line 109.

This happens after clicking Continue on the last screen, after entering Admin Account Information (step 5). $wire = new ProcessWire($config); in the index.php is failing.

**Comment by ryancramerdesign** [comment]
Not sure why that error was showing up (it wasn't occurring here), but I did just push a major update to the 3.x devns branch. As a speed optimization, we now bypass the autoloader for known core classes that will always be loaded (and WireHooks is one of them) so I'm guessing this error wouldn't continue, but please let me know if so.

**Comment by matjazpotocnik** [comment]
Ok, thank you. Will try updating and reopen if it happens again.
