### ISSUE TITLE
Sanitizer URL unexpected result

### ISSUE THREAD

**Issue by FerdiAgrio** [ryancramerdesign/ProcessWire#1479]
When using the sanitizer API function I expect the string "http://" to result in an empty string since it's not a valid URL. Strangely though I get the same input back as being a valid URL, as in following example;

var_dump(wire('sanitizer')->url("http://"));
string 'http://' (length=7)

var_dump(filter_var('http://', FILTER_VALIDATE_URL));
boolean false

https://processwire.com/talk/topic/11309-sanitizer-url-validation/

Thanks in advance!

**Comment by matjazpotocnik** [comment]
var_dump(wire('sanitizer')->url("http://", array('requireScheme' => false)));
string(0) "" bool(false)

**Comment by FerdiAgrio** [comment]
That did the trick, thanks!

**Comment by somatonic** [comment]
For me that is still a bug an unexpected. http:// isn't a valid url.

**Comment by LostKobrakai** [comment]
I think so, too. @FerdiAgrio would you please reopen the issue?

**Comment by FerdiAgrio** [comment]
Although my question is solved, that's true - still unexpected result.

**Comment by ryancramerdesign** [comment]
Thanks @FerdiAgrio , I've pushed a fix.

**Comment by isellsoap** [comment]
@FerdiAgrio Can you close this issue please? Thank you!
