### ISSUE TITLE
Unidentified check for new modules' button

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1482]
Admin > Modules > Site (no site modules installed)

"To remove a module, click the module to edit, check the 'uninstall' box, then save. Once uninstalled, the module's file(s) may be removed from /site/modules/. If it still appears in the list above, you may need to click the 'check for new modules' button for ProcessWire to see the change."

Where is  'check for new modules' button? Shouldn't that be 'Refresh' button?

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this.

**Comment by adrianbj** [comment]
In case you miss my comment in the code, you inadvertently introduced a new typo.
