### ISSUE TITLE
Template::setRoles inconsistancy

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1488]
Is there a reason why setRoles does accept plain array values per the function implementation, but not saving the view access rules when it's an array of pages? The following code would work without the PageArray obj for edit, create and add, but not for the view roles.

``` php
…
$access = array(
    "view" => array("guest", "editor"),
    "edit" => …
);

foreach ($access as $key => $rolesArray) {
    $rolesArray = array_map(function($role) use($roles) {
        return $roles->get("name=$role");
    }, $rolesArray);

    $rolesPA = new PageArray();
    $rolesPA = $rolesPA->import($rolesArray);

    $template->setRoles($rolesPA, $key);
}

$template->save();
```

**Comment by ryancramerdesign** [comment]
@LostKobrakai I'm not sure I understand this one. It's true there are some differences in the way roles are stored, but the setRoles() method is there to abstract those differences away. It accepts one of the following, regardless of roles type:

- PageArray of Role objects
- Regular PHP array of Role page IDs (integers)

While it's not documented, it looks like the code also supports a regular PHP array of role names (strings). It does not support a regular PHP array of Role objects. Though I'm not sure if that's what you were asking or not. Can you clarify?

**Comment by LostKobrakai** [comment]
I didn't expect a php array of just the role names to work, therefore I did map it to a php array of role objects. But this did only work for create/add/edit, whereas the view roles were not saved. That's the inconsistancy I'm talking about.

**Comment by ryancramerdesign** [comment]
It's not intended to accept a regular PHP array of Role objects. But I
suspect it must have worked for create/add/edit anyway due to a foreach()
not caring whether something is an array or iterable object. That
unintended side effect wouldn't work for view roles though since they are
stored differently.
