### ISSUE TITLE
Template cache option always disabled

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1489]
I didn't test is it caching or not ? when i check devns branch, i see this issue and after i checked latest dev branch its same in there.

Again din't checked caching or not.. Option always disabled maybe its also not caching.

**Comment by ryancramerdesign** [comment]
I'm not seeing that here. Can you provide steps to reproduce and maybe a screenshot so I can see what you are seeing? I'd also be curious about any 3rd party modules just in case something might be interfering.

**Comment by trk** [comment]
I see now the problem, if cache time value is "0" its not activating cache for template.

**Comment by LostKobrakai** [comment]
Maybe I've a wrong perception of this, but how and why should processwire cache anything for 0 seconds?

**Comment by trk** [comment]
Actually it is not a problem. just i see this. This is my mistake.
