### ISSUE TITLE
Renaming FieldsetTabOpen should rename FieldsetClose

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1491]
Created FieldsetTabOpen with name Test. Added Test and Test_END to the template, put some fields in between. Then I renamed Test to Test1. After that Test1 would not open any more when editing page with that template. Maybe user should be warned to rename the ending tag too? Or perhaps PW should do that?

**Comment by matjazpotocnik** [comment]
Closing this in favour of https://github.com/processwire/processwire-requests/issues/3#issuecomment-249570932

**Comment by teppokoivula** [comment]
@matjazpotocnik: are you sure that these issues are related? Seems like a different thing to me :)

**Comment by matjazpotocnik** [comment]
Uh, yes it's different, sorry ...
