### ISSUE TITLE
Autocomplete issues with ampersands (&)

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1492]
I've run into a little issue with the autocomplete page fields. I have a page with a tile of "M & S Electric". When I try and search "M & S" or even the entire string, the result is not shown. I have reproduced this issue on several pages which include the "&" character. I've tried both *= and %=.

I thought the problem might be with the htmlspecialcharacters outputformatter, but the issue persists even if I remove this formatter from the searchable fields.

PW 2.6.22 rc1

**Comment by LostKobrakai** [comment]
The autocomplete field does use ajax calls to the internal search to resolve searches. Maybe it's appending the & without masking it properly, e.g. `…&title=M & S Electic`.

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon I have committed a fix for this issue.
