### ISSUE TITLE
Error in users lister

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1497]
```
Notice: Trying to get property of non-object in /var/www/live/wire/modules/PagePermissions.module on line 231

Notice: Trying to get property of non-object in /var/www/live/wire/modules/PagePermissions.module on line 243

Fatal error: Call to a member function has() on a non-object in /var/www/live/wire/modules/PagePermissions.module on line 243
Error: Call to a member function has() on a non-object (line 243 of /var/www/live/wire/modules/PagePermissions.module) This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged. 
```

I get these errors when accessing the users lister logged in as an user, who is not a superuser, but does have page-edit and user-admin permissions.

**Comment by ryancramerdesign** [comment]
I'm not seeing that one here in testing the same setup. But looking at the line numbers it looks like either $page or $user is a NullPage or NULL. Can you think of any other potential factors I might try to duplicate it? Something like a user is in the trash, or some other module that might be installed having to do with access control? If it's easy to do, try putting a `$this->warning($user); $this->error($page);` before line 243 to see what those two actually are?

**Comment by LostKobrakai** [comment]
It's the $page, which is not present, I'd a quick glance at the trace output, but I didn't see any 3rd party code called. Maybe it's the ListerPro version, as I've currently 1.0.8 installed and just saw there's a 1.0.9 out. Will try the new version out later and report back about that.

**Comment by ryancramerdesign** [comment]
I doubt it's the ListerPro version. Good to know it's $page. I see a potential issue, which I've just pushed a fix for. Though not sure this will solve it, but it's worth a shot. My guess is there's a User in the trash which Lister is attempting to include but is no longer part of the $users API var. Please let me know if you find this fixes it. Thanks.

**Comment by LostKobrakai** [comment]
The simple return false does work, bit it's was certainly not a user in the trash. Will see, if there pop up any newly uneditable users by the change.
