### ISSUE TITLE
Finding a page through "fieldname.data[LANGID]=term" not working for non default language in a module but works in a template

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1498]
Not sure how to best illustrate this.

First off why can't I search for a language field, setting the user language and do a query like "fieldname=term"? It seems to work on normal search on a site, but I can't get it to work in a boostrap or a module. It only finds terms in the default language.

I'm doing shortcuts using a text field "shortcut_url" on template. Then hooking into ProcessPageView::pageNotFound and do a search on that field.

This is on multilanguage install, and on a 2.5 install I used something like this code:

```
$parent = "/someparent/";
$term = "jeunesse";
foreach(wire("languages") as $lang){
    wire("user")->language = $lang;
    $langID = $lang->isDefault() ? "" : $lang->id;
    $found = wire("pages")->get("has_parent=/$parent/, shortcut_url.data$langID=$term, include=hidden");
    if($found->id) {
        echo $found->url;
    }
}
````

This worked fine in a page not found hook in a module. Now on a 2.6.18 I can't get this to work for non default language. It just can't seem to find the value of the alternative language of the field.

This code still works in a bootstrap php file, it finds the correct page. Also note that just using "shortcut_url=$term" it doesn't work, but how I understand it, it should work when cycling through languages and set user language.

Any ideas what the problem may be, or better approaches? The hook is set in the init() in a autoload module.

**Comment by ryancramerdesign** [comment]
Just on mobile here so making a guess, but I think you may need to move
this to a ready() method since the API may not always know the languages or
user from within an init(). Whereas in a ready() you can count on the API
being ready for this kind of stuff.

**Comment by somatonic** [comment]
Thanks for the guess. But hooking into ProcessPageView::pageNotFound in a ready doesn't trigger it at all.

**Comment by somatonic** [comment]
It was working fine in a 2.5 install when I used the same method.

**Comment by somatonic** [comment]
Ok this is silly. I used trim() to strip strings in the url. I didn't know it used all chars in the string and removes them.

The case was that $parent is a domain name page /www.swissjews.ch/ (multisite module)

This ended in a url like: "www.swissjews.ch/jeunesse"

And I thought I can "trim" the front segment like 
$term = trim("www.swissjews.ch", "jeunesse");

Which ended in term: "jeun"

Silly me. :)

**Comment by somatonic** [comment]
This is the full code in context with my Multisite Module.

```
$url = trim($event->arguments("url"),"/");

        $domain = wire("modules")->Multisite->domain;
        $url = str_replace($domain, "", $url); // remove domain page url
        $url = trim($url, "/");

        $savedLanguage = wire("user")->language;
        foreach(wire("languages") as $lang){
            wire("user")->language = $lang;
            $langID = $lang->isDefault() ? "" : $lang->id;
            $found = wire("pages")->get("has_parent=/$domain/, shortcut_url.data$langID=$url, include=hidden");
            if($found->id) {
                wire("session")->redirect($found->url);
            }
        }
        wire("user")->language = $savedLanguage;
```

I guess my question why I can't just use "shortcut_url=$url" and need to use "shortcut_url.data$langID=$url" since I'm setting user language.

Not that setting the user language, does have effect on the $found->url, that's why I'm doing it anyway. But the $page->find() doesn't seem to find the term in the alternative language as I would assume. I'm not sure this has to do with being in init().

**Comment by ryancramerdesign** [comment]
If you find that `shortcut_url.data$langID=$url` works then that is your best bet. Since this is all happening in init(), you are dealing with a PW API that is not fully loaded/not all hooks attached. Much of language support is added via hooks, so it's entirely possible (expected even) that some of those aspects wouldn't be ready during init().

**Comment by somatonic** [comment]
Thanks for the confirmation. :)
