### ISSUE TITLE
/somename redirects to a page and I don't know what is doing that

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1499]
I enter

domain.com/media 

and it redirects me to 

domain.com/de/medien/

Why? I don't have any redirects like this, nor is there any page or page_paths with "media". PagePathHistory isn't installed since this is a multilanguage site. Drives me crazy.

**Comment by somatonic** [comment]
Ah there's a page that is:
/de/medien
/fr/medias
/en/media

Now I see. But then why is it redirecting to /de/medien and not /en/media when I enter /media?

**Comment by ryancramerdesign** [comment]
There are a many possibilities depending on our configuration. 

- Does your default language homepage resolve to "/" or "/lang/" ?
- What is your default language assigned as? (en, de?)
- Are URL segments enabled on your homepage template?
- Are you manually setting the user language anywhere?
- Are there any other modules installed that handle 404s/redirects? (your previous report sounds like you are building one)

Assuming a blank installation without other modules involved, my best guess: the /media/ URL is matching to /en/media/ (and intending to redirect there), but that something else is adjusting the language in the process, making it redirect to the /de/ version of the same page.

**Comment by somatonic** [comment]
It had nothing to do 404, as the redirect happened before and 404 wasn't involved at all.

I was able to narrow it down to Multisite module. 

Modifying the request uri ($_GET['it']) 

So a:  domain.com/media 

resulted in a: /media

where it should be: media

it was working fine as long as a language segment was present, but lead to this behavior if there is no language segment present.
