### ISSUE TITLE
General Error when uploading Images. I see in Exceptions log 

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1500]
"SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. (in /wire/core/WireCache.php line 541)"

URL in log entry: domain.com/de/bilder-galerien/test/?nc=1447115985

I get lots of these when uploading images to a images field via ajax drag and drop.

PW 2.6.18 
MySQL-Client-Version: 5.5.44

There's like 10-20 images each ~1mb
Images seem to upload ok.

**Comment by somatonic** [comment]
It also happens when I upload 1 image. Same error message.

What is also strange is when I upload 10+ images and don't hit save, but refresh the page, there's one image in the image field when there should be none. When I upload only 1 image it's ok and the image isn't saved.

**Comment by ryancramerdesign** [comment]
I think there must be some other factors present here as I've not heard of this occurring for anyone else, and not seeing it here either. Can you think of anything? Maybe what third party modules are installed. What version of PW are you using?

**Comment by somatonic** [comment]
I'm using PW2.6.18.

It happens everytime I save a page with images or upload images. It seems that it's trying to maintainCache in WireCache. But I'm not using template cache, only markup cache.

What is this url the error seems to be related with? /test/?nc=1447115985

**Comment by somatonic** [comment]
Well not MarkupCache module. I mean using $cache->get() in template code. But is doesn't seem related since I'm editing a page that isn't in the expiring templates.

I can't think of any reason, and have tried various things, disable modules etc. No luck. Any idea how to trace that?

**Comment by somatonic** [comment]
I also can't reproduce so far. But having the site locally it also happens. It happens even when i just open a page in the backend that has an images field with at least an image uploaded. I started uninstalling all site modules, but no luck.

When I enter a exit("yoooo"), just before the error occurs in WireCache before try{$query->execute() ... I see that when opening the page at the bottom after all admin layout. I'm kinda lost.

**Comment by ryancramerdesign** [comment]
The URL you mentioned `domain.com/de/bilder-galerien/test/?nc=1447115985` – any idea what this is? It sounds to me like something is loading that URL. I do recognize the "?nc=..." part of it as that's the "no cache" variable InputfieldImage adds to image files before displaying them in the admin. But you've got it appearing on a directory name, and completely outside of the /site/assets/files/. Does `/de/bilder-galerien/test/` resolve to a legitimate Page on your site? Or is the 'test' part a mystery to you as well?

Next steps I would take are replacing your core–update it to the latest 2.6.23 to make sure you've got a fresh copy. Perform a search in your /site/templates and /site/modules recursively for the string "test", to see where that might be coming from. If it doesn't turn up, maybe export the DB to an SQL file and see if it appears in there, perhaps linked from a body copy field with a failed image insertion or something. This doesn't explain the exception you are seeing, but might give clues as to where to look next.

**Comment by ryancramerdesign** [comment]
Also, if you are using one of the other Image inputfields (like CropImage or CroppableImage or ImageExtra, etc.) uninstall that temporarily to make sure it's not coming from that.

**Comment by somatonic** [comment]
I already updated to latest, see my edit in last post.

The url is correct. I'm opening a page bilder-galerien/test/, where is a normal image field, no croppable or anything special.

I uninstalled every module in site that could have something, and even more just to make sure.

I guessed the ?nc=13123123 would be a No Cache that's coming from PW, so it's definately core image field?

The upload and images area all correct and valid uploaded, but the error even shows when just loading opening the page in admin. But only if images are in the images field. One error for each image.

**Comment by somatonic** [comment]
One step futher, in that it seems to now only happen on unpublished pages, once published it doesn't happen. Once unpublished it starts again. Doh!

**Comment by somatonic** [comment]
No matter what I try, there's no request to the url the exception log is saying. Very confusing. 

I entered this in the line before the try where it's happening.

wire("log")->save("whatsup", "REQ: " . $_SERVER['REQUEST_URI']);

And there's no request to the page url test/?nc=1312323, after all I'm in the backend editing the page, there's no chance it's doing this request.

In the whatsup log I see this (local install) when I open the page:

```
philipp.urlich	/processwire/setup/logs/	REQ: /processwire/setup/logs/
philipp.urlich	/processwire/setup/logs/view/exceptions/	REQ: /processwire/setup/logs/view/exceptions/
philipp.urlich	/de/swissjews-local.ch/bilder-galerien/test/?nc=14…	REQ: /site/assets/files/0/05/549/header_culture.0x100.jpg?nc=1447174684
philipp.urlich	/de/swissjews-local.ch/bilder-galerien/test/?nc=14…	REQ: /site/assets/files/0/05/549/header_next-generation.0x100.jpg?nc=1447174685
philipp.urlich	/de/swissjews-local.ch/bilder-galerien/test/?nc=14…	REQ: /site/assets/files/0/05/549/header_antisemitismus.0x100.jpg?nc=1447174683
philipp.urlich	/processwire/page/edit/?id=5549&s=1	REQ: /processwire/page/edit/?id=5549&s=1
````

So this url I see in exceptions in not a real request but some virtual made up? Like when I have an error in a bootrap script the log shows /http404/.

I think I'm going crazy. :)

**Comment by somatonic** [comment]
Ok finally I think I narrowed it down. Since it's only happening when page is unpublished.

It's the $config->pagefileSecure = true;

Once turned off it isn't happening anymore.

**Comment by ryancramerdesign** [comment]
Thanks, after I enabled $config->pagefileSecure, then installed module SessionHandlerDB, I was able to duplicate it. Do you have SessionHandlerDB installed? I was able to fix this combination and just pushed an update. Apparently releasing a lock on a MySQL table row also requires doing a closeCursor() afterwards, at least in this scenario. If using SessionHandlerDB, can you try with the latest commit and let me know if it also fixes it on your end?

**Comment by somatonic** [comment]
Oh. Yes I'm always using SessionHandlerDB. I think on my sandbox I'm not using it, that's maybe why I couldn't reproduce it. I'll make tests later.

I'd never thought it would be something with SessionHandlerDB. Great you found it!

**Comment by ryancramerdesign** [comment]
Yeah, I wouldn't have guessed SessionHandlerDB either, but the error you mentioned usually comes from missing a closeCursor() on a PDO SELECT query. So I started logging all of the queries that occurred before the exception and it pointed to that release of a table row lock in SessionHandlerDB. Releasing a lock doesn't seem like one that would need a cursor closed, but maybe PDO is just applying this exception unnecessarily to any SELECT query, even if it's one that doesn't return results. It's a bit of a mystery why it has anything to do with pagefileSecure though... probably just a matter of those two queries being executed back-to-back when pagefileSecure is enabled.

**Comment by somatonic** [comment]
Great work. I was able to test and installed SessionHandlerDB, it then occurred. Updating the module with your commit solved the error. 

Happy we we're able to fix that, took me hours to narrow it down to pageFileSecure :)
