### ISSUE TITLE
system-updater result "older than current"

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1502]
Example:
ProcessWire Core (Stable/Master)	ProcessWire master	2.6.23	2.6.1	Older than current

...should be labeled "newer than current" in such cases?

**Comment by LostKobrakai** [comment]
This did confuse me even a few times as well, but in fact it's correct. The version you would updete to is older than the current version.

**Comment by ryancramerdesign** [comment]
That's correct, 2.6.23 is newer than 2.6.1, unless I've misunderstood the question.

**Comment by tbba** [comment]
Well - that is obviously correct :) ...but....
I was actually confused what column "Older" and "current" relates to. I normally see my installed plugin as the one to look at (the subject of my comparison) and I related the message to THAT. You relate to message to the last column. - So be are both correct, depending on how you read the info. :)
What about writing "Older than installed" (instead of current) - Wouldn't that be 100% clear then?
