### ISSUE TITLE
Sorting pages

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1508]
With [horst's recent topic](https://processwire.com/talk/topic/11431-pagetree-moving-pages-in-very-long-branches/) about moving pages I saw how much boilerplate is actually needed to sort a page within the siblings, while it's actually something the core does already do. It would be really nice if you could abstract out the code ProcessPageSort does use, so it's callable without faking a ProcessPageList ajax request.

For later it might also be interesting to have an way to sort a whole bunch of siblings and just save the resulting state instead of each single movement. But I think that's nothing urgent if the above does work.

**Comment by ryancramerdesign** [comment]
Make sense to me, it could be moved into the Pages class. I'll put this on the @todo for 3.x.

**Comment by LostKobrakai** [comment]
Are there any news on that one?

**Comment by LostKobrakai** [comment]
I'll have to ask again for this. I'd really like to create pages after/before other ones via migrations and therefore via the api.

**Comment by richgcook** [comment]
Any news?

**Comment by LostKobrakai** [comment]
Certainly not here in the old repo. You might want to look here https://github.com/processwire/processwire-requests for the request or open one referencing this.
