### ISSUE TITLE
ProcessLogger - undefined index: id

### ISSUE THREAD

**Issue by GerardLuskin** [ryancramerdesign/ProcessWire#1509]
Running a fresh install of ProcessWire 2.7 on Apache 2/PHP 5.6, with error reporting switched on and PW in debug mode...

Every time you expand the drop-down menu under Setup > Logs, an undefined index error/notice is recorded:

    Undefined index: id in /srv/www/htdocs/test/wire/core/Process.php on line 373

This seems to be due to the ___executeNavJSON function in ProcessLogger.module returning items from WireLog::getLogs()... which have no "id" key

**Comment by ryancramerdesign** [comment]
Thanks @GerardLuskin I have committed a fix for this issue to the dev branch.

**Comment by isellsoap** [comment]
@GerardLuskin Can you close this issue please? Thank you!
