### ISSUE TITLE
showIf/required field has wrong required

### ISSUE THREAD

**Issue by phlppschrr** [ryancramerdesign/ProcessWire#1511]
In a FormBuilder form i have a InputfieldDateTime field with the these settings: 
showIf => belieferung!=1 
required => belieferung!=1

belieferung is a "Radio-Buttons" Inputfield with these options:
+1=Die Belieferung soll schnellmöglichst beginnen
2=Zum Wunschtermin
3=Ich habe bereits selbst gekündigt
4=Wir sind ein- bzw. umgezogen am

Since upgrading to the latest version the date field is always required, even when belieferung=1 and hidden. The showIf-rule works like expected, only the required part stopped working.

Downgrading to a dev version before 2.6.19 fixes the bug. Seems like the "Optimizations to dependency support in InputfieldForm.module" commit is to blame (https://github.com/ryancramerdesign/ProcessWire/commit/51f04ba6ba630065fa0b79d0a2a91d7d9d32ccfb)

**Comment by Renobird** [comment]
I can confirm this. It appears as though the required only if part of all our forms isn't working correctly — at least when using field!=value

**Comment by ryancramerdesign** [comment]
Thanks @phlppschrr and @Renobird I have committed a fix to the dev branch.

**Comment by phlppschrr** [comment]
Thank you Ryan! I can confirm this fixes my issue.
