### ISSUE TITLE
Field import didn't send field to template

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1513]
,"send_templates":[54]

When importing it's showing the info to what template it will get added, but it doesn't add it to the template.

**Comment by ryancramerdesign** [comment]
Thanks @somatonic that property actually shouldn't have been getting saved in field settings. It's not something meant for, or supported by the field import. I have corrected the issue that was causing it to get saved in the field settings.

**Comment by Da-Fecto** [comment]
Actually, this one drove me nuts. Sometimes it was saved as object {} sometimes as [] array. 
Thanks @somatonic  & @ryancramerdesign
