### ISSUE TITLE
Feature Request : Can you add a depth or level option for template family

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1515]
What i mean ?

Think have an 'album-list' template and allowed parents for this template is 'home(template)' and 'album-list(template)' and if we want to use this template for pages. It will look like this (without depth or level limit) :

* - Home (depth-or-level-0)
* -- Album List 1 (depth-or-level-1)
* --- Album List 1-1 (depth-or-level-2)
* ---- Album List 1-1-1 (depth-or-level-3)
* ............

and if we have an option like max. allowed depth or level for template value : 2 user can't add new pages if have template 'album-list' under Album List 1-1, and page structure look like this :

* - Home (depth-or-level-0)
* -- Album List 1 (depth-or-level-1)
* --- Album List 1-1 (depth-or-level-2)

**Comment by ryancramerdesign** [comment]
Hi @trk your best bet here is to use the template "family" settings, which you'll see when editing a template (Setup > Templates > [some template]) and clicking on the "Family" tab. Here you can control which templates are allowed for children (and/or parents). For the template used by your last depth of page, you would want to choose "No" for the "are pages using this template allowed to have children?". That will prevent further additions.

On the other hand, if all pages in the parent tree are using the same template, then the "family" settings would not provide what you'd need. That's kind of an uncommon case, but you can still accommodate that with a hook in your /site/templates/admin.php file:
````````
wire()->addHookAfter('Page::addable', function($event) {
  if(!$event->return) return;
  $page = $event->object;
  if($page->template == 'album-list' && count($page->parents) >= 3) {
    $event->return = false;
  }
}); 
```````

**Comment by trk** [comment]
Template > Family options are good but in some case need some options like depth or level for no create extra templates. For now i added 1 more template maybe like this it will be much better for theming but both main templates have same theming :

Before : Album List (allowed parents : home and album-list templates allowed children : album-list and album view)

After : Albums (allowed parents : home Allowed children : album-list) Album List (Allowed parents : albums Allowed children : album-view)

**Comment by teppokoivula** [comment]
> On the other hand, if all pages in the parent tree are using the same template, then the "family" settings would not provide what you'd need. That's kind of an uncommon case [...]

Just wanted to mention that, at least for me, it's actually a very common use case. I've had to work around this using multiple, identical templates in the past, though a hook solution is probably cleaner. 

This is one case for which I would like to see support in template family settings at some point, though not sure about the exact format. It's a bit like the "only one" support added recently: great, but many of my use cases at least require another specific number to be allowed, so it's not really useful :)
