### ISSUE TITLE
Modal redirects to page tree and does not close when a page is deleted

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1517]
When editing a page in a modal window, deleting the page from the delete tab does not cause the modal to close, and instead redirects to the page tree within the open modal.

Edit: Upon further investigation, this issue is intermittent. It seems to happen whenever I am using a modal within another modal (modalception).

**Comment by ryancramerdesign** [comment]
Can you tell me more about the scenario? Is this from PageTable, ListerPro or something else?

**Comment by thetuningspoon** [comment]
In this case it is actually my own module, AdminPageFieldEditLinks, which uses your built-in modal classes to generate a modal window to edit pages selected in a page field of any type. I use ListerPro in modal mode, so I am often inside of a modal already when I use this edit link functionality.

It looks like PageTable removes the delete tab altogether so this wouldn't be an issue there.

This is unrelated to the issue I'm having, but just a suggestion that I brought up somewhere else on the forums -- I wonder if it would be possible when opening a modal window within another modal window, for the inner window to expand to cover the parent modal's chrome completely. That way there would only ever be one set of save/action buttons, scrollbar, and a single close button, and the user wouldn't get confused as to which corresponded to which. Once the child modal was closed, the parent would then be visible again. This would also allow for many levels of modal windows to be open at the same time, without the size of the window becoming smaller and smaller.

I don't know if this is even technically feasible since the modals are actually iframes and I'm not sure if you could get the inner iframe to overlap the chrome of the parent, but I think it would be worth looking into.
