### ISSUE TITLE
Duplicate entry in Page Select

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1519]
I have an import that updates a page field. Occasionally I get a duplicate error:

Uncaught exception 'WireException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '330546-0' for key 'PRIMARY'' in /xxx/wire/core/FieldtypeMulti.php:262

Code is

```
$artVarColor->select_children->removeAll();
$artVarColor->select_children->add($sizesPages);
$artVarColor->save("select_children");
```

**Comment by ryancramerdesign** [comment]
Is it possible that this particular bit of code is running parallel to another of the same? Like the import is executing in two separate requests at the same time? Also, is this on a site where you are using InnoDB?

**Comment by somatonic** [comment]
I'm currently investigating. It seems the script is run twice. I call the php script (testing) in chrome, and it seems it's either that the browser is requesting it two times. Cause I get the import report email, I send after it's done, two times.

It's on a server using php in FastCGI mode. I'm now trying to run the script via ssh and see if it still happens.

No I don't think the DB is innodb, it's PW default and nothing has been changed there.

Do you also think that this code shouldn't product duplicate error? I don't see why it would and never experienced it with this kind of code.

**Comment by ryancramerdesign** [comment]
If it's executing twice in two requests, then it does seem feasible if the save operations happen to overlap at just the right time. Consider this:

Request 1: Delete all from page field
Request 2: Delete all from page field
Request 1: Insert new values into page field
Request 2: Insert new values into page field (BAM!)

**Comment by ryancramerdesign** [comment]
Seems like you can safely catch that exception and continue along. But there may be other issues with running two imports doing the same thing at the same time.
