### ISSUE TITLE
How to get min or max value ?

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1521]
If i have template and template use a field "price (float) field" how can i get max and min prices by using selector from all templates used by pages?

I didn't see on here https://processwire.com/api/selectors/ how to?, on my side solution is function like this : 

```php
function getMinMaxValues($field, $template="", $parentIDS=NULL) {
    $return = array(
        'min_value' => 0,
        'max_value' => 0,
        'error' => true,
        'success' => false
    );
    if(is_array($field) || is_string($field) != '') {
        $parentFilter = "";
        if(!is_null($parentIDS)) {
            if(is_array($parentIDS) && count($parentIDS) > 0) {
                $parentFilter = " AND (pages.parent_id=" . implode(' OR pages.parent_id=', $parentIDS) . ")";
            }
        }
        if(is_array($field)) {
            foreach($field as $key => $item) {

            }
        } else {
            $filterQry = "SELECT MIN(field_{$field}.data) AS min_{$field},
                        MAX(field_{$field}.data) AS max_{$field}
                        FROM pages INNER JOIN field_{$field} ON pages.id = field_{$field}.pages_id
                        INNER JOIN templates ON pages.templates_id = templates.id
                        WHERE templates.name = '{$template}'{$parentFilter}";

            $results = wire('db')->query($filterQry);
            if($results->num_rows > 0) {
                foreach($results as $result) {
                    $return = array(
                        'filter' => $filterQry,
                        'min_value' => floor($result["min_" . $field]),
                        'max_value' => floor($result["max_" . $field]),
                        'error' => false,
                        'success' => true
                    );
                }
            }
        }

        return $return;
}

$minMaxValues = getRangeFilters('field', 'template', array(1059, 1060, 1061, 1062));
echo '<pre>' . print_r($minMaxValues, true) . '</pre>';
```

Is there a easier way to do this?

**Comment by LostKobrakai** [comment]
You're not selecting any pages, therefore it's expected that the selector engine does not help you there. You could look into the db query classes of the core to make the query building less procedural, but I think that's all processwire has to offer for you in that case.

**Comment by trk** [comment]
You can use it for selecting as page also, its up to your usage. For example :
Maybe something like this could be helpful :
```php
// Single result
$maxPricePage = $pages->find("template=products, price.max");
echo $maxPricePage->price;

// Single result
$minPricePage = $pages->find("template=products, price.min");
echo $minPricePage->price;

// Or Multiple result
$minMaxPrices = $pages->find("template=products, price.min, price.max");
foreach($minMaxPrices as $pagePrice) echo $pagePrice->price;
```

**Comment by ryancramerdesign** [comment]
You would want to do this:
`````````
$minPage = $pages->get("template=products, sort=price");
$maxPage = $pages->get("template=products, sort=-price"); 

echo "<p>Min: $minPage->price</p>";
echo "<p>Max: $maxPage->price</p>";
`````````

**Comment by LostKobrakai** [comment]
Now I feel a bit stupid.

**Comment by trk** [comment]
This will sort all pages by using price value, i want to get only min price (page) or max price (page) or both of min price (page) and max price (page). No need to get all pages, just get needed page or pages like template=basic-page or like your SkyscrapersProfile max floor value or min floor value from pages.

**Comment by trk** [comment]
@LostKobrakai if you don't use you can't know what can i do width these values.

Let me explain with an example. You have an real estate website and want to show min. rent priced and max rent priced houses. With this method you can show them easily where you want. Also you can use these values on your filter form.

On this website : http://goo.gl/IWC8Wf filter form getting max and max : Guest Capacity, Cabins, Length and Built values range filters from yachts and you can make filter by using these values. Don't write values manually and if it possible don't make empty queries to db.

On my side my idea is get max and min values and make filter or use them how you want.

**Comment by ryancramerdesign** [comment]
Those are not loading more than one page. Note the use of $pages->get()
rather than $pages->find(). Those two $pages->get() operations will only
retrieve one page. It's not loading more than one page behind the scenes
either. Give it a try, I think it's exactly what you are looking for.

**Comment by trk** [comment]
As you see, i edited my comment. I saw get method after answer to @LostKobrakai :)

**Comment by LostKobrakai** [comment]
@trk I've used this method before in an other context, so yeah, I could've figured that as well. Is this solved with the answer? If so it would be nice if you close the issue.

**Comment by ryancramerdesign** [comment]
> As you see, i edited my comment. 

Sorry didn't see that, was reading from email rather than in GitHub. I see now. :)
