### ISSUE TITLE
Access control FieldsetTabOpen

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1524]
Hi Ryan.

I have setup a field of type FieldsetTabOpen. If I set the access control for this field within the field settings, the tab is not displayed. If I try to override this setting by template, the tab is still displayed but when clicked the fields are not displayed within this (which is fine, but the tab shouldn't display).

**Comment by ryancramerdesign** [comment]
I'm not seeing that here. If I uncheck all the "view" boxes for a FieldsetTabOpen field (specific to a template context), my editor role can no longer see the tab in the editor. What access control settings do you have for the FieldsetTabOpen field outside of template context? (i.e. when editing the FieldsetTabOpen field by itself in Setup > Fields)

**Comment by cb2004** [comment]
Outside of template context it is just set to 'No' for 'Access'. Then template settings are:

![template](https://cloud.githubusercontent.com/assets/6205980/11626768/3f45ee80-9cdd-11e5-912c-cdf67af72e5a.png)

Using 2.7.2 dev

**Comment by ryancramerdesign** [comment]
Thanks, that was it. I turned off access control for the non-context version and was then able to duplicate it. I have pushed a fix to dev.

**Comment by cb2004** [comment]
Cheers Ryan. Fix confirmed.

**Comment by valieand** [comment]
Looks like this fix caused unexpected changes in FiedsetOpen hidden behavior (and maybe FieldsetTabOpen, didn't test) - https://processwire.com/talk/topic/11721-hidden-fieldsetopen-new-behavior/
