### ISSUE TITLE
Languages order

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1531]
It would be nice if the Languages would be in the order as the language pages under the admin setup languages page.

Languages.php getAll()

$selector = "parent_id=$parent_id, template=$template, include=all";

to 

$selector = "parent_id=$parent_id, template=$template, include=all, sort=sort";

Would accomplish that. So language tabs would be in the order as they are as pages.

**Comment by ryancramerdesign** [comment]
Makes sense to me, thanks. I have added this.
