### ISSUE TITLE
Image variations won't delete in 2.7.1

### ISSUE THREAD

**Issue by Renobird** [ryancramerdesign/ProcessWire#1532]
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageEditImageSelect/ProcessPageEditImageSelect.module#L1187 seems to be the issue.

This seems to clear it up.
```
$delete = $this->wire('input')->post('delete');
if(is_array($delete) && count($delete) && $hasEditPermission) {
```

**Comment by ryancramerdesign** [comment]
Thanks Tom! I've pushed that fix to dev.
