### ISSUE TITLE
Template Cache doesn't get deleted when saving a page

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1533]
I thought this was really working well so far, but I have problems on a site when the client reported multiple times about cache no getting deleted. I confirmed this by simply testing, and it only get's deleted when cache time expired but not on a save. Also no message shown after saving.

I updated the dev to 2.7.1 from 2.6.10 to see if there's something. But still not working. I tested with a simple page with cache enabled to 600s and cache only get deleted for the page saved using this template.

In Template this would be an expire = 0.
const cacheExpirePage = 0;

I investigated a little and traced it what happens in PageRender.module

It seems in the hook clearCacheFile() it never get's into deleting something cause it checking for 

```
// clear the page that was saved
if($page->cache_time > 0) {
```

Which means it isn't true for my template. Simply adding a >=

if($page->cache_time >= 0) {

It would then start working.

**Comment by somatonic** [comment]
Oh ok I see now that it's $page->cache_time. I'm not sure what $page->cache_time is but it's empty in my case. That would explain why the >= 0 triggers it then. All following cache deleting seems to work, just no the cache of the saved page doesn't get deleted.

This is on a server running php FastCGI.

Any idea how to track this down?

**Comment by somatonic** [comment]
Me again :). Hm shouldn't it be $page->template->cache_time?

This would be the cache time in my case, unless I'm missing something.

**Comment by ryancramerdesign** [comment]
Thanks Soma, you are right it should be $page->template->cache_time. I will update here soon.
