### ISSUE TITLE
Language tabs covered by inline-CKE textarea menu

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1534]
I have a small inconvenience, when using 
the language tabs plugin together with inline-CKE textareas.

The CKE menu is 100% covering the languages tabs of a textarea, when the textarea is active.
I have to click to some other field first before I am able to switch the language of the textarea field.

- Safari/ PW 2.7.2dev

**Comment by ryancramerdesign** [comment]
I understand what you are saying, but I don't think that's something we have control over. I usually click outside of the CKE field to blur it before clicking to another language. Either that, or I'll use a non-inline editor when it comes to language tabs. You can also click the folder icon on the top right of the field to open all the tabs together.

**Comment by tbba** [comment]
ok - understood. I will think about it.
