### ISSUE TITLE
Skip rename table for runtime-only Fieldtypes

### ISSUE THREAD

**Issue by kongondo** [ryancramerdesign/ProcessWire#1538]
For runtime-only Fieldtypes that do not store data in the database such as [FieldtypeConcact](http://mods.pw/3P) and [FieldtypeRuntimeMarkup](http://mods.pw/AE), as reported [here](), it is currently not possible to rename the fields since MySQL looks for and doesn't find their corresponding **.frm** files on disk, i.e. '**field_my_concat_field.frm**' and throws the error *SQLSTATE[HY000]: General error: 1017 Can't find file: '.\dev\field_concat.frm'*. The error is generated in the **___save()** method in **Fields.php** at [these lines](https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/core/Fields.php#L150-L151). 

Although the method is hookable and will probably not require much resources to be hooking into (renaming doesn't occur often), I am wondering if there is a better way to solve this, maybe at core level, e.g. introducing a method which if implemented by a Fieldtype will tell **___save()** to ignore the attempt to rename a 'non-existent' table and let the field's name be changed. Alternatively, if this really is a matter for module developers, aside from using a hook, is there any other way to override **___save()**? I tried to override it similar to how our modules above override other db-related methods (e.g. ___sleepValue()) but without success. 

Thanks

**Comment by ryancramerdesign** [comment]
Thanks @kongondo I've pushed an update which should enable fieldtypes without tables to be renamed.

**Comment by kongondo** [comment]
Nice. Thanks. Tested and works fine.
