### ISSUE TITLE
Title and content in page head are filled with html when front end editing enabled

### ISSUE THREAD

**Issue by madebymats** [ryancramerdesign/ProcessWire#1539]
PW 3 alpha 4 default site profile:

![meta](https://cloud.githubusercontent.com/assets/1630407/11602295/73632b3e-9ad9-11e5-89f1-87617d9bb643.gif)

**Comment by ryancramerdesign** [comment]
Mats, see the blog post I just finished. It covers why you'd not want to
make a field like "title" inline editable (if being used elsewhere in the
page) as you already discovered. :) But there are many alternatives
available–take a look at the post when you get a chance.

**Comment by madebymats** [comment]
Read the blog post. :-)
