### ISSUE TITLE
Repeater with image field error if there is a "This item will become editable after you save." item

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1541]
I am getting error and losing entered data when there is a item "This item will become editable after you save."

Here errors i got :

New page '/admin/repeaters/for-field-178/for-page-1158/1449321805-42-2/' must be saved before... 1 min 
New page '/admin/repeaters/for-field-178/for-page-1158/1449321805-42-2/' must be saved before files can be accessed from it

**Comment by ryancramerdesign** [comment]
When you add a new item and it says "this item will become editable after you save" there should not be any inputs available for it. When you say that you are losing entered data, is it in some other item in the repeater, or are you somehow seeing inputs for the non-editable item? 

Since non-editable items don't show inputs, I'm going to assume you are losing data in some other item in the repeater. I have tried to duplicate that scenario here, but so far cannot. 

What version of PW btw? I'm assuming 2.7.1 or 2.7.2 but want to double check. I am testing in 2.7.2, though it should be identical to 2.7.1 in this respect. 

The error you mentioned occurs when something attempts to work with a files field on a page that does not yet have a database id assigned to it. Most likely there is some module or hook, hooking before a Pages::save or Pages::saveReady hook, or some other hook. And it's attempting to access files from those repeater items that aren't yet saved. The first thing I would look at is what modules you have installed (or custom hooks) that might be getting involved. With debug mode on, you might try taking a look at "Debug Mode Info" at the bottom and looking in the "Hooks" section.

**Comment by trk** [comment]
I created new page and after create new page added my repeater items (3 items) and clicked for 4. item.
![repeaterwithimage field-entered data](https://cloud.githubusercontent.com/assets/455983/11629246/ade41d0e-9cff-11e5-856d-39ed766b7435.jpg)

After I click save button, here is result :

![repeaterwithimage field-afterclicksave](https://cloud.githubusercontent.com/assets/455983/11629245/adddd958-9cff-11e5-90b7-184c20d8cc49.jpg)

**Comment by trk** [comment]
Also after save items on image field there is no edit image button appear. On the last image you can see the result.

**Comment by trk** [comment]
I have "ProcessCustomUploadNames" module and i removed this image field from filters and tested again. Result is same.

**Comment by trk** [comment]
If i uninstall the "ProcessCustomUploadNames" module system saving empty fields correctly. But i can't see variations and edit image options if the image field inside repeater. I will open new issue for this.

**Comment by adrianbj** [comment]
Hi @trk - I am sorry that CustomUploadNames (CUN) has caused you issues with repeaters. The support for repeaters is fairly recent in this module and I don't think it has been tested very extensively.

When you say that " i removed this image field from filters and tested again. Result is same." do you mean the CUN rules? What are the filters you are referring to?

Is there any particular thing you can think of that is unique to your repeater setup that I need to test to replicate this error?

**Comment by adrianbj** [comment]
Could you please post a screenshot of your CUN settings as I think that will help.

**Comment by trk** [comment]
Here are settings :

![ekran resmi 2015-12-09 14 05 37](https://cloud.githubusercontent.com/assets/455983/11684956/02d3f616-9e7e-11e5-95bd-2eccfc80b2c5.png)

**Comment by adrianbj** [comment]
Thanks - is any difference without the "rename on save" option? I typically don't use this option, especially when using $page->name in the filename format - typically the page name doesn't change in PW when the title is changed unless you are making use of PageRenameOptions or something else to change this behavior.

Also, just curious, it seems a little weird having the filename format ending in a period (.) - the sanitizer is probably removing that automatically, but just wondering the purpose for it.

I don't think I ever tested repeater items beyond the number of items in the "Ready to Edit" setting, so I guess that is the issue. I will try to take a look at this tomorrow for you.

**Comment by trk** [comment]
Tested with these options result is same and if i remove **image** field from settings result also same. Like ryan told :

**The error you mentioned occurs when something attempts to work with a files field on a page that does not yet have a database id assigned to it. Most likely there is some module or hook, hooking before a Pages::save or Pages::saveReady hook, or some other hook. And it's attempting to access files from those repeater items that aren't yet saved. The first thing I would look at is what modules you have installed (or custom hooks) that might be getting involved. With debug mode on, you might try taking a look at "Debug Mode Info" at the bottom and looking in the "Hooks" section.**

![ekran resmi 2015-12-09 14 19 28](https://cloud.githubusercontent.com/assets/455983/11685215/06e7291a-9e80-11e5-877d-6d770cc125a6.png)

**Comment by adrianbj** [comment]
Understood thanks - I think it should be easy to replicate - just need to exceed the number of items in the ready to edit setting. Hopefully I will have a solution for you tomorrow - just under a work time-crunch here right now. I guess temporarily you could increase that setting - that does solve it, correctt?

Thanks for your patience.

**Comment by trk** [comment]
Default value i have : 3

**Comment by adrianbj** [comment]
Right, but from what I understand, the error only appears when you add a 4th repeater item? So could you set the default value to say 10, or whatever the max number of days could possibly be. 

I will still sort out a fix for CUN, but would this not work for now? Or does it not actually fix the error?

**Comment by trk** [comment]
ah, you right ! :)

**Comment by adrianbj** [comment]
Good to know - thanks for confirming!

PS @ryancramerdesign - sorry for the time you put into debugging this!

**Comment by adrianbj** [comment]
@trk - I just committed a new version that should fix the error you were getting. Could you please confirm and then close this issue if there are no problems? Thanks!

**Comment by trk** [comment]
@adrianbj Thanks for quick response. It look like ok now.
