### ISSUE TITLE
Forcing modal in PageFrontEdit (PW3)

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1544]
In PageFrontEdit.modal there are commenst about how to force modal edit on the field:

$value = $page->edit('field_name', '<strong>markup</strong>', true); // make editable region, forcing modal

In function hookPageEditor, this line produces error:

$event->return = $this->modalRenderEditor($page, $fields, $arg2);

because modalRenderEditor expects second argument $fields to be an array, not ProcessWire\Field Object. I made this change to make it work (I wanted datetime field to open in modal):

$f = array(); $f[$arg1] = $field;
$event->return = $this->modalRenderEditor($page, $f, $arg2);

**Comment by ryancramerdesign** [comment]
Thanks, I have updated locally so this will be in the commits monday or tuesday.
