### ISSUE TITLE
FieldtypeURL not applying Textformatters

### ISSUE THREAD

**Issue by BitPoet** [ryancramerdesign/ProcessWire#1546]
FieldtypeURL provides its own __formatValue implementation, overwriting that same method of FieldtypeText. Therefore, any assigned Textformatters are not applied. The relevant code should be added to FieldtypeURL.

```php
		$value = (string) $value; 

		if($this->allowTextFormatters() && is_array($field->textformatters)) {
			foreach($field->textformatters as $name) {
				$this->log("Loading Textformatter {$name} for field {$field->name}");
				if(!$textformatter = $this->fuel('modules')->get($name)) continue; 
				$textformatter->formatValue($page, $field, $value); 
			}
		}
```

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this to the dev branch. It was just missing a parent::___formatValue() call in the existing formatValue() method.

**Comment by BitPoet** [comment]
Wow, that was quick. Thanks, Ryan!
