### ISSUE TITLE
PageArray::explode does not work with instance method as callable

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1553]
Per the php docs a callable can be declared as `array($this, 'myMethod')`, but this does not work for the explode function.

**Comment by ryancramerdesign** [comment]
Makes sense, I will add support for this. Thanks.

**Comment by LostKobrakai** [comment]
A workaround is wrapping the instance method inside a closure:

```php
protected function someMethod(){
    $closure = function($item){ return $this->myMethod($item); };
    $pageArray->explode($closure);
}
```
