### ISSUE TITLE
Trying to get property of non-object (PW 3.0.2)

### ISSUE THREAD

**Issue by vidhogskole** [ryancramerdesign/ProcessWire#1558]
I'm getting this message on a few sites (back end when editing). Haven't been able to pin it down to a common denominator.

Notice: Trying to get property of non-object in /Users/something/anything/thething/wire/core/Page.php on line 1211
Notice: Trying to get property of non-object in /Users/something/anything/thething/wire/core/Page.php on line 1211
Notice: Trying to get property of non-object in /Users/something/anything/thething/wire/core/Page.php on line 1212

It appears when editing the "home" template. Even when it only has a "title" field. And also on other templates when editing as well.

The message appears above the ProcessWire menu bar. But is duplicated when I click the "Children" tab, then it shows between the page tabs and the children/subpages list.

A few more details if it helps: I have enabled multi-language, but have tried both with PageTitle and PageTitleLanguage. This was not a fresh install. Could be something else I have missed, I don't know.

**Comment by ryancramerdesign** [comment]
Thanks for the report @vidhogskole, can you check if you have a user in your system with an ID of 41? i.e. /processwire/access/users/edit/?id=41

The error message you've mentioned seems to indicate that it can't find the default/system superuser account.

**Comment by vidhogskole** [comment]
You are correct. The ID is not 41. I'm closing this issue and taking my problem to the forum. Thanks, Ryan!

**Comment by ryancramerdesign** [comment]
Since your original superuser is no longer in the system, you may want to
add this line to your /site/config.php file, just so that PW knows what the
main superuser is:

`````
$config->superUserPageID = 1234;
`````

Replace 1234 with whatever the ID of the user is. That might correct the
error that you saw.

**Comment by vidhogskole** [comment]
Thanks, it did correct the error.
