### ISSUE TITLE
Translations abandoned on upgrade to 3.0.1 alpha-4 

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1560]
Translations in Functions.php  were abandoned after upgrading to 3.0.1 alpha 4.

**Comment by ryancramerdesign** [comment]
That's correct, the functions.php was becoming far too general purpose and
procedural for PW, so I moved much of it to dedicated classes in different
files. Though definitely with some hesitation for movement of translation
phrases. But I figured a major version change is the best time to do this.
The existing functions do remain for backwards compatibility, but they call
upon the new dedicated classes/API variables. Examples of more dedicated
files:

/wire/core/WireFileTools.php
/wire/core/WireDateTime.php

**Comment by kalmarlansmuseum** [comment]
Ok!  Very handy functions.
