### ISSUE TITLE
ProcessCommentsManager : If you make translation for Turkish for status urls, some status urls returning 404

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1561]
On my side if i translate status urls to Turkish i have problem with urls. For example :

**Approved = Onaylı** (in Turkish), url for this translation is **"onaylı"** and character is a latin character and the browser returning 404 page. Url and Label values are same on translation side. Need to separate label from url. This will be helpful for translating module to other languages.

If you can't see the Turkish character here a screenshot from issue text :

![ekran resmi 2015-12-14 16 22 04](https://cloud.githubusercontent.com/assets/455983/11783251/ef057eca-a27e-11e5-8fe7-a35afcbf08da.png)

I made a pull-request for @kongondo **ProcessCommentsManagerEnhanced** module, if you want check you can see my changes.

On my side **ProcessCommentsManagerEnhanced** module working well with changes.

https://github.com/kongondo/ProcessCommentsManagerEnhanced/pull/1

**Comment by ryancramerdesign** [comment]
Thanks @trk that's a good find. I am updating ProcessCommentsManager to separate the translated status names from those used in the URLs and should have this committed on the dev branch here by early next week.
