### ISSUE TITLE
PW302 CKEditor only showing on the first result with the front-end editor using PageTable

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1564]
This may also be the case with many repeaters. However I have a repeater (PageTable) and I have a content field in each PageTable. 

```
foreach($page->page_table as $result) {
    echo $result->edit("content");
}
```

I currently have 5 pages in my PageTable.

**Comment by ryancramerdesign** [comment]
@TomS- I wasn't seeing the same error as you, CKEditor continued to work for me, but I noticed an id attribute collision which I think was the problem. I have fixed that, which I think should also fix the issue you saw with CKE. Please let me know if you find it doesn't. Thanks for reporting it.

**Comment by TomS-** [comment]
@ryancramerdesign - Hi Ryan, just replaced the file with the one in the commit. I can confirm that this has fixed the issue on my end. Everything is running smoothly now. Thank you.
