### ISSUE TITLE
2.7.2 markupValue not triggered on PageTable modal dismissal 

### ISSUE THREAD

**Issue by ddroescher** [ryancramerdesign/ProcessWire#1565]
As per [this forum topic](https://processwire.com/talk/topic/11489-truncate-content-of-fields-in-admin-columns/): I added functionality to improve the output of body text inside a PageTable column. This is where I noticed that the column is not refreshed correctly after editing and dismissing a PageTable modal. Probably because markupValue is not triggered.

#### Before editing a PageTable
![Before](http://dl.blue.de/1crBn/3RxKZhGl+)

#### After editing a PageTable or dismissing the modal
![Before](http://dl.blue.de/1cj0U/29OPrEuu+)

#### This is my ready.php:

```php
$wire->addHookAfter('Fieldtype::markupValue', function($event) {

  $page = $event->arguments(0);
  $field = $event->arguments(1);

  if($field->type == 'FieldtypeTextareaLanguage' or $field->type == 'FieldtypeTextarea') {
    $displayValue = strip_tags($page->get($field));
    if(strlen($displayValue) > 100) {
        $displayValue = substr($displayValue,0,97).'...';
    }  
  }
  else {
      return;
  }
  
  $event->return = $displayValue;
});

```

**Comment by LostKobrakai** [comment]
Had this issue some days before (https://github.com/ryancramerdesign/ProcessWire/issues/1555). Use the init.php instead of the ready.php.

**Comment by ddroescher** [comment]
Thanks, that worked! As the issue is explained in your link (#1555) and not a bug, I’ll close this.
