### ISSUE TITLE
Multiple text formatters not working for image and file descriptions

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1568]
If more than one text formatter is set for descriptions in an Image or File field, only the first text formatter is applied.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this issue to the 3.x devns branch and it will be migrated to the regular dev branch next week.

**Comment by isellsoap** [comment]
@Toutouwai Can you close this issue please? Thank you!
