### ISSUE TITLE
Difficult to work with CKEditor custom CSS and styles JS due to caching

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1569]
Working with the CKEditor field settings "Custom Editor CSS File" and "Custom Editor JS Styles Set" is difficult because these options are contained in linked files that are cached by the browser. It's hard to get the browser to reload these files after changes are made - a hard refresh wont do it. I find I have to go into the field settings and append a query string (e.g. "/site/modules/InputfieldCKEditor/contents.css?2" every time the file is changed in order to see changes reflected in the editor.

Could some method of cache-busting be implemented for these linked files? Or just have the CSS and JS styles content inserted inline like some of the other CKEditor settings (Extra Allowed Content, Custom Config Options, etc).

**Comment by ryancramerdesign** [comment]
I usually enable developer tools whenever editing this kind of stuff so that caching is turned off. However, if cache busting those URLs reduces confusion, I think it's a good idea. I have gone ahead and added this to the devns branch.

**Comment by Toutouwai** [comment]
Disabling the cache with dev tools works for development, but sometimes new CKEditor styles need to be added to a production site where editors will already have local cached files. The cache-busting query string will fix that - thanks.

**Comment by isellsoap** [comment]
@Toutouwai Could you please close this issue? Thank you!
