### ISSUE TITLE
InputfieldSelector memory problems when lot of users and using multiple user templates

### ISSUE THREAD

**Issue by apeisa** [ryancramerdesign/ProcessWire#1570]
Problems are due this line: https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L367

That check doesn't count for different user templates. This makes it impossible to use InputfieldSelector when there are over 5000 users (in our test server).

**Comment by ryancramerdesign** [comment]
Thanks Antti, I have pushed a fix for this to the devns branch and will migrate to the dev branch by early next week.
