### ISSUE TITLE
FileCompiler and error suppression operators

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1573]
In one specific case I've got the error suppression operator @ in front of a wire() method. Turns out that the FileCompiler misses this, as it doesn't expect @. Perhaps not the most common use case, but could support for this be added?

Once again I might've missed something, but this seems to fix the issue for me:

```
diff --git a/wire/core/FileCompiler.php b/wire/core/FileCompiler.php
index 97a81ab..3d19d06 100644
--- a/wire/core/FileCompiler.php
+++ b/wire/core/FileCompiler.php
@@ -430,7 +430,7 @@ class FileCompiler extends Wire {
                        if(stripos($data, $function) === false) continue; // if function name not mentioned in data, quick exit

                        $n = 0;
-                       while(preg_match_all('/^(.*?[()!;,\[=\s.])' . $function . '\s*\(/im', $data, $matches)) {
+                       while(preg_match_all('/^(.*?[@()!;,\[=\s.])' . $function . '\s*\(/im', $data, $matches)) {
                                foreach($matches[0] as $key => $fullMatch) {
                                        $open = $matches[1][$key];
                                        if(strpos($open, 'function') !== false) continue; // skip function defined with same name
```

**Comment by ryancramerdesign** [comment]
No problem, I will add this. But out of curiosity, what's the purpose of putting a @ in front of a wire method call? I know what the purpose is when it comes to PHP functions like rmdir() or the like, but just trying to think of what possible output coming from wire() this would be intended to suppress? :)

**Comment by teppokoivula** [comment]
Thanks!

In this case a module calls a separate script to render multiple pages in the background, and in case those pages return errors, I needed to suppress them in order to let the script continue as expected.

The details are a bit fuzzy by now to be honest, but I seem to remember that this did the trick :)

**Comment by teppokoivula** [comment]
This was also added in 7c7e95dcda004ce5b70e57b997a5c8c82cb795ba. Closing the issue.
