### ISSUE TITLE
PW3.0.2 datetime 24 hour issue

### ISSUE THREAD

**Issue by vidhogskole** [ryancramerdesign/ProcessWire#1576]
I noticed a small error in my 3.0.2 devns installation. The date/time picker in Datetime field will show 0-12 twice, not 0-24 hours. Both on Sliders and Select. I am using the 24 hour clock, not AM/PM.

E.g. When choosing what is supposed to be 17:00, it will jump to 05:00 (in the morning). Outputting it front end will then show 05:00 in the morning, making 17:00 an impossible option when date/time picker is used. Also typing in numbers manually seems to be broken (only 1 number before I have to click to focus and type in another number).

There's no issue when date/time picker is deactivated, and manual input is used.

(When downgrading to 2.7.2 it was solved at once. Therefore I am reporting it as an issue.)

**Comment by matjazpotocnik** [comment]
See https://github.com/ryancramerdesign/ProcessWire/issues/1528
