### ISSUE TITLE
PW302 Edit Field causes all instances to be editable

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1578]
Hello,

I've found a bug with the front-end editor.

Declaring:
````
<?=$page->edit("title")?>
````
Makes: 
````
<?=$page->type->title?>
````
Editable. However I would very much like to declare:
````
<edit type><?=$page->type->title?></edit>
````

So I can edit the page relationship rather than the relationship title. This doesn't work only allowing me to edit the title.

**Comment by ryancramerdesign** [comment]
Thanks @TomS- I have pushed a fix for this issue. Though I'm not sure I duplicated your condition exactly, so please let me know if you if you continue to see it occur.

**Comment by TomS-** [comment]
@ryancramerdesign, You're awesome! That's working perfectly. Thanks :-)

**Comment by isellsoap** [comment]
@TomS- Can you please close this issue? Thank you!
