### ISSUE TITLE
On PW 3.x, function _x() not returning the translated string, but always the default value

### ISSUE THREAD

**Issue by maniqui** [ryancramerdesign/ProcessWire#1580]
Hi. 
I'm running PW at v3.0.3 (devns branch, at commit 218410940d3644b4c125d9e461ef785b1e770c96).
I'm testing the `site-language` profile. 
For example, in this line of code

```php
<html lang="<?php echo _x('en', 'HTML language code'); ?>">
```

the function `_x()` always return `en`, even when switching to German or Finnish.
This, of course, happens for any place where the `_x()` is being called. 

If I downgrade to v2.7.x, the function returns the correct value for each language.
I couldn't find yet in which commit this issue has been introduced. 

**Update:**

I'd bet it's something related to templates being compiled. Why?
Because if I do some `echo` (yeah, poor's man debugging) inside the function `___getTranslation` on [wire/modules/LanguageSupport/LanguageTranslator.php](https://github.com/ryancramerdesign/ProcessWire/blob/1e8c2f0c2d1a25ef31c9f1e608334e2ede03820d/wire/modules/LanguageSupport/LanguageTranslator.php#L251), there, the `$textdomain` value is set to the path of a compiled template. In my case, it is
`site/assets/cache/FileCompiler/site/templates/_main.php` instead of `/site/templates/_main.php`.

Tracing this back a little more, I arrive to the definition of function `__()` on [wire/core/LanguageFunctions.php](https://github.com/ryancramerdesign/ProcessWire/blob/1e8c2f0c2d1a25ef31c9f1e608334e2ede03820d/wire/core/LanguageFunctions.php#L27). 
A new poor's man debugging via `echo` shows that when `__()` function is called, the `$textdomain` is null, and then, in line 27, some voodoo magic runs and thus, **it's right there where `$textdomain` is set to `/site/assets/cache/FileCompiler/site/templates/_main.php` instead of `/site/templates/_main.php`**.

So, being that the `$textdomain` is set wrongly, then, the string returned is the default value, instead of the corresponding translated string.

**Update 2:**

If I explicitly set the `$textdomain` parameter to `__FILE__` when calling `_x()`, it returns the correct translated string. Example: 

```php
<html lang="<?php echo _x('en', 'HTML language code', __FILE__); ?>">
```
I hope that's enough info to get rid of this bug :)

PS: I'm new to PW, let me know if I can give you any other information to help you debug this issue.

**Comment by maniqui** [comment]
Hi @ryancramerdesign. I'm tagging you just to put this issue on your radar. I hope that's not _too_ disrespectful. After posting the initial post in this thread, I've added two updates that I hope you find them useful to chase this bug.
Thanks.

**Comment by ryancramerdesign** [comment]
Thanks @maniqui I have pushed a fix for this issue. Please let me know if you continue to see any issues here.

**Comment by maniqui** [comment]
Hi @ryancramerdesign . 
Thanks for the prompt reply and the bug fix. A quick test seems to show that the issue is fixed. I've yet to test it more thoroughly. Will let you know if anything else arises. In the meanwhile, I will close this issue.
