### ISSUE TITLE
Placeholder option does not have multilanguage support

### ISSUE THREAD

**Issue by clsource** [ryancramerdesign/ProcessWire#1582]
When creating a new field the placeholder option does not enables multiple placeholders depending on the language. As an example I´m configuring a site with two languages but just the default one is supported.

![captura de pantalla 2015-12-27 a las 9 50 08](https://cloud.githubusercontent.com/assets/292738/12010302/527d66ca-ac7f-11e5-93bf-bfcf379eeec1.png)

:+1:

**Comment by justonestep** [comment]
Multilanguage support for placeholders has been added ([7cbc09f](https://github.com/ryancramerdesign/ProcessWire/commit/7cbc09f749d630d08ea84a320c5d8a1ac97f77cd)).
