### ISSUE TITLE
Add patch and delete to WireHttp

### ISSUE THREAD

**Issue by pwFoo** [ryancramerdesign/ProcessWire#1583]
I build a module to work with a jsonapi and the WireHttp could replace some custom code, but I need also PATCH and DELETE support.

To add the methods should be simple and would be great for jsonapi based modules.

**Comment by ryancramerdesign** [comment]
I haven't yet looked into what's required to implement these methods, but you mentioned it's simple to do. Is it just a matter of replacing the GET or POST method argument value with PATCH or DELETE? For instance, if send() were a public method: `$http->send($url, $data, "PATCH");`? If that's adequate, one solution might be that we just make the send() method public (currently it is protected).

**Comment by pwFoo** [comment]
Hi Rayn,

becaue I try to build a module communicate with a jsonapi a public send() method would be great. A have a simple class extends WireHttp and the methods looks like that.
```
	public function patch($url, $data) {
		if(!isset($this->headers['content-type'])) $this->setHeader('content-type', 'application/vnd.api+json');
		return $this->send($url, $data, 'PATCH');
	}

	public function delete($url) {
		if(!isset($this->headers['content-type'])) $this->setHeader('content-type', 'application/vnd.api+json');
		return $this->send($url, null, 'DELETE');
	}
```

It's just copy & paste existing two line function and change send method to DELETE / PATCH.

But additional make __send() public would be more flexible for all cases.

**Comment by pwFoo** [comment]
Maybe the header isset check could be moved to send()? Or is it because of security?

The functions get(), post(), delete(), patch() are just simplified send() calls.

**Comment by ryancramerdesign** [comment]
I've updated the send() method to be public on the 3.x devns branch, and
added PATCH as an allowed http method. I'd like to keep WireHttp relatively
low-level http, but will do more research here with regard to new methods
as it might make sense to add them if there's significant demand for their
use. But if you'd like to start using them now, here's one way: add this to
your /site/ready.php file (using patch as an example):
````
$wire->addHook('WireHttp::patch', function($event) {
  $http = $event->object;
  $url = $event->arguments(0);
  $data = $event->arguments(1);
  $http->setHeader('content-type', 'application/vnd.api+json');
  $event->return = $http->send($url, $data, 'PATCH');
});
```

On Thu, Dec 31, 2015 at 9:29 AM, pwFoo <notifications@github.com> wrote:

> Maybe the header isset check could be moved to send()? Or is it because of
> security?
>
> The functions get(), post(), delete(), patch() are just simplified send()
> calls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryancramerdesign/ProcessWire/issues/1583#issuecomment-168204086>
> .
>

**Comment by pwFoo** [comment]
Hi Ryan,

could you also allow DELETE?
I'll need it to build a Flarum api module for a nice PW integration to delete users, posts, ...

**Comment by ryancramerdesign** [comment]
I'm pretty sure delete has always been there as an allowed http method. You
should see it in the top of the class file var definitions. I'm not at the
computer anymore to check, but let me know if not there.

**Comment by pwFoo** [comment]
OK, I'm not at home and @mobile. So I'll take a look later. Seems to be allowed. Thanks Ryan!

**Comment by pwFoo** [comment]
Tried to add it as hook, but it doesn't work.
Started a forum topic because maybe I do it wrong after some time without hooks and moved to PW3 now.
https://processwire.com/talk/topic/11814-problems-with-addhookafter-wirehttpsend/
