### ISSUE TITLE
has_parent still buggy

### ISSUE THREAD

**Issue by er314** [ryancramerdesign/ProcessWire#1588]
Hi, 
I am struggling with some pages having erroneous (missing) "has_parent" data.
At first I was thinking that it was related to issue #1195, and that it was still erroneous due to some pages data not being refreshed after the fix.
But further investigation lead me to think that there is still another unresolved problem.
So I did additional testings, and now I think I have nailed down the problem to its simplest, reproductible, expression, see procedure below.

(all actions in backend GUI)
* perform new install, with "blank" site profile
* create template "execpad", all default settings
* create new page /execpad/ , title execpad, template execpad, save+publish
* create template "page-container", all default settings
* create new page /dirA/ , title dirA, template page-container, save+publish
* create new page /dirA/page1/ (dirA -> new), title page1, template basic-page, save+publish
* create new page /dirA/page2/ (dirA -> new), title page2, template basic-page, save+publish
* move page1 into "/" , inbetween /execpad/ and /dirA/  -> now : /page1/
* move page1 back into "/dirA/" , back at 1s position before page2  -> now : /dirA/page1/
* check for has_parent data for page1 : it does only contain "/" , __but NOT dirA__

	check to be done by any means, personally it is with the following code in template execpad.php :
```php
	<?php
	$id = 1017;  //// <<-- set this to the id of the page which has problems (id to be obtained from the backend GUI)
	$the_page = $pages->get($id);
	echo "which parents do have page " . $the_page->id . " || " . $the_page->url . " || " . $the_page->title . " ?<br><br>\n";
	$i=0; $j=0;
	foreach ($pages->find("id>0") as $current_pg) {
		if (! ($pages->get("has_parent={$current_pg}, id={$id}") instanceof NullPage)) {
			echo "- has_parent : " . $current_pg->id . " || " . $current_pg->url . " || " . $current_pg->title . "<br><br>";
			$j++;
		}
		//else echo "no : " . $current_pg->id . " || " . $current_pg->url . "<br>";  // enable if want verbosity
		$i++;
	}
	echo "<br>end processing, found {$j} has_parent occurrences in all {$i} pages of the site";
```

**Comment by ryancramerdesign** [comment]
Thanks, I was able to reproduce that too. The issue actually isn't the missing entry in pages_parents, as that is intentional (since the data is redundant, already stored in the pages table). The issue was that PageFinder wasn't including direct children, only grandchildren and further. I've attempted a fix for this on the last commit to PW3 devns branch. Can you confirm it also fixes the issue there? Thanks.

**Comment by er314** [comment]
Hi, yes, this fixed the case described, plus the more complex ones on real site,
so this seems all right !

On a side note, I'm having several problems with migration to PW 3.0.x : 
- first, inclusion of swift php library, with require_once($config->paths->templates . "markup/swiftmailer/lib/swift_required.php"); , does fail, see message below ; maybe an issue with space characters in path ? (see "ProgramFiles(x86)")
- second : a "cannot redeclare" error, while there is no redeclare.. the function is the 1st one from a php file which is subject to several "include_once" (but never "include")


Compile Error: require(): Failed opening required 'C:/ProgramFiles(x86)/EasyPHP-DevServer-14.1VC11/data/www_smh/site/templates/markup/swiftmailer/lib/classes/Swift.php' (include_path='.;C:\php\pear') (line 20 of C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\www_smh\site\assets\cache\FileCompiler\site\templates\markup\swiftmailer\lib\swift_required.php)


Compile Error: Cannot redeclare date_format_country() (previously declared in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\www_smh\site\assets\cache\FileCompiler\site\templates\markup\commodity_functions.php:9) (line 38 of C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\www_smh\site\assets\cache\FileCompiler\markup\commodity_functions.php)

**Comment by isellsoap** [comment]
@er314 Could you please close this issue and open another one if you’re having other issues? Thank you!

**Comment by er314** [comment]
issue fixed
