### ISSUE TITLE
3.0.3 dev namespace problem with JqueryFancybox

### ISSUE THREAD

**Issue by warenhaus** [ryancramerdesign/ProcessWire#1592]
I upgraded from pw 2.7.something and I had to manually add the namespace you suggested (<?php namespace ProcessWire;) to the following file: 

/wire/modules/Jquery/JqueryFancyboxJquery/Fancybox.module

**Comment by ryancramerdesign** [comment]
JqueryFancybox [isn't part of the core in 3.x](https://github.com/ryancramerdesign/ProcessWire/tree/devns/wire/modules/Jquery). It sounds like you might have a /wire/ directory that is two different PW versions merged? I would remove your /wire/ directory and replace it with a fresh copy, as merged /wire/ dirs could cause problems elsewhere too.

**Comment by warenhaus** [comment]
yes, that is true. I upgraded, and thought upgrading was done by copying all from the 3.x wire directory into the existing one. I'll do as you suggest.
thanks!

**Comment by ryancramerdesign** [comment]
Sounds good, I'll close this one out, but just let me know if you run into anything related.
