### ISSUE TITLE
session->getIP() returns 0.0.0.0 (add support for IPv6)

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1596]
Developing on Win 8.1, IIS, localhost, _SERVER["REMOTE_ADDR"] = ::1 (IPv6). ip2long and long2ip don't work with IPv6 addresses

**Comment by formmailer** [comment]
It looks like this issue isn't fixed, will this be fixed soon? 
session->getIP() returns 0.0.0.0 on Linux/Apache as well, running PW 3.0.123.

**Comment by arjenblokzijl** [comment]
hi @formmailer, this repository isn't used anymore, please check this one instead https://github.com/processwire/processwire-issues/.

**Comment by formmailer** [comment]
Hi @arjenblokzijl, thanks for pointing that out. I actually didn't check that since I found the issue report using Google. 😊
I'll check if someone filed a similar issue report in the current repo. If not I will create one.

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/48a37bcc5c0eb890f5886d749c7c6c1c62d7549b
