### ISSUE TITLE
$pages->findOne error when returning a hidden page without include=all

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1597]
If you are finding a page that is hidden without including "include=all" it will return an error rather than 0 results. 
```
Error: Call to a member function viewable() on a non-object (line 342 of /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/Pages.php) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

To replicate: 
Create a template
Create a page with new template
Set template to hidden

Use $pages->findOne("template=newtemplate")->children() 

This should return the error. I know it's only a small bug, however I haven't tested it with two pages using this template with the first one hidden.

**Comment by ryancramerdesign** [comment]
Thanks @TomS- I was able to duplicate that as well and the latest commit should fix this issue.

**Comment by isellsoap** [comment]
@TomS- Can you close this issue please? Thank you!
