### ISSUE TITLE
PW303 - "hello" when login is incorrect

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1599]
This has been in since 3.0, I just thought it was something strange with that particular installation however it appears to be a very minor bug. 

When the login is incorrect you get the following:
![ax23xyc](https://cloud.githubusercontent.com/assets/4595662/12099149/8daf5244-b31e-11e5-956f-eaaf91e3a627.png)

**Comment by ryancramerdesign** [comment]
That's just a friendly hello. Following up an negative notification with a positive and friendly affirmation  can help with password recognition. But for consistency the first letter should probably be capitalized, and it might be more effective if it was something like "Hello, you are almost there, you can do it champ". I think I was just being lazy and/or trying to make things easy on the translators. But I will correct this.

**Comment by TomS-** [comment]
Hi Ryan, I agree that the wording could be slightly tweaked. Just "hello" on it's own initially felt like it was left in for testing. It just seems there with no explanation.

I agree that a more conversational message maybe better, but I also feel like it needs an explanation for being there (if that makes sense).

"Hello, unfortunately your Username or Password was incorrect. Please try again." - Maybe?

Thanks again for all your great work :-)

**Comment by mikerockett** [comment]
> "Hello, you are almost there, you can do it champ"

Hehe! :wink:

**Comment by ryancramerdesign** [comment]
Tom, actually I was just joking with you. :) That "hello" was a debugging
message that wasn't supposed to be there. I actually removed it a day or
two ago, so it shouldn't be there anymore.

**Comment by TomS-** [comment]
Haha! Ryan, I'm so gullible haha! :relaxed:
