### ISSUE TITLE
Should findOne return false/NullPage if it get's no results?

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1601]
I've just tried:
```
$journey = $pages->findOne("template=journey, journey_start=$page");
if($journey) { $journey = $journey->journey->prepend($page); }
```
However I get:
```
Error: Call to a member function prepend() on a non-object (line 11 of /var/sites/a/asg.returnonideas.co.uk/public_html/site/templates/document.php) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```
If it gets no results.

**Comment by LostKobrakai** [comment]
Depending on the situation both have their pros and cons. I'm using `if($journey && $journey->id)` in my code so it won't matter.

**Comment by ryancramerdesign** [comment]
Just like $pages->get(), $pages->findOne() returns NullPage if there are no
results. So your if() would need to instead be: `if($journey->id) { ... }`

**Comment by TomS-** [comment]
$(journey->id), got it. My apologies. I thought just ($journey) would do it.
