### ISSUE TITLE
Compile Error on devns

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1606]
All of a sudden i started getting this error:

Compile Error: 'continue' not in the 'loop' or 'switch' context (line 655 of /storage/content/91/155391/xxxxxxxxxx/public_html/site/modules/ProcessWireUpgrade/ProcessWireUpgrade.module)

Removing ProcessUpgrade fixes the issue.

**Comment by ryancramerdesign** [comment]
A fix for that module was committed in December, and that particular issue only appears to surface in PHP 7. But if you are seeing it, you may want to upgrade to the latest version.

**Comment by isellsoap** [comment]
@kalmarlansmuseum Can this issue be closed?

**Comment by isellsoap** [comment]
@kalmarlansmuseum I close this issue as it seems fixed or hasn’t had any reaction from you for months. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.
