### ISSUE TITLE
3.0.4 need to call parent::___uninstall(); to uninstall ProcessPage.

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1608]
~~When uninstalling a 'native' PW3 process module I need to call parent::___uninstall(); to uninstall the Process Page. I don't remember to do this on 2.7 and lower. Is this expected behaviour?~~
```php
// Only with parent::___uninstall() the ProcessPage will be trashed.
public function ___uninstall() {
	parent::___uninstall();
}

```
Being stupid here... if I implement ___uninstall I should take care of it my self... Sorry for the inconvenience.

**Comment by ryancramerdesign** [comment]
That's normal, and would be the case with any PW version. That's because
the base Process module contains the code for installing and/or
uninstalling the Process page. You'd want to do the same with your
___install()  method too, if present.

**Comment by Da-Fecto** [comment]
That said... I just was confusing my self...
