### ISSUE TITLE
Page tree disappeared 

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#1609]
Page tree disappeared when updating to 2.7.2 stable (same when testing the new 3 devns).
Don't know if it's a feature or not:
When using the Default admin theme it's no problem, because clicking the 'Pages' label itself will take you to the tree. But when using Reno you have to remember to doubleclick the label, otherwise it just folds out.

**Comment by LostKobrakai** [comment]
If you're using the Reno theme simply unhide the page again via the page tree. It's meant to remove the duplication in the default theme and in reno or you can also simply click on the processwire logo to get to the page tree.

**Comment by junofornow** [comment]
Okay, so it's a feature / choice;
but....
in Reno though it's kinda weird, clicking on "Pages" doesn't show you the pages in your site. So you have to tell users to click on the PW logo or double-click the Pages label instead ?? That's really confusing. Then at least enabling Reno should unhide the tree by default.

**Comment by LostKobrakai** [comment]
That's not really an option for the core, as the hidden status is global, but each user can have his or her own admin theme setting. But you could certainly add a hook yourself to make that happen.

**Comment by junofornow** [comment]
Sure, but adding a hook is quite overkill for fixing a confusing UX choice/default (in respect to Reno). Certainly because it was never a problem in the first place before PW v. 2.7

**Comment by tbba** [comment]
+1 my users also find that confusing.

**Comment by eladnova** [comment]
+1 my users too reporting it as "broken"

**Comment by teppokoivula** [comment]
This is an usability issue, no more, no less. While I get that it's related to the differences between built-in Admin Themes and that one *can* indeed manually unhide the page to fix it, in my opinion the system should take care of fixing this automatically. It's not very nice to introduce issues and then pass the responsibility of fixing them to users :)

**Comment by ryancramerdesign** [comment]
Didn't realize the Tree page wasn't showing in AdminThemeReno. That was not intentional. I have committed a fix on 3.x and will migrate this to 2.x as well.

**Comment by junofornow** [comment]
Ah,  mystery solved, thanks Ryan.
