### ISSUE TITLE
3.0.3 devns error trying to activate SystemNotifications.module

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1610]
Just tried to install the SystemNotifications module and FieldtypeNotifications and got this white screen error
```
Fatal error: Call to a member function message() on null in /Users/admin/Can/htdocs/processwire/happyfamily/wire/modules/System/SystemNotifications/SystemNotifications.module on line 647
```

Tried to remove the module manually from database but couldn't manage, so needed to import a backup to get rid of it.

**Comment by ryancramerdesign** [comment]
I can't duplicate this one so far. SystemNotifications installs correctly here. I've taken a closer look at the block of code indicated by the line number, but nothing fruitful. I've gone ahead and wrapped it with an if() statement to prevent that error from occurring, but have a feeling it's not a solution. I think there may be some other condition present, but don't know what it might be. Lets see if anyone else can duplicate this one.

**Comment by CanRau** [comment]
Kay, just re-tried but no luck, same error.

Maybe I got something making problems..

**Comment by CanRau** [comment]
can't verify as I don't remember which installation produced this error and all of which I just checked have both modules installed, so it might be obsolete..

I'm closing it for now, if I encounter it again I'll reopen it..  ;)
