### ISSUE TITLE
language-alternate fields and replacements

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1613]
I have a setup with a  language-alternate field like this (in PW 3.x):

 language-alternate field (profield table) "mytablefield" (German)
 language-alternate field (profield table) "mytablefield_en" (English)

It is showing the content of the main language, if the content for the 2nd language has no row.
Is this intended, is there a way to change this behavior (show notthing in lang2 if there is no content)?

**Comment by ryancramerdesign** [comment]
Language fields fallback to default when a localized version isn't available. This is one case where you may want to retrieve the localized value programatically.

``````
$value = $page->get('mytablefield' . ($user->language->isDefault() ? '' : '_' . $user->language->name));
``````

**Comment by tbba** [comment]
That's fine with me. This is my workaround already. 
I just wanted to know if this is intended.
Thanks for the code example anyway (much more elegant than my solution).

**Comment by tbba** [comment]
ahm. sorry to reopen this... it is actually vice versa.
There *is* a fallback to the default language active, at least in my setup.
German is default, English is 2nd language.

If the user uses English (which is not the default) and the mytablefield_en field has no content, the mytablefield (German content) is shown. I expected that there will be nothing shown.

**Comment by ryancramerdesign** [comment]
Since German is the "default" language, then that's also the fallback
language. Meaning, a blank mytablefield_en should fallback to mytablefield
(default/German). The behavior you describe sounds consistent with what was
intended there. You'd want to use that previous bit of code I mentioned to
use a different behavior. Or let me know if I've misunderstood?

**Comment by tbba** [comment]
I see, I read your first statement wrongly (English isn't my first language - and too much coffee).
Thanks for the clarification!
