### ISSUE TITLE
Matrix: creating a matrix type with no fields causes issues

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1614]
Let's say you create a matrix field with two types:

'type1' has no fields
'type2' has a couple integer fields

Now when you use the matrix field in a page and click 'type1', it shows the fields from *type2*.  'type2' also shows the fields for 'type2'.

**Comment by ryancramerdesign** [comment]
Thanks, I've just updated the ProFields download thread with version 1a,
which fixes that issue. Just out of curiosity, what's the purpose of a
matrix type with no fields? Do you use it to represent a horizontal rule or
something?

On Fri, Jan 15, 2016 at 9:13 PM, Jonathan Lahijani <notifications@github.com

**Comment by jlahijani** [comment]
Not sure of an exact use case for it having a type with no fields yet, although it could potentially come up when doing some advanced page-building stuff.  For example, opening and closing a "row".

**Comment by mikerockett** [comment]
I wonder if these shouldn't be marked appropriately, instead of just showing an empty row. Sure, each use case would be different, but we could make the text configurable.

**Comment by isellsoap** [comment]
@jlahijani Can you close this issue please? Thank you!
