### ISSUE TITLE
If field value empty, $page->render('field'); always returning "1" for output

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1615]
**ProcessWire 3.0.5 devns issue**

I have a checkbox field on my site and if i want to use it like :
```php
$page->render('field');
// or
$page-render->field;
// or
$page->_field_

// output is :
1
```

**More info about fields**
Fields : **special_offer (checkbox), special_offer_description (textarea with ckeditor)**
![ekran resmi 2016-01-16 22 09 35](https://cloud.githubusercontent.com/assets/455983/12374255/5968356c-bc9e-11e5-9b66-33c61ac61558.png)

Field **special_offer** settings
![ekran resmi 2016-01-16 22 10 04](https://cloud.githubusercontent.com/assets/455983/12374260/732c655e-bc9e-11e5-8e01-33c9e545de9f.png)

Field **special_offer_description settings**
![ekran resmi 2016-01-16 22 10 24](https://cloud.githubusercontent.com/assets/455983/12374261/8512c894-bc9e-11e5-8602-481be1460b4b.png)
![ekran resmi 2016-01-16 22 10 40](https://cloud.githubusercontent.com/assets/455983/12374262/89cd5ade-bc9e-11e5-96c4-589870b1a48d.png)

My Field Template for **special_offer_description.php** :
```php
<?php if($page->get('special_offer') == 1 && $value != ""): ?>
<div class='avb-title avb-title-blue avb-title-icon avb-title-upper mt10 mb10'>
    <div class='avb-title-left'><span class="uk-icon-diamond"></span></div>
    <div class='avb-title-line'></div>
    <div class="avb-title-text"><h2>Special Offer</h2></div>
</div>
<div class="uk-width-1-1">
    <?=$value?>
</div>
<?php endif; ?>
```

My usage :
```php
$page->render->special_offer_description
```

Result is if **special_offer is 0** :
```php
1
```

If **special_offer vaue is 1** everything look like ok.

if my template is empty (no data for display field value, for test) result is: **1**

And if i want to use field in same page twice with different markup or different templates with different markups, how to usage must be ?

Can you add suffix support to field templates for different usages ?

**Example :**
```php
$page->render('field', 'home'); // field-home.php
$page->render('field', 'featured'); // field-featured.php
$page->render('field', 'listing'); // field-listing.php
// etc..
```

**Comment by trk** [comment]
If there is no value for called field template its return **"1"**

**Comment by ryancramerdesign** [comment]
Thanks, I have committed a fix for the issue.

**Comment by trk** [comment]
Still have this issiue after update your fix

**Comment by ryancramerdesign** [comment]
Okay I see what you mean – just pushed a second try. :)

**Comment by trk** [comment]
And what you think about usage like this:

Can you add suffix support to field templates for different usages ?

```php
$page->render('field', 'home'); // field-home.php
$page->render('field', 'featured'); // field-featured.php
$page->render('field', 'listing'); // field-listing.php
// etc..
```

For now my field template for title field is :

```php
<?php if($value != ""):
    $template = wire('page')->template;
    $templatesLink = array('photo-gallery-view');
    ?>
    <?php if(!in_array($template, $templatesLink)): ?>
        <div class='avb-title avb-title-blue avb-title-icon avb-title-upper uk-text-center mb10'>
            <div class='avb-title-left'><span class='avb-icon-contact-yachts'></span></div>
            <div class='avb-title-line'></div>
            <div class='avb-title-text'><h1><?=$value?></h1></div>
        </div>
    <?php endif;?>
    <?php if(in_array($template, $templatesLink)): ?>
        <div class='avb-title avb-title-blue avb-title-icon avb-title-upper uk-text-center mb10'>
            <div class='avb-title-left'>
                <a class='avb-title-link' href='<?=$page->parent->url?>' title='<?=$page->parent->title?>'>
                    <span class='uk-hidden'>Photo Gallery</span><span class='uk-icon-angle-left uk-icon-medium'></span>
                </a>
            </div>
            <div class='avb-title-line'></div>
            <div class='avb-title-text'><h1><?=$value?></h1></div>
        </div>
    <?php endif; ?>
<?php endif;
```

**Comment by matjazpotocnik** [comment]
If I understand what you want, maybe this could be used. Quoting Ryan:

"I didn't document it yet because I wasn't sure I was going to keep it there. But sounds like maybe we should keep it there. The format it uses is this:
 
field.template.php
example: body.basic-page.php
 
Since this is already built in, you can try it out now if you'd like. It checks for a template-specific file before a general purpose one. It will use the template-specific one if present, or the general purpose one if not."

**Comment by ryancramerdesign** [comment]
While this is still a very new feature and I'm sure it will evolve, the
intended purpose at this stage is to provide a default/common rendering
output for a field... so that you always know what you are going to get
when you use it. My thought was that if one needed a "custom" rendering,
they would do that as needed rather than using the default/common output.
Though perhaps a second argument where you can specify the view is
something to consider, but technically it would be more efficient just to
make your own function for that purpose. Like @matjazpotocnik mentioned you
can use the field.template.php format if you'd like. I originally wasn't
sure we should keep it because it gets a little too far away from the
"default/common rendering" intention, but sounds like a couple of people
have already found it useful so I'm pretty sure we'll keep that now. Will
put more thought into a separate view/template argument, but it probably
can't hurt anything, so I think it would be fine.

**Comment by trk** [comment]
@matjazpotocnik advice is useful for some cases, but if you need to get pages from different pages?

Examples from **Skyscrapers** profile

http://demo.processwire.com/cities/albuquerque/ **Albuquerque Skyscrapers**
http://demo.processwire.com/ **Featured Skyscrapers** have different markup from original http://demo.processwire.com/cities/new-york-city/chrysler-building/ **Chrysler Building**

(template=city) inside **Albuquerque Skyscrapers** $page->images field only displaying 1 image and has different image sizes
(template=home) inside **Featured Skyscrapers** $page->images field only displaying 1 image
(template=skyscraper) inside **Chrysler Building** $page->images displaying all images

**Comment by teppokoivula** [comment]
> Though perhaps a second argument where you can specify the view is
> something to consider, but technically it would be more efficient just to
> make your own function for that purpose.

I would definitely vote for this.

At least for me it's common that a field might have multiple use cases depending on context: images could be used for a gallery view, list of images, JSON array, etc. Those layouts are often reused on multiple templates, and thus it makes sense to separate them from templates themselves.

Sure, I can do this with other methods too, but in my opinion it would be a logical use case for the new field-level template files feature. It could also further limit the risk of these files turning into ugly if-mess in the long run :)

On the other hand the template-specific file support seems much less useful to me: if it's tied to one template anyway, the benefit of moving it to separate file seems questionable at best. Might make sense in some Repeater or PageTable related situations, but not much else.

**Comment by LostKobrakai** [comment]
Having context based templates could also allow for a community/core json api to be build upon.

**Comment by trk** [comment]
On my side i tried **title.template-name.php** usage, but many duplicates like this :

![ekran-resmi-2016-01-21-20 35 06](https://cloud.githubusercontent.com/assets/455983/12490670/5e8fffd6-c07f-11e5-8a6f-d908dce659c4.png)

This is much useful than **title.template-name.php** example. Of course if there is no update about usage :)

```php
<?php if($value != ""):
    $template = wire('page')->template;
    $templatesLink = array('photo-gallery-view');
    ?>
    <?php if(!in_array($template, $templatesLink)): ?>
        <div class='avb-title avb-title-blue avb-title-icon avb-title-upper uk-text-center mb10'>
            <div class='avb-title-left'><span class='avb-icon-contact-yachts'></span></div>
            <div class='avb-title-line'></div>
            <div class='avb-title-text'><h1><?=$value?></h1></div>
        </div>
    <?php endif;?>
    <?php if(in_array($template, $templatesLink)): ?>
        <div class='avb-title avb-title-blue avb-title-icon avb-title-upper uk-text-center mb10'>
            <div class='avb-title-left'>
                <a class='avb-title-link' href='<?=$page->parent->url?>' title='<?=$page->parent->title?>'>
                    <span class='uk-hidden'>Photo Gallery</span><span class='uk-icon-angle-left uk-icon-medium'></span>
                </a>
            </div>
            <div class='avb-title-line'></div>
            <div class='avb-title-text'><h1><?=$value?></h1></div>
        </div>
    <?php endif; ?>
<?php endif;
```

**Comment by trk** [comment]
Just tested, api calls like **$page->render->children** working :+1:
