### ISSUE TITLE
Inputfield datetime shows only 12 hour independend of settings

### ISSUE THREAD

**Issue by juergenweb** [ryancramerdesign/ProcessWire#1617]
In PW 3.05 the slider (or select) of the time input from the inputfield datetime always shows 12 hour format independend of what input format is set. I have set it to 24 hours (format H:i) but it shows only 1-12 hours.

**Comment by juergenweb** [comment]
Possible solution:

Replace

$timeFormatJS = str_replace('h24', 'h', $timeFormatJS);

with

$timeFormatJS = str_replace('hh24', 'HH', $timeFormatJS);

in InputfieldDateTime.module (line 160).

Thanks to Matjazp from the PW forum for this solution

**Comment by cstevensjr** [comment]
Related ProcessWire Forum post is :

https://processwire.com/talk/topic/11934-pw-305-and-inputfield-datetime-problem/#entry111113

**Comment by ryancramerdesign** [comment]
Thanks, I have added the proposed fix.

**Comment by matjazpotocnik** [comment]
Ryan, fix does not work, you should replace hh24 with HH, not with hh.

**Comment by isellsoap** [comment]
@juergenweb Can you close this issue please? Thank you!
