### ISSUE TITLE
textarealanguage / cke sometimes don't save content

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1618]
PW 3.x
I had to put in lot's of content recently and had a reocurring error which resulted in data loss.
(I think that my problem only occurs with textarealanguage fields & cke)

I fill in text,and hit save (while the cke still has focus). -> What I just typed in is gone sometimes!
I fill in text and click somewhere else (cke looses focus) and save -> everything is ok!

Am I the only one here or is this repeatable to you?.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate this one. I tested both normal and inline mode on a 3-language site in PW 3.0.5. This is testing in the latest Chrome on OS X. 

Though the issue sounds familiar, as we had something similar in the past with at least one version of CKEditor when hitting save while an inline-mode editor is still in focus.
 
If you are able to consistently repeat it, can you try opening your JS console to see if any JS errors are occurring? Also: What browser? And you mentioned 3.x but what version of 3.x? Thanks.

**Comment by tbba** [comment]
I am always at the very latest 3.x - i check for updates daily. Its 3.0.5.
The CKE is in inline mode.
The browser is Safari 9-0-3 Mac. - I will try the console.

**Comment by teppokoivula** [comment]
Earlier versions of CKEditor had a very similar issue on some versions of Internet Explorer: saving while the field had focus didn't work, but blurring the field first did. I haven't heard of this issue before, but on the other hand I've heard pretty bad stuff about the quality of Safari lately, so wouldn't rule a Safari-specific CKEditor issue out completely.

@tbba, does this happen on other browsers too, or just this one?

**Comment by tbba** [comment]
Teppo this is a great idea. I had not checked the other browsers, since I am so used to the Safari console (but I startet to be suspicious already). By the way console. At least the Safari console does not show js errors or so. Since this is a 100% private music website (for testing out PW 3.x an entertaining way) I would not have a problem to give access to it to see the effect in real.

**Comment by tbba** [comment]
I close this for now. Did not see that behavior in a while.
