### ISSUE TITLE
Subfield sorting not working in 2.7.3

### ISSUE THREAD

**Issue by Renobird** [ryancramerdesign/ProcessWire#1621]
This is a new issue related to: https://github.com/ryancramerdesign/ProcessWire/issues/1547
It appears that somewhere between 2.7.1 and 2.7.3 sorting on subfields stopped working.

In 2.7.1, the following worked as expected:
$pages->find("template=scholarships, sort=page_selector.title");

In 2.7.3 the same selector results in the following error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '_sort_page_selector_title.title' in 'order clause'

**Comment by Renobird** [comment]
If I revert the changes made here https://github.com/ryancramerdesign/ProcessWire/commit/8d6cf7aef7461dda473f6f91079ca95e082435b0

Things return to working as they did previously. I'm not sure of the full scope of what those changes effect, but that seems to be the culprit.

**Comment by ryancramerdesign** [comment]
Strangely, I can't duplicate this one in 2.7.3 or 3.0.5. The selector I tested with:
```````
template=product, sort=supplier.title
``````
The "supplier" field is a Page field. Can you think of any other factors? Like is your "page_selector" field something other than Page field, like maybe a PageTable field or something else? Just trying to figure out what conditions I need to setup to reproduce it.

**Comment by Renobird** [comment]
page_selector is set to "Single page (Page) or boolean false when none selected".

**Comment by ryancramerdesign** [comment]
Okay that explains it! I was able to reproduce once I used that setting. I have pushed a fix. Thanks!

**Comment by Renobird** [comment]
Everything is working as expected. Thanks for the quick fix.
