### ISSUE TITLE
Language change is ignored between two calls to $page->children

### ISSUE THREAD

**Issue by captain-speculatius** [ryancramerdesign/ProcessWire#1622]
When $page->children is called twice for two different languages, second call always returns the same result as the first one. Please see forum post for more information:

https://processwire.com/talk/topic/11951-get-active-children/

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this to the devns (3.x) branch, and will migrate it to dev as well a little later.

**Comment by isellsoap** [comment]
@captain-speculatius Can you close this issue please? Thank you!

**Comment by captain-speculatius** [comment]
Sorry :) Closing.
