### ISSUE TITLE
Provide method for internal linking based on id

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/ProcessWire#1623]
## Problem/Motivation:
Internal links to other pages in Processwire can easily break.  Anytime you or some other editor reorganizes the page hierarchy links will break.  This can happen many times during the development of site and in production when the client wants to restructure their sitemap.

The existing solutions IMHO fall short:
http://modules.processwire.com/modules/page-path-history/ - works but doesn't fix the problem of having the incorrect links in the source and it leads to many 301 redirects.

http://modules.processwire.com/modules/process-redirect-ids/ - works great, but provides many ways to internally link to a page.  The problem is that there is no standard.

In Drupal, the standard is
```
<a href="/node/10">Test Link</a>  = links to the node id of 10
```
In modx, the standard is
```
<a href="[[~10]]">Test Link</a> = output the url to resource with the id of 10
```
In Craftcms, the standard is
```
<a href="http://craftcms.dev/news/2015/we-just-installed-craft-neat#entry:3:url">Test Link</a>
```
Other CMS systems do this as well such as Pimcore, Concrete5, and Silverstripe.

By using id based linking, the links become "portable" across dev, stage, and production environments and the links never break!

~~Note: when the page is outputted the links are transformed into the correct url.~~
*** Edit: this note is not correct.  Processwire would still need a text formatter module to convert the id based links on output to the correct url so that the id based links don't get indexed by search engines ***

## Proposed resolution:
I'm requesting that Processwire provide a core(standardized) way to handle internal links of pages based on the page id.  It would be nice if http://modules.processwire.com/modules/process-redirect-ids/ or something similar was included in core.

If this module can't be included in core, can you at least provide a standard for internal id linking?  That way people can still use the process-redirect-ids module in a future proof way.  It would also need a new module to convert id based links to the correct url when viewing pages.

Thank you for your consideration.

**Comment by LostKobrakai** [comment]
How about `$pages->get($id)->url;` and you've exactly the described behaviour? About your proposal. I'm not sure most people are using hard coded links to often. At least in my work it's far more common to embrace dynamic selected pages over any hard coded id's.

**Comment by gmclelland** [comment]
Thanks @LostKobrakai, but I'm talking about links in text areas that the content editors write.

The code you mentioned would probably work fine when working in templates.

**Comment by teppokoivula** [comment]
This is exactly what [Page Link Abstractor](https://processwire.com/talk/topic/236-module-page-link-abstractor/) was used for. It worked behind the scenes, automatically converting local links into ID-based ones.

As of ProcessWire 2.5 this module was deprecated in favor of current textarea content-type options.. except that the content-type HTML feature doesn't actually seem to handle changes in Page URLs like the abstractor did, making it (in my humble opinion) a much less versatile solution.

Anyway, @ryancramerdesign should probably step in and provide more details. It's entirely possible that I'm missing something important here :)

**Comment by tbba** [comment]
I am missing the _Page Link Abstractor_ a lot. It was so extremely useful. Now we can get an automated redirect, which is also nice, but not the same, SEO wise. Or am I wrong?

**Comment by adrianbj** [comment]
Looks like your prayers were answered today:
https://github.com/ryancramerdesign/ProcessWire/commit/bf4dfb79456a52f3e36740ae4fb6d6b32a90b1c7

More info coming in the blog post :)

**Comment by gmclelland** [comment]
Fantastic!  Can't wait for the blog post

**Comment by tbba** [comment]
Whow, THATS great news. - Does this work with multi-language fields also?

**Comment by adrianbj** [comment]
But of course :)

https://github.com/ryancramerdesign/ProcessWire/commit/bf4dfb79456a52f3e36740ae4fb6d6b32a90b1c7#diff-0e0c3c28fce39583571a51a077f24674R227

**Comment by gmclelland** [comment]
For reference...Here's the related blog post http://processwire.com/blog/posts/processwire-3.0.6-brings-pages-upgrades-and-link-abstraction/

I just tried out 3.0.6 and I'm very impressed how the internal linking works.  It's like magic :)  This is a HUGE feature IMHO.

I guess this issue can be marked as fixed now?

**Comment by ryancramerdesign** [comment]
Thanks, Glad you guys like it. I'll go ahead and close this one.
