### ISSUE TITLE
Switch from date() to DateTime() to support dates prior to 1901

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1624]
https://processwire.com/talk/topic/11845-date-time-field-not-showing/

Not sure if there are any advantages to using date() at all anymore, but at least for the datetime field I think it should start using DateTime() so users can enter dates before 1901.

**Comment by Da-Fecto** [comment]
+1

**Comment by LostKobrakai** [comment]
+1

**Comment by adrianbj** [comment]
Added here: https://github.com/processwire/processwire-requests/issues/25
