### ISSUE TITLE
3.0.5 Front-end editing dont work when URL have not ending slash

### ISSUE THREAD

**Issue by eresik** [ryancramerdesign/ProcessWire#1625]
3.0.5 Front-end editing dont work when URL have not ending slash.
1. Select template with Front-end editing field
2. Select tab "URLs"
3. Switch "Should page URLs end with a slash?" to "NO"
4. Edit page by front-end editing, and try save it.
5. Get error (message box) "Edited page does not match current page ID (1014 != 1015)"

**Comment by ryancramerdesign** [comment]
Thanks @eresik I have pushed a fix for this issue.

**Comment by isellsoap** [comment]
@eresik Can you close this issue please? Thank you!

**Comment by isellsoap** [comment]
@ryancramerdesign Since @eresik doesn’t close this issue, could you do it please? Thank you!
