### ISSUE TITLE
Warning when hitting the automatic page name limit

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1628]
See here: https://processwire.com/talk/topic/11990-limitation-of-pages-with-the-same-name/

**Comment by Da-Fecto** [comment]
I think 100 iterations is quite a lot when people rely on it without knowing how it works.

**Comment by LostKobrakai** [comment]
Sure. It just shouldn't silently fail.

**Comment by Da-Fecto** [comment]
Agree, I was thinking about log at 25 and exception on 100.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this.
