### ISSUE TITLE
Ampersands (&) and $sanitizer->selectorValue()

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1630]
I have a use case in which I am trying to find matches for a user inputted string which contains an ampersand in it, i.e. "A&B Company". However, when I use $sanitizer->selectorValue() to sanitize it before putting it into the selector, the sanitizer turns it into "A& B Company" due to line 765 in Sanitizer.php, which states "disallow ampersands from beginning entity sequences". Because of this added space, the matching page is not returned.

I'm not sure how important this line is for security, but it was a problem in my case and I'm wondering if there might be a better way to handle this.

**Comment by ryancramerdesign** [comment]
Numeric entities are already removed by an earlier replace in the selectorValue() method, so I think that line 765 can be removed entirely. We don't have a need to remove named entities at this point in time. I will update the code to remove that part. Thanks.

**Comment by thetuningspoon** [comment]
Glad I could help. Thanks Ryan!
