### ISSUE TITLE
devns-3.05 (multilang) - can't set default language name empty

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1634]
If I left the default language name empty, it restores the last value on save.

This makes it impossible to have urls like "site.com/subpage/" in the default language, even if using "localUrl().

![](http://rolandtoth.hu/pic/pw-305-langnames.png)

I've set the default language homepage to be same as the root url in module "LanguageSupportPageNames" but no difference.

As I remember this worked fine in 2.7.

**Comment by rolandtoth** [comment]
Update: this happens only if the logged-in superadmin language is set to a non-default language. If his language is the default, setting the default language name to empty is saved.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by rolandtoth** [comment]
All is fine after the fix. Thanks!

**Comment by isellsoap** [comment]
@rolandtoth Can you close this issue please? Thank you!
