### ISSUE TITLE
FilenameArray to extend Wiredata? Method to get PHP Array?

### ISSUE THREAD

**Issue by blynx** [ryancramerdesign/ProcessWire#1635]
Hi,

I am checking out AIOM and I want to use the `$config->styles/scripts` variables to store the needed files in the frontend. It is possible to pass an array of filename-strings to AIOM but I cant easily get the necessary array from `$config->styles/scripts` ...

Of course I could just use my own whatever array as I will be doing now, but I wonder why `$config->styles/scripts` is not derived from WireData?
Or, couldn't it be useful to have a method to retrieve that kind of array from those fields in general?

**Comment by LostKobrakai** [comment]
> …, but I wonder why $config->styles/scripts is not derived from WireData?

Somewhere in another issue Ryan said this is to keep the object's footprint small, where a full WireData handling is not really needed.

**Comment by blynx** [comment]
Ah - ok,
I'll figure a way I like, thanks!
