### ISSUE TITLE
Sort fields and templates lists

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1642]
It would be great to have a sort option in addition to the filters on the Fields and Templates pages in the admin. When manually copying things I've done in a dev environment to live on a live site it would help if we could sort newest to oldest as a visual aid.

Of course nothing beats making notes as you go, but this would help as an additional, low-tech quick check I think.

**Comment by ryancramerdesign** [comment]
Pete, there already is a sort option–it's the column headings. Click them to sort. Note however we don't currently keep track of dates for fields, so don't have that as a sort option for the Fields list at least.

**Comment by isellsoap** [comment]
@Notanotherdotcom If this is still a thing you want to see implemented, [please open an issue in the new requests repository](https://github.com/processwire/processwire-requests). Thank you!
