### ISSUE TITLE
PW 2.6+ & 2.7.+ index.php overwrites site/config.php settings with defaults from wire/config.php

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/ProcessWire#1643]
Ahrghhh! Please ignore! Found out that this behave is from autoloaded third party module.

Everything is fine! Sorry!

**Comment by teppokoivula** [comment]
@horst-n: after an extremely busy morning, opening GitHub just to find an issue titled "PW is fine" was exactly the reassurance I needed. I know this probably wasn't your intention, but thanks anyway :D

**Comment by horst-n** [comment]
My pleasure! :)
