### ISSUE TITLE
WireFileTools in 3.0.6 - absolute path detection broken on Windows

### ISSUE THREAD

**Issue by BitPoet** [ryancramerdesign/ProcessWire#1648]
WireFileTools checks for absolute paths in line 412 (function render) with the following code:
`} else if($options['defaultPath'] && strpos($filename, '/') !== 0) {`

This breaks on Windows where absolute paths are indicated by a drive letter and colon. A quick fix would be to change this line to:
`} else if($options['defaultPath'] && strpos($filename, '/') !== 0 && strpos($filename, ':') !== 1) {`

This fix was reported to work in [this thread](https://processwire.com/talk/topic/12084-update-305-to-306-not-possible/#entry112167).

**Comment by ryancramerdesign** [comment]
Thanks @BitPoet I have committed your fix.
