### ISSUE TITLE
Problems with the new frontend editing

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/ProcessWire#1650]
I just tested the pw 3.0.6 using the Classic profile and noticed some strange things that I thought I should report.

I'm using Option A for frontend editing.  I make the body and sidebar fields editable.

## Problem 1.
When I try to edit the /about/ page on the frontend, ckeditor doesn't load when double clicking the first paragraph but I do see the save and cancel buttons.  When I try to change the text and click the save button, nothing happens.

In the Google Chrome(Mac) console I see:
![image](https://cloud.githubusercontent.com/assets/40570/12700071/2f08af62-c799-11e5-99e4-25cf2090554d.png)

## Problem 2.
If I go to about/background/ and double click on the first paragraph, I now can see ckeditor and I can make and save changes to the text.  The strange thing is that if I highlight some text and click the link button in the ckeditor toolbar, nothing happens.  The normal processwire link modal dialog doesn't popup.  Same thing happens if I click on the image button in the toolbar.

In the Google Chrome(Mac) console I see:
![image](https://cloud.githubusercontent.com/assets/40570/12700079/8a3e4bbc-c799-11e5-86dd-50c558683ebf.png)

Note: Editing both of these pages on the backend work correctly.  I've also tried editing the pages in Firefox with the same problems.  This is a fresh install with only core modules, no contrib modules installed.

I'm just curious if someone else is able to reproduce the problems?  Anyways, I hope that helps.

**Comment by ryancramerdesign** [comment]
I think the problem might be that the Classic profile is very old, and likewise using a very old version of jQuery. If you still have this install available, I was wondering if you could just remove these two lines from the head.inc file and see if that resolves the issue?
`````
<script type="text/javascript" src="<?php echo $config->urls->templates?>scripts/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php echo $config->urls->templates?>scripts/main.js"></script>
`````

**Comment by gmclelland** [comment]
That did the trick.  All seems to work well now.

**Comment by isellsoap** [comment]
@gmclelland Can you close this issue please? Thank you!
