### ISSUE TITLE
WireUpload class on Windows

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1652]
PHP stores the uploaded file in the folder determined by upload_tmp_dir directive in php.ini. By default this is C:\Windows\Temp directory. After the uploaded file is stored to the upload_tmp_dir, ProcessWire will then move/rename the file to the final destination directory and that doesn’t inherit destination directory’s permissions.

I don't have upload problems in admin (while editing the page and uploading the file from Images fieldtype), because I used $config->$uploadTmpDir pointing to the /site/assets/uploads folder (created by me). Uploaded file is read from php://input and then created at the $config->$uploadTmpDir (if set) folder. Since /site/assets/uploads folder inherits /site/assets folder permissions, moving/renaming the file is not the problem.

When uploading using WireUpload execute() method, PHP's $_FILES global variable stores relevant data about the uploaded file and $config->$uploadTmpDir is not used - files are uploaded to the folder set up by upload_tmp_dir directive and then MOVED to the target directory.

Possible solution would be to COPY the file to the final destination instead of MOVING it. As copying is slower than renaming, I'm not sure if this is the right solution (file WireUpload.php in function saveUpload, line 434, my code is commented):

```
        if($ajax) {
            $success = @rename($tmp_name, $destination); //original
            /* $success = @copy($tmp_name, $destination);
            if(is_file($tmp_name)) @unlink($tmp_name); */
        } else {
                $success = move_uploaded_file($tmp_name, $destination); //original              
                /* $success = is_uploaded_file($tmp_name);
                if($success) $success = @copy($tmp_name, $destination);
                if(is_file($tmp_name)) @unlink($tmp_name); */
            }
```

Then maybe we don't even need $config->$uploadTmpDir ?

**Comment by ryancramerdesign** [comment]
> Possible solution would be to COPY the file to the final destination instead of MOVING it.

I've read through your issue report a couple of times, but I'm not clear on what the problem is that we're trying to solve? I see you've mentioned a solution, but what's the solution solving? Sorry, the morning coffee hasn't kicked in here yet. :)

**Comment by matjazpotocnik** [comment]
My solution solves se*cur*ity issue. 

When copying a folder or file to an NTFS partition (same or different), the copy of the folder or file inherits the destination folder permissions. When moving a folder or file to the same NTFS partition, the folder or file will retains its original permissions. 

Example:

- I have TEMP folder (source). Users A, B and C may create files on TEMP folder and they may delete files from TEMP folder. 
- I have ASSETS folder (destination). User D (and only user D) may create files on ASSETS folder and he may delete files from ASSETS folder.
- User A create the file in TEMP folder. When he MOVE the file from TEMP to ASSETS folder, users A, B and C have access to that file. When he COPY the file from TEMP to ASSETS folder, users A, B and C do not have access to that file.

**Comment by ryancramerdesign** [comment]
Uploaded files should have user/group of the user Apache is running as (or as the user of the account), and file permissions that are consistent with $config->chmodFile setting in /site/config.php. PHP has no control over user/group, but can set file permissions, and that's what ProcessWire does after a file is uploaded. Are you saying that part isn't working in Windows?

**Comment by matjazpotocnik** [comment]
A lot of PHP file functions don't work on windows. There is no 644 permission on windows, so I don't know what could chmod possible do on windows ... that's why I use copy/unlink.

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/51bda526eb637f86fc56694cc85f6d5a7fba306b

Thx!
