### ISSUE TITLE
Add curl method if allow_url_fopen is not enabled for adding files/images from external URLs.

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1655]
On servers that don't have allow_url_fopen enabled, it isn't possible to do a: 
```
$page->images->add("http://externalurl.com/myimage.jpg");
```
It just comes back with an "Unable to Copy" error message.

Seems like it would be nice if there was an attempt to use CURL instead, rather than failing.

**Comment by teppokoivula** [comment]
WireHttp::download already has a pretty good implementation of cURL + fopen + sockets, perhaps Pagefile could/should be updated to use that instead of copy? :)

**Comment by ryancramerdesign** [comment]
Makes sense to me, I have updated this to use WireHttp instead, which attempts CURL as it's first choice. CURL is superior to fopen or sockets when it comes to download files because it writes them in chunks rather than trying to load whole file in memory as all the alternatives do.

**Comment by adrianbj** [comment]
:+1:  Thanks Ryan!
