### ISSUE TITLE
Sort by parent field not working in selector?

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1657]
`$mypages = wire('pages')->find("template=my-template,sort=parent.date_received");`

Gets the following error:
Fatal error: Uncaught exception 'ProcessWire\PageFinderException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '_sort_parent_date_received.date_received' in 'order clause'' 

Can you use selectors to sort by a parent's field?  I don't remember if I've ever done this, but according to the PW forum past topics, it's possible.

**Comment by ryancramerdesign** [comment]
We have actually not supported parent custom fields for sorting. We've only supported parent properties native to the parent table, such as name, created, modified, etc. However I've just pushed a commit to 3.x that adds support, so your selector should work in the latest 3.x commit.

**Comment by isellsoap** [comment]
@jlahijani Could you please close this issue? Thank you!
