### ISSUE TITLE
Swallowed exceptions

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1659]
For writing tests with processwire it would be nice to have an option to prevent exceptions from being catched, like it's happening here: 
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/PagesEditor.php#L664-L669

In such a case it would be more useful to have the exception thrown, so the test doesn't just "silently" fail, in that it doesn't show an error while still failing. 

Edit: I'm not sure if all of them are handled by trackException, so maybe just overwriting it would be enough.

**Comment by teppokoivula** [comment]
@LostKobrakai: sounds like you're looking for [$config->allowExceptions](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/config.php#L925).

**Comment by LostKobrakai** [comment]
That might be exactly what I looked for.
