### ISSUE TITLE
PW3dev Drag images sporadic doesn't work

### ISSUE THREAD

**Issue by Jugibur** [ryancramerdesign/ProcessWire#1661]
Unfortunately I can't reproduce when exactly this issue occurs. 
But to test drag the images a few times randomly in a new order; in my case, the error then happend.

![image](https://cloud.githubusercontent.com/assets/271000/12789910/106189da-caa0-11e5-88e4-d769473524e1.png)

**Comment by ryancramerdesign** [comment]
Thanks @Jugibur I've seen the issue too, and likewise not exactly sure when/why, but it seems to be a jQuery UI thing as best as I can tell. We're actually replacing the InputfieldImage very soon with a new version by @LostKobrakai. I think we'll let this one go for now, as the drag/sort issue definitely doesn't seem to occur in @LostKobrakai version, it's quite a lot nicer. We should have it committed on 3.x in the next 2-3 weeks.

**Comment by isellsoap** [comment]
@Jugibur It seems that this issue can be safely closed. If you think the issue isn’t fixed yet or requires additional work to do, please add a comment to this issue and I re-open it.
