### ISSUE TITLE
PW 3.0.x -  Session: Failed to construct module: \FieldtypeCroppableImage

### ISSUE THREAD

**Issue by kbreynck** [ryancramerdesign/ProcessWire#1663]
Hi.

I'm trying to install the Module "CroppableImage" via:
Modules > Install > Add Module From Directory

In the last step (Click on [Install] in the Module-Table-Row "FieldtypeCroppableImage") the following log message occures and the module installation seems to be interrupted:

Log Messages:
Session: Modul-Installation -
Session: No module specified
Session: Failed to construct module: \FieldtypeCroppableImage - Unable to create directory C:/Users/MYUSER/Documents/Projects/pw-devns/site/assets/cache/FileCompiler/C:\Users\MYUSER\Documents\Projects\pw-devns\site\modules\CroppableImage\classes/

(strange path, isn't it?)

Nevertheless, the following files have been created in the directory \site\assets\cache\FileCompiler\site\modules\CroppableImage\:
- \FieldtypeCroppableImage\FieldtypeCroppableImage.module
- \FieldtypeCroppableImage\FieldtypeCroppableImageConfAdaptor.php
- \InputfieldCroppableImage\InputfieldCroppableImage.module
- \ProcessCroppableImage\ProcessCroppableImage.module

System:
Local XAMPP (v5.6.8) installation on Windows 7
ProcessWire 3.0.6 (3.0.x) devns

**Comment by BitPoet** [comment]
This could be the same issue as  #1648 which Ryan has fixed already. Could you check if the fix is already present in your PW installation?

**Comment by kbreynck** [comment]
I have the latest version (3.0.6) and the fix installed and double checked the sourcecode in the file "/wire/core/WireFileTools.php" on line 412 

The issue looks similar, but the fix doesn't work in this case.

Has this something to do with issue #1639 ?

**Comment by ryancramerdesign** [comment]
This appears to be an issue of directory separators, as best as I can tell. Though I don't have a Windows server to test from, so I've attempted a fix and pushed it to the devns branch. Are you able to tell if this fixes the issue? Thanks.

**Comment by kbreynck** [comment]
Confirmed! This issue is fixed.
Thank you for the fast response, Ryan (@ryancramerdesign).
