### ISSUE TITLE
Add stars field to FieldtypeComments.module's find method (around line 1000):

### ISSUE THREAD

**Issue by juergenweb** [ryancramerdesign/ProcessWire#1664]
Issue in forum talk at https://processwire.com/talk/topic/696-quick-guide-to-the-comments-system/?p=112486

To filter comment depending on star rating it would be great if you add the stars field to the FieldtypeComments.module's find method (around line 1000):

Replace this line of code
if(in_array($f, array('id', 'status', 'created', 'pages_id', 'parent_id', 'created_users_id', 'upvotes', 'downvotes'))) {

with this line of code
if(in_array($f, array('id', 'status', 'created', 'pages_id', 'parent_id', 'created_users_id', 'upvotes', 'downvotes', 'stars'))) {

Then the stars field will be integrated in the find method and you are able to filter comments depending on their rating value. I have tested it on my site and it works excellent.
Special thanks to BitPoet for finding the solution

**Comment by ryancramerdesign** [comment]
Thanks @juergenweb I have added this.
