### ISSUE TITLE
Add New not selecting template correctly

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1665]
I've a parent with two allowed child templates. When using the "Add new" json navigation to add one of those two then the following page does have the last used template selected and not the template that was clicked.
PW 2.7.2

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix.

**Comment by isellsoap** [comment]
@LostKobrakai Can you close this issue please? Thank you!
