### ISSUE TITLE
Field dependencies enhanced OR selectors

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1671]
I know we can do: `field=foo|bar` and `this_field|that_field=value`, but what about support for `this_field=foo|that_field=bar`

or perhaps expressed like:
`(this_field=foo), (that_field=bar)`
to be consistent with PW selectors.

**Comment by ryancramerdesign** [comment]
The selectors supported for dependencies are minimal. They have to be processed both in PHP and in JS, so trying to keep the scope of them to something I can maintain by limiting the complexity   somewhat. JS is not my native language, and I'm not too keen on maintaining a full selector engine in JS. You might try `this_field|that_field=foo|bar` though to be honest, I'm not 100% positive OR conditions in both field and value are supported at the same time (code not in front of me).

**Comment by adrianbj** [comment]
I understand - just thought it might be a nice addition if you hadn't thought of it yet.

FYI that option of `this_field|that_field=foo|bar` didn't work.
