### ISSUE TITLE
File compiler and instantiating a core module class

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1672]
In order to make my module support PW 2 and 3, I had to do the following:
```
        $this->modules->get('FieldtypeFieldsetTabOpen');
        if(class_exists("\ProcessWire\InputfieldFieldsetTabOpen")) {
            $field = new \ProcessWire\InputfieldFieldsetTabOpen;
        }
        else {
            $field = new InputfieldFieldsetTabOpen;
        }
```
Am I missing something? Shouldn't the file compiler be able to work with just this:
```
        $this->modules->get('FieldtypeFieldsetTabOpen');
        $field = new InputfieldFieldsetTabOpen;
```

**Comment by ryancramerdesign** [comment]
InputfieldFieldsetTabOpen is not part of the public API or one of our
publicly exposed classes, as it's not intended to be used outside of
FieldtypeFieldsetTabOpen. You would usually use the JqueryWireTabs module
instead, as those tab fieldset/inputfield modules are intended exclusively
for definition within fieldgroups. But if you want to use
InputfieldFieldsetTab, you may still be able to (I've never tried), but
regardless of PW version, I think you'd need to do this:
```````
$fieldtype = $modules->get('FieldtypeFieldsetTabOpen');
$inputfield = $fieldtype->getInputfield(new NullPage(), new NullField());
```````

**Comment by adrianbj** [comment]
What I am doing has been working for many PW versions now and still works with that extra check. 

I realize it's a bit of a hack, but it's the only way I have been able to insert a new tab between two existing tabs on an edit page - I want to insert between Content and Children.

This is why I ended up with the InputfieldFieldsetTabOpen approach, which I lifted from Nico's SEO module. I was initially doing:
```
$newTab = new InputfieldWrapper();
$newTab->prepend();
``` 
but that put the new tab at the end as I could never figure out how to reference the Content tab when doing insertAfter. I also mentioned this here: https://github.com/ryancramerdesign/ProcessWire/issues/1076

I know you mentioned that I could use it that way, but I never figured it out before - any idea where I might have gone wrong?

Thanks!

**Comment by ryancramerdesign** [comment]
Adrian, if you are putting a new tab in the page editor, then the InputfieldFieldsetTabOpen/InputfieldFieldsetTabClose may be a fine way to go then. Those are meant just for the page editor, so the context is right. 

Btw, I don't think that a `$newTab->prepend();` would do anything except maybe produce an Exception? It's expecting an argument of what you want to prepend in $newTab. Though sounds like InputfieldFieldsetTabOpen/Close is really what you want here anyway, so doesn't matter. :)

**Comment by adrianbj** [comment]
Thank for the confirmation that InputfieldFieldsetTabOpen is still the only way to do this. It still seems a shame that I have to have that conditional for PW 2 vs 3 though. I guess most users or even module developers will come across this, so not a big deal.
