### ISSUE TITLE
Backend Cache problem

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1673]
I updated a ProcessWire 2.6.7 website to 3.0.7. Website is a multi-language website. I translated templates, fields. For easily edit these things i changed my profile language to Turkish. After all changes done i changed my profile language to English.

- Firstly backend navigation displayed in Turkish (After clear modules cache, its ok)
- In Setup > Templates template names are English, but in Bookmark shortcuts, shortcuts are Turkish

**Comment by ryancramerdesign** [comment]
Some of this stuff gets cached in $session. You may have to logout and login again. Please let me know if it persists after logout/login.

**Comment by trk** [comment]
You are right !

When i check it today its look like ok !
