### ISSUE TITLE
Namespace string in icon list (PW3)

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1674]
The first icon in the list is a namespace string:

![pw-namespace-icon](https://cloud.githubusercontent.com/assets/5349356/12900050/95bbc4e8-ceb4-11e5-9422-1f201638cab4.png)

**Comment by matjazpotocnik** [comment]
Ah, good finding, it's in /wire/modules/Inputfield/InputfieldIcon/icons.inc

**Comment by ryancramerdesign** [comment]
Thanks, looks like a leftover from one of the automated namespace conversions from PW2 to PW3. Fixed.

**Comment by isellsoap** [comment]
@rolandtoth Can you close this issue please? Thank you!
