### ISSUE TITLE
Improvements to 'renderBodyClass' for AdminThemeDefault

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1677]
The default admin theme body class outputs some useful body classes, but perhaps it can be extended further.  Suggestions:

- if editing a page, output the template name and page id of the page being *edited* (right now it's the template name and id of the "edit" page itself).
- in addition to the above, perhaps the template name and id of the page's rootParent

**Comment by ryancramerdesign** [comment]
@jlahijani I will go ahead and add this, as it's easy to do. But just in case anyone asks what they are for, can you help me understand where/how one would use these body classes? The current id-[n] class has some good use cases for targeting different pages in the admin. But I'm wondering what sort of things one might use the proposed classes for that identify the page being edited?

**Comment by jlahijani** [comment]
It's mainly for super-fine control if doing admin CSS overrides.  For example, one could manipulate the nav onstate/current-state with this level of precision purely with CSS.
