### ISSUE TITLE
Default size for FieldtypeInteger and FieldtypeFloat

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1681]
The `InputfieldInteger` has currently a `size`-property applied with the default value `10`. This also affect `InputfieldFloat` as it depends on it. Would nice to be able to change/remove it as already possible with `InputfieldText`

**Comment by ryancramerdesign** [comment]
Good idea, I have added this in the latest commit to devns.

**Comment by isellsoap** [comment]
@yckart Could you please close this issue? Thank you!
