### ISSUE TITLE
File compiler problem when require or include in a conditional on the one line.

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1682]
This:
```
if($this->data['showPWPanel']) {
     require_once './ProcesswirePanel.inc';
}
```
gets properly compiled to:
```
if($this->data['showPWPanel']) {
     require_once(\ProcessWire\wire('files')->compile(\ProcessWire\wire("config")->paths->root . 'site/modules/TracyDebugger/ProcesswirePanel.inc',array('includes'=>true,'namespace'=>true,'modules'=>false)));
}
```

But, this:
```
if($this->data['showPWPanel']) require_once './ProcesswirePanel.inc';
```
is left completely untouched by the compiler resulting in a "failed to open stream: No such file or directory" error.

**Comment by adrianbj** [comment]
Just wanted to add that if I add __DIR__ (which is required for Windows and is good practice anyway), it works fine, eg.
```
if($this->data['showPWPanel']) require_once __DIR__ . '/ProcesswirePanel.inc';
```
I wonder if there is something still that should be fixed or not?

**Comment by adrianbj** [comment]
I just came across a scenario where a related problem showed up again, even with the `__DIR__` in the path. This time I was trying to use `wire()` in the required file and it was saying that it was undefined. As soon as I made it a multiline conditional it worked fine. Note that curly braces alone aren't enough, it actually has to be on multiple lines.

**Comment by ryancramerdesign** [comment]
@adrianbj I've pushed an attempted fix here, which seems to resolve it on this end. Let me know if you still see any issues on that end. Thanks.

**Comment by adrianbj** [comment]
Issue seems to be fixed - thanks Ryan!
