### ISSUE TITLE
ProcessWire 2.7 update error: "Unknown error, please try again later" + "Deprecated: Wire has a deprecated constructor in \wire\core\Wire.php"

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#1683]
After updating to ProcessWire 2.7, I get "Unknown error, please try again later" when trying to access the admin interface.

PHP also reports this error message: "Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Wire has a deprecated constructor in \wire\core\Wire.php on line 51".

I was updating from 2.6.x. I updated by replacing the wire-folder with the 2.7 version + replacing the index.php and .htaccess files. I also tried to replace the /site folder with "/site-default" (renamed to "/site"). See contents of my config.php file below.

Screenshot:
![pw-update-error](https://cloud.githubusercontent.com/assets/129573/13032681/8ea253e2-d2fc-11e5-8208-e0b49525cb21.png)

config.php:

	if(!defined("PROCESSWIRE")) die();
	$config->debug = false;
	$config->prependTemplateFile = '_init.php';
	$config->appendTemplateFile = '_main.php';
	$config->dbHost = 'localhost';
	$config->dbName = '********';
	$config->dbUser = '********';
	$config->dbPass = ''********';
	$config->dbPort = '****';
	$config->userAuthSalt = '********'; 
	$config->chmodDir = '0755'; // permission for directories created by ProcessWire
	$config->chmodFile = '0644'; // permission for files created by ProcessWire 
	$config->timezone = 'Europe/Copenhagen';
	$config->httpHosts = array('localhost', '127.0.0.1');

Environment info:

- ProcessWire 2.7
- Apache 2.4
- MariaDB 10.1 (x64)
- PHP 7.0.3.

The update status said:

	SystemUpdater: Update #12: Initializing update
	SystemUpdater: Update #12: Added 'published' column to pages table
	SystemUpdater: Update #12: Populated values to 'published' for 551 pages
	SystemUpdater: Update #12: Completed!
	SystemUpdater: Update #13: Initializing update

	Modules: Detected 36 module version changes (will be applied the next time each module is loaded):
		FieldtypeFloat: 1.0.3 => 1.0.5
		InputfieldRepeater: 1.0.1 => 1.0.2
		FieldtypeURL: 1.0.0 => 1.0.1
		InputfieldAsmSelect: 1.1.4 => 1.1.9
		InputfieldCheckbox: 1.0.1 => 1.0.4
		InputfieldCheckboxes: 1.0.0 => 1.0.7
		InputfieldCKEditor: 1.2.8 => 1.5.4
		InputfieldDatetime: 1.0.3 => 1.0.5
		InputfieldFile: 1.1.5 => 1.2.4
		InputfieldFloat: 1.0.2 => 1.0.3
		InputfieldForm: 1.0.4 => 1.0.7
		InputfieldImage: 1.1.1 => 1.1.7
		InputfieldInteger: 1.0.2 => 1.0.3
		InputfieldMarkup: 1.0.1 => 1.0.2
		InputfieldPage: 1.0.4 => 1.0.6
		InputfieldPageListSelect: 1.0.0 => 1.0.1
		InputfieldPageListSelectMultiple: 1.0.1 => 1.0.2
		InputfieldPageName: 1.0.4 => 1.0.6
		InputfieldRadios: 1.0.2 => 1.0.5
		JqueryTableSorter: 2.0.3 => 2.2.1
		JqueryWireTabs: 1.0.5 => 1.0.7
		MarkupAdminDataTable: 1.0.3 => 1.0.7
		MarkupPagerNav: 1.0.3 => 1.0.4
		ProcessField: 1.0.8 => 1.1.1
		ProcessLogin: 1.0.1 => 1.0.3
		ProcessModule: 1.1.7 => 1.1.8
		ProcessPageAdd: 1.0.6 => 1.0.8
		ProcessPageEdit: 1.0.7 => 1.0.8
		ProcessPageEditImageSelect: 1.0.9 => 1.1.9
		ProcessPageEditLink: 1.0.5 => 1.0.8
		ProcessPageLister: 0.1.8 => 0.2.4
		ProcessPageTrash: 1.0.1 => 1.0.2
		ProcessPermission: 1.0.0 => 1.0.1
		ProcessRole: 1.0.1 => 1.0.3
		ProcessTemplate: 1.0.9 => 1.1.4
		ProcessUser: 1.0.4 => 1.0.7

	SystemUpdater: Update #13: Completed!

Related: [Admin area not working](https://processwire.com/talk/topic/11630-admin-area-not-working/)

**Comment by klor** [comment]
MySQL reports below error on most tables. Repairing the tables did not do the trick (the error persists).

    mysqld.exe: Table '.\mydb\pages_parents' is marked as crashed and should be repaired

**Comment by ryancramerdesign** [comment]
If you are using ProcessWire with PHP 7+ I recommend using the 3.0 version, which is compatible with PHP 7. Or if you want to use 2.7, you should be able to resolve this error by adding the following in the /wire/core/Wire.php file, as the first method in the Wire class:
`````
public function __construct() {}
`````
I don't know about the table crashed error, but would guess that perhaps it might be related to the above, or maybe your MySQL version isn't completely compatible with the PHP version.

**Comment by klor** [comment]
Fixed. Thanks Ryan.

 

 

Fra: Ryan Cramer [mailto:notifications@github.com] 
Sendt: 1. marts 2016 15:26
Til: ryancramerdesign/ProcessWire <ProcessWire@noreply.github.com>
Cc: klor <kristoffer@bohmann.dk>
Emne: Re: [ProcessWire] ProcessWire 2.7 update error: "Unknown error, please try again later" + "Deprecated: Wire has a deprecated constructor in \wire\core\Wire.php" (#1683)

 

If you are using ProcessWire with PHP 7+ I recommend using the 3.0 version, which is compatible with PHP 7. Or if you want to use 2.7, you should be able to resolve this error by adding the following in the /wire/core/Wire.php file, as the first method in the Wire class:

public function __construct() {}

I don't know about the table crashed error, but would guess that perhaps it might be related to the above, or maybe your MySQL version isn't completely compatible with the PHP version.

**Comment by ckbrewer15** [comment]
@ryancramerdesign 

Hello, I have this same error message after a new install, it loads the pages after logging in but any subsequent attempts will display that error. I tried your suggestion of adding the construct method to the Wire class with no luck. Same error using Chrome and FF.

ProcessWire 2.7.2
PHP 5.5.9-1
mysql  Ver 14.14 Distrib 5.5.47
Apache/2.4.7

![screen shot 2016-03-16 at 5 34 56 pm](https://cloud.githubusercontent.com/assets/5055017/13829462/8d9fb48a-eb9d-11e5-842c-7290fb74a56c.jpg)

Thank you.

**Comment by wanze** [comment]
@ckbrewer15 
Can you check your Apache/PHP error logs to see if there's any meaningful error message?

**Comment by mindplay-dk** [comment]
Why wasn't the constructor fix merge to 2.7?

I seem to have no other problems thus far running 2.7 on PHP 7.
