### ISSUE TITLE
cloning of pagetrees - images links in CKE not updated

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1687]
If I clone a page with subpages, the images in the cke fields of the clone still link to the images of the source page and not to the ones in the cloned assets files. (I my test case that was true for the subpages and has not been tested for the root page of the source tree)
I am pretty sure that worked before.

PW 3.08

**Comment by ryancramerdesign** [comment]
The clone process doesn't get involved in the markup of individual fields, and hasn't ever before. Overall ProcessWire generally stays out of markup (other than that runtime MarkupQA class). I'm not sure how feasible it is for the clone process to get involved in modifying HTML in textarea fields, but I'll definitely take a closer look to see if it might be something we can do.

**Comment by BitPoet** [comment]
I've wrapped a snippet of code I've been using to do just that into a [small module and put it on github](https://github.com/BitPoet/ProcessPageCloneAdaptUrls). It just hooks into Pages::cloned, iterates through all fields for ones configured with InputfieldCKEditor and rewrites /site/assets/files/$oldid/ to /site/assets/files/$newid/ inside src and href attributes using a regex.

**Comment by tbba** [comment]
Hi, this sounds very cool.Thank you, BitPoet.
I was sure this worked before in the core but I probably remember that wrong.

(Can the issue be closed? - Its marked as "feature request" and now there is an existing workaround)

**Comment by BitPoet** [comment]
You're welcome @tbba. Just a heads up that I've eliminated a rather embarrassing bug (don't ask) in my module code and got language support working.

**Comment by tbba** [comment]
Very cool!

**Comment by tbba** [comment]
Appears to be solved via a cool external plugin.
