### ISSUE TITLE
Page field: self-references in PageListSelect and PageListSelectMultiple don’t get persisted

### ISSUE THREAD

**Issue by isellsoap** [ryancramerdesign/ProcessWire#1689]
If I want to select the page I’m currently editing in a page field with the input field type PageListSelect or PageListSelectMultiple, the page selection doesn’t get persisted after saving the page (tested in 2.7.3 and 3.0.8). Is this intentional or is this a bug?

**Comment by teppokoivula** [comment]
This is often referred to as circular reference, and to be honest I can't remember anymore if it should be possible, or shouldn't. It's been discussed in various forum topics and GitHub issues from various points of view, and I can't seem to recall the current status of this.

My opinion is that circular references (or self-referencing) is an important feature, and these should be allowed.

**Comment by isellsoap** [comment]
I didn’t know that this was discussed before, interesting. 

I wonder if there’s a technical argument against this feature. From a functional point of view this feature should be definitely allowed.

**Comment by teppokoivula** [comment]
Circular reference kind of explains the technical problem involved in self-referencing: in some cases an item referencing itself (or item A referencing item B which references item A, etc.) can cause an infinite loop and bring the whole system down.

Anyway, if you look for "circular reference mitigation", you'll probably find something in the core that prevents these, and [here's a forum post where Ryan explains why this had to be done](https://processwire.com/talk/topic/5354-usergroups-module-in-development-groups-page-based-permissions/?p=51968).

**Comment by ryancramerdesign** [comment]
Circular references aren't currently reported in Page fields, so this one is intentional. I understand there may be use cases for circular references, but I've not yet found a way to reliably support them since it has the possibility to trigger an infinite load cycle. As a result, PW attempts to detect and abort circular references in order to prevent such a condition. But I'll mark this one as a feature request and will keep exploring possibilities.

**Comment by isellsoap** [comment]
I close this one as it is an edge case which I don’t use and need anymore.
