### ISSUE TITLE
Forced transform to lowercase of PageList actions strings

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#1690]
/wire/modules/Process/ProcessPageList/ProcessPageList.css
Can we please have it without "text-transform: lowercase;" in line 166?

**Comment by ryancramerdesign** [comment]
Yes, I can remove that. This really should be a matter for the admin theme rather than ProcessPageList.css

**Comment by isellsoap** [comment]
@processwired Could you please close this issue? Thank you!
