### ISSUE TITLE
PageFrontEdit.module conflicts with TemplateEngineFactory.module

### ISSUE THREAD

**Issue by dreerr** [ryancramerdesign/ProcessWire#1691]
Due to priority order it is currently not possible to make TemplateEngineFactory.module work together with PageFrontEdit.module . It is not possible to set the priority of `addHookAfter('Page::render',…)` in TemplateEngineFactory.module:77 under 100.
It would be needed to set PageFrontEdit.module:170 hooks priority above 100. This is similar to the issue [here](https://github.com/ryancramerdesign/ProcessWire/issues/1218) if I am correct.

**Comment by ryancramerdesign** [comment]
I can't see any problem with increasing the hook priority level here, I've bumped it to 102 in the latest commit.

**Comment by isellsoap** [comment]
@dreerr Could you please close this issue? Thank you!

**Comment by isellsoap** [comment]
@dreerr This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
