### ISSUE TITLE
3.0.8 > Repeater Matrix doubled child items

### ISSUE THREAD

**Issue by Jugibur** [ryancramerdesign/ProcessWire#1692]
If I set the option "Repeater item visibily in editor" to "Items always open ..." and click on a new child item, then the Repeater Matrix added always two of them. 
And – marginal but strange – there are two "moving"-icons for rearraging an child element.

![screenshot](https://cloud.githubusercontent.com/assets/271000/13092931/cd47dbb4-d502-11e5-82bc-a27462474724.png)

**Comment by ryancramerdesign** [comment]
Thanks @Jugibur I've pushed a fix for this. Though the way I was able to duplicate it was a little different than in your screenshot, so just wanted to confirm that it also fixes it on your end?

**Comment by Jugibur** [comment]
Have tested it now and both problems are gone, thanks!

**Comment by isellsoap** [comment]
@Jugibur Can you close this issue please? Thank you!
