### ISSUE TITLE
Small typo on https://processwire.com/docs/tutorials/how-to-use-url-segments/page3

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/ProcessWire#1693]
I couldn't find where to report this, so I apologize if this is the wrong place.

Anyways, I thought you would like to know.

![how to use url segments](https://cloud.githubusercontent.com/assets/40570/13111915/1fbc3002-d54e-11e5-8984-f305dad8ef2e.jpg)

**Comment by LostKobrakai** [comment]
It's fixed.
