### ISSUE TITLE
Upgrade from 2.7.2 to 3.0.8 give Class 'ModuleJS' not found

### ISSUE THREAD

**Issue by desaparecido** [ryancramerdesign/ProcessWire#1695]
As the title say , when upgrading PW from master to devns I have the following error :

> Error: Class 'ModuleJS' not found (line 3 of Z:\wamp\www\pw\wire\modules\Jquery\JqueryFancybox\JqueryFancybox.module)

**Comment by adrianbj** [comment]
Make sure you overwrite the wire folder rather than merging. PW 3.x no longer includes Fancybox - it used Magnific instead.

You may also need to Modules > Refresh.

**Comment by desaparecido** [comment]
ok solved. I was merging the folder.
