### ISSUE TITLE
PW 3.0.8 // "Repeater Matrix" // "Matrix Type" // Multilanguage // Labels are not saved

### ISSUE THREAD

**Issue by kbreynck** [ryancramerdesign/ProcessWire#1696]
The Issue: "Matrix Type" Labels are not saved in additional language(s).

Setup: I have a multilanguage setup with "de" (default) and "en" (second language).

1. Add a new "Matrix Type" to a "Repeater Matrix"
2. Edit "Name" and "Label" of the default language
3.Save (everything is fine here)
4. Edit the "Label" in the diffrent language(s) field and Save again.

! The "Label" field in the additional language is empty again.

**Comment by ryancramerdesign** [comment]
Thanks @kbreynck I have fixed the issue and posted an update in the ProFields support board.

**Comment by isellsoap** [comment]
@kbreynck Can you close this issue please? Thank you!

**Comment by kbreynck** [comment]
Thank you!
