### ISSUE TITLE
PW308: language translator loses language_id after save

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1698]
After saving a language in the language translator, the language_id parameter gets lost from the url. Therefore if you edit several languages on several tabs, language translator loads the default language on reload (save).

**Comment by ryancramerdesign** [comment]
The language_id parameter is only used to set the translation language, and from that point it's handled in the session, until it gets set to something else. As a result, ProcessLanguageTranslator would not support the context you've mentioned (several tabs translating different languages).

**Comment by rolandtoth** [comment]
I see, thanks. It seemed like a bug because on page reload I didn't notice the language change (because on other tab another translator page was open).
