### ISSUE TITLE
Notice: Trying to get property of non-object in /wire/core/Session.php on line 236

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1700]
Notice: Trying to get property of non-object in /wire/core/Session.php on line 236

found: $useFingerprint = $this->config->sessionFingerprint;
should be: $useFingerprint = $this->wire('config')->sessionFingerprint;

**Comment by ryancramerdesign** [comment]
@kixe what version of PW are you using? I'm using 3.0.x here. The `$this->config->sessionFingerprint;` is what it should be using, not the `$this->wire('config')` variation. Note the $this->config is a local property of the Session class, set by the constructor. I'm not seeing the 'property of non-object' notice here, so I think we need to look further to see why you are getting that. Maybe it's something PW version specific, or maybe Session is getting instantiated before Config somehow? (though PW's bootstrap creates the $config API var as the first thing it does).

**Comment by kixe** [comment]
The Error happened during development of an autoload module which redirect the user after detecting browser language (PW 3.0.8). You are right, obviously the session was instantiated before config was ready. Now everything is working properly an as expected. The Issue can be closed.
