### ISSUE TITLE
Typo in SessionHandlerDB (class constant 'tableName') produces Fatal Error

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1701]
Fatal error: Undefined class constant 'tableName' in wire/modules/Session/SessionHandlerDB/SessionHandlerDB.module on line 286

the defined constant is 'dbTableName' not 'tableName'

**Comment by ryancramerdesign** [comment]
Thanks @kixe I have pushed a fix for this.

**Comment by isellsoap** [comment]
@kixe Can you close this issue please? Thank you!

**Comment by kixe** [comment]
Done!
