### ISSUE TITLE
HTML tags in Warnings log

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1702]
I am seeing the following in the Setup > Logs > Warnings

```
Warning, your /site/config.php specifies file permissions that are too loose for many environments:<br /><span style='font-family:monospace'>$config->chmodFile = '<u>0777</u>';<br />$config->chmodDir = '<u>0777</u>';</span><br /><i class='fa fa-angle-right'></i> <a href='https://processwire.com/docs/security/file-permissions/' target='_blank'>Read "Securing file permissions" for more details</a><br /><small class='ui-priority-secondary'>To suppress this warning, set $config->chmodWarn = false; in your /site/config.php file.</small> (ProcessLogin)
```

This is one of my local test installs, hence the 777 and not being worried about it :)

**Comment by ryancramerdesign** [comment]
Some log entries can have HTML (like those coming from Notice::allowMarkup), though the HTML is not always important to the log. Even if not the case here, sometimes a block of HTML is an important part of the log entry, or the log entry lacks context without it. Of course, the HTML is never rendered as HTML, and logs are plain text files where HTML is not interpreted, but it is technically allowed in log entries and notices that specify Notice::allowMarkup.
