### ISSUE TITLE
Better Error-Handling when using Comments/CommentsManager-Module

### ISSUE THREAD

**Issue by NameLess--** [ryancramerdesign/ProcessWire#1706]
The current default behavior after installing "Comments" and the "CommentsManager" is that an Error occurs when trying to use "CommentsManager" if NO field with type "comment" exists. 

Even uninstalling does not work, as CommentsManager requiers Comment.php to uninstall. But this file is not loaded until a comment-field exists. Vice versa the Comment-module can't be uninstalled because CommentsManager requires it. 

It would be better to a) default load the Comment-Module even if no field exists or maybe better b) catch the error and give an warning that a field with comment-type is needed to use it. 
If using b) it would be great to also find a solution for uninstalling without the need of a field. 

More information here: https://processwire.com/talk/topic/12194-comments-manager-module-error-usinguninstall-comments-not-working-272
and also here: https://processwire.com/talk/topic/11603-uninstall-processcommentsmodule-fails/

**Comment by ryancramerdesign** [comment]
Thanks @NameLess-- I've pushed a fix for this issue.

**Comment by isellsoap** [comment]
@NameLess-- Can you close this issue please? Thank you!

**Comment by NameLess--** [comment]
Of course ;)
