### ISSUE TITLE
PW 3.0.8 // Repeater Matrix // Default "view" settings of image fields

### ISSUE THREAD

**Issue by kbreynck** [ryancramerdesign/ProcessWire#1707]
Images in repeater_matrix types are always displayed in grid view, even though its default view is set to rows.
You are only able to toggle the view after saving a new image.

**Comment by Jugibur** [comment]
Doesn't help you, but in my installation this works as expected (set to a single image, could this be the reason?). Have you tried to override the settings of images inside the Repeater Matrix?

**Comment by ryancramerdesign** [comment]
Thanks @kbreynck I have pushed a fix for this issue.

**Comment by isellsoap** [comment]
@kbreynck Can you close this issue please? Thank you!

**Comment by kbreynck** [comment]
Thank you!
