### ISSUE TITLE
Make modal close button larger

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1710]
something along:

`button .fa-times {font-size: 20px !important}`

**Comment by matjazpotocnik** [comment]
I used AdminCustomFiles module to "fix" that, so this issues could be marked fixed or closed.

**Comment by yckart** [comment]
I like it small and thin ;) and <kbd>ESC</kbd> is even faster to reach than any ui-element.

**Comment by matjazpotocnik** [comment]
I like it B&B - big and bold :-) Esc is not working for me. Am I missing something?

**Comment by yckart** [comment]
@matjazpotocnik This is an option (`closeOnEscape=true`) that you could set in your `config.php`. It's just not enabled per default. https://github.com/ryancramerdesign/ProcessWire/blob/105fd1fa90f30f50670d95526e71fc4ad4bba892/wire/config.php#L918

**Comment by matjazpotocnik** [comment]
I already have this in /site/config.php

```
$config->modals = array(
	'large' => "15,15,30,30,draggable=false,resizable=true,hide=250,show=100", 
	'medium' => "50,49,100,100", 
	'small' => "100,100,200,200",
	'full' => "0,0,0,0",
	'closeOnEscape' => true,
);
```
and it is not working (for me)...

**Comment by yckart** [comment]
@matjazpotocnik You have to set it for each entry, like so:

```
$config->modals = array(
    'large' => "15,15,30,30,draggable=false,resizable=true,hide=250,show=100,closeOnEscape=true", 
    'medium' => "50,49,100,100,closeOnEscape=true", 
    'small' => "100,100,200,200,closeOnEscape=true",
    'full' => "0,0,0,0,closeOnEscape=true"
);
```

**Comment by matjazpotocnik** [comment]
Yee, its working, thx!
