### ISSUE TITLE
Notice for array to string conversion line 555 Inputfield.php

### ISSUE THREAD

**Issue by jtborger** [ryancramerdesign/ProcessWire#1713]
After submitting a form with formfields rendered via module->get("InputfieldText"), I got this Notice of array to string conversion on line 555 of Inputfield.php.

`if(i!strlen("$value") && (!$value = $this->get($attr))) continue; `
It typecastst it value to a string.
I displayed the contents of $value and it contained also error messages in array form.
Have not dived deep into all of this but:
`if(is_string($value) && !strlen("$value") && (!$value = $this->get($attr))) continue;`

fixes it.

**Comment by ryancramerdesign** [comment]
Thanks @jtborger I have pushed a fix for this issue.

**Comment by isellsoap** [comment]
@jtborger Can you close this issue please? Thank you!

**Comment by jtborger** [comment]
Sure Sorry Im quite new to github.
Will do
