### ISSUE TITLE
Repeaters with title, body fields note saving

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1715]
I added title and body fields to repeater. When i edit page with repeater, after save the page repeater fields are empty. If i add some custom created fields to repeater it working for custom fields.

Using latest devns version with languages support body and title fields have language support also.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate the issue here. Most of my repeaters already use multi-language title and body fields. I tested various scenarios here, but all save normally. So there must be some other factor that we need to look at. Maybe a Modules > Refresh is needed, or maybe there is some other 3rd party module interfering. Look for errors in your JS console, as well as errors in your Setup > Logs > errors log. Btw, both "title" and "body" are themselves custom fields, so there's no technical difference between them and any other custom field.

**Comment by trk** [comment]
What i made for test and check problem :

Modules > Refresh
Modules > Clear compiled files
Setup > Fields > Title > Actions > Check Field Data
Setup > Fields > Body > Actions > Check Field Data
Setup > Fields > Repeater Field > Actions > Check Field Data
Setup > Logs there is no error
Firebug > Console There is no error on console

Result is same on my side

**Comment by trk** [comment]
If i directly edit repeater item from :
Admin > Repeaters > repeater_field > repeater_page > repeater_item

Its saving the data. If i edit this data from repeater inside page its not saving modified data for body field.

Other fields saving inside same repeater (image, options)

**Comment by trk** [comment]
I found the issue, if **Autojoin** option selected from field settings. Fields inside repeaters not saving.

**Comment by ryancramerdesign** [comment]
Glad you found it. The autojoin option is one that may not work everywhere, so unless dealing with just a simple text field or something, it has to be used with caution. In the case of repeaters, we will probably just want to disable the autojoin option entirely since it seems to be incompatible (plus, it wouldn't provide any benefit for repeaters).

**Comment by trk** [comment]
If we have auto join option for fields (title, body, etc...), if we want to use these fields with repeaters need to remove (unselect) this option from field settings.
or
We won't use these fields (title, body, etc...), we will create new fields (title_repeater, body_repeater, etc...) without auto join option for repeaters.

**Comment by ryancramerdesign** [comment]
It is fine to use autojoin for the fields in a repeater (title, body,
etc.), just not for the repeater itself. Meaning, when editing a repeater
field in Setup > Fields > my_repeater, don't use the autojoin option on the
Advanced tab. For the other fields that you might be using in the repeater,
it should not matter if autojoin is used or not.

Though I've found there to be little benefit to autojoin, and the only
fields I usually use it on are 'title' and and sometimes a 'summary' field.
Autojoin may reduce queries, but seems to have no actual effect on
performance. Basically, we've often found the JOIN operations to perform at
about the same speed as a separate query. As a result, you probably
shouldn't bother with using autojoin except for perhaps the title field
(which is already autojoin by default).

**Comment by trk** [comment]
Repeater field not have auto join option in field settings (there is no option available). Fields inside repeater field have auto join option.

**Comment by ryancramerdesign** [comment]
I'm not seeing any issue here with fields having autojoin within a repeater. They are saving normally for me at least, though I'm testing in the latest PW 3.x core version. Autojoin of fields really shouldn't matter to a repeater, as the page loading/saving is still handled by the core Pages class, not the repeater. The only potential issue I can see is if autojoin is enabled for the my_repeater field itself. What version of PW are you seeing the issue in, and are there any 3rd party modules installed?

**Comment by trk** [comment]
I am using ProcessWire 3.0.10 devns commit number 1674

As you see i don't have an auto join option in repeater field settings
![ekran resmi 2016-03-05 13 05 12](https://cloud.githubusercontent.com/assets/455983/13547232/f307748a-e2d2-11e5-9242-85a6c85f84fc.png)

If my body field have this auto join option

![ekran resmi 2016-03-05 13 06 38](https://cloud.githubusercontent.com/assets/455983/13547237/2cffb3a0-e2d3-11e5-829c-e68c0a4822fb.png)

When i save page body field inside repeater field not saving data.

I have 3rd party modules installed, i removed which modules have hook result is same.

Installed Modules :

- AIOM+ (All In One Minify) for CSS, LESS, JS and HTML
- FieldtypeFontIconPicker
- Map Marker
- Matrix
- Custom Upload Names
- Google Analytics
- Tracy Debugger
- WireMailPHPMailer (I wrote this module and not added it to module directory yet)

**Comment by teppokoivula** [comment]
For the record, I can't seem to reproduce this issue either. Tested with 3.0.6 and 3.0.10.

**Comment by somatonic** [comment]
Do you happen to use inputfield dependencies in the repeater? Because that does not work with repeaters out of the box and has the effect to not save fields.

**Comment by trk** [comment]
Not have dependencies in the repeaters. My repeater fields are image, textarea, options. i created a fresh installation and tested repeaters with body and title fields, its working. I think somethings happen when i imported fields by using fields import / export tool. When i updated new repeater version this field asked me to repair body and some other used fields. After do that i have problem with repeaters for existing sites.

Now i started a new project i will create same repeater field and same fields inside repeater, will see what will happen. I will let you know what result.

**Comment by larrybotha** [comment]
I've experienced the same issue with 2.7.2 and autojoined `title` and `summary` fields in repeaters, no field dependencies.

It's quite possible that dropping and importing dbs multiple times has affected something - we automate dropping and importing with Gulp, and sometimes imports don't go completely smoothly.

Anyways, disabling autojoin on the affected fields solved the repeater fields not saving for me - I'm mostly adding Google index juice here :)
