### ISSUE TITLE
Ajax-loaded tabs cause interruptions and weird jumping

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1717]
I'm currently experiencing this on 2.7.2, so not sure if the 3.x branch behaves differently, but:

If I click the children tab and then navigate elsewhere, when the AJAX load is finished, the children tab gets focus and whatever else I was doing is interrupted. This is particularly annoying if the children tab takes a while to load.. which also happens to be when AJAX loading is most helpful.

Not sure if this is by design, but it's definitely not what I'd expect. AJAX loading is great, but it should happen in the background, and it most definitely shouldn't interrupt other tasks :)

**Comment by ryancramerdesign** [comment]
@teppokoivula I agree, I've just pushed a fix for this issue.

**Comment by teppokoivula** [comment]
@ryancramerdesign Thanks. This also seems to have fixed another issue I've been having with this feature, i.e. not having a proper load indicator.

This does lead to another question, though: in my case the problem is specifically related to 2.7.2. Are you planning to migrate some of the fixes applied to 3.x to 2.x too? If not, I can always backport this locally, but I'd like to avoid doing that for as long as possible.

**Comment by teppokoivula** [comment]
Closing this issue. This problem is fixed on 2.8, which in turn should be relatively painless to upgrade from 2.7.2.
