### ISSUE TITLE
Session: Changed: Body although nothing changed

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1718]
![image](https://cloud.githubusercontent.com/assets/370148/13530832/a36e7874-e223-11e5-8906-eb0a06481517.png)

I get this message on every save, although nothing has changed. I tracked it down to HTML Purifier being disabled. Once I enable it, it doesn't show anymore.

This is confusing.

**Comment by ryancramerdesign** [comment]
Thanks @somatonic I've tracked down the issue and committed a fix. It turns out to carriage return vs linefeed issue. CKEditor apparently inserts carriage returns which Purifier removes.
