### ISSUE TITLE
Notice when installing Imagick Image Sizer

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1720]
![screen shot 2016-03-04 at 12 12 37 pm](https://cloud.githubusercontent.com/assets/871211/13539044/b073bffa-e202-11e5-83c7-05569dfed08a.png)

**Comment by adrianbj** [comment]
It seems to be only with this module - no problem installing other ones.

**Comment by adrianbj** [comment]
Only happens when you don't have Imagick available. If you do, then the notice isn't thrown. Still I think there should be a check for this to prevent it.

**Comment by adrianbj** [comment]
Related thought - what would happen when migrating a site from a server that has iMagick to one that doesn't - the modules table in the db will have an entry for it and so it will be installed. Is there a check that will uninstall it if it's not available? or doesn't it matter because of the fallback to GD anyway?

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks - seems to be fine now!
