### ISSUE TITLE
Cannot get the front-end editing to work on a fresh 3.0.10 install AND solution

### ISSUE THREAD

**Issue by krisj** [ryancramerdesign/ProcessWire#1723]
So I did a fresh install from git of the latest 3.0.10

Using the multi-language profile tried to set up the front end editing. Noticed CKEditor plugin load errors and changes would not save with a "no changes to save" error. (obviously CKEditor wasn't loading to begin with)

To solve I had to copy the 3 plugins: pwlink, pwimage and sourcedialog from

/wire/modules/Inputfield/InputfieldCKEditor/plugins

to

/wire/modules/Inputfield/InputfieldCKEditor/ckeditor-4.5.5/plugins

after that changes save as expected. #

**Comment by ryancramerdesign** [comment]
Thanks @krisj I've pushed a fix for the issue. It wasn't actually an issue of files in the wrong location, but rather a JS error occurring in a dynamically loaded script, which prevented the CKE plugins from being loaded properly.

**Comment by krisj** [comment]
Great and thanks for the lightning fast fix!
