### ISSUE TITLE
Reliable releases tags

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1724]
The provided master version on https://processwire.com/ is `2.7.2`, [here at github](https://github.com/ryancramerdesign/ProcessWire/releases) `2.7.1`. Would be nice if we could rely on them ;)

Also tags for `dev` and `devns` could be helpful.

**Comment by adrianbj** [comment]
Agreed - I have never really like the approach of having the release tag show only the last version, not the current one. It seems to go against the convention used in other projects.

**Comment by ryancramerdesign** [comment]
See here for more info on PW core and release tags: http://processwire.com/blog/posts/composer-google-calendars-and-processwire/#git-tags-and-packagist
