### ISSUE TITLE
PageAutocomplete incorrect default options

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1725]
There are some fields that have incorrect options per default (in relation to their description or title). I can unfortunately just remember those for `PageAutocomplete`

- **Input**
  - **Label field**
    - `Custom format (multiple fields)...` should be `title (default)`  
      (Note: *Select "Custom format" if you want to specify multiple fields, or other fields you do not see above.*)

  - **Autocomplete Advanced Options**
    - **Autocomplete search operator**
      - `%=` should be `*=`  
      (Note: *If you aren't sure what you want here, leave it set at the default: *=*)

There are a few more, which are mostly just inconsistent with their *recommend*ation (rational or not, depends on the case.) I've just forgotten to write them down :(

**Comment by adrianbj** [comment]
Duplicate of: https://github.com/ryancramerdesign/ProcessWire/issues/1018 ?

**Comment by yckart** [comment]
@adrianbj Ough! I'm tired, haven't slept. Go to bed now :sleeping:
