### ISSUE TITLE
Conditional autoload function always results in module autoloading in PW 3

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1726]
This could affect many modules!!

```
'autoload' => function() {
     return false;
 }
```
results in the module autoloading. As soon as I downgrade to PW 2.7.3, it doesn't load, as expected. I am refreshing the modules page with each testing change.

Obviously, my actual function had some conditional logic in it, but I was simplifying for testing purposes.

Selector conditions still work as expected, eg:
```
'autoload' => 'template=admin'
```

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this. It was working for 3.x modules but not for 2.x modules, due to a namespace detection issue.

**Comment by adrianbj** [comment]
Thanks Ryan - I was sure I already commented on this to say it's working and closed it - oh well :)
