### ISSUE TITLE
Latest 3.0.10 changes to Pagefile::install method breaks adding new files

### ISSUE THREAD

**Issue by mikelexp** [ryancramerdesign/ProcessWire#1728]
I had to revert this commit in order to stop it from constantly throwing exceptions when I try to add a file/image using $page->images->add(filepath) because WireHttp fails to download a local file path, it always wants you to pass a valid URL as a parameter, not a file path.

I reverted this commit and it's working fine again.

https://github.com/ryancramerdesign/ProcessWire/commit/582e6e17808116decb46d3faa0d65813561b3e02

**Comment by ryancramerdesign** [comment]
Thanks @mikelexp I've pushed a fix for this.

**Comment by mikelexp** [comment]
Thank you for the quick fix Ryan!
