### ISSUE TITLE
PW 3.0.8 | FileCompiler filetypes

### ISSUE THREAD

**Issue by FerdiAgrio** [ryancramerdesign/ProcessWire#1735]
Hi there!

After completing a new module which uses TwitterOAuth class from Abraham Williams (https://twitteroauth.com/), the PW FileCompiler leaves the file cacert.pem behind when compiling is finished. This results in an incomplete cached folder and breaks PW.
`ProcessWire: ProcessModule: error setting certificate verify locations: CAfile: /Users/ferdi/Sites/www_domains/pw_3.0.8/htdocs/site/assets/cache/FileCompiler/site/modules/PublishToTwitter/TwitterOAuth/Abraham/TwitterOAuth/cacert.pem CApath: none`

After placing the .pem file manually in this folder, it works fine again.
Can I solve this by non-caching this (part of the) module using a variable/setting?
Thanks in advance.

(module will be posted soon @ modules.processwire.com)

**Comment by ryancramerdesign** [comment]
What is the line that includes or loads that cacert.pem file? I'm guessing
it's something like `file_get_contents(__DIR__ . '/cacert.pem');`? If
that's the case, try changing it to:
`file_get_contents($this->wire('config')->paths->PublishToTwitter .
'TwitterOAuth/Abraham/TwitterOAuth/cacert.pem');`

Another alternative is that you can force FileCompiler to skip any file
just by placing this text anywhere in the file `FileCompiler=0`. For
instance, you might place that in a PHP comment at the top, or something
like that.

Lastly, FileCompiler won't attempt to compile modules that declare a
namespace at the top. So if you do a `namespace ProcessWire;` at the top of
your module, or some other namespace, then FileCompiler won't attempt to
compile it at all. The only issue with that is that it would then make your
module PW 3.x exclusive.

**Comment by FerdiAgrio** [comment]
Unfortunately option one and two aren't possible since it 1) is a external library and will cause problems when updating it (rather not), 2) results in an error where PW cannot find 'WireData' (which the module extends). 
So I altered the module by calling 'namespace ProcessWire;' at the top and will keep a different version for < v3 and v3+ which works for our company (added the requirement in getModuleInfo).

Many thanks for thinking along!
