### ISSUE TITLE
PW 3.0.10 — InputfieldImageListToggle double icon

### ISSUE THREAD

**Issue by fijha** [ryancramerdesign/ProcessWire#1736]
![inputfieldimagelisttoggle](https://cloud.githubusercontent.com/assets/17672049/13619245/4c4a730a-e588-11e5-8d3f-75a3318e474c.png)

When I set image field visibility to "**Closed + Load only when opened (AJAX) †**" the `InputfieldImageListToggle` icon is doubled on ajax load

— the icon is already there, so no need to insert it again on ajax load…

`<a href="#" class="InputfieldImageListToggle HideIfEmpty"><i class="fa fa-th"></i></a>`

**Comment by ryancramerdesign** [comment]
Thanks @fijha I've pushed a fix for this issue.

**Comment by isellsoap** [comment]
@fijha This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
