### ISSUE TITLE
PW 3.0.10 - Strange behaviour with the use include

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1739]
In my HTML I have a <p> tag with the word include inside. However when output to the browser the word include is replaced with include(\ProcessWire\wire('files')->compile(a/home/thelandtoforget1/public_html/site/templates/ny logos,array('includes'=>true,'namespace'=>true,'modules'=>true))

The full sentence is "include any logos".

**Comment by adrianbj** [comment]
I think this might be related: https://processwire.com/talk/topic/12472-upgrade-3010-trouble/?p=115417

**Comment by gingebaker** [comment]
I had some similar problems in php comments. Ryan made a fix for that...
#1745

**Comment by ryancramerdesign** [comment]
@TomS- can you confirm that the latest fix also resolves the issue you were seeing there? Thanks.

**Comment by TomS-** [comment]
@ryancramerdesign sorry for the delay, seems to be fixed. Thanks
