### ISSUE TITLE
FormBuilder: Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1740]
I'm using PW 2.7.3 and FormBuilder 0.2.5e.

I have a form which I'm embedding using method A (iframe based).  I'm using the Bootstrap output framework.  No other special settings or file modifications.

It results in the following JS error:

`Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher`

**Comment by zgjonbalaj** [comment]
Had the same issue try this https://processwire.com/talk/topic/11979-bootstraps-javascript-requires-jquery-version-191-or-higher/

**Comment by gingebaker** [comment]
This solves the Problem also for me...
