### ISSUE TITLE
References to $config->compat2x still exist

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1741]
eg. https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Modules.php#L1324

I am pretty sure that mode no longer exists.

**Comment by ryancramerdesign** [comment]
It still exists, but will be removed at some point. Currently I'm finding it convenient for my IDE and modules in the root namespace, as it still enables IDE tips and autocompletion and such to work.
