### ISSUE TITLE
PW 3.0.10: FileCompiler Error if string "include" in PHP comment

### ISSUE THREAD

**Issue by gingebaker** [ryancramerdesign/ProcessWire#1745]
Hi 
Just found following problem when working in 3.0.10.
I was uploading a Module. After installing I got following error...

**Parse Error: syntax error, unexpected 'var' (T_VAR)** ...

The Line of the Error is only a PHP Comment Section on the top of the original File.
I saw nothing special on the original file so i checked the compiled Module File wich looked like this...

```php
/**
 * ProcessWire Addons Module
 *
 * Adds some hooks ...Also  include(\ProcessWire\wire('files')->compile(*/var/[path-to-my-module]/site/modules/[module-dir]/ some template helpers,array('includes'=>true,'namespace'=>true,'modules'=>false)))
 *
 * ....
 * ....
```
The Original file looks like this:

```php
/**
 * ProcessWire Addons Module
 *
 * Adds some hooks ...Also include
 * some template helpers
 *
 * ProcessWire
 *
````

I think this problem comes up if you have the String "include" at the end of a line in a php comment.
I also tested it with include_once, require_once. Same error...

Perhaps the problem is somewhere in the regex in FileCompiler starting around here:
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/FileCompiler.php#L287

Can you confirm this problem?
Don´t know why the PHP Error relates to the orignal file an not to the file in assets/cache... where the error happens?

**Comment by ryancramerdesign** [comment]
Thanks @gingebaker I've pushed a fix for this, can you confirm it also fixes it there?

**Comment by ryancramerdesign** [comment]
Note: you'll need to either make a change to the original file or clear your file compiler cache in order for it to re-compile it.

**Comment by gingebaker** [comment]
Hi @ryancramerdesign 
Yes it fixes the issue... Thanks!
