### ISSUE TITLE
Collapse entire site tree

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1749]
As @adrianbj already [commented](http://processwire.com/blog/posts/processwire-3.0.8-brings-smarter-faster-page-tree/#Comment12392), it would be nice if we could close the entire site tree again.

Adrian suggested <kbd>double click</kbd>, I would <kbd>alt</kbd> + <kbd>click</kbd> (as in *Finder* on OS X and *Sublime Text*).

**Comment by ryancramerdesign** [comment]
Thanks, this one is now built in to 3.0.13, by just clicking the "Home" link in the tree.
