### ISSUE TITLE
FileCompiler generates incorrect output if type hinting TemplateFile

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1750]
If a type declaration specifies `TemplateFile` as a certain parameter type, the `FileCompiler` generates incorrect output. This occurs only if there's whitespace (`\9` and `\20` — but not `\a` and `\d`) between the type and variable name, also `TemplateFile$var` would result in correct output.

```php
function fooIsNotEqualToBar(TemplateFile $var) {

}
```

```php
function fooIsNotEqualToBar( TemplateFile(\ProcessWire\wire('files')->compile($var) {,array('includes'=>true,'namespace'=>true,'modules'=>true)))

}
```

Tested with all classes specified in `$corePreloads`.

Could be (probably) solved by ignoring whitespace in [`$re`](https://github.com/ryancramerdesign/ProcessWire/blob/5315be18a13374bd0b0730c9100d532d20fea5be/wire/core/FileCompiler.php#L365) in `FileCompiler`, but have no time to test it further.

**Comment by ryancramerdesign** [comment]
Thanks @yckart I've pushed a fix for this one.
