### ISSUE TITLE
PW 3.0.11 FileCompiler wireRenderFile -> require_once(): Failed

### ISSUE THREAD

**Issue by dfile-de** [ryancramerdesign/ProcessWire#1756]
Hello,

i have a maintemplate (controler), here i load (echo) a view with wireRenderFile('_views/mainview.php',$data);

in _views/mainview.php i include the header.php

main.php
_views
...| header.php
...| mainview.php

main.php:
```
$data['title']=$page->title;
$data['content']=$page->content;
echo wireRenderFile('_views/mainview.php',$data);
```
_views/mainview.php:
```
<?php
//don't work anymore:
require_once('header.php');
?>
<!-- ########################################### -->
<div class="container">
		<h1 class="headline"><?=$title ?></h1>
		<div class="content-article"><?=$content ?></div>
</div><!-- container -->
```
Compile Error: require_once(): Failed opening required '_views/header.php' 
FileCompiler add '_views' to the header.php path?

with $config->templateCompile = false - everything works fine.

**Comment by teppokoivula** [comment]
Not sure if this is actually expected behaviour or a bug, but it has been suggested that some paths should be prefixed with $config->paths->templates. At least that should fix the issue for now.

**Comment by dfile-de** [comment]
Hello Teppo,
you're right.
require_once($config->paths->templates.'_views/header.php');
this works, prepend the path with a dot don't work.
thank you!
