### ISSUE TITLE
Strip trailing whitespace from all files

### ISSUE THREAD

**Issue by fijha** [ryancramerdesign/ProcessWire#1757]
There is unnecessary trailing whitespace in almost every file… Needs to be cleaned up…

**Comment by ryancramerdesign** [comment]
Whitespace at the end of lines and/or between lines is inconsequential per our style guide. It's the whitespace at the beginning of lines that we care about. See here: http://processwire.com/api/coding-style-guide/#2.3-indentation-tabs-spaces

**Comment by fijha** [comment]
Hi Ryan, sorry, I was thinking about unnecessary **whitespace** at the and of lines (after semicolon etc.) which is just noise… You can see in the screenshot that it looks like there are a lot of a changes made, but just spaces was removed… also file size can be a little smaller…

![screen shot 2016-04-05 at 23 42 16](https://cloud.githubusercontent.com/assets/17672049/14299032/85bdc0d6-fb88-11e5-9af7-60a2597d7c9d.png)

… or there is added whitespace (https://github.com/ryancramerdesign/ProcessWire/commit/1ea08e6db29909a4b8129b7c48e55f87389cd55b)

![screen shot 2016-04-05 at 23 58 10](https://cloud.githubusercontent.com/assets/17672049/14299375/5ba59286-fb8a-11e5-9cf2-092b6220332c.png)

I use TextWrangler on a mac which has an option "Strip trailing whitespace" before save… It would be nice if git has that option too, after commit, or just making sure trailing whitespace was removed before commit so only real useful changes will be committed…

**Comment by teppokoivula** [comment]
While I agree that consistency is a good thing, even when it comes to small things, I can't say that I see much real value in this. Hopefully I don't sound too rude, but in my opinion going through all files just to remove trailing whitespace would be micro-optimization at best, and for the most part just waste of time.

Additionally I think you might've missed the part of the ProcessWire coding style guide Ryan was pointing to, as it clearly states that whitespace at the end of lines is perfectly fine:

> Additional whitespace MAY be used between or at the end of lines (whitespace is disregarded in diffs).

If it's GitHub diff you're worried about, try appending "?w=1" at the end of the URL and it won't display space changes anymore. If you're using git client locally, you can add the -w flag to get the same result there.

**Comment by fijha** [comment]
Thanks @teppokoivula, I'm new to git and didn't know about that option… I still can't see the point of having whitespace at the end of lines, but as you mentioned, is just micro-optimization… not a big deal… It wouldn't be hard to clean that up… even trough some PHP script (`rtrim()` on every line)… I just think it would be nice :), but of course it is not that important.

**Comment by ryancramerdesign** [comment]
Admittedly I find a space at the end of lines helpful in my editing
environment (which is either VIM or PhpStorm running in VIM mode). Though
I'm not suggesting that anyone adopt trailing whitespace as a standard
(which would be silly). But rtrim()'ing lines is just one of those things
that doesn't seem worthwhile at this point in time, especially when it's
actually kind of handy (for me anyway). We've got better things to focus
time on, for now at least. :) I know there are also projects that desire to
maintain no whitespace at the end of lines, which I think is primarily for
the purpose of diffs that don't ignore whitespace. So I understand where
you are coming from .The reasons are of course understandable, but so far
those don't translate to PW. If at some point it surfaces as a
consequential issue we'll definitely reconsider it though.
