### ISSUE TITLE
3.0.x devns $pages->touch($page) throwing error (typo)

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1763]
Just tried out new touch() method and gave it a single page like
`$pages->touch($page)`
but it's saying the following
```Notice: Undefined variable: page in /wire/core/PagesEditor.php on line 1119```
I'm on 3.0.9 guess you added some line breaks later on..

while this works fine
`$pages->touch(array($page->id));`
so page is of course valid..

aha, found it [L1124](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/PagesEditor.php#L1124) should read `$pages->id`

Nice feature by the way!

**Comment by ryancramerdesign** [comment]
Thanks @CanRau good find! I've pushed the fix for that.

**Comment by isellsoap** [comment]
@CanRau This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Comment by CanRau** [comment]
uh thanks for closing @isellsoap forgot to do it myself
