### ISSUE TITLE
Mysql Error trying to trash multilanguage page from page tree.

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1768]
Tried to trash a multilanguage page from PageTree Action button:
http://example.org/admin/page/?action=trash&id=1995

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test-7' for key 'name1030_parent_id'

Language specific name should also be unique when moved to trash.

**Comment by ryancramerdesign** [comment]
Thanks @kixe – good find! I've pushed a fix for this one.
