### ISSUE TITLE
Commit #1700 update errors : Trying to get property of non-object and Cannot modify header information

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1770]
After update from version **2.5.11 -> 3.0.13 (didn't get error) -> 3.0.13 commit 1700 (i got error)** started to get errors, if i comment this line **/...../..../...../........./wire/core/Pagefile.php on line 206** like everything working.

```php
Notice: Trying to get property of non-object in /...../..../...../........./wire/core/Pagefile.php on line 206

Notice: Trying to get property of non-object in /...../..../...../........./wire/core/Pagefile.php on line 206

Notice: Trying to get property of non-object in /...../..../...../........./wire/core/Pagefile.php on line 206

Notice: Trying to get property of non-object in /...../..../...../........./wire/core/Pagefile.php on line 206

Warning: Cannot modify header information - headers already sent by (output started at /...../..../...../........./wire/core/Pagefile.php:206) in /...../..../...../........./wire/modules/Process/ProcessPageView.module on line 142

Warning: Cannot modify header information - headers already sent by (output started at /...../..../...../........./wire/core/Pagefile.php:206) in /...../..../...../........./wire/core/admin.php on line 16

Warning: Cannot modify header information - headers already sent by (output started at /...../..../...../........./wire/core/Pagefile.php:206) in /...../..../...../........./wire/core/Session.php on line 662

Warning: Cannot modify header information - headers already sent by (output started at /...../..../...../........./wire/core/Pagefile.php:206) in /...../..../...../........./wire/core/Session.php on line 663
```

**Comment by ryancramerdesign** [comment]
I can't duplicate this one yet. Line 206 is this:
`````
$language = $this->wire('user')->language; 
`````
My best guess is that you've got some module attempting to access files from a page before the API is ready? I would try to track down the source, because that's not a line you want to comment out unless you don't need multi-language support.

**Comment by trk** [comment]
I have some other errors and more :)

What i did, downgraded to older version 2.7.2 now its look like everything ok. After everything done i will try to update latest 3.x.x version again.

For the moment need to make some changes...

**Comment by trk** [comment]
With version 2.7.2 i don't have this issue. If i want to update to latest 3.x.x i have this error again. I have same modules with another pw website (running 3.x.x version) there no error.

This website not have multilingual support only one language have and i didn't install multilingual modules.

As you see in my error **Notice: Trying to get property of non-object** if we don't have multi language support why need to check user language ?

If i print **$languages** count result, result is : 0. What i made inside this else :

```php
// no JSON values so assume regular language description
$languages = $this->wire('languages');
$language = (count($languages) > 0) ? $this->wire('user')->language : null;

if($languages && !is_null($language) && !$noLang && !$language->isDefault()) {
	parent::set("description$language", $value);
} else {
	parent::set("description", $value);
}
```
With these changes, my error gone.
