### ISSUE TITLE
Module select no more visible if there are multiple modules of the same type

### ISSUE THREAD

**Issue by juergenweb** [ryancramerdesign/ProcessWire#1771]
The feature to use multiple instances of a module and select the one to use introduced in this article [https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-copies-of-the-same-module](https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-copies-of-the-same-module) doesnt work in PW. 3.0.13 (or maybe in lower versions).

See these forum post: [https://processwire.com/talk/topic/12963-does-copying-of-modules-not-working-in-pw3/?p=117592](https://processwire.com/talk/topic/12963-does-copying-of-modules-not-working-in-pw3/?p=117592)

Best regards Jürgen

**Comment by kixe** [comment]
you need to edit your link targets in your comment ...

**Comment by juergenweb** [comment]
I have corrected it.

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this issue.

**Comment by juergenweb** [comment]
Perfect!
