### ISSUE TITLE
Multisite not working

### ISSUE THREAD

**Issue by eresik** [ryancramerdesign/ProcessWire#1773]
Multisite not working

Need at
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/ProcessWire.php#L640
change
```
$hostConfig = function_exists("ProcessWireHostSiteConfig") ? ProcessWireHostSiteConfig() : array();
```
to
```
$hostConfig = function_exists("\ProcessWire\ProcessWireHostSiteConfig") ? ProcessWireHostSiteConfig() : array();
```

**Comment by ryancramerdesign** [comment]
Thanks @eresik I've pushed the fix for this. I've updated it to detect either root namespace file or ProcessWire namespace file, as folks upgrading from PW2 to PW3 won't have a namespace in their index.config.php file.

**Comment by isellsoap** [comment]
@eresik This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
