### ISSUE TITLE
markupValue in inputfield context

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1781]
It would be nice to have a markupValue() function in the Inputfield context as well. It would make outputting FormBuilder fields on the frontend quite a bit easier and userfriendly (e.g a nice date instead of a timestamp).

**Comment by ryancramerdesign** [comment]
Inputfields use a renderValue() method instead, which depending on the Inputfield may or may not involve markup. So the purpose is a little different, but it may provide what you are looking for.
