### ISSUE TITLE
PW 3.0.15: 2 Repeater in one template don't work

### ISSUE THREAD

**Issue by beatep** [ryancramerdesign/ProcessWire#1788]
I have 2 different repeaters in my template. As I had only one, it worked, but as I added a second one, the first on (below the other one) doesn't work any more, the entries don't expand on click and I can't add a new entry, in both repeaters. I don't know it it is only in 3.0.15, as I didn't had this case before. The firebug console is empty.

The bug must be there for a longer time, switching back to 3.0.13 didn't solve the problem....

**Comment by beatep** [comment]
I tested it in version 2.7.0, there's everything ok. I guess the major changes in version 3.0.5 concerning the repeater are the problem...

**Comment by beatep** [comment]
I just tested 3.0.17 and it seems to be fixed?

**Comment by ryancramerdesign** [comment]
Hi @beatep I'm not aware of any fixes particular to this, but there have been a lot of repeater upgrades on the 3.x devns branch, so perhaps we fixed it without realizing it. I'm glad to hear it seems to be fixed though! Please let me know if you find it turns up again.

**Comment by beatep** [comment]
Yes, indeed I didn't have any problems with the latest releases, so I consider this ticket to be closed.
