### ISSUE TITLE
Repeater field in multi-language site, it shown on default language only

### ISSUE THREAD

**Issue by adrianmak** [ryancramerdesign/ProcessWire#1790]
My site has three languages setup, default (chinese traditional), chs (chinese simplified) and eng (English)

The repeater field has three text (not multi-language) vlaue, product_id. product_price and product_quantity,
which will attach to the order template

The order will not create at the back-end ui but when a online payment (paypal) made success, my site will create an order thru api.

I found that I could see the order item in default language, where order item could not see in chs and eng front-end 
Order template
![baidushurufa_2016-4-24_6-16-54](https://cloud.githubusercontent.com/assets/1168716/14764261/2657bc36-09e4-11e6-93a9-fe9f276733ee.png)
order_items repeater field
![baidushurufa_2016-4-23_14-26-6](https://cloud.githubusercontent.com/assets/1168716/14764263/417a66f8-09e4-11e6-98f4-14a329db87c5.png)
![baidushurufa_2016-4-23_14-26-36](https://cloud.githubusercontent.com/assets/1168716/14764299/737ac782-09e5-11e6-88fc-d6091d2f051b.png)

This is the code snippet to create an order 
```
// Add a customer order in database
$orders = $pages->get(1152);
$p = new Page();
$orderByUser = $user;
$p->template = "order";
$p->parent = $orders;
$counter_name = $order_number_prefix . date('Y');
$number = $this->modules->get('DatabaseCounters')->next($counter_name, 1, 5000);
$ordernumber = $counter_name . '-' . sprintf("%06u", $number);
$p->of(false);
$def = $wire->languages->get("default");
$chs = $wire->languages->get("chs");
$eng = $wire->languages->get("eng");
$p->title->setLanguageValue($def, $ordernumber);
$p->title->setLanguageValue($chs, $ordernumber);
$p->title->setLanguageValue($eng, $ordernumber);
$p->order_number = $ordernumber;
$p->member = $orderByUser;
$p->payment_method = $session->get("payment_method");
$p->order_time = $session->get("order_time");
$p->paypal_transaction_id = $session->get("paypal_transaction_id");

foreach($session->get("cart_item") as $cart_item) {
    // create order items
    $item = $p->order_items->getNew();
    $item->product_id = $cart_item['id'];
    $item->product_price = $cart_item['price'];
    $item->product_quantity = $cart_item['quantity'];

    $p->order_items->add($item);
    $transaction_amount += ($cart_item['price'] * $cart_item['quantity']);
}
$item->save();

$p->transaction_amount = $transaction_amount;
$p->save();
foreach($languages as $lang) {
    if($lang->isDefault()) continue;
        $p->set("status$lang", 1);
    $p->save();
}
```

Here is a youtube video to show my issue which I described.

I also posted a thread on the forum a few days before for whole dicussion.
https://processwire.com/talk/topic/13098-pages-created-by-api-could-not-able-to-retrieve-from-other-languages/

**Comment by ryancramerdesign** [comment]
Repeaters actually don't know anything about languages, so if you are creating repeater items from the API, you'll likewise have to enable those items for the language. Also, I see a couple of issues with the locations of your save() calls. See my uppercase notes below: 
````````
// this line included just for context of where this example is starting
$p->paypal_transaction_id = $session->get("paypal_transaction_id");

foreach($languages as $lang) $p->set("status$lang", 1); // ADD THIS (moved from below)
$p->save(); // ADD THIS because repeater must be added to page that already exists

foreach($session->get("cart_item") as $cart_item) {
    // create order items
    $item = $p->order_items->getNew();
    foreach($languages as $lang) $item->set("status$lang", 1); // ADD THIS (to enable for all langs)
    // ... your code here ...
    $item->save(); // ADD THIS (moved from below)
    $p->order_items->add($item);
}
// $item->save(); // REMOVE THIS (moved to above)
````````
In this next block of code, you are saving $p in the wrong places. I don't think it's causing a problem, but it's also not necessary. Remove all of this:
````
// REMOVE ALL OF THIS
$p->transaction_amount = $transaction_amount;
$p->save();
foreach($languages as $lang) {
    if($lang->isDefault()) continue;
        $p->set("status$lang", 1);
    $p->save(); 
}
````
and replace it with this:
`````
$p->transaction_amount = $transaction_amount;
$p->save();
`````

**Comment by adrianmak** [comment]
Just tested with your code modification, and repeater fields with multi-language site is working properly.
Thank you Ryan.
