### ISSUE TITLE
WireArray::explode option suggestion

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1796]
It would sometimes be great to manipulate the array keys for the explode() resultset. E.g. converting page arrays to an array keyed by id. My use case for this is feeding select boxes with keys and values for nette/forms.

```php
$data = $pageArray->explode('title', array('keyProp' => 'id'));
// results in [1001 => 'My Title', …]
```

**Comment by ryancramerdesign** [comment]
That's an excellent suggestion. I have added this in the latest commit.

**Comment by LostKobrakai** [comment]
Thanks for that.
