### ISSUE TITLE
php errors

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1798]
> Fatal error: Cannot declare class Breadcrumbs, because the name is already in use in /Users/benni/Projekte/Mammut Event Platform/root/html/wire/core/compat2x/Classes.php on line 16

I've also head some issues, where php complained about $config not being defined in that file. 

<img width="1201" alt="screenshot 2016-04-29 12 43 29" src="https://cloud.githubusercontent.com/assets/2489835/14914142/0869db96-0e08-11e6-807b-6e5733100bcb.png">

My composer.json does look like this:
```json
 "autoload": {
    "files": [ "wire/core/ProcessWire.php" ],
    "psr-4": {
      "MammutEvents\\": "site/templates/src/"
    }
  },
  "autoload-dev": {
    "classmap": [ "wire/core" ],
    "psr-4": {
      "tests\\": "spec/"
    }
  },
```

**Comment by LostKobrakai** [comment]
Ok this helped:
```json
    "exclude-from-classmap": ["wire/core/compat2x/"],
```

**Comment by ryancramerdesign** [comment]
That compat2x directory doesn't need to be there anymore. I've only left it there for now because it keeps phpstorm happy when I'm editing non-namespaced modules. But it's not going to appear in the 3.x master.

I wonder how Composer is finding it? I haven't had that occur here. Is it possible you've got $config->compat2x = true; ?

**Comment by LostKobrakai** [comment]
The classmap autoloader does find them and I need composer to autoload the core classes (instead of pw) as otherwise the classes are not stub'able by the testing framework. But this is probably not something you need to accomodate for.

**Comment by LostKobrakai** [comment]
I'll close this as it's really not related to processwire and the exclude from classmap does resolve the issue anyways.
