### ISSUE TITLE
Deleting Language causes SQL Error in Fields

### ISSUE THREAD

**Issue by TomasKostadinov** [ryancramerdesign/ProcessWire#1801]
Deleting a language causes SQL Errors when trying to create new Fields.
See my post in the forum:
https://processwire.com/talk/topic/13060-sql-errors-after-deleting-language/

**Comment by ryancramerdesign** [comment]
Hi @TomasKostadinov I've replied in the forum you linked.

**Comment by TomasKostadinov** [comment]
@ryancramerdesign Did my forum post get deleted? I'm getting an error :(
