### ISSUE TITLE
Usage of __ CLASS __ has changed with $modules in devns branch

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/ProcessWire#1805]
Hi,
in PW < 3, we could use the __ CLASS __ constant to reference to our classes name when building modules, what was very conveniant.

For example, I often used something like: `$data = wire('modules')->getModuleConfigData(__ CLASS __)`
Now with namespace, this will fail, as __ CLASS __ also contain the processwire namespace prepended, if it is a native PW3 module. I would like to see something like `$className = str_replace(__ NAMESPACE __ . '\\', '', $class);` (Yes, first check if it is a string and not an object!) in the modules method [getConfig()](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Modules.php#L2894)  and [saveConfig()](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Modules.php#L3405)

**Comment by LostKobrakai** [comment]
https://processwire.com/api/ref/wire/class-name/

**Comment by horst-n** [comment]
Thanks for the hint!
