### ISSUE TITLE
child/children selector in 3.0.15

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1807]
The child/children selector does not seem to work correctly.
![screenshot 2016-05-02 10 29 10](https://cloud.githubusercontent.com/assets/2489835/14950277/ced04514-1050-11e6-8fac-d862c213d6c4.png)
![screenshot 2016-05-02 10 29 21](https://cloud.githubusercontent.com/assets/2489835/14950278/cee59a22-1050-11e6-9c91-705e8bb299a4.png)

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix for this.
