### ISSUE TITLE
Selector my_checkbox!=1 fails to match empty checkboxes

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1811]
For a checkbox field named 'my_checkbox', selector my_checkbox!=1 should match pages where my_checkbox is empty (unchecked), but it doesn't.

**Comment by adrianbj** [comment]
For reference: https://processwire.com/talk/topic/13153-excluding-pages-from-bootstrap-menu/?p=119402

And to clarify, I don't believe it has anything to do with the name of the checkbox field being "checkbox", but please clarify if I am mistaken.

**Comment by Toutouwai** [comment]
I can see how that's confusing so have edited.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this issue.

**Comment by isellsoap** [comment]
@Toutouwai Is this issue fixed? If yes, please close the issue. Thank you.
