### ISSUE TITLE
Case issue with anchor links in new API docs

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1812]
Here's an example:

**Go to:** https://processwire.com/api/ref/page/url/
**then click on:** Page::localUrl() under "See Also"
**which redirects from:** https://processwire.com/api/ref/page/localurl/ 
**to:** https://processwire.com/api/ref/page/#api-localurl 
**but it needs to be:** https://processwire.com/api/ref/page/#api-localUrl 

Note the uppercase "U" in Url

**Comment by ryancramerdesign** [comment]
Thanks Adrian! I have fixed this so that it should work now.
