### ISSUE TITLE
When adding a new page the 'Label for Page Name property' is not displayed

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1813]
As the title says, if you are adding a new page the label is displayed as 'Name' even if you have entered something in the template. Guessing this may be difficult to fix as a new page can have a choice of templates?

**Comment by ryancramerdesign** [comment]
That's correct, if multiple templates are possible, then it has to use the original/common label for it. Whereas if only one template is possible in the location, then it will use your custom labeled name instead.

**Comment by cb2004** [comment]
Cheers @ryancramerdesign
