### ISSUE TITLE
3.0.16: image in repeater is throwing an error when trying to resize

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1814]
This was a fresh install, built a load of repeaters with images in my time so I am confused, been over my code and again and again:

```
<?php foreach ($page->repeater_hero->shuffle() as $slide): ?>
<div>
	<img src="<?= $slide->image_hero->size(1560, 624)->url ?>" alt="">
	<p><?= $slide->text_1 ?></p>
</div>
<?php endforeach; ?>
```

Error: Exception: Method Pageimages::size does not exist or is not callable in this context (in /home/sites/SITE.co.uk/public_html/beta/wire/core/Wire.php line 409) #0 /home/sites/SITE.co.uk/public_html/beta/wire/core/WireArray.php(2103): ProcessWire\Wire->___callUnknown('size', Array) #1 [internal function]: ProcessWire\WireArray->___callUnknown('size', Array) #2 /home/sites/SITE.co.uk/public_html/beta/wire/core/Wire.php(347): call_user_func_array(Array, Array) #3 /home/sites/SITE.co.uk/public_html/beta/wire/core/WireHooks.php(555): ProcessWire\Wire->_callMethod('___callUnknown', Array) #4 /home/sites/SITE.co.uk/public_html/beta/wire/core/Wire.php(370): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Pageimages), 'callUnknown', Array) #5 /home/sites/SITE.co.uk/public_html/beta/wire/core/Wire.php(371): ProcessWire\Wire->__call('callUnknown', Array) #6 /home/sites/SITE.co.uk/public_html/beta/wire/core/Wire.php(371): ProcessWire\Pa

**Comment by cb2004** [comment]
The image appears with this, seems url is just returning the files folder and not the actual image.

`<img src="<?= $slide->image_hero->url ?><?= $slide->image_hero ?>" alt="">`

**Comment by ryancramerdesign** [comment]
Is this being triggered from front-end code, or is this happening on the
admin side? If front-end, can you paste the code you are using? The error
seems to indicate that some code is calling the size() method on an array
of images rather than on single image().

**Comment by cb2004** [comment]
Hi Ryan, hope you are well.

You nudged me in the right direction, I set the maximum files allowed to 1 and all is fine again.

Cheers.
