### ISSUE TITLE
error in compat2x: $config not defined

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1815]
Got this (and some other) notices/ warnings/errors after setting $config->compat2x = true;
Notice: Undefined variable: config in [...]wire/core/compat2x/Classes.php on line 71

**Comment by ryancramerdesign** [comment]
The compat2x mode is no longer in use, we decided not to keep it. I've only got it around in the devns branch to keep phpstorm happy with some module development, but it'll be removed completely before 3.x reaches the master branch.

**Comment by kixe** [comment]
Thanks for the information.
