### ISSUE TITLE
Save log files to custom folder, not only to site/assets/logs

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessWire#1823]
I often have a need to save log from custom service scripts, that bootstrap PW. I want to save them outside of PW installation close to the service script itself. It would be great to use PW in-built functions for that. As PW is becoming more of a framework, I guess it is not necessary to limit such general functions to pre-configured values.

**Comment by wanze** [comment]
Hi Ivan,
You can put your own log files anywhere, just make sure that the destination path is writeable:
```php
$log = new FileLog('/path/to/your/logfile/', 'my-log-file');
$log->save('test');
```

**Comment by ivangretsky** [comment]
thanks, that worked
for writing to current dir i used
`$log = new FileLog('./', 'my-log-file');`
