### ISSUE TITLE
3.0.17: images tooltips are cut off.

### ISSUE THREAD

**Issue by PawelGIX** [ryancramerdesign/ProcessWire#1826]
![screen shot 2016-05-11 at 17 10 33](https://cloud.githubusercontent.com/assets/391153/15186043/bcfd45b0-179b-11e6-95dc-ba68b2dd7e63.png)

**Comment by ryancramerdesign** [comment]
I tried putting a CKEditor textarea using inline mode above an images field, but am not seeing that z-index issue here. Is that text field above your images field something different than what it hooks like?

**Comment by PawelGIX** [comment]
Not occurred since the version (3.0.18)

**Comment by isellsoap** [comment]
@PawelGIX Can this issue be closed?

**Comment by PawelGIX** [comment]
Yes
