### ISSUE TITLE
Non-blank PageLabelField leads to problems with incorrectly displayed page names in the page list if the last character of the page label is an html entity

### ISSUE THREAD

**Issue by netcarver** [ryancramerdesign/ProcessWire#1827]
Found this in 3.0.17 - I haven't checked if it is present in any other version.

How to reproduce.
- Edit a template and navigate to the 'advanced' tab.
- Scroll down to "List of fields to display in the admin page list" control and enter '{title}' as the value (without quotes.)
- Create a new page using your edited template and title it '15€' (without quotes.)
- Save your new page.

View the new page in the page tree and you'll see it is displayed as '15&euro'. 

This happens with any field included in the page label custom definition - not just title.
This happens when any character in the last position of the last field gets entity encoded - not just for the euro symbol.

I tracked this down to Sanitizer's markupToText() method ([L987 in devns](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Sanitizer.php#L987)). The method, as called when setting up custom page list labels, converts the string to entities but then trims off trailing semicolons. This neuters the last html entity in a page's list label.

Removing the ';' from the list of default trim characters fixes the issue for me but I don't know if it introduces regressions elsewhere.

**Comment by ryancramerdesign** [comment]
That's some excellent detective work there. Unfortunately I wasn't able to duplicate the issue after setting up the same test case that you mentioned with 15€. Perhaps there's some other factor. But the source of the problem you tracked down makes a lot of sense and I can see that needs to be fixed regardless of whether I can duplicate the same issue. I've pushed a fix. Please let me know if you continue to observe the issue. Thanks @netcarver !
