### ISSUE TITLE
name format for children with 1+ allowed templates

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1831]
if you setup name format for children "title" with 1 allowed children template everything works fine. if you need a second allowed child template and add this to the template setting of the parent template, the field for the name format disappears, but it's value is still "title" causing buggy behaviour when adding new pages.

1st step: set page title + template
2nd step: edit page --> bug: title field is empty, page name is "untitled"

processwire should ignore the name format when 1+ templates are selected or clear the name-format-field on save, when 1+ templates are selected

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock that's a good find, I've pushed a fix for this issue.
