### ISSUE TITLE
3.0.18: Hook order and error checking, is the error check firing too early

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1832]
I have a system with numerous hooks in ready.php. When a page is selected, if certain fields are empty, these are populated from the fields in the selected page. I will strip this down to make it easier to follow.

Lets say I have a textarea field and it is set as required. If you consider the hook:

```
$pages->addHookBefore("saveReady", function($event) {
	$page = $event->arguments(0);

	if ($page->template->id == 1) {
		if ($page->page_selector) {
			if (empty($page->textarea))
				$page->textarea = $page->page_selector->textarea);
		}
	}
});
```

So my field textarea is populated from the $page->page_selector->textarea correctly, however there is a warning that textarea is not populated after save, although at this point it holds data.

I have tried numerous hook methods, and this may not even be a bug, but it is puzzling.

Cheers.

**Comment by LostKobrakai** [comment]
Inputfield requirements are not evaluated on the page level, but **just** on the page edit interface level. There no such thing as a required field, but rather the edit form does require an input (hence inputfield requirements). To prevent the message you'd need to hook before ProcessPageEdit::processInput or alike.

**Comment by cb2004** [comment]
Ben, I need to keep a list of how many times you have helped me. Its all about finding the right hook, and that was it.

Thank you.
