### ISSUE TITLE
$users->get(ID) returns Page-instance instead of NullPage

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1833]
```php
$users->get(1)->name // => "home"
```
*ProcessWire 3.0.18 devns*

**Comment by ryancramerdesign** [comment]
Thanks @yckart that's a great find, I have pushed a fix. The issue was a matter of caching.

**Comment by isellsoap** [comment]
@yckart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
