### ISSUE TITLE
Missing ? breaks Add New shortcut when there is only one possible parent page

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1834]
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L203
```
$url = "./parent_id=" . $parents->first()->id; 
```
should be:
```
$url = "./?parent_id=" . $parents->first()->id; 
```
without the ? it actually shows the page on the front-end.

PS It's line 201 on the devns branch.

**Comment by rolandtoth** [comment]
+1

**Comment by ryancramerdesign** [comment]
Thanks Adrian! I've just pushed a fix for this one.
