### ISSUE TITLE
Session Handler Database does not honour $config->timezone

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1838]
In the core Session Handler Database module timestamps are stored with MySQL NOW() and no correction is made for differences between the MySQL timezone and the timezone set in $config->timezone.

If a website is hosted on an overseas server chances are the MySQL timezone will be wrong for that website and it's difficult to correct this in a shared hosting environment.

Related [forum topic](https://processwire.com/talk/topic/13307-session-handler-database-times-out-by-two-hours/).

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. Can you confirm it also fixes it on your end?

**Comment by Toutouwai** [comment]
Yes, it's fixed. Thanks.
