### ISSUE TITLE
Field dependencies don't work properly on User templates

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1839]
When saving a User page, if I have a field which makes use of inputfield dependencies ("Show if..."), the value of the field is not saved. If I remove the "Show if..." condition, it will then save properly.

**Comment by ryancramerdesign** [comment]
Field dependencies seem to be working okay for me when editing a user page. Can you tell me more about what type of dependency you are using and the exact string used to define it? Also, just to confirm, this is when editing a user, not when editing your own profile? Thanks.

**Comment by thetuningspoon** [comment]
The field I am checking is the roles field. I think I was using the page id to match it, i.e. roles=1001
