### ISSUE TITLE
WireArray and ArrayObject returning wrong number of items in foreach

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1842]
Now that's a weird one. I wanted to add few fieldtypeoptions options with my migrations module on a site. The migration worked wonderfully on my local vm, but didn't do so on the live server. Then I tried to add the new options manually, which didn't do it as well. It turned out that SelectableOptionsArray and it's base class WireArray where somehow swallowing items for the usage in foreach loops. 

WireArray::getIterator does return a new ArrayObject instance, where this did happen:

``` php
        $obj = new ArrayObject($this->data); 
        $this->message('b+' . $obj->count()); // 'b+17'
        $i = 0;
        foreach ($obj as $value) $i++;
        $this->message('c+' . $i); // 'c+16' - Missing the one new option I guess
        return $obj;
```

whereas this worked correctly

``` php
        $obj = new ArrayIterator($this->data); 
        $this->message('b+' . $obj->count()); // 'b+17'
        $i = 0;
        foreach ($obj as $value) $i++;
        $this->message('c+' . $i); // 'c+17'
        return $obj;
```

PW 2.7.2 dev (shouldn't matter that much)
PHP Version 5.5.9-1ubuntu4.14
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

**Comment by LostKobrakai** [comment]
Just to add that here. The array that happened with was a SelectableOptionsArray with a new option added to it like that:
```php
		$opts = $this->modules->get('FieldtypeOptions')->getOptions('hr_made_sizestrousersw');
		$item = $opts->makeBlankItem();
		$item->title = '27';
		$opts->insertBefore($item, $opts->get('title=28'));
		$this->modules->get('FieldtypeOptions')->setOptions('hr_made_sizestrousersw', $opts);
```

**Comment by LostKobrakai** [comment]
Ok, does really seem to be an PHP issue in 5.5: https://bugs.php.net/bug.php?id=67360
Maybe using ArrayIterator might be the better bet.

**Comment by ryancramerdesign** [comment]
That's some good debugging work, I'm impressed you tracked that one down. Sounds like they actually fixed this one on the same day that it was reported, nice.

**Comment by LostKobrakai** [comment]
Maybe we should still accommodate for that, as ubuntu's 14.04 default php version is still affected by this. Meaning anybody running on such a machine cannot add any options to the options fieldtype (and possibly other things, which rely on empty keys). I'm also not really sure why we need the ArrayObject anyway, as it's also just returning an ArrayIterator instance.
