### ISSUE TITLE
Save options when editing in modal popup

### ISSUE THREAD

**Issue by ottogal** [ryancramerdesign/ProcessWire#1843]
If you edit a page in the modal popup, the Save button should have the same options dropdown like in the normal edit view.

**Comment by ottogal** [comment]
Rethinking my proposal: it seems not adequate to the "modalitiy" of a modal window...

**Comment by ryancramerdesign** [comment]
In a modal, the options don't apply because there aren't really any other paths for the user to take here. Depending on the case, we either close the modal for them on save, or let them close it.

**Comment by ottogal** [comment]
Yes, that was my second thought about it... Thx, Ryan.
