### ISSUE TITLE
Parse Error: syntax error, unexpected ',' 

### ISSUE THREAD

**Issue by kriscreative** [ryancramerdesign/ProcessWire#1844]
I upgraded my ProcessWire 2.7.2 installation to 3.0.18. Backend works ok. However the file compiler seems to choke on php include statements in my templates:

The below code:
`<?php include_once("./includes/header.inc") ?>`

Is turned into the below code:
`<?php  include_once(\ProcessWire\wire('files')->compile(\ProcessWire\wire("config")->paths->root . "site/templates/includes/header.inc") ,array('includes'=>true,'namespace'=>true,'modules'=>true,'skipIfNamespace'=>true))?>`

Which throws an error when trying to open the page:
Parse Error: syntax error, unexpected ',' (line 4 of /home/koryu693/www/dev.koryu693.jp/site/assets/cache/FileCompiler/site/templates/home.php)

**Comment by cb2004** [comment]
Try this:

`include_once $config->paths->templates . 'includes/header.inc';`

**Comment by teppokoivula** [comment]
Sounds like a broken regex to me. The workaround provided by @cb2004 seems to make sense, but it doesn't solve the actual issue :)

**Comment by kriscreative** [comment]
The workaround is working ok for me. Thank you.

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this. The issue was that the PHP statement is missing a semi-colon at the end, and FileCompiler expects PHP statements to be terminated with a semicolon. It looks like a semi colon is optional in this case, so I've updated FileCompiler to recognize that.

**Comment by isellsoap** [comment]
@kriscreative This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
