### ISSUE TITLE
3.0.18: Images in Lister results invisible, have zero width and height

### ISSUE THREAD

**Issue by rwetzlmayr** [ryancramerdesign/ProcessWire#1856]
Steps to reproduce:

1. Add any **Image** column to the Lister
1. Find any pages with an image
1. Notice that the image's drop shadow is shown at a very tiny size while the image itself is not visible at all

It seems that `div.gridImage__overflow` elements have an explicit width and height applied to them on the "Edit Page" page:

![screenshot - 01 06 2016 07_23_44](https://cloud.githubusercontent.com/assets/357054/15699109/ca572570-27ca-11e6-9578-47a12a2eeb1a.png)

The same elements are used in Lister cells containing images and do not have explicit dimensions. Thus the image is invisible:

![screenshot - 01 06 2016 07_25_00](https://cloud.githubusercontent.com/assets/357054/15699120/dfcb0d2c-27ca-11e6-8b8c-596739340f4f.png)

**Comment by mikelexp** [comment]
I can confirm this bug, and it's also present on 3.0.20, using ListerPro 1.09.

**Comment by mikelexp** [comment]
@rwetzlmayr It seems like the recently released ListerPro 1.10 fixes this issue, could you please test it?

**Comment by rwetzlmayr** [comment]
@mikelexp I do not own Lister Pro. This issue concerns the [core Lister](https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageLister/ProcessPageLister.module).

**Comment by mikelexp** [comment]
@rwetzlmayr That's weird. I've upgraded ListerPro on all my 3.0.18/20 installations and the issue is not present anymore. Maybe ListerPro overrides some Lister code that's causing the issue.

**Comment by ryancramerdesign** [comment]
Thanks @rwetzlmayr I've pushed a fix for this issue.

**Comment by rwetzlmayr** [comment]
Thanks.
