### ISSUE TITLE
InputfieldPageAutocomplete javascript, no focus() after hitting Enter key

### ISSUE THREAD

**Issue by gingebaker** [ryancramerdesign/ProcessWire#1859]
I found following issue after having to add a lot pages to an InputfieldAutocomplete. Tested this on PW 2.7.2 and 3.0.16.

After typing and selecting the needed Item (with up/down keys) from the Autocomplete List shown under the input I am hitting the enter key. The Item should be added to the list above and the focus should stay on the input field to type again. I think this is how it should be?

However, the item gets perfectly added to the list, but the focus gets lost after hitting enter... at least here on my installations?

I did some checks and noticed that when I comment out
```js
$(this).blur();
```
here:
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.js#L209

Then it works perfectly for me. 
Can anyone confirm this issue?

**Comment by ryancramerdesign** [comment]
The blur is needed to trigger another set of events. However, I think it's okay if we tell it to focus again after that blur. I've added this, so will see if any issues turn up.

**Comment by gingebaker** [comment]
thx ryan!
