### ISSUE TITLE
trackException

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1861]
Shouldn't allowExceptions allow **all** exceptions? I'm using this with my testing suite and I'd really like pw to throw all exceptions no matter what it is.

https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Wire.php#L1181-L1183

**Comment by ryancramerdesign** [comment]
Exceptions are considered severe by default, so the option is only provided if it needs to be overridden for some reason. Meaning, the allowExceptions option allows all exceptions, unless the developer has specifically indicated that one shouldn't be. Is there some exception in particular that it's coming through the way you need it?

**Comment by LostKobrakai** [comment]
I just noticed it, when implementing bugsnag into one of my projects. I just looked at the few exceptions, which you tagged as non-severe and most of them are really not of my concern, so maybe you're right on this, but still feels a bit odd that allowExceptions would not throw all of them.
