### ISSUE TITLE
Deprecated constructor in TextformatterSmartypants module

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1863]
The core TextformatterSmartypants module gives deprecated constructor notices in PHP7. The issue lies in the [SmartyPants library](https://github.com/michelf/php-smartypants) by Michel Fortin which is used in the module, but this library has not been updated since 2013 so maybe it should be fixed in the PW repository rather than waiting for a fix from the library owner?

There is some [discussion](https://github.com/getkirby/kirby/pull/430) on this topic at the Kirby GitHub, along with the [necessary code changes](https://github.com/getkirby/kirby/commit/5dff274eb93e6673c49b2ab3b766788107166621).

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update for this .
