### ISSUE TITLE
devns: InputfieldFile::init() misinterprets 'post_max_size=0' setting in php.ini

### ISSUE THREAD

**Issue by rwetzlmayr** [ryancramerdesign/ProcessWire#1864]
PHP 5.3.2+ [allows unlimited post size by setting `post_max_size` to 0](https://secure.php.net/manual/en/ini.core.php#ini.post-max-size). 

[InputfieldFile::init()](https://github.com/ryancramerdesign/ProcessWire/blob/86d5d20dd94f22b45993de52b18ab6da21473e5d/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L124) sets `$this->maxFilesize`to a default of 5M in that case. This contradicts the purpose of mirroring PHP's native post limits.

**Comment by ryancramerdesign** [comment]
This is intentional. There may be situations in PHP where it's okay to have no limit, but in our context it's not okay. So if the limit is not set in PHP (indicating unlimited) we substitute our own default. I could certainly bump it up to a larger number if you think that would help? But from a security standpoint, I think it's best to have some kind of limit even if PHP itself doesn't.

**Comment by rwetzlmayr** [comment]
Thanks for the explanation. May I add some background?

- I am working on a local development server. The security implication of an unlimited post size in this use case is 'me shooting myself in the foot'.
- I am using ImportPagesCSV with a > 30MiB CSV file. This file may grow as the project progresses.
- ImportPagesCSV seems to import just nothing until I realize that `post_max_size` protects me from myself.
- So I disable `post_max_size` in php.ini - but no dice because, as I learned after a bit of debugging,  PW also tries to protect me from myself.

> I think it's best to have some kind of limit even if PHP itself doesn't. 

Taken this as a given, wouldn't it be advisable to handle the `post_max_size=0k` case in a similar way, too? Currently, it [sets `$this->maxFilesize` to 0](https://github.com/ryancramerdesign/ProcessWire/blob/86d5d20dd94f22b45993de52b18ab6da21473e5d/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L123). This is, btw, my current workaround for this issue ;)

**Comment by rwetzlmayr** [comment]
> https://github.com/ryancramerdesign/ProcessWire/commit/4f1fb9cb1b575c35b4baff64fbe416fefb52003e

This **was** my current workaround for this issue ;)
