### ISSUE TITLE
Example site profiles namespace consistency

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1866]
Just found out that the default profile comes with namespaced template files, but the beginner one does not.

I am not sure whether they should be or not, but perhaps they should be consistent across the board?

Just for reference, this is how I came across this:
https://processwire.com/talk/topic/13473-trouble-with-class-not-found-in-append-file/?p=121723

**Comment by ryancramerdesign** [comment]
The beginner ones are meant to be as absolutely simple as possible, which is why we leave the namespace out of that.
