### ISSUE TITLE
showListFilters option in ProcessField module has no effect

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1867]
Filters are always visible (collapsed), maybe this option could removed?

**Comment by ryancramerdesign** [comment]
Yes, that can be removed. I have deleted it. Thanks.

**Comment by isellsoap** [comment]
@yckart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
