### ISSUE TITLE
Deleting default Find Lister (via Lister Pro) break Usage section in ProcessTemplate

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1868]
https://processwire.com/talk/topic/13281-unrecognized-path-in-template-edit-page/

**Comment by ryancramerdesign** [comment]
The default Lister is not meant to be deleted, since it serves as the admin search engine, among other things. I'll update ListerPro to prevent deleting of it. Thanks.

**Comment by noelboss** [comment]
How can one fix this isse? I think i have it reconfigured right?

![screen shot 2017-10-16 at 16 08 59](https://user-images.githubusercontent.com/114080/31616215-5b0c1bdc-b28c-11e7-8f43-08fadc529bca.png)

**Comment by adrianbj** [comment]
@ryancramerdesign - even the very latest version of ListerPro still lets you delete the default Find lister. Can you please fix!
