### ISSUE TITLE
"Save + Exit" does not apply template change

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1872]
When changing the template for a page in Page Edit, choosing "Save + Exit" does not apply the change. Choosing "Save" does apply the change as expected.
PW 3.0.20

**Comment by teppokoivula** [comment]
This issue looks like a duplicate of #1779. Please correct me if I'm wrong.. and thanks for reporting it either way :)

**Comment by Toutouwai** [comment]
I missed that issue. Yes, this is a duplicate.
