### ISSUE TITLE
Default admin theme: alignment of collapse icons

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1873]
A minor styling issue...
If an inputfield header contains more than one icon the following CSS rule places an additional margin to the right of the inputfield collapse icon, putting it in a different position than the normal alignment.
> .Inputfields .InputfieldStateToggle .ui-icon + .ui-icon, .Inputfields .InputfieldStateToggle i + i {
>     margin-right: 0.5em;
> }

![collapse-icons](https://cloud.githubusercontent.com/assets/1538852/15982483/056c9a22-2fdd-11e6-89dc-c692b9cbdf53.png)

**Comment by ryancramerdesign** [comment]
Thanks, I hadn't noticed that before but you are right. I've just pushed a fix.
