### ISSUE TITLE
Default admin theme: CKEditor focus style looks odd

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1874]
A minor styling issue, and matter of opinion. Just close this if you don't agree :-)
When unfocused CKEditor has a 1px grey border. When focused the border turns white, and this looks a bit odd to my eye. Darkening or lightening the border would be fine, but white disappears into the background and makes the field look less focused if anything.
![editor-focus](https://cloud.githubusercontent.com/assets/1538852/15982522/7153c57a-2fde-11e6-862a-ec2eac63d3f1.png)

**Comment by ryancramerdesign** [comment]
I completely agree. It looks like a style meant for the inline editor was getting applied to the regular editor. I have pushed a fix for this, thanks.
