### ISSUE TITLE
Automatic Page Name Format Stopped Working for PageTable in PW 3.0.21

### ISSUE THREAD

**Issue by cstevensjr** [ryancramerdesign/ProcessWire#1878]
After upgrading from PW 3.0.20 to 3.0.21, the Automatic Page Name Format in the PageTable field stopped working.  If you revert back to PW 3.0.20, it works again.

Opened a ProcessWire Forum post on this same subject

https://processwire.com/talk/topic/13538-automatic-page-name-format-not-working-for-pagetable-pw-3021/

**Comment by cstevensjr** [comment]
Updated to PW 3.0.23 and same problem exists.  Had to downgrade back down to 3.0.20 to properly use PageTable fields.

**Comment by ryancramerdesign** [comment]
Thanks @cstevensjr I have pushed a fix for this issue.

**Comment by cstevensjr** [comment]
I can confirm that this fix works on an updated PW 3.0.23 for PageTable field
