### ISSUE TITLE
Still having issues with CKEditor and mystyles.js

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1880]
PW 3.0.17

If two CKEditor text fields on the same page are configured to use the same "mystyles" name/reference, then only one will correctly load the custom style configuration. If you copy the code in the mystyles.js file and give it a different name/reference (i.e. yourstyles) and then configure the second CKEditor field to use that name instead, then both fields will load the custom configuration correctly.

We've been having a lot of issues like this with custom configuration of CKEditor in our 3.0 sites. I'm surprised that it hasn't been reported by others, so maybe it is something unique to our installations? Can anyone else try and reproduce this?

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon I've pushed a fix for this issue. Please let me know if you see any more errors.
