### ISSUE TITLE
MarkupCache.module Example code with $cache

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1882]
In the top of the MarkupCache.module there's an example code.

 * Example usage:
 * 
 * $cache = $modules->get("MarkupCache"); 
 * if(!$data = $cache->get("cityOptions")) {

I think this needs to be changed since the $cache is now System var for WireCache.

**Comment by ryancramerdesign** [comment]
Thanks, I've updated that example.
