### ISSUE TITLE
when loading page from asm select, "crop" and "variations" button appear in modal window

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1883]
Let's say you have a Page field that is ASM Select, that is configured to allow you to edit a page directly from clicking the item in the ASM Select.

The modal window has a Save button as it should, but it also erroneously has a "Crop" and "Variations" button.
![x](https://cloud.githubusercontent.com/assets/4558/16133510/17c48038-33cd-11e6-9969-ed99dc8bfd4d.jpg)

**Comment by jlahijani** [comment]
Note: This only occurs AFTER images have been uploaded to the page and the page is opened in the modal after this fact.

**Comment by jlahijani** [comment]
Note: It also only occurs when the images of a field are being viewed using the "list" view (the view that allows you to edit the description).

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I've pushed a fix for this issue.
