### ISSUE TITLE
Maybe "Page" is not a very explicit term to refer to the content nodes?

### ISSUE THREAD

**Issue by fabschurt** [ryancramerdesign/ProcessWire#1886]
I've stumbled upon ProcessWire this week, and I don't get how I've never heard about this CMS before, because it's so awesome.

Having read the whole documentation and preparing to develop my first professional project with the CMS, there's this one thing that I found very peculiar about the design of the framework: the choice of the word **Page** to refer to the various entities managed by the platform.

To me, the term **Page** is misleading, because it seems to refer to something visual, when it can actually refer to more abstract things like users, permissions, and other non-visual content. As a newcomer, I would have found other words much clearer: **Node**, **Entity**, etc.

I don't know if this has come up before (I've made a quick search in the GH issues but found nothing), and if it's even conceivable to modify such a central term of PW's vocabulary, not even mentioning the huge code refactoring needed to take such a change into account, but I'm asking anyway because it seems important to me.

**Comment by tbba** [comment]
I understand why are you saying this. I am coming from the Drupal world of "nodes" and "entities" (and super clever people trying to explain the difference) and found this super abstract terminology always a down turner there, adding to the learning curve: Things felt much more complicated than they often were, when explanations were wrapped in super strict science terminology. 

It's a matter of taste but I think that "page" sounds much more friendly (like the whole PW world is passionate but very friendly) and I am sure you get adapted with the casual language style terminology as quickly as I. :-)

_It is just another opinion, of course (I am not scientist, I come from the brand design worlds)_

**Comment by fabschurt** [comment]
Well, yes, I agree that in a sense, this choice of word is practical and does lower the learning curve because "page" actually works well in 90% of the cases, when nodes do translate to "pages" on the frontend. It only gets a bit confusing when you realize that non-visual nodes are "pages" too (users, etc.). That being said, this may actually be clearly stated somewhere in the documentation, I can't really remember because I've read it all in 2 days and that was a lot to get a grasp of!

Closing the issue 👍

**Comment by apeisa** [comment]
There is lots of topics about this in processwire.com/talk/
