### ISSUE TITLE
"Missing required value (labelFieldFormat)" when saving a page field

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1890]
I get this error show although the label format is set and not empty

![image](https://cloud.githubusercontent.com/assets/370148/16271508/93a5488c-389a-11e6-8e71-c81ed01dd8e2.png)

**Comment by ryancramerdesign** [comment]
I'm not seeing that error here. Though did make some updates to the labelFieldFormat a couple weeks ago (on 3.x & 2.8.x), so thinking this one may already be fixed. Please let me know if you continue to see it in the future.

**Comment by somatonic** [comment]
This is in pw2.7.2 and pw2.7.3 does that mean I'm left with this broken? It's also when using FormBuilder Page field setup, it always shows the error when saving.

I'm also having sandbox local install with 3.0.25 and there its the same issue. The title options is selected but when saving -> Session: Missing required value (labelFieldFormat)

**Comment by somatonic** [comment]
It still tries to validate the custom format field, although it's not selected. So I have to enter something and save and then change to title...
