### ISSUE TITLE
Empty image field produces error in finder?

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1894]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) )) WHERE (pages.status<8192) AND (((num_field_tumnagel_1>0 AND pages.templ' at line 4

![finder-error](https://cloud.githubusercontent.com/assets/11423659/16293116/7d4d95e4-3917-11e6-8a2b-ec048fc05131.jpg)

**Comment by ryancramerdesign** [comment]
I'm not seeing that error here. Just to confirm – "Tumnagel" is an images field? What version of PW? If you enable debug mode, Lister should show you the selector that it is using (underneath the results) to find the pages. Can you tell me what the selector shows? Here's what mine shows:
```````
has_parent!=2, images.count>0, limit=25, sort=-modified, include=unpublished
```````

**Comment by isellsoap** [comment]
@kalmarlansmuseum Can you please provide more information to this issue as per the comment above?

**Comment by kalmarlansmuseum** [comment]
The field was a croppable image-field.
