### ISSUE TITLE
selector on pageTable.fieldname.data1xxx does find a match where it shouldn't ?

### ISSUE THREAD

**Issue by er314** [ryancramerdesign/ProcessWire#1896]
default language page id is 1009, fr language page id is 1013.
```
$pages->find("body%=someTextInEnglish"); // does return one page match, as expected
$pages->find("body.data1013%=someTextInEnglish"); // does not return a match, as expected
$pages->find("myPageTable.body%=someOtherTextInEnglish"); // does return one page match, as expected
$pages->find("myPageTable.body.data1013%=someOtherTextInEnglish"); // does ALSO return the same page match, where it shouldn't
```

can you reproduce & do you agree ?
PW 3.0.22

**Comment by ryancramerdesign** [comment]
There's no such thing as `a.b.c` selectors in PW, only `a.b`. Typically I'd say to just change `$user->language` to the language you want the search to be performed in, but looks like that's not quite what you are wanting here. So you'd have to find a different way to to execute that search. For instance:
`````
$pages->find("myPageTable.id=[body.data1013%=someOtherTextInEnglish]");
`````
We might actually be able to support some types of `a.b.c` selectors just by converting them internally to the format above. I'll look into that.

**Comment by teppokoivula** [comment]
@ryancramerdesign Unless I'm missing something obvious here and it's actually unrelated, support for `a.b.c` selectors etc. seems more important now than ever before. We have PageTable fields, which could contain Repeaters, which could contain Table fields, which could contain... you get the point :)

**Comment by ryancramerdesign** [comment]
Well everything can be done with subselectors already, so it's really just
a matter of using the right syntax. I think the a.b.c syntax would be nice
to support as an alternative syntax for a subselector, where it's possible.
But if needing to match any more than one property that way, subselectors
will probably still be preferable.

**Comment by teppokoivula** [comment]
Got it. The main benefits of `a.b.c` syntax are obviousness and consistency with OOP. Subselectors are a great feature, but (in my opinion) they're not quite as straightforward or easy to understand. Even if from a technical point `a.b.c` would just be a shorthand for some simple subselectors, that would be perfectly fine :)

**Comment by er314** [comment]
Ah ok, understood.
I'm no expert in selectors, plus I thought that .dataxxxx was somewhat special/magical, but actually, it's not that much :-)
thanks
