### ISSUE TITLE
Wish: Show tooltips on hover

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1899]
In many places in the backend I wish there was a tooltip when hovering certain buttons or icons. Sometimes the icon isn't clear what it does. For example:

![image](https://cloud.githubusercontent.com/assets/370148/16417425/130a1940-3d46-11e6-834f-63ebb4519ec3.png)

A simple > title="description" < would suffice to show when hovering.

**Comment by matjazpotocnik** [comment]
+1

**Comment by ryancramerdesign** [comment]
@somatonic seems like a good thing to do, I have gone ahead and added these. Any others you've come across that need title attribute tooltips?
