### ISSUE TITLE
Selector nesting

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1905]
When working on my [Paginator](https://github.com/LostKobrakai/Paginator) class I tried to use this to calculate the total number of findable pages by multiple selectors, but it seems that subselectors do not allow for or-groups, which might be part of any selector passed to the class.

``` php
wire('pages')->count('(id=[' . implode(']), (id=[', $selectors) . '])')
```

**Comment by ryancramerdesign** [comment]
That's true it looks like we don't support nesting sub-selectors within OR groups at present. It probably could be supported, but I'm not able to look close enough at the moment. Most likely it would involve some further examination of the selector within this [if block](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/PageFinder.php#L505) and then going recursive or letting it run through the `preProcessSubSelector()` method.
