### ISSUE TITLE
3.0.24: latest commit breaks user edit

### ISSUE THREAD

**Issue by incognitoms** [ryancramerdesign/ProcessWire#1909]
I have two roles defined: superusers and editors. Editors have permissions to edit users. If I try to change a user as superuser, everything works. If I try with editor role, it breaks: for example, calling /access/users/edit/?id=12345 leads to: "ERR_TOO_MANY_REDIRECTS" in Chrome

The problem has been introduced with the latest commit aa91faae0d40701d8f476b39a6c6d14f88b80351 

Up to commit f094064f579f8e5294e072182c9c9c1659d61967 ("Bump version to 3.0.24") everything works.

**Comment by fabschurt** [comment]
Yep, exact same problem here.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue, please let me know if you continue to see any errors with it.

**Comment by incognitoms** [comment]
All is well again. Thank you very much, Ryan.
