### ISSUE TITLE
Renaming Fieldsets and FieldsetTabs doesn't rename the closing field

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1910]
For example:
1. Create a field of type Fieldset called "test" and a closing field will be created called "test_END"
2. Rename field "test" to "foobar" and "test_END" doesn't get renamed

I'm not sure whether this is by design or not or whether the opening field doesn't need the closing field to be named similarly? If the latter is the case then please ignore this :)

**Comment by adrianbj** [comment]
Duplicate of: https://github.com/ryancramerdesign/ProcessWire/issues/1854

**Comment by Notanotherdotcom** [comment]
Noted and closed :)
