### ISSUE TITLE
AsmSelector not working Repeater/Repeater Matrix

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1912]
AsmSelector doesn't seem to be loading if it's in a repeater or matrix repeater 3.0.24. However putting an Asm field outside of the matrix will load the javascript needed to make it work inside the matrix.

**Comment by jlahijani** [comment]
I can confirm this too.

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this one. Looks like this particular issue has been there as long as we've supported the ajax loading option for repeater items.

**Comment by isellsoap** [comment]
@TomS- This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
