### ISSUE TITLE
ProcessLanguageTranslator error (PW 3.025)

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1918]
When trying to save a translation for a module I get this error:

**Call to a member function get() on null**

https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/LanguageSupport/ProcessLanguageTranslator.module#L568

Uncommenting the line doesn't help (another error comes up). Also tried with several modules and this happens all the time, even with core modules.

**Comment by ryancramerdesign** [comment]
I can't duplicate this one, but it sounds like PW can't load the current
and/or default language. What version of PW? Logout and log back in. Double
check that you don't have the default language unpublished. Or if your
language (setup in your profile page) is not default, double check that the
language you are using is not unpublished. What other languages do you have
installed other than "default"? Lastly, make sure you are not trying to
edit two different languages at the same time. The LanguageTranslator
process keeps track of the language being edited in the session, so keeping
multiple tabs open to different languages could be problematic.

**Comment by rolandtoth** [comment]
It's PW 3.025. Re-login helped, thanks. 

There are 4 languages on the site, the default is non-English. These were modules so there were no 'inactive' pages.

Seemingly it was a session issue, should've tried this first. Thanks for the help!
