### ISSUE TITLE
devns 3.0.25 - "create new" links under input page fields broken

### ISSUE THREAD

**Issue by MarcShark** [ryancramerdesign/ProcessWire#1923]
all "create new"-links under input page fields  (from "allow new pages to be created from field") have disappeared since devns 3.0.25. They appear again if you switch back to 3.0.22 and disappear when you update back to 3.0.25 - so this seems to be a version-specific issue.

This has been observed by at least two users (see these two posts in PW Forums):

https://processwire.com/talk/topic/13732-pw-3025-2825-–-enhanced-page-finding-selectors/?do=findComment&comment=123937

https://processwire.com/talk/topic/13732-pw-3025-2825-–-enhanced-page-finding-selectors/?do=findComment&comment=123952

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here so far (3.0.27). I'm using multi-page Page field and asmSelect as the input type. Are you using single or multi-page, and what is the input type in use? Do you have both template and parent provided in your field settings?

**Comment by MarcShark** [comment]
Ryan, I sent you a message in pw forums with a downloadlink for my whole developement site including db dump to check out. Problem still occurs with 3.0.27, but strangely with exception of one field. Input field types are asmselect (single), radio and check box. Yes, both template and parent provided in field settings - otherwise it wouldn't work in 3.0.22 either. Hope this helps to find the bug. As I am not the only one there must something going wrong.

**Comment by ryancramerdesign** [comment]
Thanks for sending the download, I will grab that. What's the name of the
field that is working? I will probably start by looking directly at the
field config data as it is in the database, as most likely that would point
directly to it.

**Comment by MarcShark** [comment]
Ryan, for field name see my message in PW forum (same message as the one with the download link, username there: MarcU)

**Comment by MarcShark** [comment]
Ryan, this issue seems to be fixed here in my setup in 3.0.30 or even earlier versions. Everything works fine now. It was a reproduceable bug in 3.0.25, as metioned. Even if we don't know the exact reason - I should think this cause can be closed.

**Comment by ryancramerdesign** [comment]
Sounds good, thanks for reporting back. I'll close the issue.
