### ISSUE TITLE
3.0.25 devns Trying to get property of non-object PagePermissions.module:663

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1924]
It might be related to #1409

So when editing some pages I'm getting
````
PHP Notice: Trying to get property of non-object in .../wire/modules/PagePermissions.module:663
````
As mentioned in the linked issue it seems to happen on pages having a PageReference field, in my case probably the tags field, but other then in the linked issue the tags field (and actually all page fields used on those pages) have a parent and template selected

I could figure out that $addPage on mentioned line (663) is not a NullPage but most of the values e.g. $addPage->template is NULL
so $addPage->template->id is throwing the error

But unfortunately I don't now why that happens at all..as far as I understand there must be a call for $page->addable($somePage) where $somePage is not a proper instance of Page..?!

To get rid of this for now I prepended $addPage->template to the if clause in 663, don't now yet if this could cause any other issues but I guess no..

**Comment by yckart** [comment]
Same problem here. I've also noticed that the `E_NOTICE` is also thrown on the *Children* and *Settings* tab, if a template has a `FieldtypePage`-field.

Would nice to know if adding `$addPage->template` could break something else.

**Children**
![bildschirmfoto 2016-07-25 um 12 04 00](https://cloud.githubusercontent.com/assets/529130/17098392/631ad6be-5262-11e6-91e5-566ddbcd22db.png)

**Settings**
![bildschirmfoto 2016-07-25 um 12 03 29](https://cloud.githubusercontent.com/assets/529130/17098407/75f08914-5262-11e6-835e-c911f97364c9.png)

**Comment by ryancramerdesign** [comment]
I'm not seeing the issue here, but am guessing a NullPage is ending up in that method call argument. And looks like PagePermissions isn't properly detecting NullPage here, so I've gone ahead and updated that. Please let me know if you continue to see it. Thanks.

**Comment by yckart** [comment]
@ryancramerdesign Unfortunately not, just shoves the Notice one line downwards :P

As mentioned by @CanRau, adding `$addPage->template` could fix it?

```
Notice: Trying to get property of non-object in /var/www/wire/modules/PagePermissions.module on line 664
```

**Comment by justonestep** [comment]
I just ran into the same problem. If I edit a page which contains a Page Reference Field (in this case: blog template, field tags and categories) I get the error message mentioned above (... on line 664). Using latest PW 3.0.27 including the fix.

**Comment by ryancramerdesign** [comment]
Thanks. Wish I could actually observe this one as not sure why $addPage is lacking a template, especially if it's not a NullPage. However, I've gone ahead and added that template check and it should appear in the latest commit.

**Comment by justonestep** [comment]
Thanks, the error message is gone :)

The commit message points to the wrong issue #1944 instead of #1924.

**Comment by CanRau** [comment]
Thanks Ryan! closing..
