### ISSUE TITLE
class Users overwrites pageClass

### ISSUE THREAD

**Issue by schefflerinc** [ryancramerdesign/ProcessWire#1926]
Hi,

i followed these two tutorials:
https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users
and
https://processwire.com/docs/tutorials/using-custom-page-types-in-processwire/ 

When I call `wire('pages')->get(id)` I get a page with the correct class. 
When I call `wire('users')->get(id)` afterwards, it returns an instance of the correct class, too.
But when I call `wire('users')->get(id)` without loading the the User via `wire('pages')` before,
I get an instance of class `User`.

I fixed this problem by modifying `Users` by adding the following method:
```
public function getPageClass() {
        return '';
    }
```
But I'm not sure, if there are any sideeffects.
Is there any other way to have custom classes (extending `User`) for ProcessWire Users?
Or is there any other way to have multiple different User classes with some kind of inheritance in them?

**Comment by LostKobrakai** [comment]
https://github.com/ryancramerdesign/ProcessWire/issues/1412

**Comment by schefflerinc** [comment]
Ahh, nice. Thanks. Did not find this one -.-
