### ISSUE TITLE
selector parsing error while it shouldn't (in boundary conditions)

### ISSUE THREAD

**Issue by er314** [ryancramerdesign/ProcessWire#1927]
I was deliberately playing with boundaries in order to test the errors handling of my code, 
and I've come across an inconsistency on PW side :

`$selector = "template=an-article, has_parent=/temp/, app_Body|title%=" . $sanitizer->selectorValue("aaaaa") . ", (template=another-templ, has_parent=/here/, app_Body|title%=" . $sanitizer->selectorValue("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccccccccccccccccc pppppppppppppppppppppppppppppppppppppppppp qqqqqqqqqqqqqqqqqqqqqqqqqq rrrrrrrrrrrrrrrrrrrrrrrrrr") . ", app_Body|title%=" . $sanitizer->selectorValue("ssssssssssssssssssssssssssss ttttttttttttttttttttttttttt uuuuuuuuuuuuuuuuuuu vvvvvvvvvvvvvvvvvvv") . ", app_Body|title%=" . $sanitizer->selectorValue("wwwwwwwwwwwwwwwwwwwwwwwww xxxxxxxxxxxxxxxxxxxxxxxxx yyyyyyyyyyyyyyyyyyyyyy zzzzzzzzzzzzzzzzzzzzz") . ", app_Body|title%=" . $sanitizer->selectorValue("abcaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccccc") . "), sort=-published, limit=10";`

`$pages->find($selector);`

-> each value is sanitized, the total length of the selector is well below 2048 chars, and however this fails, due to syntax/parsing error 
`Error: Exception: Unknown Selector operator: '' -- was your selector value properly escaped?
`

While when made a bit smaller, then is succeeds :

`$selector = "template=an-article, has_parent=/temp/, app_Body|title%=" . $sanitizer->selectorValue("aaaaa") . ", (template=another-templ, has_parent=/here/, app_Body|title%=" . $sanitizer->selectorValue("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccccccccccccccccc pppppppppppppppppppppppppppppppppppppppppp qqqqqqqqqqqqqqqqqqqqqqqqqq rrrrrrrrrrrrrrrrrrrrrrrrrr") . ", app_Body|title%=" . $sanitizer->selectorValue("ssssssssssssssssssssssssssss ttttttttttttttttttttttttttt uuuuuuuuuuuuuuuuuuu vvvvvvvvvvvvvvvvvvv") . ", app_Body|title%=" . $sanitizer->selectorValue("wwwwwwwwwwwwwwwwwwwwwwwww xxxxxxxxxxxxxxxxxxxxxxxxx yyyyyyyyyyyyyyyyyyyyyy zzzzzzzzzzzzzzzzzzzzz") . ", app_Body|title%=" . $sanitizer->selectorValue("abcaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccc") . "), sort=-published, limit=10";
`

It's probably not a problem in real-world use cases, but I have no idea of the scope of the inconsistency, so just to let you know.

PW 3.0.25

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed a fix for this issue.

**Comment by er314** [comment]
Confirmed ok, thanks for the fix.

BTW, could you please just reply yes/no if in the short term you intend to implement selector "a.b.c|d.e.f" ?
As per my comment attached to the commit https://github.com/ryancramerdesign/ProcessWire/commit/70b3c3f7a24017f66ea522487b9a1f1da2df4d56

thanks !

**Comment by ryancramerdesign** [comment]
Right now focused on getting 3.x released, so not planning to implement that one just yet. I did try but looked like it was going to take more effort than there is time to do it at present. Long term I'm sure we'll be supporting it though.

**Comment by er314** [comment]
Ok no problem thanks.
Yesterday evening I think I came across another problem with `has_parent` not reporting an existing parent... something similar to #1588. This evening I'll try to reproduce it in a clean install, so you can prepare for having a new issue on this :-)
