### ISSUE TITLE
devns 3.0.25 Problems Installing Multilanguage Support

### ISSUE THREAD

**Issue by clsource** [ryancramerdesign/ProcessWire#1928]
I created a test site for the devns 3.0.25
Using utf-8mb4 and MyISAM Mysql 5.5.x
PHP 7.x

On the install forced to use InnoDB
but on a not supported MySQL version.

<img width="270" alt="captura de pantalla 2016-07-20 a las 12 02 15 a m" src="https://cloud.githubusercontent.com/assets/292738/16952750/e1143334-4e0d-11e6-8e3c-f17b92d354cb.png">

<img width="1045" alt="captura de pantalla 2016-07-20 a las 12 02 45 a m" src="https://cloud.githubusercontent.com/assets/292738/16952762/ed073ace-4e0d-11e6-94e7-a40b1a5a1021.png">

First Used the Blank Profile.
Then went to modules install languages
Language Support

<img width="1437" alt="captura de pantalla 2016-07-20 a las 12 03 20 a m" src="https://cloud.githubusercontent.com/assets/292738/16952779/029a970a-4e0e-11e6-965f-ec2cdc944ac4.png">

This caused the language tab to be empty and unknown error on listing pages

<img width="305" alt="captura de pantalla 2016-07-20 a las 12 04 11 a m" src="https://cloud.githubusercontent.com/assets/292738/16952808/27f6bf9c-4e0e-11e6-91c1-2886cacb9451.png">

<img width="953" alt="captura de pantalla 2016-07-20 a las 12 04 27 a m" src="https://cloud.githubusercontent.com/assets/292738/16952814/309d8798-4e0e-11e6-8168-53cea1446c76.png">

If I use the MyISAM on the first time (not forcing InnoDB), no problems arrise and everything is fine.

I think one way to solve this is disabling the InnoDB options if the MySQL version is lesser than 5.6.4.

Thanks 👍

**Comment by ryancramerdesign** [comment]
Thanks @clsource I've pushed a fix for this issue. It looks like the problem was that the dbEngine was making it's way into the install, but not the config.php.

**Comment by clsource** [comment]
thank u :)
