### ISSUE TITLE
Devn 3.0.25: Editing trashed Page throws error

### ISSUE THREAD

**Issue by TomasKostadinov** [ryancramerdesign/ProcessWire#1930]
How to recreate:
Create a page in Tab1
Open page tree in Tab2
Move page to trash in Tab1
Edit trashed page in Tab2

Result:

Error: Call to a member function children() on boolean (line 1 of /home/httpd/vhosts/ .... wire/modules/Inputfield/InputfieldPage/InputfieldPage.module(276) : eval()'d code) 

This error message was shown because: site is in debug mode. ($config->debug = true; => /site/config.php). Error has been logged.

**Comment by ryancramerdesign** [comment]
The error you reported is not coming from PW, but from custom PHP code defined for a Page field. The error doesn't say what Page field it is, but you'll want to take a look at your "Custom code to find selectable pages" defined on all of your Page fields. That section can be found by editing the field and clicking the "Input" tab.

**Comment by TomasKostadinov** [comment]
@ryancramerdesign  I checked it, "Custom PHP code to find selectable pages" is empty
