### ISSUE TITLE
Bug: renaming comments field doesn't rename the associated votes table

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1931]
Let's say you make a comments field called 'cool_comments' and you enable voting... and some comments are made and some votes have occurred.

Then you decide to rename the 'cool_comments' field to 'awesome_comments' instead.  The related table that handles storing of the votes doesn't get renamed and errors in PW when trying to upvote/downvote a comment.

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mywebsitedb.field_awesome_comments_votes' doesn't exist
```

Edit: using PW 3.x if that makes a difference.

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani good find, I've pushed a fix for this one!
