### ISSUE TITLE
Filecomiler translatable string error

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1933]
Okay, so I should probably localise day names using PHP's built-in functions, but I found an interesting FileCompiler error with this:

`$daysArray = array(1 => __('Monday'), 2 => __('Tuesday'), 3 => __('Wednesday'), 4 => __('Thursday'), 5 => __('Friday'), 6 => __('Saturday'), 7 => __('Sunday'));`

Basically it doesn't like the last translatable string in an array - in this case Sunday. The error is:

> Call to undefined function __()

If I change it so that Sunday isn't translatable as below everything else works:

`$daysArray = array(1 => __('Monday'), 2 => __('Tuesday'), 3 => __('Wednesday'), 4 => __('Thursday'), 5 => __('Friday'), 6 => __('Saturday'), 7 => 'Sunday');`

I guess the FileCompiler isn't handling the double closing bracket well or something?

**Comment by LostKobrakai** [comment]
Just a heads up, translatable strings need to be each on their own line.

**Comment by Notanotherdotcom** [comment]
Ah, that'll be it, thanks!
