### ISSUE TITLE
prevent page save when files are currently being uploaded

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1934]
don't know if that was mentioned anywhere before. i think there should be a message when somebody clicks on "save" while he/she is uploading files to a file field. currently when you click on save the files get lost!

maybe "please wait until the upload has finished"?

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I have added this.

**Comment by BernhardBaumrock** [comment]
thank you!

**Comment by rolandtoth** [comment]
How about aborting the submit event instead of using click event? That would also show the confirmation message when submitting via Enter.

https://github.com/ryancramerdesign/ProcessWire/blob/4f2f3f8462be55573e4ed111c5dc274391548e0e/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.js#L28

**Comment by BernhardBaumrock** [comment]
i found a little bug when using modals. when you click on save (in an autoclose modal) then it will prevent the pagesave but the save-button will disappear!

**Comment by isellsoap** [comment]
@BernhardBaumrock Could you please open a new issue with the bug you mentioned [in the new issues repository](https://github.com/processwire/processwire-issues)? Thank you.
