### ISSUE TITLE
Bug? Accessing single image of a page via Page field requires ->first

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1935]
Let's say I have an image field called 'image' on a page called "Page 1" and it is configured to only allow 1 file.  Assuming an image has been uploaded, I can get the URL of the image as follows:

```
$page->image->httpUrl
```

Now let's say I have another page called "Page 2" which has a Page single-select field called "featured_page".  Let's say I choose "Page 1" for this featured_page field.

Now let's say I do this:

```
$page->featured_page->image->httpUrl
```

It doesn't return anything.  To fix it, you have to use ->first for some reason.
```
$page->featured_page->image->first->httpUrl // notice 'first->'
```

I believe I hit this issue a few years ago as well but didn't make a bug report.  Is it considered a bug?

**Comment by ryancramerdesign** [comment]
What it indicates is that `featured_page` has output formatting turned off. Are you aware of any code that might be turning the output formatting off? If not, what PW version are you seeing this in? Where does the code appear, in a template file?

**Comment by jlahijani** [comment]
Understood.  I see where my issue is.  Closing.
