### ISSUE TITLE
New translation CSV import issue (3.0.23 and up)

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1938]
_(Update: it was in fact CSV, not JSON))_ 

If I export JSON and re-import on another site, nothing happens. 
But when I export the ZIP instead and import that, new translations are saved.

The file structure is the same as in the original site.

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. Taking a JSON translation file from one site to another seems to be working here. When you say "nothing happens" can you describe that further, like the actual upload fails, or the translation doesn't appear on the front-end, or? Also, if you can, please paste the contents of the JSON file in here to take a closer look, if you've got a small one. Thanks.

**Comment by rolandtoth** [comment]
Sorry I just see that I wrote JSON instead CSV. I'll edit the title to make it clear from now on.

Here is the file in question:

http://rolandtoth.hu/files/pw-160727.csv

On "nothing happens" I meant that the admin says "CSV file to be imported after save" after I browse for the CSV file. But after I save, the page reloads but no translations (files) are added at all. Even if I add the php files beforehands which holds the translations and then do the import, no new translations appear.

I could duplicate the issue by

- download the CSV (containing translations from multiple php files)
- delete the files from the file list (just to make sure)
- import the exported CSV

Note that the above steps were done on one site, not on two sites as before. Doing the same with ZIP works fine.

Hope this helps, and sorry again.

**Comment by ryancramerdesign** [comment]
Thanks @rolandtoth I've pushed a fix for the issue.

**Comment by rolandtoth** [comment]
Thanks!
