### ISSUE TITLE
Small typos in MarkupPagerNav.module

### ISSUE THREAD

**Issue by clsource** [ryancramerdesign/ProcessWire#1939]
typos found

https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Markup/MarkupPagerNav/MarkupPagerNav.module#L100

`navigiation`

https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Markup/MarkupPagerNav/MarkupPagerNav.module#L124

`seperator`

https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Markup/MarkupPagerNav/MarkupPagerNav.module#L173

`defnults`

Cheers 👍

**Comment by jlahijani** [comment]
While on topic, "ommitted" to be "omitted":
https://github.com/ryancramerdesign/ProcessWire/search?utf8=%E2%9C%93&q=ommitted&type=Code

**Comment by ryancramerdesign** [comment]
Thanks, fixed.

**Comment by clsource** [comment]
thanks
