### ISSUE TITLE
Filename of image preventing thumbnail display?

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1941]
I have an image called '728x90.jpg'.  When I upload it to a multi-image field, it seems to make it through and the following files get created in the assets files folder:
```
728x90.260x0.jpg
728x90.jpg
```

However the thumbnail display appears blank, as in this screenshot:
![x](https://cloud.githubusercontent.com/assets/4558/17185734/19e52c70-53e7-11e6-978e-c69889897e1b.jpg)

Here is the actual image I am using (make sure to rename to 728x90.jpg... all lowercase):
![728x90](https://cloud.githubusercontent.com/assets/4558/17185747/2745e5ee-53e7-11e6-9fb3-ddb3a95359a2.jpg)

Renaming the file to something else, like 728x91.jpg works fine.  I'm assuming this has something to do with thumbnail filename generation/detection.

Please let me know if you're able to replicate this issue.  I tried it on a few 3.x installations and experienced the issue on all of them.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate it. I'm using that exact image you attached (named 728x90.jpg), but it's uploading just fine and thumbnail showing up fine. Do you have any other modules installed on all the sites you tested it on, that might be involved? Are you modifying $config->adminThumbOptions or $config->imageSizerOptions from your /site/config.php file? Thanks.

**Comment by jlahijani** [comment]
Ah... it was AdBlock.  Closing.
