### ISSUE TITLE
has_parent still not perfect

### ISSUE THREAD

**Issue by er314** [ryancramerdesign/ProcessWire#1942]
has_parent may still miss a valid parent, under specific circumstances.

Here is a scenario to exhibit it : 
- start from blank site
- create the following pages tree, all pages with template basic-page , + /check/ page with template check.php, as below : 
```
Home
    pathA
        pathB
            pathC
                testpage
    pathD
        pathE
            pathF
    check
```
check.php : 
```
<?php
$id = 1021;  // the id of testpage
$the_page = $pages->get($id);
echo "which parents do have page " . $the_page->id . " || " . $the_page->url . " || " . $the_page->title . " ?<br><br>\n";
$i=0; $j=0;
foreach ($pages->find("id>0, include=all") as $current_pg) {
	if (! ($pages->get("has_parent={$current_pg}, id={$id}") instanceof NullPage)) {
		echo "- has_parent : " . $current_pg->id . " || " . $current_pg->url . " || " . $current_pg->title . " " . $pg->url . "<br><br>";
		$j++;
	}
	$i++;
}
echo "<br>end processing, found {$j} has_parent occurrences in all {$i} pages of the site";
?>
```

- now, move testpage to a new location, as child of pathE, with the below result : 
```
Home
    pathA
        pathB
            pathC
    pathD
        pathE
            testpage
            pathF
    check
```
- refresh F5
- now, move again testpage, back to its original location, with the below result : 
```
Home
    pathA
        pathB
            pathC
                testpage
    pathD
        pathE
            pathF
    check
```
- refresh F5
- now, move again, again testpage, once again as child of pathE (yes, I'm not kidding haha), with the below result : 
```
Home
    pathA
        pathB
            pathC
    pathD
        pathE
            testpage
            pathF
    check
```
- refresh F5
- now, if you View /check/ , it will tell you that the parent pages of testpage are : 
```
has_parent : 1 || / || Home 
has_parent : 1019 || /pathd/pathe/ || pathE 
```
-> but pathD is missing

**Comment by ryancramerdesign** [comment]
Thanks @er314 I'm hoping to cover this one soon. This one takes a little more setup than most issue reports. Thank you for the excellent instructions on how to reproduce.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. Please let me know if you continue to experience it. Note that you'll have to move the page once more around in that tree before it'll fix.

**Comment by er314** [comment]
Ok, it seems ok on a few tests, thanks !
Note that I did not perform tests of moving pages via API (instead of via GUI) ; so I can't say if the problem was also existing when moved via API, and if this does fix it too.

BTW, thanks for bringing hanna-code up to date !
