### ISSUE TITLE
Edit repeater field, duplicated »and« ;)

### ISSUE THREAD

**Issue by justonestep** [ryancramerdesign/ProcessWire#1943]
There is a duplicated **»and«** in the „Notice“ text.

`Setup > Fields > Edit Field: Repeater > Details > Delete old/unused repeater items?`

> A repeater item is considered old if it is at least 3 days **and and** not yet been populated or published.

![screen shot 2016-07-28 at 08 33 45](https://cloud.githubusercontent.com/assets/4669205/17203254/9dc2c9be-549e-11e6-893a-91b461e64d74.png)

**Comment by ryancramerdesign** [comment]
Thanks, my mind always seems to collapse doubled words to one, so I seem to
make this same mistake often! I've fixed and it'll appear in one of the
next commits.
