### ISSUE TITLE
Edit user, can't add repeater item with »dynamic loading«

### ISSUE THREAD

**Issue by justonestep** [ryancramerdesign/ProcessWire#1944]
ProcessWire 3.0.x (noticed using 3.0.15, still occurs in 3.0.27).

If I edit an user, I'm not able to use **dynamic loading**:

`Edit Field: Repeater > Tab Details >  Repeater dynamic loading (AJAX) in editor` defaults to `Existing and new items (recommended, especially for repeaters that might have LOTS of items)`

Using this setting (the same counts for the second option `New items only (good for repeaters that will have only a FEW items)`) it's not possible to add a repeater item. After clicking *»Add New«* a loader appears for a short time but nothing happens. If I turn this setting off, it'll works. This behaviour occurs only if I edit an user.

![_repeater](https://cloud.githubusercontent.com/assets/4669205/17204084/aa2290f4-54a3-11e6-8b7e-3f4dad7a82a6.gif)

**Comment by ryancramerdesign** [comment]
Ajax support has been limited from the User editor, since it's a little different context. But I think I've been able to get it working in the latest commit. Please let me know if you continue to see any issues. Thanks.

**Comment by justonestep** [comment]
Thanks!
