### ISSUE TITLE
ProcessRecentPages.module small syntax bug

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1946]
Notice: Array to string conversion in .../wire/modules/Process/ProcessRecentPages/ProcessRecentPages.module on line 278
I solved it with:
`$out .= "<p>$this->{labels['nothing']}</p>";`

screenshot
![bildschirmfoto 2016-07-28 um 17 24 08](https://cloud.githubusercontent.com/assets/4683120/17218466/2b169c0c-54e8-11e6-84e6-0e7acbc22902.jpg)

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for the issue.
