### ISSUE TITLE
Some observations with editing field type Image (new) and field type File

### ISSUE THREAD

**Issue by ottogal** [ryancramerdesign/ProcessWire#1948]
PW 3.0.24 devns
Language is chosen as de-DE

![shot-1](https://cloud.githubusercontent.com/assets/756884/17243199/96b2bc00-557b-11e6-803c-30e6a21e1ad3.png)

(1) The caption of the button _Chose File_ remains in English.

(2) With an Image field the DropHere description is in English too. (With a File field it's correctly in German).

(3) Hovering over the DropHere description, with the Image field the cursor is changing to a link icon (hand) without sense.

(4) With a viewport width lower than 840 the DropHere description is lost. (May be that's intentional, as not useful on mobiles?)

**Comment by tbba** [comment]
The German language files are not including the very latest PW3 beta features.
That is known - and not a problem of the Processwire core but a decision of the German translation project team. It would be best to discuss this on [their project page](https://github.com/yellowled/pw-lang-de), if you like.

**Comment by processwired** [comment]
@ottogal You can use Manfred's repository at https://github.com/Manfred62/pw-lang-de-devns

**Comment by ottogal** [comment]
Thank you both for these hints. Manfred's repository helped me out.
