### ISSUE TITLE
Dashes in user names do not work

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessWire#1949]
I can change user names to something like _test-user_, but I am not able to login with such a name (without any error). When I change the name to _testuser_ everything works.

Field description says says "Any combination of letters (a-z), numbers (0-9), dashes or underscores (no spaces)."

We should either change the description or (preferably) allow dashes.

**Comment by ryancramerdesign** [comment]
Dashes are valid for usernames. I can't duplicate an issue here. Just created a user named "ryan-cramer" and was able to login as normal. Is it possible there's some other module involved here? Btw, I'm testing in PW 3.0.27, though can't recall any past issues regarding dashes and usernames. But still would be good to know what version you are using. Users are just pages like any other page and use the same rules for the name as any other page. Are there any page name specific settings defined in your /site/config.php file? Thanks.

**Comment by ivangretsky** [comment]
Was too quick to write an issue. It happened that it was my own code removing dashes. Sorry for that.
