### ISSUE TITLE
Getting selectable pages api

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1950]
It would be nice if getting the selectable pages of a page field would not be that verbose and somehow in need to supply $page multiple times. 

```php
$page->fieldgroup->get('cpool_country')->type->getInputfield($page)->getSelectablePages($page);
```

```php
$page->getInputfield('cpool_country')->getSelectablePages($page);
// Not sure why it does even need the page obj again.
$page->getInputfield('cpool_country')->getSelectablePages(); 
```

**Comment by ryancramerdesign** [comment]
I understand that may seem like extra verbosity, but Inputfield objects are designed to exist independent of anything Page related. While some may use the current $page (like the one in your example) Inputfield objects have no assumption of a "page editor". For instance, when using a Page field in FormBuilder or something similar, there's not going to be any Fieldtype::getInputfield call involved there. So if an Inputfield is designed to be portable (able to work outside the page editor) and if it needs something like a Page, then it's got to ask for it via a method argument.

We already have a Page::getInputfields() method which optionally accepts a field name, but always returns an InputfieldWrapper. I could certainly add a Page::getInputfield() method which just returns the requested Inputfield instead. But I'm not sure that's what you are asking about here, as something like getSelectablePages() is still going to need a copy of the Page object either way.

**Comment by LostKobrakai** [comment]
Yeah just having the option to get the inputfield without wrapper would make it a lot less verbose. With your FormBuilder example the getSelectablePages parameter does make a lot more sense and getting rid of it was just a option I wanted to be thought about. A getInputfield() function is the important one here.

**Comment by ryancramerdesign** [comment]
Sounds good, I'll add a getInputfield() method to Page.
