### ISSUE TITLE
integrate pw 2.8 in upgrades manager and "required" module option

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1957]
![image](https://cloud.githubusercontent.com/assets/8488586/17326914/de7ef4fe-58b4-11e6-9e49-1560de72db2e.png)

also when a module requires features of pw 3 it may be that it also runs on 2.8... maybe that could also be thought of when a module uses something like 'requires'  => 'ProcessWire>=3.0.1'

**Comment by ryancramerdesign** [comment]
Do you mean the non-core ProcessWireUpgrade module? I do have some pending updates there, but those will come after wrapping up 3.x core. And I definitely plan to add 2.8 repo to it. As for required module versions, it's still possible that a module could support 2.8 and not 3.x, or the other way around, so don't want to make any assumptions there. Though 2.8 will at least let you install 3.x modules–it'll give you a warning about it, but it'll let you do it.

**Comment by BernhardBaumrock** [comment]
i'm talking about this module: http://modules.processwire.com/modules/process-wire-upgrade/
ok that's just fine :) only thing really missing is a possibility to upgrade from 2.8.28 to 2.8.29 and NOT 3.0.29
