### ISSUE TITLE
Bug: Text field value gets wiped if field is inside Fieldset that's set to "Closed + Load only when opened (AJAX)"

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1961]
Let's say you have a fieldset with the visibility set to "Closed + Load only when opened (AJAX)".

Let's say there is a regular text field in that fieldset.

If you put a value for that text field and save, the value will be saved.

If you save the page again (**but without opening the fieldset**), the value will get wiped!

Tested on today's latest commit and an older installation (3.0.25).

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani not sure how this one has survived so long, thanks for tracking it down. This was a tricky one to track down, but I think I've got it fixed now.
