### ISSUE TITLE
Having more than 2 FieldsetTabs in a template results in an error when saving a page.

### ISSUE THREAD

**Issue by grimezy** [ryancramerdesign/ProcessWire#1965]
I believe this only appeared in 3.0.29.

Having the default tab and adding 2 more custom tabs results in this error.  Have default and 1 more tab works fine, however...

...using a 3rd party module such as Markup SEO which adds a custom FieldsetTab to a chosen template also results in the error? - having the default tab and the installed module which adds the SEO tab results in the error.

Have tested this on a vanilla install.

Default and 2 more custom tabs:
![tabs](https://cloud.githubusercontent.com/assets/18278963/17459714/97e9f60c-5c87-11e6-8b78-3dc110a80955.png)

Error thrown when page is saved using a template with default and 2 suctom tabs:
![pw3029_tabs](https://cloud.githubusercontent.com/assets/18278963/17459666/75f14aca-5c85-11e6-998f-520bb3879027.png)

Thanks.

**Comment by cb2004** [comment]
I am also seeing this error

**Comment by rolandtoth** [comment]
Same here.

**Comment by fuzenco** [comment]
Seeing this also after 3.0.29. Here's what I posted on the ProcessWire forums:
[error post](https://processwire.com/talk/topic/13948-pw-3029-2829/?do=findComment&comment=125473)

I do have an additional tab but it’s not from a 3rd party module. It's an SEO tab I created with the built-in abilities of ProcessWire.

**Comment by TomS-** [comment]
Yup also getting this error

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this.

**Comment by TomS-** [comment]
Fixed

**Comment by fuzenco** [comment]
I confirmed it’s fixed. Thanks so much guys!

**Comment by cb2004** [comment]
Confirmed fix. @grimezy please close the issue.

**Comment by grimezy** [comment]
Confirmed fixed. Thanks.  Will now close the issue.
