### ISSUE TITLE
Feature request: pass array of variables to $page->renderField()

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1967]
It would be great to be able to pass an array of our own variables to be used in $page->renderField() and $page->renderValue(), similar to what can be done with wireRenderFile()/[$files->render()](https://processwire.com/api/ref/files/render/) and the original [$page->render($options)](https://processwire.com/talk/topic/3145-multiple-views-for-templates/?do=findComment&comment=32876).

**Comment by yckart** [comment]
Possible duplicate of #1680
