### ISSUE TITLE
 Long UTF8 (Chinese) page name cause error

### ISSUE THREAD

**Issue by gideonso** [ryancramerdesign/ProcessWire#1968]
I tried the UTF8 page name function. I whitelisted 3000 Chinese characters. It is indeed very good but it seems limit the number of Chinese Character to 16. If the page name is more than 16 Chinese Characters, the whole backend become a blank page. I enabled the debug mode and found this error:

( ! ) Fatal error: Maximum function nesting level of '256' reached, aborting! in /home2/web/testserver/WireCore-3.0/core/Sanitizer.php on line 551

I tried increase the max_nesting_level of xdebug but whatever value I set still get the same error. If disable xdebug, it just shows a message "connection timeout". 

Attached a screen shot of last two lines of the debug report.

![2016-08-07 14-26-23](https://cloud.githubusercontent.com/assets/16899800/17500496/9c8e3f9c-5e08-11e6-9178-7dbb7000a188.png)

Processwire version 3.0.28
php version 7.0.0
OS: Linux

Gideon So

**Comment by ryancramerdesign** [comment]
Thanks @gideonso – could you paste in your `$config->pageNameWhitelist`, as well as the page name you were attempting to set (or an example of one that would trigger the error).

**Comment by gideonso** [comment]
"pageNameWhitelist": "-_.abcdefghijklmnopqrstuvwxyz0123456789æåäßöüđжхцчшщюяàáâèéëêěìíïîõòóôøùúûůñçčćďĺľńňŕřšťýžабвгдеёзийклмнопрстуфыэęąśłżź一是在不了有和人這中大為上個國我以要他時來用們生到作地于出就分對成
會可主發年動同工也能下過子說產種面而方後多定行學法所民得經十三之進著等部度家電力裡如水化高自二理起小物現實加量都兩體制機當使點從業本去把性好應開它合還因由其些然前外天政四日那社義事平形相全表間樣與關各重新線內數>正心反你明看原又麼利比或但質氣第向道命此變條只沒結解問意建月公無系軍很情者最立代想已通並提直題黨程展五果料象員革位入常文總次品式活設及管特件長求老頭基資邊流路級少圖山統接知較長將組見計別她手角期根論運農指幾九區>強放決西被幹做必戰先回則任取據處隊南給色光門即保治北造百規熱領七海地口東導器壓志世金增爭濟階油思術極交受聯什認六共權收證改清已美再採轉更單風切打白教速花帶安場身車例真務具萬每目至達走積示議聲報鬥完類八離華名確才>科張信馬節話米整空元況今集溫傳土許步群廣石記需段研界拉林律叫且究觀越織裝影算低持音眾書布復容兒須際商非驗連斷深難近礦千周委素技備半辦青省列習響約支般史感勞便團往酸歷市克何除消構府稱太準精值號率族維劃選標寫存候毛>親快效斯院查江型眼王按格養易置派層片始卻專狀育廠京識適屬圓包火住調滿縣局照參紅細引聽該鐵價嚴首底液官德調隨病蘇失爾死講配女黃推顯談罪神藝呢席含企望密批營項防舉球英氧勢告李台落木幫輪破亞師圍注遠字材排供河態封另施>減樹溶怎止案言士均武固葉魚波視僅費緊愛左章早朝害續輕服試食充兵源判護司足某練差致板田降黑犯負擊範繼興似餘堅曲輸修的故城夫夠送筆船佔右財吃富春職覺漢畫功巴跟雖雜飛檢吸助昇陽互初創抗考投壞策古徑換未跑留鋼曾端責站簡>述錢副盡帝射草衝承獨令限阿宣環雙請超微讓控州良軸找否紀益依優頂礎載倒房突坐粉敵略客袁冷勝絕析塊劑測絲協重訴念陳仍羅鹽友洋錯苦夜刑移頻逐靠混母短皮終聚汽村雲哪既距衛停烈央察燒行迅境若印洲刻括激孔搞甚室待核校散侵吧>甲遊久菜味舊模湖貨損預阻毫普穩乙媽植息擴銀語揮酒守拿序紙醫缺雨嗎針劉啊急唱誤訓願審附獲茶鮮糧斤孩脫硫肥善龍演父漸血歡械掌歌沙著剛攻謂盾討晚粒亂燃矛乎殺藥寧魯貴鐘煤讀班伯香介迫句豐培握蘭擔弦蛋沉假穿執答樂誰順煙縮>徵臉喜松腳困異免背星福買染井概慢怕磁倍祖皇促靜補評翻肉踐尼衣寬揚棉希傷操垂秋宜氫套筆督振架亮末憲慶編牛觸映雷銷詩座居抓裂胞呼娘景威綠晶厚盟衡雞孫延危膠還屋鄉臨陸顧掉呀燈歲措束耐劇玉趙跳哥季課凱胡額款紹卷齊偉蒸殖>永宗苗川爐岩弱零楊奏沿露桿探滑鎮飯濃航懷趕庫奪伊靈稅了途滅賽歸召鼓播盤裁險康唯錄菌純藉糖蓋橫符私努堂域槍潤幅哈竟熟蟲澤腦壤碳歐遍側寨敢徹慮斜薄庭都納彈飼伸折麥濕暗荷瓦塞床築惡戶訪塔奇透梁刀旋跡卡氯遇份毒泥退洗擺>灰彩賣耗夏擇忙銅獻硬予繁圈雪函亦抽篇陣陰丁尺追堆雄迎泛爸樓避謀噸野豬旗累偏典館索秦脂潮爺豆忽托驚塑遺愈朱替纖粗傾尚痛楚謝奮購磨君池旁碎骨監捕弟暴割貫殊釋詞亡壁頓寶午塵聞揭砲殘冬橋婦警綜招吳付浮遭徐您搖谷贊箱隔訂>男吹樂園紛唐敗宋玻巨耕坦榮閉灣鍵凡駐鍋救恩剝凝鹼齒截煉麻紡禁廢盛版緩淨睛昌婚涉筒嘴插岸朗莊街藏姑貿腐奴啦慣乘夥恢勻紗扎辯耳彪臣億璃抵脈秀薩俄網舞店噴縱寸汗掛洪著賀閃柬爆烯津稻牆軟勇像滾釐蒙芳肯坡柱盪腿儀旅尾軋冰>貢登黎削鑽勒逃障氨郭峰幣港伏軌畝畢擦莫刺浪秘援株健售股島甘泡睡童鑄湯閥休匯舍牧繞炸哲磷績朋淡尖啟陷柴呈徒顏淚稍忘泵藍拖洞授鏡辛壯鋒貧虛彎摩泰幼廷尊窗綱弄隸疑氏宮姐震瑞怪尤琴循描膜違夾腰緣珠窮森枝竹溝催繩憶邦剩幸>漿欄擁牙貯禮濾鈉紋彈罷拍咱喊袖埃勤罰焦潛伍墨欲縫姓刊飽仿獎鋁鬼麗跨默挖鏈掃喝袋炭污幕諸弧勵梅奶潔災舟鑑苯訟抱毀率懂寒智埔寄屆躍渡挑丹艱貝碰拔爹戴碼夢芽熔赤漁哭敬顆奔藏鉛熟仲虎稀妹乏珍申桌遵允隆螺倉魏銳曉氮兼隱礙>赫撥忠肅缸牽搶博巧殼兄杜訊誠碧祥柯頁巡矩悲灌齡倫票尋桂鋪聖恐恰鄭趣抬荒騰貼柔滴猛闊輛妻填撤儲簽鬧擾紫砂遞戲吊陶伐餵療瓶婆撫臂摸忍蝦蠟鄰胸鞏擠偶棄槽勁乳鄧吉仁爛磚租烏艦伴瓜淺丙暫燥橡柳迷暖牌纖秧膽詳簧踏瓷譜呆賓糊>洛輝憤競隙怒粘乃緒肩籍敏塗熙皆偵懸掘享糾醒狂鎖澱恨牲霸爬賞逆玩陵祝秒浙貌役彼悉鴨著趨鳳晨畜輩秩卵署梯炎灘棋驅篩峽冒啥壽譯浸泉帽遲硅疆貸漏稿冠嫩脅芯牢叛蝕奧鳴嶺羊憑串塘繪酵融盆錫廟籌凍輔攝襲筋拒僚旱鉀鳥漆沈眉疏添>棒穗硝韓逼扭僑涼挺碗栽炒杯患餾勸豪遼勃鴻旦吏拜狗埋輥掩飲搬罵辭勾扣估蔣絨霧丈朵姆擬宇輯陝雕償蓄崇剪倡廳咬駛薯刷斥番賦奉佛澆漫曼扇鈣桃扶仔返俗虧腔鞋稜覆框悄叔撞騙勘旺沸孤粘吐孟渠屈疾妙惜仰狠脹諧拋霉桑崗嘛衰盜滲臟>賴湧甜曹閱肌哩厲烴緯毅昨偽症煮嘆釘搭莖籠酷偷弓錐恆傑坑鼻翼綸敘獄逮罐絡棚抑膨蔬寺驟穆冶枯冊屍凸紳坯犧焰轟欣晉瘦禦錠錦喪旬鍛壟搜佛撲邀亭酯邁舒脆閒憂酚頑羽漲卸仗陪薄闢懲杭姚肚捉飄漂昆欺吾郎烷汁呵飾蕭雅郵遷燕撒姻赴>宴煩削債帳斑鈴旨醇董餅雛姿拌傅腹妥揉賢拆歪葡胺丟浩徽昂墊擋覽貪慰繳汪慌馮諾姜誼兇劣誣耀昏躺盈騎喬溪叢盧抹易悶咨刮駕纜悟摘鉺擲頗幻柄惠慘佳仇臘窩滌劍瞧堡潑蔥罩霍撈胎蒼濱倆捅湘砍霞邵萄瘋淮遂熊糞烘宿檔戈駁嫂裕徙箭捐>腸撐曬辨殿蓮攤攪醬屏疫哀蔡堵沫皺暢疊閣萊敲轄鉤痕壩巷餓禍丘玄溜曰邏彭嘗卿妨艇吞韋怨矮歇郊祿捻漠粹顛宏冤肪飢呵仙押挨醛娃拾沒佩勿嚇訛侯戀夕鋅篡戚淋蓬豈釉兆泊魂拘亡槓摧氟頌渾凌鈾誘犁譴頒舶扯嘉萌猶滋焊舌匹媳肺掠釀烹>疲馳鴉窄辱狹樸遣菲姦韌辣拳稈臥醉竭茅墓矣哎艷敦輿締雇尿葬履契禽渣襯躲賠咸溉賊醋堤抖妃褲廉晴挽掀茫醜亥攔悠闡慧佐奇豎孝櫃麟繡遙逝愁肖昭芬逢窯捷圜盲閘宙輻披賬狼幽綢蜂慎餐酬誓惟叉彌址幟芝砌欸僕濤臭翠盒劫慨炳闔寂椒倘>拓畏喉巾頸墾拚獸蔽蘆乾爽竊譚掙崩模褐傳翅儒傘晃謬胚剖湊眠濁霜礁蔑抄闖灑碑蓉耶猜蹲壺喚澳鋸郡玲綿紐梳掏籲錘鼠穴椅殷遮吵萍厭畜俱誇呂囊捧雌閩饒瞬鬱哨鑿朝俺滸茂肝勳盯籽恥菊濫稼戒奈帥鞭蠶鎂詢跌烤壇宅笛鄂蠻顫棍睜鼎岌降>侍藩嚷匪岳糟纏迪洩卑氛堪蘿盛碘縛悅澄甫攀屠溢拱晰攜朽吟菱謙凹俊芒盼嬸艘趁唇挫羞浴疼萎餚愚腫刨絞樞嫁慕艙鏟蘋豫諭迭潘頃翁榜匠欠茬疇胃沾蹤弊哼鵬歧桐沃悼惑潰蔗薦潭孢露診庸聰嫌廚龐祁鉗肆梭贈崖籃穎甸藻搗且撕詔貞賜慈炕>胖茲差瓊鏽汛卓棵饋撓灶嬰蒂膚衫瀝崙勉滬逸蜜浦嗓暈膏祭贏艾扮鵝憐蒲兔孕嚦蘗挪淑謠懼廊緬俘驕膀陡宰誕峻惱腺獵渦夷愉魔銨葛賈似蔭喲脊鈔苛錳橢鑲杏溴倚滯會氓捏斬傲匆僵滷燙衍榨攏裸屑咽坊舅渴翔邪拄窖貓砌欽媒脾勺柏柵噪晝耿>扁辰秤得販糕梁曇衷宦扔哇詐囑藤卜岡悔廓皂拐氰杉瑪矢寓瓣罕垮筍淘銜稱恭喇帕桉秉簾銘蛇摔齋叭帆裸儉瘤篷砸肢闢脖瞪暑卜竿殲笙酮蘊嘩瞎喀刃楔喘枚嵌撾廂粵甩拴膝懇腕娓熄錨忌愧哦荊圃騷丸蒜毯弗俯鹿梢屯衙轎賤壘諒踢啞滔渥餉泳>棕熬擱梨吻櫻奠捆姨柏聘惕鄆綁冀裹酥寡彥稠啡鈍汝擅汰埔敞嘿遜棟謹咖鯉雀傭庵葫賄鱗拼搏謊塌忉膩戊怖墳禾剎嘻桔坎拇煽獅癢曾梗寇鷹燭哄莽雯胳龜亟糠泌坪傻什喻淵蚌跪巷涅釗譬蕊膛侮奕枕辮況扼郝寥淒廈腥鈞耦蹄戥屁誦匈樁釣涵倦>袍抒嶼蹈忿敷虹聊嗣尉燦糙蹬嗯姬狡笨辜僧茨諷翰枉岐棗嶄焚咕猴攬澇耍趟洶咋傍鍍給爵虜劈璋踩瞅迄昔汞呱詭魄祺嘲惶贓癌咐歉扳鄙廬聶便芡軀貶煌擰隋襄淤寵炊滇謇懶栓佑憾駱裙猖兜孵痼盥曝泣絮韻眷曠噢參棲盞鰲濺煎校榴暮琪淆陛巢>噠吼槐唧其沛乞蜀蜇賺捍鉸冪堯咒耽叮褂煥煞雹搓釜鉻揀募淹瑰鰱茄灼鄒躬覺嬌焉彰鶴琳淪畔惹庶斃皖邢禹漬繃竄翹淫簞陌膊韃咳玫巫拂蕉瀾贖綏鋤囪賭頰縷寅躁稚庚苟氦魁珊蛻蛭酌逗閨蔓撇豌朕緝襟鎳桅熒姪卒佃瞿娶飪聳乍靶痴靖摃筐韶>囂崔蓿岔氘娥剿霖喃搪雍裳撰豹駿慷温誌祈禱註曆",

Then you just need to make the page name longer than 17 characters. For example, 一二三四五六七八九十十一十二十三十四.

Thanks for your response, @ryancramerdesign 

Gideon So

**Comment by ryancramerdesign** [comment]
Thanks @gideonso I've pushed a fix for this issue.

**Comment by gideonso** [comment]
Hi Ryan,

Confirm that it is fixed. Thanks for your quick and great effort.

Gideon
