### ISSUE TITLE
Name Format Children Option creates 2 pages instead of 1 since 3.0.9

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1971]
![bildschirmfoto 2016-08-09 um 16 14 03](https://cloud.githubusercontent.com/assets/4683120/17519472/5a923550-5e4c-11e6-909c-b84225f09c46.jpg)

I am using the 'Name Format Children' option. But two pages are created instead of a single one.
This happens with Versions 3.0.9 and up.
Until 3.0.8 everything is working as expected.

**Comment by ryancramerdesign** [comment]
Not seeing the issue here. What is the name format that you are using (I'm using "title"), and what's the version of PW that you are using? (I'm using 3.0.29)

**Comment by kixe** [comment]
I am using title too. I tried out (nearly) all versions between 3.0.1 and 3.0.29
As I said it works until 3.0.8 and not from 3.0.9 up.

**Comment by ryancramerdesign** [comment]
I'm unable to duplicate this one. Anybody else seeing the issue? The only thing I can guess is maybe a hook or module is involved somewhere in the process.

**Comment by isellsoap** [comment]
I’m also unable to reproduce this issue following the exact steps you mentioned on a fresh 3.0.34 installation. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
