### ISSUE TITLE
More than one FieldsetTab in PW 2.8

### ISSUE THREAD

**Issue by NilsWiere** [ryancramerdesign/ProcessWire#1972]
Today I installed PW 2.8.29, which works great so far – except this small problem:

As soon as I assign more than one FieldsetTabOpen Field to a template I get this error message whenever I try to save a page using that template:

Error: Call to a member function add() on null (line 629 of /.../processwire/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module) 

When I delete the second FieldsetTab in the template, everything works es expected again. 

Could this be a bug or am I missing something here?

**Comment by ryancramerdesign** [comment]
Hi Nils, I had fixed this one on a commit yesterday, hadn't pushed the
commit to 2.8.29 yet. I've just pushed it, so it should be there now.
Thanks.

**Comment by NilsWiere** [comment]
Yep, it's working now – thanks!
