### ISSUE TITLE
MySQL Strict Mode causes PW installation to fail

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1975]
```
CREATE TABLE `modules` ( ... `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ... ) ...
and
CREATE TABLE `pages` ( ... `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ... ) ...
```
 
The “DEFAULT '0000-00-00 00:00:00'” on the “created” column of these two tables causes failure when the return value of “SELECT @@GLOBAL.sql_mode” includes “NO_ZERO_IN_DATE”.
 
This could be replaced with CURRENT_TIMESTAMP:
 
`... `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ...`

At the very least it seems like PW should check the MySQL setting before trying to install, to avoid failure when it goes to create the modules and pages tables.

**Comment by Toutouwai** [comment]
A related forum thread: https://processwire.com/talk/topic/13987-installation-issue-digitalocean-serverpilot/

**Comment by ryancramerdesign** [comment]
This one was fixed awhile ago (in 2.8 and 3.x). Which version are you seeing it in?

**Comment by thetuningspoon** [comment]
Version is 3.0.29

**Comment by ryancramerdesign** [comment]
PW 3.x doesn't have any SQL statements like the ones quoted in your original message (though it did in 2.7). Is it possible those are coming from a 3rd party profile or module instead? All of PW's install.sql files use definitions like this for timestamp columns: 
``````
`created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
```````

**Comment by thetuningspoon** [comment]
I am using a third party (my own) profile, so that must explain it. I didn't realize that that would affect how the core tables are installed, aside from adding some additional data.

**Comment by isellsoap** [comment]
@thetuningspoon Can this issue be closed?

**Comment by thetuningspoon** [comment]
Yes, thank you.
