### ISSUE TITLE
Incorrect return value in PageArray::get 3.0 

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1977]
```php
$page->usages->get("revision=$lastRevision");
```
The above will return false if nothing is found in the PageArray, but it's [supposed to return null](https://processwire.com/api/ref/wire-array/get/). This is because findOne is using ->first(), which in turn is using reset($this->data).

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this.
