### ISSUE TITLE
SessionLoginThrottle bug doesn't keep attempts in DB 

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#198]
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Session/SessionLoginThrottle/SessionLoginThrottle.module#L102

Shouldn't this be $allowed = false?

Because I can't get it to work and save attempts because it deletes the entry right after with the OR name=

**Comment by LostKobrakai** [comment]
@somatonic @tbba Is this still an issue? Might be fixed by this one https://github.com/ryancramerdesign/ProcessWire/commit/a5b84e011d94c5524cc86029edf083f33b00685a If not could you please close this soma?

**Comment by tbba** [comment]
never had the issue since a long while... can be closed i.m.h.o.

**Comment by isellsoap** [comment]
@somatonic Can you please close this issue? Thank you!

**Comment by isellsoap** [comment]
@somatonic Ping. Can you please close this issue? Thank you!
