### ISSUE TITLE
checkbox value recovery

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1981]
when i submit a pageedit with a required field that is not filled it throws an error BUT the checkbox that was checked before is unchecked after that.

all other fields hold their values correctly.

**Comment by cb2004** [comment]
@BernhardBaumrock I was experiencing the same as this a few weeks back but didn't have a chance to look into it properly. I changed tactics to get round it but I believe it is an issue.

**Comment by ryancramerdesign** [comment]
What version did you see the issue in? I've just tried reproducing it in PW 3.0.30 but not able to observe the issue taking place. 

My setup is a single checkbox field, and a required "title" field. I check the box and save. Then I make the "title" blank, and save. The next screen gives me an error about the blank title, but the checkbox remains checked. 

Any other factors you can think of that might help me reproduce it?

**Comment by cb2004** [comment]
@ryancramerdesign I forget what version I was experiencing this in. If I remember correctly I may have had a required if stipulation on the checkbox. @BernhardBaumrock may be able to comment more as I worked around this at the time.

**Comment by BernhardBaumrock** [comment]
hmmm, thank you @ryancramerdesign 
unfortunately i can't remember where it happened. i tried it again and it seems to work here... if it comes up again i will create a new issue with more information. i'll close this one.
sorry for stealing you time...
