### ISSUE TITLE
Backwards compatibility for PagesType constructor

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1985]
The constructor of PagesType in 2.8/3.0 [expects three parameters](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/PagesType.php#L77), starting with an instance of ProcessWire:

`public function __construct(ProcessWire $wire, $templates = array(), $parents = array()) {`

In earlier versions this same method [only expected two parameters](https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/core/PagesType.php#L68):

`public function __construct($templates = array(), $parents = array()) {`

If you could tweak the 2.8/3.0 implementation so that this newly required argument (`$wire`) is the last one instead of being the first one, it would be easy to instantiate PagesType in a way that supports both versions (since extra params don't matter in PHP).

Alternatively accepting params in both orders might be worth considering. While this would mean ditching the benefits of type hinting, unless my memory fails me that's already what some parts of the core do and, in my opinion, the benefits would be far greater than the negative implications.

Any chance you could reconsider the new implementation? I'm currently trying to solve [an issue this change has caused for UserGroups](https://github.com/apeisa/UserGroups/issues/45), but it would be wonderful if there was a solution that worked for all versions without the need to include version checks etc. extra baggage. Tried to ping you via the UserGroups repository earlier, but you probably missed that.

Thanks for considering this! :)

**Comment by LostKobrakai** [comment]
I can see where you're coming from, as this will bite me as well, because I'm using custom PageTypes quite often. But when actually using those PageTypes by your proposal it would seem quite strange to me to write it like this: `$roles = new Roles(array(), array(), $wire)`.

**Comment by teppokoivula** [comment]
Agreed, that doesn't look good at all. Even worse, this would still require changes for 2.8/3.0 compatibility, so it's only partial solution. Looks like I *really* didn't think that option through :)

This leaves us with the ability to provide options in multiple orders: if the first param is an instance of ProcessWire treat it like that, otherwise expect an array. Something like this:

```
public function __construct($wire = null, $templates = array(), $parents = array()) {
    // backwards compatibility ProcessWire < 2.8
    if ($parents instanceof ProcessWire) {
        $_wire = $parents;
        $parents = $templates;
        $templates = $wire;
        $wire = $_wire;
    }
    if (!$wire instanceof ProcessWire) {
        throw new WireException("Provide an instance of ProcessWire as the first param");
    }
   ...
}
```

Another option would be leaving this as-is. That will break any code that relies on the earlier implementation of PagesType, but as long as such breaking change are properly documented that's always an option. For existing codebases that need to support both versions, that would mean adding something like this:

```
if (version_compare($config->version, '2.8', '<')) {
    $groups = new PagesType($template, $parent);
} else {
    $groups = new PagesType($wire, $template, $parent);
}
```

**Comment by LostKobrakai** [comment]
The latter one is exactly how Ryan implemented it in the DynamicRoles module. I feel like it's the cleaner solution. I prefer the single clear documented way to the "you know we were unsure" multiple implementation, especially as you noted, the $wire parameter has to be added anyways.

**Comment by teppokoivula** [comment]
Thanks for mentioning the DynamicRoles example!

Sounds to me like Ryan might've already made up his mind regarding this one. I'm leaving this issue open for a while in case the man himself has any opinions to share, but looks like I should just suck it up and solve this with `version_compare()`.

In this case a few lines of extra code in the module are perfectly fine :)

**Comment by ryancramerdesign** [comment]
I know where you are coming from and this was one of the 2.7 to 3.x things I didn't like having to do, but seemed like it was necessary. Current PW instance is pretty much critical in PW3, whereas there could only ever be one instance in PW 2.7 so it didn't matter. I figure since it's going to need that $wire instance either way (in 2.8+/3.0+), there's not much getting around having to do something or another here. Actually didn't realize anyone else was using this other than me. I have a feeling you might be the only two others. We ought to start a support group for survivors of this. :)

**Comment by LostKobrakai** [comment]
I even wrote a tutorial about using custom page types. Would be strange if I wouldn't use them :) It's kinda like extending Eloquent in Laravel to have different models.
