### ISSUE TITLE
Use servertime instead of NOW()

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1989]
I've some time ago had the issue, that the mysql timezone didn't match with the php (config.php) timezone and therefore `created` and other system dates where off by the difference. Wouldn't it be more failsave to supply the timestamp of php instead?

**Comment by rwetzlmayr** [comment]
This would also help MySQL [to cache queries](https://dev.mysql.com/doc/refman/5.5/en/query-cache-operation.html):

>  A query cannot be cached if it contains any of the functions shown in the following table.
> [...] NOW()

**Comment by LostKobrakai** [comment]
I'm not really sure if this is an relevant issue if we're talking about queries holding a creation timestamp, which is literally different every second granted that the created pages are even the same.
