### ISSUE TITLE
Cannot redeclare error when using module disable checkbox with certain modules

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1990]
```
Fatal error: Cannot redeclare class ProcessWireUpgradeCheckConfig in /Users/ajones/Sites/pw3/site/assets/cache/FileCompiler/site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.config.php on line 21

Compile Error: Cannot redeclare class ProcessWireUpgradeCheckConfig (line 21 of /Users/ajones/Sites/pw3/site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.config.php) 
```

I haven't tested thoroughly yet, but I wonder if this might be a common issue with all modules using a separate `.config.php` file?

I think the only way to recover from this is direct manipulation of the db to manually change the module's flag field to remove `disable` from it.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this issue. Btw, the disable option is kind of dangerous in some cases. I'd avoid using it if you can. I'd moved it to advanced mode only option, but have sometimes wondered if I should remove the option completely because there are some cases where it could ruin things.

**Comment by adrianbj** [comment]
I realize it has potential to do damage. I am wondering if you have had any thoughts on a better approach that might not be as risky.

I have added a Module Disabler panel to Tracy (protected by advanced and debug mode) to make it easy to quickly disable all autoload modules. @rolandtoth has taken a different approach with AdminOnSteroids - he is storing module settings on uninstall so that they are restored when the module is reinstalled (https://processwire.com/talk/topic/13389-adminonsteroids/?do=findComment&comment=126894). I am tempted to have the Module Disabler panel use a similar method to his, but not actually sure whether it might come with its own set of problems - for example modules that install custom DB tables will likely lose this data (assuming their uninstall routine automatically deletes these).

**Comment by rolandtoth** [comment]
The approach I'm using in my module serves different purpose, I just basically dump and re-import module config data:

```php
public function ___install() {
    // apply default module settings on install or use settings.php
    @$settings = file_get_contents($this->settingsFile);
    $settings = $settings ? json_decode($settings, true) : self::getDefaultData();
    $this->wire('modules')->saveModuleConfigData($this, $settings);
}

public function ___uninstall() {
    // save current config to settings.php
    @file_put_contents($this->settingsFile, json_encode($this->modules->getModuleConfigData($this)));
}
```
There are no module dependencies in AdminOnSteroids so I don't have to deal with that.

Another workaround for disabling a module is to have a dedicated "enabled" field in the module and module developers should add this if their modules can be disabled. This way a module could be easily disabled provided if it has such field.

**Comment by adrianbj** [comment]
Right - I realized after looking at your new version of AOS that the module settings was just for your module - for some reason I thought it was for all.

I am contemplating adding an "Uninstall" vs the existing "Disable" option to the Tracy Modules panel. I would do something very similar to what you have, but instead store the settings for all uninstalled modules either in Tracy's config settings db field, or perhaps a json file in /site/assets/cache/TracyDebugger/modulesettings.json

Maybe this would be a safer option than the disabled flag. I am just worried about other custom things that modules do like setting up their own db tables, or custom fields/templates - it gets complicated :)

**Comment by ryancramerdesign** [comment]
The disable option that's currently in PW is perfectly safe for you guys, since you know how to resolve correct the issue when the site stops as a result. But for others, where they might be totally stuck if things halt, it's probably not safe. For instance, lets say you disable ProCache and the site's _main.php is using the $procache API var to merge+minify stylesheets. Once ProCache is disabled (or uninstalled), the site will halt because the template is making a function call on a non existent variable. This is just one example of all sorts of issues that could turn up with disabling modules that are expected to be there.

**Comment by adrianbj** [comment]
I forgot to mention - thanks for the fix :)

**Comment by adrianbj** [comment]
@ryancramerdesign - just wanted to update here with one final comment. I ended up adding an automatic modules DB backup feature (https://processwire.com/talk/topic/12208-tracy-debugger/?do=findComment&comment=127332) into Tracy so that if disabling a particular module results in a fatal error, it is really easy to restore the modules table from the backup which should make this safer/easier for the average user.
