### ISSUE TITLE
FieldtypeCache gives LanguageSupport.module 566 error 

### ISSUE THREAD

**Issue by franctic-aerobic** [ryancramerdesign/ProcessWire#1992]
I have just upgraded to 3.0.30 and am having issues with FieldtypeCache. (I upgraded from 2.7.2.)

> Fatal error: Call to a member function attr() on null in /Users/*/*/*/wire/modules/LanguageSupport/LanguageSupport.module on line 566

Error occurs when trying to edit pages with a cache field, creating a new cache field, or editing an existing cache field.

**Comment by ryancramerdesign** [comment]
Thanks @franctic-aerobic I've pushed a fix for this issue.

**Comment by isellsoap** [comment]
@franctic-aerobic This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
