### ISSUE TITLE
WireHttp send method needs ability to set user_agent

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1996]
I am sure others will also find this useful, but I need it to fix the Validator panel in TracyDebugger which no longer works due to a recent requirement to provide a user_agent.

Not sure whether you'd prefer to make it possible to modify the entire $options array via the get(), post() etc methods, or maybe add a setUserAgent() method.

I need to effectively change this:
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/WireHttp.php#L434

```
$options = array(
	'http' => array( 
		'method' => $method,
		'timeout' => $this->getTimeout(), 
		'content' => $content,
		'header' => $header,
		)
	);  
```

into:

```
$options = array(
	'http' => array( 
		'method' => $method,
		'timeout' => $this->getTimeout(), 
		'content' => $content,
		'header' => $header,
		'user_agent' => 'MyCustomUserAgent',		
		)
	);   
```

I don't think there is currently a way to do this, but please let me know if I am missing something.

**Comment by teppokoivula** [comment]
Regarding the ability to modify the entire $options array, I'm just wondering how this would work if send() has to fall back to sendSocket(), or perhaps in the future to sendCURL()?

While it's a bit annoying and somewhat limited, it would probably be easier and more predictable to just open specific settings, such as user agent: for send() you can define this via stream context, for sendSocket() you can include it as a header, etc. Then again, you could probably already call setHeader() before send() and just set the User-Agent header this way.. :)

**Comment by adrianbj** [comment]
Thanks for your thoughts @teppokoivula - I definitely didn't think through the best options completely. I just wanted to get things working quickly, so for Tracy I actually cloned and renamed the entire `WireHttp` class, and added the user_agent option to the send() method.

Looking at things more carefully, I see that `fsockopen` does allow you to send the user_agent as part of the header and of course curl uses `CURLOPT_USERAGENT` - with this in mind, I guess it probably makes sense to added a setUserAgent method that can be used by each of the send methods as needed.

> Then again, you could already call setHeader() before send() and just set the User-Agent header this way.. :)

Are you saying this works as is for the send() method? I didn't think user_agent could be part of the header for `stream_context_create` when using `fopen` - I thought it needed to be a separate key in the `http` array like I have it above - at least it's working for me that way anyway.

**Comment by adrianbj** [comment]
Just a follow up - I added a `setUserAgent()` method to my cloned version of the `wireHttp()` class. You can see what I have done here: https://github.com/adrianbj/TracyDebugger/commit/b6ae74712adb57f655bbf5d4a26ce58387c6081a#diff-fce24a50f3087c0aecfd92530b29b317

If you like the approach, you should be able to incorporate this directly. It works for both `send()` and `sendSocket()` methods and I even added the appropriate line in for the `sendCURL` method so it's ready to go once that method is activated.

**Comment by teppokoivula** [comment]
> I didn't think user_agent could be part of the header for stream_context_create when using fopen - I thought it needed to be a separate key in the http array like I have it above - at least it's working for me that way anyway.

However you define User Agent, it ends up being a header. Context option user_agent is a kind of a shortcut, and [the PHP manual](http://php.net/manual/en/context.http.php) explains it like this:

> Value to send with User-Agent: header. This value will only be used if user-agent is not specified in the header context option above.

In other words: yes, you can already set the User-Agent header :)

**Comment by adrianbj** [comment]
Thanks @teppokoivula - I obviously didn't read through that fully - not sure why I thought the user agent wasn't sent via the header - oh well :) 

I also just confirmed (as you would expect), that you can do the same with curl
