### ISSUE TITLE
not conform saving of fieldnames in table fields

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/ProcessWire#1999]
Hi Ryan,
once again I got catched by following issue:
when creating a new field, the pagename get sanitized to match a-z _ 0-9 ($sanitizer->pageName())
If we use a name with uppercase leters in it, the created TABLE is only lowercase, thats fine.
In the TABLE 'fields' under 'name' it is stored unsanitized, containing uppercase letters too!

This can let to problems when further on, for example, I get a userinput for a fieldname with uppercase letters, sanitize it to lowercase and want to use it to access that field ($page->get($sanitizedPageName)). On some, not all MySQL installations you seem to must match casesensitive names, otherwise it will not work.

I think it would be much better to store the "name" in TABLE "fields" as lowercase too!

**Comment by ryancramerdesign** [comment]
Page names and field names are different sanitizers. Field names allow uppercase characters, so it's fine to use uppercase characters if you'd like. 

There is a `$config->dbUseLowercaseTables` that is true by default. But that setting is specific to the table names used by fields, not the actual field names. If you've found an instance where that setting doesn't seem to be getting applied, please let me know and I can fix it. Thanks.

**Comment by horst-n** [comment]
Oh! On every page that is openend for creating a new Field, there is to read under the name inputfield:

**Any combination of ASCII letters [a-z], numbers [0-9], or underscores (no dashes or spaces).**

That's why I never used Uppercase letters. I really like to use CamelCaseFieldNames, so it would be good to display it more correct at that prominent place. :)

Than I need to rewrite some parts of my modules again. But this issue can be closed after you have read it, Ryan (@ryancramerdesign).

**Comment by horst-n** [comment]
It is this line: https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Process/ProcessField/ProcessField.module#L1043
It should be more like this: **Any combination of ASCII letters [a-zA-Z], numbers [0-9], or underscores and dots (but no dashes or spaces).** 
(Or are dots not allowed?)

**Comment by ryancramerdesign** [comment]
Thanks @horst-n I have updated the description. Also, dots are not allowed. Field names follow the exact same format as PHP variables because they are ultimately used as PHP variables, i.e. $page->field_name.

**Comment by horst-n** [comment]
Thanks @ryancramerdesign !
