### ISSUE TITLE
Maxlength 0 causing Text field not editable (3.032)

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#2001]
If I set a text (or textlanguage) field maxlength to 0 I get "maxlength=0" in the markup so the field is not editable (Chrome). If I set it to other value it's OK, but setting it back to 0 brings back the issue again.

The field's note says '_A value of “0” indicates no maximum._' so it looks like a bug to me, or the field's note is inappropriate. I had to uncomment line 71 in InputfieldText.module to be able to edit pages (surely the issue is not with this line but hadn't time to dig in deeper).

**Comment by ryancramerdesign** [comment]
Thanks @rolandtoth I've pushed a fix for this issue.

**Comment by rolandtoth** [comment]
Thanks, seems to work fine!
