### ISSUE TITLE
Notices in Template "Usage" iframe

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#2004]
![screen shot 2016-08-29 at 6 31 22 am](https://cloud.githubusercontent.com/assets/871211/18053020/51725cdc-6db2-11e6-8468-c8baa2e0dc35.png)

Not too bad in this case, but image if there were a lot of notices - it would look pretty messy.

**Comment by ryancramerdesign** [comment]
Adrian, those are just debug mode notices. They are supposed to show when debug mode is on. Yes it would look messy if there were lots of them, but that's what debug mode is for. :)

**Comment by adrianbj** [comment]
Yeah I understand they are only displaying in debug mode - I just feel like they should maybe be suppressed when: `$input->get->modal == 'inline'`

That would hide them from these inline iframes within the PW admin. Are there any other cases other than the Template Usage section?

**Comment by ryancramerdesign** [comment]
These are supposed to show in debug mode, that's the purpose of them. If we turned them off, then sooner or later someone is going to miss something important that they expect to see. Debug mode is about showing this stuff, regardless of what we think is pretty. And when we want stuff to be pretty then we turn off debug mode.

**Comment by adrianbj** [comment]
You have a very good point - sorry for harping :)

I guess my ideal scenario would be if the notifications were at the top of the page, rather than in that iframe which of course would be hard to do.

From the other side of the coin - if the Notifications module is installed, notices triggered when opening the Usage section don't get displayed anywhere from what I can see.
