### ISSUE TITLE
Module MarkupRSS.module is using strings to build XML

### ISSUE THREAD

**Issue by stefan-scholl** [ryancramerdesign/ProcessWire#2006]
It's considered bad practice to generate XML with text based templates or adding strings together.

https://hsivonen.fi/producing-xml/

**Comment by ryancramerdesign** [comment]
XML is a text-based format. Regardless of someone's opinion, sooner or later any data in XML has to be converted to strings and connected into text. That's the reality. I'd agree that I'd want some other dedicated XML library or functions to do this for me when it comes to generating complex XML documents (and I often do). But we're talking about very simple RSS here, so lets get real. :) On the other hand, if you have you found a bug that is causing an error, please let me know.

**Comment by isellsoap** [comment]
@stefan-scholl This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
