### ISSUE TITLE
loss of $siteDir override in index.php (3.0 branch)

### ISSUE THREAD

**Issue by KeeneState** [ryancramerdesign/ProcessWire#2007]
The alternative naming of the /site/ directory accessible in index.php by way of $siteDir is no longer accessible in the devns branch. The logic was moved from the more edit friendly index.php, to core/Processwire.php. 

In case you're wondering why the alt-naming in the first place, /site/ was also a content path, and it seemed misleading to have both a /site/ content url and a /site/ code path that were completely unrelated with one another. 

Is there any chance of reinstating this config override in some manner, or was the removal intentional? I'd be happy to create a pull request if it would help--but thought it best to first to check whether this was intentional.

Thanks.
Ben

**Comment by ryancramerdesign** [comment]
I've just pushed an update to the wire/core/ProcessWire.php file which should fix this. In your index.php file you currently have this line:
~~~~~
$config = ProcessWire::buildConfig($rootPath);
~~~~~
Update it to this:
~~~~~
$config = ProcessWire::buildConfig($rootPath, null, array('siteDir' => 'site'));
~~~~~
Replace 'site' with the name of your site directory.

**Comment by KeeneState** [comment]
Ryan, the override is working perfectly as far as I can tell. If I hit anything related I'll let you know, but the override held up through testing across a variety of templates..

Thank you.
