### ISSUE TITLE
Removing module inputfields leaves orphaned data in database

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#2012]
Module inputfields are set in getModuleConfigInputfields() or getInputfields() or as an array in contruct(). If an inputfield is later removed (perhaps in a update to the module, or as in my current project where I am attempting to have a flexible number of inputfields) the data for that inputfield is left orphaned in the database when the expectation is that it would be removed.

This is because in [ProcessModule](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Process/ProcessModule/ProcessModule.module#L1255) the post data coming from the config form is merged with the existing config data when I expected it to replace the existing data. The net effect of this is that the inputfields specified in ModuleConfig can only ever add to the array of saved fields, never remove fields from it. That seems wrong.

**Comment by ryancramerdesign** [comment]
This is intended. ModuleConfig/getModuleConfigInputfields is just one funnel to module configuration data. Modules may use configuration data for whatever they wish beyond that. Many of my modules do so for instance. If you are a module developer and want to specifically remove something from previous module config data that you stored, you can do so like this:
~~~~~
$data = $modules->getModuleConfigData('YourModuleName');
unset($data['yourPropertyName']);
$modules->saveModuleConfigData('YourModuleName', $data); 
~~~~~

**Comment by Toutouwai** [comment]
Understood - it hadn't occurred to me that saved module config would be used for anything apart from the inputfields, but that makes perfect sense now you mention it.
