### ISSUE TITLE
Password entry required needlessly on any user profile edit

### ISSUE THREAD

**Issue by rwetzlmayr** [ryancramerdesign/ProcessWire#2014]
PW requires a user to enter her old (or even a new) password whenever she wants to change any other setting at her profile, like e-mail address, preferred language, or theme. 

I do not think that this is intentional, even more as the password input field is initially hidden and only the browser's notification bubble hints that something went wrong:

![screenshot - 02 09 2016 07_44_58](https://cloud.githubusercontent.com/assets/357054/18193819/73fb78a6-70e1-11e6-84e2-dbc0f242c65d.png)

**Steps to reproduce:**

1. Go to http://example.com/processwire/profile/
1. Click "Submit"

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. What browser are you seeing it in? I'm testing in the current Chrome version in OS X.

**Comment by rwetzlmayr** [comment]
I can reproduce this. Please follow along:

1. Use Firefox and a recent devns clone like 3.0.32. This apparently does not happen in Chrome.
1. Assert that you have logged out of your PW backend.
1. Log back in to your PW backend.
1. **Crucial:** Allow Firefox to save your password to it's built-in password store.
1. Go to your user profile page.
1. Hit "Submit".
1. Experience issue.

I think that Firefox prefills the password input with its stored password. This fires a `change` event which hits [here](https://github.com/ryancramerdesign/ProcessWire/blob/132ea079f79c574dd39a4a7ca37bd852259e217a/wire/modules/Inputfield/InputfieldPassword/InputfieldPassword.js#L120) and sets the `required` attribute.

Here's a screenshot featuring Firebug at an "attribute change" breakpoint for `ìnput#Inputfield_pass` as the profile page is loaded (no user interaction has yet occurred):

![screenshot - 03 09 2016 05_53_20](https://cloud.githubusercontent.com/assets/357054/18222554/0f4fd3ce-719b-11e6-812e-b3165ef73484.png)

At the spot I marked with the violet [1], Firefox detects an attribute change (Attributänderung) because the property 'value' is set to my stored password (Eigenschaft Wert) while the initial attribute is 'null' (Attribut Wert). Boom!

**Comment by somatonic** [comment]
https://github.com/ryancramerdesign/ProcessWire/issues/1236

**Comment by ryancramerdesign** [comment]
It looks like our previous fix no longer worked for whatever reason, so I've made some adjustments and it seems to be working again. Please let me know if you continue to experience the issue. Thanks.

**Comment by rwetzlmayr** [comment]
Better now.
