### ISSUE TITLE
fatal error with config option moduleCompile set to false (devns, bare-bones install)

### ISSUE THREAD

**Issue by KeeneState** [ryancramerdesign/ProcessWire#2015]
Using a bare-bones minimal profile with devns branch, when the config option moduleCompile is set to false, an uncaught exception occurs. It appears to be a namespace related issue that is masked by the FileCompiler when enabled.

I've gone through the git history, divide and conquer style--I've narrowed it down to being introduced in commit _c8293044fb20d475dbea5147b1e9c378032926cf_.

If I extract the wire directory of the previous commit[1], the error is not thrown, on replacing the next commit's[2] wire directory, an uncaught exception is thrown.

[1] https://github.com/ryancramerdesign/ProcessWire/archive/c0b30dbb24d30845d98ab1c9d103bbead1a6e629.zip
[2] https://github.com/ryancramerdesign/ProcessWire/archive/c8293044fb20d475dbea5147b1e9c378032926cf.zip

The error message is as follows:

```
Error: Uncaught Error: Class 'ProcessWire\FieldtypePage' not found in [devdir]\wire\core\Modules.php:493
Stack trace:
#0 [devdir]\wire\core\Modules.php(950): ProcessWire\Modules->newModule('ProcessWire\\Fie...')
#1 [devdir]\wire\core\Modules.php(770): ProcessWire\Modules->loadModule('[devdir]...', '[devdir]...', Array, Array)
#2 [devdir]\wire\core\Modules.php(326): ProcessWire\Modules->load('[devdir]...')
#3 [devdir]\wire\core\ProcessWire.php(272): ProcessWire\Modules->init()
#4 [devdir]\wire\core\ProcessWire.php(118): ProcessWire\ProcessWire->load(Object(ProcessWire\Config))
#5 [devdir]\index.php(52): ProcessWire\ProcessWire->__construct(Object(ProcessWire\Config))
#6 {main}
thrown (line 493 of [devdir]\wire\core\Modules.php) 
```

Let me know if I can provide any additional information. 

Ben

**Comment by ryancramerdesign** [comment]
Thanks @KeeneState I've pushed a fix for this issue in the latest commit. Please let me know how it works for you.

**Comment by KeeneState** [comment]
Thanks @ryancramerdesign, this solves it--both with the minimal and a more complex site profile. I'll keep an eye out for any oddities, but this seems to take care of it. This will help get our in-house modules squared with 3.0.
