### ISSUE TITLE
ProcessWire 3.0.33: Notice: Undefined offset: 1 in /wire/modules/Process/ProcessModule/ProcessModule.module on line 608

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#2016]
ProcessWire 3.0.33: If a module has an invalid name, ProcessModule throws a notice.
Notice: Undefined offset: 1 in /wire/modules/Process/ProcessModule/ProcessModule.module on line 608

**Comment by ryancramerdesign** [comment]
So far I can't figure out how to duplicate this one. Can you tell me the steps necessary to observe the error? Thanks.

**Comment by processwired** [comment]
I tried now, but strangely I can't reproduce it anymore. Before I had opened the issue, I accidentally had named a module with two upper case letters at the beginning, resulting in a message that the module name is invalid. I renamed it, updated the modules' overview and did see the mentioned notice. Since it is an rare edge case, I think the issue can be closed. I'll keep an eye open if I observe it again.
