### ISSUE TITLE
Notice: Undefined variable: result in wire/modules/System/SystemUpdater/SystemUpdate12.php on line 48

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#2017]
This can show up in a bootstrapped file. Just need to set `$result = false` at the start of the execute function.

**Comment by adrianbj** [comment]
Actually now I am wondering why my 3.0.32 install was reset to System Version 11 - weird! I'll let you know if I figure out anything on that front.

**Comment by adrianbj** [comment]
I know why it was set to 11, so I don't see this affecting anyone else from here on in, but still something to maybe watch out for.

I'll close though anyway.

**Comment by marcoraven** [comment]
The advice here is "Just need to set $result = false at the start of the execute function."

Sorry, but that doesn't mean anything to me. 
Can anyone guess where this should be added? Which execute function? In which file?

**Comment by adrianbj** [comment]
@marcoraven - are you seeing the notice mentioned in the OP? What version of PW are you running? This shouldn't be relevant for recent versions, but here is the execute function I was referring to: https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/modules/System/SystemUpdater/SystemUpdate12.php#L9

**Comment by marcoraven** [comment]
@Adrianbj: Thanks for your response! Yes, the message as shown in the OP. 
My version: 3.0.62. I though I was running "update 16" (according to the SystemUpdater module), but strangely enough it had switched back to "update 11". After bringing it back to version 15 (immediately changed to 16) the error message disappeared. So thank you, but issue solved.
