### ISSUE TITLE
Caches table not created

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#2018]
I got this error on the most recent version 3.0.33:

Wanted to install the intermediate profile with utf8_mb4 and InnoDB.

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'processwire.caches' doesn't exist

**Comment by ryancramerdesign** [comment]
I think I tracked it down. Still had some varchar(255) in the install.sql files, which needed to be varchar(250) for utf8mb4. I'm pretty sure I'd corrected those once before so not sure how they are back, but most likely some kind of error on my part.
