### ISSUE TITLE
[ModuleConfig] False values are empty strings?

### ISSUE THREAD

**Issue by mikerockett** [ryancramerdesign/ProcessWire#2023]
Forgive me for not looking through the code to understand this (perhaps it's just too early in the morning), but I've just noticed that `false` default options are saved in the DB as an empty string instead of `0`. When changed to `true`, the value is `1`, which is obviously quite fine.

Is this intended?

**Comment by LostKobrakai** [comment]
I'm quite sure the module settings don't know anything about the used inputfields and 0 would not be empty for anything displaying text.

**Comment by mikerockett** [comment]
Sure, I get that, but If a default value is `false` (indicating a boolean field) and then config is saved, `0` should be the value saved. No?

**Comment by ryancramerdesign** [comment]
@mikerockett what's the Inputfield connected with the config value you are talking about? (InputfieldCheckbox?)

**Comment by mikerockett** [comment]
Hi Ryan, yes, that is correct.
________________________________

**Comment by ryancramerdesign** [comment]
In that case, blank string is correct. That's what we use as the default unchecked value. There's a good  reason for it, but I don't remember what it is at the moment. :) https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Inputfield/InputfieldCheckbox.module#L26

**Comment by mikerockett** [comment]
Thanks for the clarification. As long as it works, then I'm sure there's no issue. As I didn't delve into the code, I was not sure if this was a bug.
