### ISSUE TITLE
Password confirmation required needlessly on any user access edit

### ISSUE THREAD

**Issue by rwetzlmayr** [ryancramerdesign/ProcessWire#2024]
Applies to PW 3.0.33, Firefox.

The password field in `ProcessUser` suffers from the same issue as in #2014, and the [fix there](https://github.com/ryancramerdesign/ProcessWire/commit/b4e5977161d36cd8a9617c63a1b7beb0b0993810#diff-b49b5256779b14f5ffbe105307aa2be2R153) does not help here as this password field lacks the `autocomplete` attribute.

Thus Firefox inserts the saved password in the `pass` field but leaves the `_pass` 
field empty. Upon save this mismatch causes an error:

![screenshot - 06 09 2016 08_35_03](https://cloud.githubusercontent.com/assets/357054/18263781/aa139c2e-740c-11e6-8410-176e4a814720.png)

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this one.

**Comment by rwetzlmayr** [comment]
Thanks, works for me.
