### ISSUE TITLE
Chrome 53 kills AdminThemeReno double click on parent in the left menu

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#2026]
My Chrome updated to 53 and the double click on parent (Pages etc) now doesn't work in the menu.

**Comment by ryancramerdesign** [comment]
I've taken a close look at this one and it appears to be a bug in Chrome 53 as far as I can tell. So have been a little reluctant to try and accommodate it, but with most of us using Chrome, plus who knows how long this issue will be present, so I've put in a workaround. :) Thanks.

**Comment by cb2004** [comment]
@ryancramerdesign thank you Sir. Confirmed fix.
