### ISSUE TITLE
Dropdown save options don't save template change

### ISSUE THREAD

**Issue by slkwrm** [ryancramerdesign/ProcessWire#2038]
If I change a page's template and use any of the dropdown save options (Save+Exit, Save + Add New, Save + Next) the template doesn't change after save. The main Save button works as expected. Running 3.0.33 devns.

**Comment by LostKobrakai** [comment]
Template changes is one of a few things, which need a confirmation page, which is not shown if there's a session redirect after the first save.

**Comment by ryancramerdesign** [comment]
LostKobrakai is correct on this one, but I can see how the behavior may cause confusion. In this case it's simple to change. I've pushed an update which changes the priority so that a template change overrides the dropdown action, rather than the other way around.
