### ISSUE TITLE
validation of links in CKE: rel="noreferrer" rel='nofollow'

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#2039]
I have a funny validation problem: 2 **rel** attributes for a link added inside of a CKE module: 
rel="noreferrer" rel='nofollow'

With the help of ProcessPageEditLink I had added rel='nofollow'. That was intended.

But I have no idea where the rel="noreferrer" comes from (maybe HTML Purifier) and why the attr is added twice instead of adding just a value if the attr exists.

(PW 3.033, CKE inline, HTML purifier on)

**Comment by ryancramerdesign** [comment]
I can't duplicate this one so far (inline CKE with HTML Purifier enabled). I also have ACF enabled (as it is by default). I'm adding nofollow links, but the resulting markup just has the `rel="nofollow"` and not the extra one you mentioned. 

Can you double check in your ProcessPageEditLink module settings that your rel attribute options say just `nofollow` (1-word) and not literally `rel='nofollow'`? 

If all looks good in your module settings, can you test and see if you can consistently reproduce the behavior when adding new links? Also use the "Source" button in CKE to view the source after saving the page, just to rule out that there isn't something on the front-end adding the extra rel attribute too.

**Comment by tbba** [comment]
My settings were as they should be (your module clearly describes how to use it), thanks for asking.
I can say now that I could not reproduce it with a new page myself today. Now it works.
(Simply re-saving the page did not work - but removing and re-applying the links made the problem go away.) I will monitor this the next weeks and file it under "mystery bug". If I find a reproducible situation (which I had at the time of writing, 2 weeks ago) I will let you know. But I close this for now.

**Comment by tbba** [comment]
Found the culprit. Has nothing to do with the core - a dysfunctional third party module reminder which is not compatible with PW3 any more (and not needed there).

**Comment by ryancramerdesign** [comment]
Okay sounds good, thanks for reporting back.
