### ISSUE TITLE
RangeSlider does not work inside a repeater field

### ISSUE THREAD

**Issue by creativejay** [ryancramerdesign/ProcessWire#2040]
I've been using a Range Slider inside a repeater field in 2.7.x but now that I'm replicating the same field structure in a new dev installation, I find that the range slider portion of the repeater 
does not present the slider.

![rangeslider within repeater in 2 7 2](https://cloud.githubusercontent.com/assets/12252325/18597611/ba5593c2-7c1c-11e6-9e96-c01bc9379b00.png)
![rangeslider within repeater in 3 0 33](https://cloud.githubusercontent.com/assets/12252325/18597610/ba53d46a-7c1c-11e6-82c0-4fe8db395081.png)

**Comment by LostKobrakai** [comment]
This is because the javascript for the slider is not supporting ajax loaded fields.

**Comment by ryancramerdesign** [comment]
I'll close this one since it looks to be a range slider specific issue rather than a PW one. It appears that range slider Inputfield does not support dynamic insertion. However, chances are that module could be updated relatively easily to support it.
