### ISSUE TITLE
Fieldset Description and Notes not displaying

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#2046]
Should the Description and Notes content be displayed at the top and bottom of a fieldset? I am not seeing anything in a fieldset tab (I didn't check a normal fieldset).

I think it would be nice if this worked to provide general instructions for a tab of fields.

**Comment by gebeer** [comment]
+1
In normal fieldsets it is working already. But would be nice for tabs, too.

**Comment by adrianbj** [comment]
Moved to the new repo in the hopes of some action ;)
https://github.com/processwire/processwire-issues/issues/494
