### ISSUE TITLE
Installing LanguageSupport Module in 3.0.33 error

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#2048]
Not sure what's about it, never seen it before.

Module reported error during install (LanguageSupport): SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes

**Comment by somatonic** [comment]
This is a local testinstall that was a 2.8 install that was upgraded to 3.0.33.

**Comment by ryancramerdesign** [comment]
That error means trying to use InnoDB on a version of MySQL prior to when InnoDB supported fulltext indexes. You've got to have MySQL 5.6.4 or newer to use InnoDB with ProcessWire. See your /site/config.php file in the $config->dbEngine setting, which probably needs to be changed from InnoDB to MyISAM.

**Comment by tbba** [comment]
> $config->dbEngine
One quick question: Is it safe to change such a setting on a running website or is this only advised during installation?

**Comment by LostKobrakai** [comment]
You can do it manually (update all table's engine / column settings), but on installation is probably far less error prone.

**Comment by somatonic** [comment]
Hrm, no I don't use InnoDB. It's set to MyISAM. Also never set something to InnoDB and the DB tables are all MyISAM.

**Comment by somatonic** [comment]
Ah, no I see there's it's set in config.php, but can't remember I set that, so I must have been at install. So then why are all tables in DB MyISAM? Never changed something in that regard.

**Comment by somatonic** [comment]
Ok, but after I installed and deinstalled that LanguageSupport module it can't be installed anymore and throws that error: 

Module reported error during install (LanguageSupport): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'languages-22' for key 'name_parent_id'

There's a "Languages" page under "Setup" in the admin branch (not menu) that seems like it got installed once, but I can't remove it cause I have no permission.

**Comment by isellsoap** [comment]
@somatonic What’s the status of this issue? To me it doesn’t seem to be a reproducible issue. If it can be reproduced, please tell us the steps that lead to the issue. Otherwise I would like to close this one. Thanks.
