### ISSUE TITLE
Allow whitespaces in passwords

### ISSUE THREAD

**Issue by gRegorLove** [ryancramerdesign/ProcessWire#2052]
I was surprised to learn that InputFieldPassword does not allow whitespace*. I'd strongly recommend allowing them since I'm not aware of any technical reasons for the restriction.

\* My PW password has had whitespace for a while, so at first I thought maybe the code changed. Then I remembered I had forgotten my password and reset it via the API, which doesn't have the whitespace restriction. Only today did I go in to change a password via the admin. :]

**Comment by adrianbj** [comment]
Hi @gRegorLove - please note the new location for Issues: https://github.com/ryancramerdesign/ProcessWire/issues/2051

Thanks,
Adrian

**Comment by gRegorLove** [comment]
Oops, sorry! Will close and re-open.
