### ISSUE TITLE
PagefilesManager should tolerate wrong datetime of files

### ISSUE THREAD

**Issue by gerritvanaaken** [ryancramerdesign/ProcessWire#2055]
```
$page->filesManager->getFile('some_image.jpg')
```

If the databse entry for "some_image.jpg" has a created-datetime like "1970-01-01 01:00:10", it does not pass the validation and won’t get selected, even if the image itself would be perfectly okay to handle.

This is related to #2054

**Comment by LostKobrakai** [comment]
@gerritvanaaken Could you please open your issues in our new repository: https://github.com/processwire/processwire-issues 

Issues here are only kept for historical reasons.

**Comment by gerritvanaaken** [comment]
thanks, have done that.
