### ISSUE TITLE
$sanitizer->url allows invalid URLs

### ISSUE THREAD

**Issue by FerdiAgrio** [ryancramerdesign/ProcessWire#2062]
When checking a bunch of URLs, I came past an odd example of an 'URL' which passed the $sanitizer->url() method. Basically I'm only checking a random word like 'processwire' with the extra option to disallow relative-URLs and the need of scheme 'http' or 'https'.
Example:
`$sanitizer->url('processwire', array('allowRelative' => false,'allowSchemes' => array('http', 'https')));`

I tried to narrow it down:
`$scheme = parse_url($value, PHP_URL_SCHEME);
if($scheme !== false && strlen($scheme)) {...}`
which didn't pass (correct, returns null)

Further on it checks for incorrect $scheme:
`if(!$scheme) {...}`

and checks the option 'allowRelative':
`if($options['allowRelative']) {...}`

since the value is 'processwire' we move to the _else_ which says:
`// relative urls aren't allowed, so add the scheme/protocol and validate
$value = $this->filterValidateURL("http://$value", $options);`
...which somehow passes

It would be nice if somebody can clear this up for me. Thanks in advance.

**Comment by LostKobrakai** [comment]
This is the old legacy repo of processwire. See here about where to submit your issue:
https://github.com/ryancramerdesign/ProcessWire/issues/2051

**Comment by FerdiAgrio** [comment]
Damn bookmarks need updating! Tnx!
Although I won't post it - found a satisfying answer [here](https://processwire.com/talk/topic/11309-sanitizer-url-validation/?do=findComment&comment=128505)
