### ISSUE TITLE
Admin homepage can say "page isn’t redirecting properly"

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#2063]
My browser says "The page isn’t redirecting properly" in this scenario:

1. Log into the editing interface - here: http://www.example.com/processwire/
User is now redirected to: http://www.example.com/processwire/page/?login=1

2. Delete your cookies (or log out on another tab in your browser)
(You are here: http://www.example.com/processwire/page/?login=1)

3. Refresh the page or type enter in the web address field
(You are here: http://www.example.com/processwire/page/?login=1)

4. Result:
Firefox 55 now says "The page isn’t redirecting properly".
(You are here: http://www.example.com/processwire/page/?login=1)

ProcessWire 3.0.62

**Comment by mikerockett** [comment]
Please open your issue here instead: https://github.com/processwire/processwire-issues/issues (per #2051)
