### ISSUE TITLE
Language Support - Page Names - Bug in Multilanguage use

### ISSUE THREAD

**Issue by pieterjanmaes** [ryancramerdesign/ProcessWire#2069]
Hi, 

I found a small bug,

When u have a multilanguage website and change the "Page number prefix for pagination" for the default language in the "Language Support - Page Names Module", and leave the others empty. 

The pagination doesn't work for the non-default languages.

**Comment by LostKobrakai** [comment]
@pieterjanmaes this repo is a old legacy repo. Please open your issue here: https://github.com/processwire/processwire-issues

**Comment by pieterjanmaes** [comment]
Thx for your reply. Added the [issue](https://github.com/processwire/processwire-issues/issues/658).
