### ISSUE TITLE
InputfieldPageListSelect outputs duplicate container, translations not working

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#219]
Already mentioned this in a other case in the forums, but since it's hard to keep track, here you go.

This is in the source:

```
<div id='PageListContainer' data-token-name='TOKEN427843011' data-token-value='57529bf049bf0a0f50459ec68e6fb21b1b86c3b7decf204cc516e51e80d72c4d'></div>
<div id='PageListContainer' data-token-name='TOKEN427843011' data-token-value='57529bf049bf0a0f50459ec68e6fb21b1b86c3b7decf204cc516e51e80d72c4d'></div>
```

One too many :)

I'm not sure if that's the problem that the translation of the labels "select" etc doesn't work. The config.ProcessPageList is in the html source but it's not handed over to the jquery plugin correctly.

**Comment by matjazpotocnik** [comment]
Doubled PageListContainer div seems to be fixed, at least in PW3, so this could be labeled fixed?

**Comment by isellsoap** [comment]
@somatonic According to @matjazpotocnik this seems to be fixed now. Can you close the issue please?
