### ISSUE TITLE
multi-language support with 1 language

### ISSUE THREAD

**Issue by ryancramerdesign** [ryancramerdesign/ProcessWire#223]
page titles have an editing issue when only default language is installed. See this thread for details: 
http://processwire.com/talk/topic/4277-cant-change-page-titles-from-admin/

**Comment by adrianbj** [comment]
@ryancramerdesign - I think the template `noLang` flag may cause this issue to occur still so it might be worth revisiting this. I have also noted this on the forum thread linked to above.

**Comment by adrianbj** [comment]
@ryancramerdesign - the `noLang` flag bit me again today - I do think this needs fixing please.
