### ISSUE TITLE
integer field ignores zero when set as a min value

### ISSUE THREAD

**Issue by designbrigade** [ryancramerdesign/ProcessWire#257]
The integer field doesn't allow for zero to be a min value. Zero should be allowed, because integers can be negative numbers and specify a min value of zero is a way to disallow negative numbers and is at times essential. 

The solution may be as simple as commenting out line 30 in wire/modules/InputField/InputfieldInteger.module, but I have not tested.

Here's the forum topic. http://processwire.com/talk/topic/4656-integer-field-with-minimal-value-0-doesnt-work/#entry45845

**Comment by plauclair** [comment]
This is working now, should be marked as closed.

**Comment by LostKobrakai** [comment]
@designbrigade Could you please close this issue as it's resolved?

**Comment by designbrigade** [comment]
Closed, thanks!
