### ISSUE TITLE
LanguageTabs load on ProcessPageEdit good idea?

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#261]
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/LanguageSupport/LanguageTabs.module

Is now missing this last PR I did to LanguageFieldTabs to support Fredi. Now the core one doesn't work with Fredi again.

https://github.com/adamspruijt/LanguageFieldTabs/blob/master/LanguageFieldTabs.module#L42

This raises the question which modules should support what? Wouldn't it make sense to load LangaugeTabs on all InputfieldForms that have language fields? Isn't loading only on ProcessPageEdit::execute limiting?

I started a ticket also in Fredi repository. 
https://github.com/apeisa/Fredi/issues/12

But thought mention it here too as it's now in core.

**Comment by isellsoap** [comment]
@somatonic As https://github.com/apeisa/Fredi/issues/12 is closed now, is this issue still relevant? If it is still relevant, maybe you could open a new one in the [new requests repository](https://github.com/processwire/processwire-requests)? Thanks!
