### ISSUE TITLE
Even if a template can't be used for new pages, superusers can still change existing pages to use said template

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#263]
Not entirely sure if this is a bug or a feature, but even if a certain template, "home" for an example, can't be used for new pages (family settings), superuser can still create a page with another template (can't select "home" template at this point yet) and then change it's template to "home".

Looks like this only applies to superuser, so it's not such a big problem in most cases -- though it could, in some cases, become that, especially in case that multiple people with superuser roles work on same site. There's probably a good reason why certain template shouldn't be used for new pages, ie. it might serve some kind of a special role.

Mostly this is just confusing, really. Shouldn't these family settings at least behave similarly in both cases, when creating new pages and when altering existing ones? Or, if that's not possible, it'd be good to explain somewhere that _in some cases_ they only apply to non-superusers to avoid unnecessary confusion.. :)

**Comment by teppokoivula** [comment]
@ryancramerdesign: as a heads-up, [this feature is still causing confusion](https://processwire.com/talk/topic/10097-meaning-of-family-setting-can-this-template-be-used-for-new-pages/). Any chance you could revisit this at some point?

**Comment by rolandtoth** [comment]
> and/or somehow informing superusers that they're the only ones able to do this

Perhaps adding a note/description to field "Can this template be used for new pages?" would be just enough. Eg. "Note: superusers will still be able to use this template".

**Comment by BernhardBaumrock** [comment]
+1 for moving it to advanced

**Comment by matjazpotocnik** [comment]
+1 for moving it to advanced or/and adding a note for superusers
