### ISSUE TITLE
Untranslatable text in modal dialog.

### ISSUE THREAD

**Issue by mseed** [ryancramerdesign/ProcessWire#277]
Hi, previously fixed bug from commit https://github.com/ryancramerdesign/ProcessWire/commit/b578b4322db1776bd177f639630acde78d185690 is again here.

Cant translate "select" and "cancel" text.

I have non en language pack as default and here is screenshot http://rapidlab.cz/_pw/pw_bug.png

Looks like commit https://github.com/ryancramerdesign/ProcessWire/commit/29417801c06a5a241445f5aa3e7165e9796ec5f3 broke it.

**Comment by LostKobrakai** [comment]
@mseed Is this still an issue? If not, could you please close this one?

**Comment by mseed** [comment]
Problem is fixed.
