### ISSUE TITLE
Error when deleting page

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#310]
I got this error already a couple times. It seems that when creating a page that has already the name used, after creating the page again with different name, and after deleting that page I get this error:

 TemplateFile: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test-7' for key 'name1013_parent_id'
#0 /xxx/wire/core/Pages.php(691): PDOStatement->execute()
#1 /xxx/wire/core/Pages.php(614): Pages->savePageQuery(Object(Page), Array)
#2 [internal function]: Pages->___save(Object(Page))
#3 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#4 /xxx/wire/core/Wire.php(317): Wire->runHooks('save', Array)
#5 /xxx/wire/core/Pages.php(986): Wire->__call('save', Array)
#6 /xxx/wire/core/Pages.php(986): Pages->save(Object(Page))
#7 [internal function]: Pages->___trash(Object(Page))
#8 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#9 /xxx/wire/core/Wire.php(317): Wire->runHooks('trash', Array)
#10 /xxx/site/modules/ProcessPageDelete/ProcessPageDelete.module(39): Wire->__call('trash', Array)
#11 /xxx/site/modules/ProcessPageDelete/ProcessPageDelete.module(39): Pages->trash(Object(Page))
#12 [internal function]: ProcessPageDelete->___execute()
#13 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#14 /xxx/wire/core/Wire.php(317): Wire->runHooks('execute', Array)
#15 /xxx/wire/core/ProcessController.php(196): Wire->__call('execute', Array)
#16 /xxx/wire/core/ProcessController.php(196): ProcessPageDelete->execute()
#17 [internal function]: ProcessController->___execute()
#18 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#19 /xxx/wire/core/Wire.php(317): Wire->runHooks('execute', Array)
#20 /xxx/wire/core/admin.php(49): Wire->__call('execute', Array)
#21 /xxx/wire/core/admin.php(49): ProcessController->execute()
#22 /xxx/site/templates-admin/controller.php(13): require('/home/www-data/...')
#23 /xxx/site/templates/admin.php(32): require('/home/www-data/...')
#24 /xxx/wire/core/TemplateFile.php(139): require('/home/www-data/...')
#25 [internal function]: TemplateFile->___render()
#26 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#27 /xxx/wire/core/Wire.php(317): Wire->runHooks('render', Array)
#28 /xxx/wire/modules/PageRender.module(339): Wire->__call('render', Array)
#29 /xxx/wire/modules/PageRender.module(339): TemplateFile->render()
#30 [internal function]: PageRender->___renderPage(Object(HookEvent))
#31 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#32 /xxx/wire/core/Wire.php(317): Wire->runHooks('renderPage', Array)
#33 /xxx/wire/core/Wire.php(381): Wire->__call('renderPage', Array)
#34 /xxx/wire/core/Wire.php(381): PageRender->renderPage(Object(HookEvent))
#35 /xxx/wire/core/Wire.php(317): Wire->runHooks('render', Array)
#36 /xxx/wire/modules/Process/ProcessPageView.module(113): Wire->__call('render', Array)
#37 /xxx/wire/modules/Process/ProcessPageView.module(113): Page->render()
#38 [internal function]: ProcessPageView->___execute()
#39 /xxx/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#40 /xxx/wire/core/Wire.php(317): Wire->runHooks('execute', Array)
#41 /xxx/index.php(192): Wire->__call('execute', Array)
#42 /xxx/index.php(192): ProcessPageView->execute()
#43 {main}

Seems to have to do with pages I got already in trash.
After deleting trash, I can delete the page fine.

**Comment by isellsoap** [comment]
@somatonic Please provide the exact steps to reproduce the issue.

**Comment by somatonic** [comment]
Related to this? https://github.com/ryancramerdesign/ProcessWire/issues/2030

**Comment by isellsoap** [comment]
@somatonic I can’t reproduce this one, after following the steps mentioned in https://github.com/ryancramerdesign/ProcessWire/issues/2030 I guess this one has been fixed. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
