### ISSUE TITLE
Page Names problems with saving on alternative language

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#321]
I'm again struggling to save pages with LanguageSupportPageNames installed and saving page when on alternative languages.

This is from the Shop module ShoppingCheckout I'm currently adding language support, cause it works when on default language, but fails when on a alternative language. I get "can't save page 0 cause there's no name.. " type of error.

This is the code I'm trying to implement and think should work but doesn't:

```

if( wire("languages") && count(wire("languages")) ){
	foreach(wire("languages") as $lang) {

		if(wire("fields")->get("title")->type instanceof FieldtypePageTitleLanguage) {
			$order->title->setLanguageValue($lang, $orderTitle);
		}

		if($this->modules->isInstalled("LanguageSupportPageNames")) {
			$langid = $lang->isDefault() ? '' : $lang->id;
			$order->set("name$langid", $orderName);
			$order->set("status$langid", 1);
		}
	}
} else {
	$order->title = $orderTitle;
	$order->name = $orderName;
}
```

I tried tracking down and thought maybe LanguageSupportPageNames is (as so many times) the problem. But I'm getting correct result at the point of 

```
public function hookPageSaveReady(HookEvent $event) {
...
}
```

this hook is called and the $extraData is filled correctly but saving fails:

This is the extraData array at the end of the method

Array ( [name1013] => 5ac95732362ad8499609a2ed63b83d72 [status1013] => 1 [name1014] => 5ac95732362ad8499609a2ed63b83d72 [status1014] => 1 )

I'd be very thankful if you have an idea what's happening or alternatives.

This is the error I'm getting:

Fatal error: Exception: Can't save page 0: /fr/processwire/shop/orders/9a8c872a02b7c793eec04320be6f0755/: It has an empty 'name' field (in /home/www-data/sev.update.ch/wire/core/Pages.php line 604) #0 [internal function]: Pages->___save(Object(Page), Array) #1 /home/www-data/sev.update.ch/wire/core/Wire.php(359): call_user_func_array(Array, Array) #2 /home/www-data/sev.update.ch/wire/core/Wire.php(317): Wire->runHooks('save', Array) #3 /home/www-data/sev.update.ch/wire/core/Page.php(1113): Wire->__call('save', Array) #4 /home/www-data/sev.update.ch/wire/core/Page.php(1113): Pages->save(Object(Page), Array) #5 /home/www-data/sev.update.ch/site/modules/ShoppingCart/ShoppingCheckout.module(635): Page->save() #6 /home/www-data/sev.update.ch/site/modules/ShoppingCart/ShoppingCheckout.module(231): ShoppingCheckout->createOrder() #7 /home/www-data/sev.update.ch/site/modules/ShoppingCart/ShoppingCheckout.module(159): ShoppingCheckout->renderConfirmation() #8 /home/www-data/sev.update.ch/site/templates/sc-checkout.php(34): Shoppi in /home/www-data/sev.update.ch/index.php on line 214

**Comment by isellsoap** [comment]
@somatonic I close this issue due to long inactivity on your part. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
