### ISSUE TITLE
repeater fields not saved when using showIf option 

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#358]
As soon as I make a field textarea in a repeater set to only show when a select has a certain id, the textarea field doesn't get saved.

http://processwire.com/talk/topic/5521-fields-not-saving-in-repeater/

**Comment by boundaryfunctions** [comment]
I was just able to reproduce this error with current master (2.6.1). A repeater field is also not saved if the `requiredIf` option was used.

If the functionalities aren't supported for repeaters at the moment, could it then be disabled or a notice shown in repeater context? In the current state, it's relatively easy to assume it "just works" which it doesn't.
