### ISSUE TITLE
Installing Admin Themes via Modules

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#390]
I can install Admin Themes via Modules "new" part, they are copied to /site/modules/.. but they can't be automatically installed or used from there. This can cause some confusion as mentioned here: http://processwire.com/talk/topic/5757-admin-theme-install-how-to-really/?p=56240.

I'm sure that this makes sense when (and if) all Admin Themes are modules, but for themes built before 2.4 and Admin Theme modules were available, this doesn't seem like a very good idea.

Of course one possible solution would be simply marking all themes *not 2.4 compatible* by default. I wouldn't wait all admin theme authors to step in and fix that themselves.

**Comment by isellsoap** [comment]
@teppokoivula What’s the status off this issue? Can be closed or needs more discussion?

**Comment by teppokoivula** [comment]
@isellsoap In my opinion the issue mentioned here is unresolved. It's still easy to use the built-in module installer to install a module, which in fact isn't a module at all, and the result is unexpected behaviour.

In the end it's up to @ryancramerdesign to decide if something can be done about this.

**Comment by q2apro** [comment]
It is super unclear - i. e. missing in the docs - how to *enable* the admin theme after it has been installed using the module. 

Just by an article on smashingmagazine I found the solution: 

![capture](https://cloud.githubusercontent.com/assets/6764548/17592017/486a4fe0-5fe9-11e6-91bd-900ebf3aacc0.PNG)

**Comment by isellsoap** [comment]
@ryancramerdesign Do you want to look further into this issue (see @teppokoivula’s [comment](https://github.com/ryancramerdesign/ProcessWire/issues/390#issuecomment-135407656))?

**Comment by teppokoivula** [comment]
Old admin themes shouldn't show up as being compatible with latest versions of ProcessWire, so I think it's relatively safe to close this issue by now.

On a side note it seems that @ryancramerdesign has hidden the whole Admin Themes category from modules directory. Not sure if that's intentional or not -- there are links pointing there from elsewhere, the page still exists, and this means that more recent admin themes are now harder to find. Not directly related to this issue, just noticed this while checking the status of admin themes.
