### ISSUE TITLE
Cannot change user language

### ISSUE THREAD

**Issue by rlanvin** [ryancramerdesign/ProcessWire#401]
I have a strange behavior when trying to change user language directly from the code. The language is changed for the current page, but not saved (i.e. when I refresh the page, the language is back to "default").

Code example:
```
var_dump($user->language->name); // 'default'
$user->language = 'fi';
$user->save();
var_dump($user->language->name); // 'fi'

var_dump(wire('users')->get($user->id)->language->name); // still 'default'
// I can also check database or admin panel, the language is "default"
```

I'm using Processwire 2.4.0. The same code use to work fine with the previous version of Processwire. Is this a bug or is there a new way to set the language?

**Comment by isellsoap** [comment]
@rlanvin Is this still an issue?

**Comment by rlanvin** [comment]
@isellsoap I don't know, I'm not using ProcessWire anymore.
