### ISSUE TITLE
minor feature request

### ISSUE THREAD

**Issue by pine3ree** [ryancramerdesign/ProcessWire#406]
hi Ryan,

is it planned to make ProcessPageListRenderJSON::renderChild hookable?
kind regards,
maks

**Comment by isellsoap** [comment]
@pine3ree This issue doesn’t seem to require a fix. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.

**Comment by pine3ree** [comment]
It's ok, i forgot to close it myself (it was more than 2 yersa ago). I haven't checked lately if renderChild has been made hookable, but the purpose at the time of the "issue" was to add different icons in admin for different type of pages, which was added in PW core.
kind regards
