### ISSUE TITLE
out of memory error in wireSendFile for large files

### ISSUE THREAD

**Issue by jlj** [ryancramerdesign/ProcessWire#407]
I have a file download page using wireSendFile similar to the one described in Soma's tutorial http://processwire.com/talk/topic/4602-flexible-downloads-using-pages/

When I try to download a large file from this page, the following error occurs:

> Allowed memory size of 33554432 bytes exhausted (tried to allocate 30265344 bytes) (line 403 of /Users/jean-luc/pw/wire/core/Functions.php)

This corresponds to the call to `readfile` in `wireSendFile`.

However the PHP documentation says:
> Note:
> readfile() will not present any memory issues, even when sending large files, on its own. > If you encounter an out of memory error ensure that output buffering is off with ob_get_level().

Actually it turns out that output buffering in on when  `readfile` is called.

Not sure if there is a good reason for keeping the buffering on, but replacing `ob_clean` by `ob_end_clean` in

    @ob_clean();
	@flush();
	readfile($filename);

solves the memory issue and the 30MB file can be downloaded without having to tweak the php memory size.

**Comment by isellsoap** [comment]
@jlj Can this issue be closed?
