### ISSUE TITLE
Localization, text domain in module not working

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#412]
I have a module that I want to take translation from another module that already is translated:

This works, through the translation string is shown in the translator for this module, but since it's taking it from the other text domain, it shouldn't show... Also I'm not sure why __("") works in a module???
```
$this->textDomainCheckout = "/site/modules/ShoppingCart/ShoppingCheckout.module";
__('First name', $this->textDomainCheckout)
```

This should be working, but doesn't work, the translation is not done, and it shows the default text:
```
$this->textDomainCheckout = "/site/modules/ShoppingCart/ShoppingCheckout.module";
$this->_('First name', $this->textDomainCheckout)
```

**Comment by isellsoap** [comment]
@somatonic This issue doesn’t seem to require a fix. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.
