### ISSUE TITLE
Page clone and page name

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#430]
I would really like to see the page name automatically get updated when a user edits the title for the first time on the new cloned page.

I have actually ended up disabling this module because I think it is too much to expect a user to also remember to go to the settings tab and modify the name to match the new title.

Actually I think I'd prefer to have the name always get updated on all changes to titles in general unless you specifically check something to say you don't want the changes applied. Obviously I am getting beyond the scope of my initial issue now, but I guess that would require Page Path History to be installed by default to prevent broken link issues.

Maybe a safer and easier option to implement would be a checkbox next to the title field that says "update page name?". Maybe devs could configure this to be on or off by default?

Maybe I should just write a module to do that?

Anyway, some food for thought, but I still think this is really important for the clone behavior to be more user friendly.

**Comment by isellsoap** [comment]
@adrianbj Maybe open a feature request for this issue [in the new repository](https://github.com/processwire/processwire-requests/issues)?

**Comment by adrianbj** [comment]
@isellsoap - honestly I don't really care about this anymore because my Page Rename Options module (http://modules.processwire.com/modules/page-rename-options/) takes care of it. It is always going to be more flexible than this core enhancement, so I am happy to let this one go, although I do think there is merit in the suggestion by @horst-n so maybe that should be a new feature request? This is sort of already possible with an advanced mode setting, but I think his suggestion would be much nicer.
