### ISSUE TITLE
Feature-Request: More options how to store files under site/assets/files

### ISSUE THREAD

**Issue by wanze** [ryancramerdesign/ProcessWire#432]
Currently, ProcessWire stores files under site/assets/files/{page-id}/. On an ext3 file system, the limit of subdirectories per directory is 32'000. On ext4 it's 64'000. But we all know that Pw is able to handle millions of pages ;)

For a bigger project with pages > 200.000 and growing (all containing assets like images), I needed to modify this behavior. My strategy is to split the page id in multiple directories, which generates at max 110 directories per level:

`/site/assets/files/1934/ => /site/assets/files/19/34/
 /site/assets/files/19349/ => /site/assets/files/19/34/9/`

However, this is only one strategy among others. I think it would be nice to let the developer decide the strategy, if the project requires it.

I needed to patch two core files in order to make this work. For more details what modifications I did, please take a look at this post:
https://processwire.com/talk/topic/5961-filesystem-limit-32000-reached/?p=59035

My idea is that the PagefilesManager introduces a hookable method which returns the path for a page, relative to site/assets/files/. The default implementation would be to return simply the page id, but if hooked, the developer could return any path.

``` php
protected function ___makePath() {
  return "{$this->page->id}/";
}
```

This method would then be used in all places where currently, the page id is hardcoded. For example:

``` php
static public function _path(Page $page) {
  $config = wire('config');
  $path = $config->paths->files; 
  //$publicPath = $path . ((int) $page->id) . '/';
  $publicPath = $path . $this->makePath();
  // [...]
```

``` php
public function ___url() {
  //return $this->config->urls->files . $this->page->id . '/';
  return $this->config->urls->files . $this->makePath();
}
```

In addition, the current wireMkdir should support creating recursive directories.

@ryancramerdesign and others: What do you think about this? It would need of course some testing especially in combination with the pageFileSecure feature. So far it's working fine here for me and I didn't have any problems at all :) Nevertheless it  would be nice if there were no hacks needed to implement this strategy.

**Comment by teppokoivula** [comment]
@wanze @ryancramerdesign, can this issue be closed to avoid unnecessary confusion? The rest of the discussion is not related to the pagefileExtendedPaths feature, which has already been implemented – yet it can be easily read like there's something "missing" from this feature.

Thanks!

**Comment by wanze** [comment]
I'll close since the proposed feature has been implemented. 👍
