### ISSUE TITLE
check_access won't work with has_parent=/protected/path/

### ISSUE THREAD

**Issue by suntrop** [ryancramerdesign/ProcessWire#507]
I've got this one in my module:
```php
$events = wire('pages')->find('template=event, has_parent=/protected/events/, check_access=0');
```
It only returns the events (restricted by the protected page) if I am logged in.

But if I change from path to ID like:
```php
$events = wire('pages')->find('template=event, has_parent=1015, check_access=0');
```
… I get all my events as expected.

Seems there is something wrong with the has_parent when putting in a path. I had a similar problem with has_parent's path and the not()-Selector (https://processwire.com/talk/topic/6265-has-parentpage-not-working-within-not/)

**Comment by isellsoap** [comment]
@suntrop Did you have a chance to try the suggestion from the above comment? Can this issue be closed?

**Comment by suntrop** [comment]
Yes, please close it. I don't have the code base anymore
