### ISSUE TITLE
$pages->find("name=somename") isn't language aware

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#509]
A find on page name only works in default language,  what do I have to do to find page by their names in other languages?

I tried
$pages->find("name$langID=somename") to find it in other languages where the name is different.

And get 

Error: Exception: Field does not exist: name1013 (in /home/www-data/processwire/wire/core/PageFinder.php line 470)

Can this be implemented?

**Comment by gadgetto** [comment]
> Using the path is the correct way of retrieval with multi-language pages since the name may or may not be unique among languages (only the path is guaranteed unique). However, I see no problem with adding the ability to query a specific language name field directly, so I've added the ability to do "name$langID=something" like you mentioned, to the latest dev.

Is this still valid?

I get different paths for different categories. The only real unique value seems to be the page id.
