### ISSUE TITLE
Update .htaccess for Apache 2.4

### ISSUE THREAD

**Issue by MECU** [ryancramerdesign/ProcessWire#513]
I'm not an expert in Apache, but I think the only changes required to the .htaccess for upgrading from v2.2 to v2.4 is changing this:

```
<FilesMatch "\.(inc|info|module|sh|sql)$|^(\..*)$">
  Order allow,deny
</FilesMatch>
```
to this:
```
<FilesMatch "\.(inc|info|module|sh|sql)$|^(\..*)$">
  Require all denied
</FilesMatch>
```

Perhaps just add a comment like this:
```
<FilesMatch "\.(inc|info|module|sh|sql)$|^(\..*)$">
  Order allow,deny
# If using Apache 2.4, comment out the above line and un-comment this line:
#  Require all denied
</FilesMatch>

**Comment by phlppschrr** [comment]
I think this can be closed. We have currently rules for both versions in the htaccess which can be swapped by commenting in/out.

I also just made a PR (#1128) which incorporates a universal rule like suggested above.

**Comment by ryancramerdesign** [comment]
Thanks, I will close this out and check out that PR you mentioned.
