### ISSUE TITLE
You do not have permission to execute this module - ProcessPageSearch

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#520]
Hey Ryan,

It looks like the newly added checks for module permissions around line#457 of Modules.php (https://github.com/ryancramerdesign/ProcessWire/commit/2c0762d1f346a3f01171b4f65fa97242f17fd916#diff-995c5c9ce48d4bff459f52363c6e190eR457)

has caused an issue for calls when not logged in with the Pages Web Service module because ProcessPageSearch requires page-edit permissions. Not sure if this affects any other modules.

More details here: https://processwire.com/talk/topic/1654-module-pages-web-service-servicepages/?p=65380

which also includes another issue with the Pages Web Service module and $_GET['it']

**Comment by owzim** [comment]
`'noPermissionCheck'` not working here. 

```
$this->modules->getModule('MyModule', array('noPermissionCheck' => true));
```

Does not prevent the permission exception and additionally throws a notice: `Notice: Undefined variable: class in /wire/core/Modules.php on line 1022`

on `2.7.2`

**Comment by isellsoap** [comment]
@adrianbj Is this still an issue?

**Comment by adrianbj** [comment]
Honestly don't know, but Ryab recently unpublished the module that was broken by this core issue anyway - I don't know why, but I guess that makes it a non-issue :)
