### ISSUE TITLE
New $page methods and properties #documentation

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#577]
The [$page](http://cheatsheet.processwire.com/pages/) and [$pages](http://cheatsheet.processwire.com/pages/) documentation miss the following info:

* "Added new $page->hasChildren() method, which works exactly the same as $page->numChildren() except that it returns only number of visible children (you can also pass a selector string to either method)."
* "Added new $page->editUrl (or $page->editURL if you prefer) property that returns the URL to the page editor for the current page."
* We have added a $sanitizer->purify($html) method that makes use of the HTML Purifier module. For more about HTML Purifier, be sure to visit http://htmlpurifier.org.

Source: http://www.flamingruby.com/blog/processwire-weekly-11/

(This is a note to Ryan. I am aware this is not a bug, but Ryan goes through Github issues on a regular basis.)

**Comment by isellsoap** [comment]
@klor I think this issue can be closed. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
