### ISSUE TITLE
New user via API and guest role not being added

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#588]
When adding a new user via the API - if you don't specifically add the guest role it doesn't seem to be added by default.

Not sure if this is intended or not, but I feel like it might be helpful if it was automatically added.

**Comment by isellsoap** [comment]
@adrianbj Can this issue be closed?

**Comment by adrianbj** [comment]
Honestly I think there are some inconsistencies here that should still be attended to (one way or another). They don't break anything, so not a priority, but I wouldn't like to see this problem forgotten about. Yes, I could reopen in the new issues repo, but that seems to suggest an urgency and if I did that with all the minor issues I still have open here, then the new issues repo would all of a sudden be quite large again. Are we ok with leaving low priority issues here? I don't expect they will ever be fixed unless we can submit (and have accepted) our own PRs for these small and unimportant issues though.

Sorry for going so OT :)

**Comment by isellsoap** [comment]
Sure, that’s totally ok. I’m just trying to go through every issue in this repo here and see which ones can be closed, and which ones cannot. So we leave this issue as it is. Thanks for your feedback!

**Comment by adrianbj** [comment]
Fixed in https://github.com/processwire/processwire/commit/6fe703f699782e4e144568eb8b1e688229dce104
