### ISSUE TITLE
File/Image title bar - extra move to top/bottom trigger areas bug

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#599]
If you move your mouse slowly to the right, starting from hovering over the dimensions of an image there is a section where the cursor changes from "move" to "pointer" and then further along, back to "move".

These changes to InputfieldImage:: renderItem will help you see what I mean. I am just adding title attributes, which I think would be a nice addition so people know what those up and down arrows actually do.

```
"\n\t\t\t<label title='Mark for deletion' class='InputfieldFileDelete'><input type='checkbox' name='delete_$id' value='1' /><span class='ui-icon ui-icon-trash'>Delete</span></label>" .
"\n\t\t\t<a title='Move to bottom' class='InputfieldFileMove InputfieldFileMoveBottom' href='#'><span class='ui-icon ui-icon-arrowthickstop-1-s'></span></a> " .
"\n\t\t\t<a title='Move to top' class='InputfieldFileMove InputfieldFileMoveTop' href='#'><span class='ui-icon ui-icon-arrowthickstop-1-n'></span></a> " .
```

**Comment by isellsoap** [comment]
@adrianbj Can you please close this issue? Thank you!
