### ISSUE TITLE
some missing translation strings

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#609]
maybe you can make them translatable before introducing PW 2.5.

Under 'access/user/name-of-user' the folllowing heading "Roles" and phrase is not translatable (found this phrase in /wire/core/install.sql, line 194)
Under 'access/roles/name-of-user' the heading "Permissions" is not translatable

Also see thread: https://processwire.com/talk/topic/3768-processwire-dev-branch/page-10#entry69071

**Comment by isellsoap** [comment]
@Manfred62 Can this issue be closed?

**Comment by Manfred62** [comment]
yes, can be closed. Think, all issues with "fixed" or "completed" can be closed?
