### ISSUE TITLE
Unable to delete image in repeater

### ISSUE THREAD

**Issue by amasca** [ryancramerdesign/ProcessWire#655]
Hello Ryan,
thank you so mush for Processwire !!!!!

I have an urgent problem and someone on processwire forum told me to ask you directly on github.
I have a repeater with a textlanguagefield, a textarealanguagefield and some Image field (set to 1).
After adding a row to the repeater, and inserting the image. I'm unable to delete the image. Press the trash and save the Page will not delete the image. The message is green: Saved Page: /en/company/ (1 change)  but nothing happened.
I notice also that now is impossible to change position or add a description to a file field in a repeater.
 
Some ideas?
 
Thank you very much
Andrea

**Comment by isellsoap** [comment]
@quickjeff Can you please close this issue? Thank you!

**Comment by isellsoap** [comment]
@quickjeff This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
