### ISSUE TITLE
Admin Theme Reno translation

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#665]
we can easy make more strings translatable in AdminThemeReno.module:
line 53-57
line 66-67
line 82
line 87-88
line 95
line 104

the headings "Pages, Setup, Modules, Access" in the Icons section are not translatable?

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
