### ISSUE TITLE
Admin Theme Reno buttons

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#666]
if Reno is activated: in the language section the buttons 'ZIP download' and 'translate new file' are doubled under the top.
![pw-reno-language](https://cloud.githubusercontent.com/assets/5367033/4260213/37bb814e-3b30-11e4-8e2c-888270d9479b.jpg)

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
