### ISSUE TITLE
translation "Trash" in page tree

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#667]
in the page tree the "Trash" isn't translated anymore? So far I see in older devs, it was always translated. Is there something broken or did I overlook it?

**Comment by plauclair** [comment]
@ryancramerdesign still seeing this one in 2.5.3. I see you made some changes in commit 63692bdda65090032d4d5a0c29475263ea707bf7 around this:
```php
$this->trashLabel = $this->_('Trash'); // Label for 'Trash' page in PageList // Overrides page title if used
```
But there's no overriding going on, it just always says "Trash", no matter what. Note that I installed a language pack in default, English is another one.

**Comment by isellsoap** [comment]
@plauclair Is this still an issue?

**Comment by plauclair** [comment]
I've been away from PW for a while because of ongoing projects at work, I can't confirm nor infirm, sorry!
