### ISSUE TITLE
Lister not always updating after page delete

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#681]
I just deleted a user but the lister view still showed it. I went to edit it to delete again and got a:
```
TemplateFile: Unknown page
```
Obviously the page doesn't actually exist, hence the error, but because Lister didn't refresh, it is a little confusing. 

Usually it does refresh just fine (so hard to reproduce), but wondering if the ajax request needs to be reconfigure slightly to ensure it works more consistently?

**Comment by isellsoap** [comment]
@adrianbj This issue doesn’t seem to be a bug or cannot be reproduced, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
