### ISSUE TITLE
Admin Theme Reno sidebar items on hover (css)

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#682]
[dev 2.5.2]
in the sidebar are strange effects: when an item is selected the icon doubled the height of the element. Also when hover slowly over the links, it's jumping.

![pw-theme-reno-sidebar-selected](https://cloud.githubusercontent.com/assets/5367033/4358989/9089e5c8-426e-11e4-8c3f-ec2fb091cfb1.jpg)

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
