### ISSUE TITLE
Admin Menu Display Issue

### ISSUE THREAD

**Issue by GuruMeditation02** [ryancramerdesign/ProcessWire#683]
Version: 2.5.2 Dev - fresh install
Browser and OS: Linux Manjaro / Firefox 32.0.1

Hi, I've noticed the following issue after both an upgrade from 2.5.0 and a fresh install. Basically, the sub-menu arrows don't line up correctly in the admin menus (see the attached image).

![menu](https://cloud.githubusercontent.com/assets/8806058/4363717/801a104e-4298-11e4-96cd-b8384d8348d0.png)

**Comment by isellsoap** [comment]
@GuruMeditation02 Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!

**Comment by isellsoap** [comment]
@ryancramerdesign Since @GuruMeditation02 doesn’t close the issue, can you do it?
