### ISSUE TITLE
Typo in dev $this->labels['Cancel']

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#684]
[There's a typo](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessModule/ProcessModule.module#L893) in ProcessModule.module

Cancel should be cancel...

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
