### ISSUE TITLE
Images display on the front end before page is saved

### ISSUE THREAD

**Issue by knee-pham** [ryancramerdesign/ProcessWire#689]
https://processwire.com/talk/topic/4312-images-display-on-the-front-end-before-page-is-saved/?p=74879

I have an issue with how images are saved in v2.5 of ProcessWire. They are being saved when uploaded even though the page is not saved.

**Comment by isellsoap** [comment]
@knee-pham Has this issue been addressed with Ryan’s commit https://github.com/ryancramerdesign/ProcessWire/commit/40672080bdf3c610b992880a69b2d860315fec7a?

**Comment by knee-pham** [comment]
I'm not entirely sure if that commit help but I've been using a higher ver. of pw. and I haven't noticed the problem coming up.
