### ISSUE TITLE
error message when uploading too large images

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#707]
in my opinion the error message when uploading too large images with the images field is not very explaining - especially not for clients. see this thread for details: https://processwire.com/talk/topic/7749-max-image-dimensions-not-a-recognized-image-bug

maybe something like "maximum image size - try to resize your image before upload"?

**Comment by isellsoap** [comment]
@BernhardBaumrock Is this still an issue?

**Comment by isellsoap** [comment]
@BernhardBaumrock I close this issue as it seems outdated. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.
