### ISSUE TITLE
WireDatabaseBackup's restore doesn't remove new tables

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#714]
Hey Ryan,

When restoring a backup, any new tables added between the time of the backup and the restore are not removed during restore. This is particularly problematic for fields that were added during that time. The field_fieldname table still exists in the database, but the row for that field no longer exists in the "fields" or "fieldgroups_fields" tables.

Simple solution would obviously be to drop the entire database and recreate it all from scratch during restore. Alternatively it might be safer to create a new database with a "_restore" temporary suffix. When success has been determined, rename the current DB to "_old", remove the "_restore" from the new one, and then delete the "_old" one. 

Or something like that :)

Let me know if you have any questions about what I mean.

Thanks!

**Comment by LostKobrakai** [comment]
I want to put my +1 here as well. This would be really useful for testing. Kinda like a db transaction, just that the testing db can be fully separate, loaded in the beginning of the test replacing the current one, and reseting back to the previously made backup after the tests.

**Comment by adrianbj** [comment]
Closed by https://github.com/processwire/processwire/commit/932ad94dc4bfa78fc8591017432acb0ef59df72b
