### ISSUE TITLE
Manual drag-n-drop sort order fails on child pages

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#719]
I have pages sorted in a manual drag-n-drop order.

* The parent page has this setting: Children > Sort Settings > Children are sorted by: Manual drag-n-drop.
* Expected result: Child-pages are sorted by manual drag-n-drop order.
* Observed result: Child-pages are not sorted.

Code:
```php
<?php foreach ($pages->get('/foo')->find('template=bar') as $p): ?>
	<br><?=$p->title?>
<?php endforeach; ?>
```

I also tried adding sort=sort:

```php
<?php foreach ($pages->get('/foo')->find('template=bar, sort=sort') as $p): ?>
	<br><?=$p->title?>
<?php endforeach; ?>
```

Pages in ProcessWire 2.5 admin says: "Sort settings: If you want all current and future children to automatically sort by a specific field, select the field below and optionally check the 'reverse' checkbox to make the sort descending. Leave the sort field blank if you want to be able to drag-n-drop to your own order."

**Comment by isellsoap** [comment]
@klor This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
