### ISSUE TITLE
ProcessWire 2.5.3: $config->paths->tmp points to a non-existing directory

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#733]
$config->paths->tmp points by default to [...]/site/assets/tmp/
But there is no "tmp" directory in /site/assets after clean install.
Issue is in 2.5.3 (master) and 2.5.4 (current dev).

**Comment by isellsoap** [comment]
@processwired This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.
