### ISSUE TITLE
add translatable string to wire/templates-admin/default.php

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#744]
in 'wire/templates-admin/default.php' you can add:
 * __("Recent");

to make the title in sidebar and heading of module ProcessRecentPages translatable

**Comment by isellsoap** [comment]
@Manfred62 Can this be closed?

**Comment by Manfred62** [comment]
@isellsoap 
Ryan fixed this and it's translatable. But it's no more visible/used in the backend anymore?

**Comment by isellsoap** [comment]
@Manfred62 So this can be closed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
