### ISSUE TITLE
Settings tab

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#762]
With $config->advanced = true I can go to System tab and disable the Settings tab ($template->noSettings = 1;). I think the Settings tab should only be hidden for nonadmins, superuser should always have unlimited access.

**Comment by isellsoap** [comment]
@matjazpotocnik Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by adrianbj** [comment]
@matjazpotocnik - there is this module that allows you to hide specific tabs from users/roles that you choose, based on permission settings: http://modules.processwire.com/modules/restrict-tab-view/
