### ISSUE TITLE
Allow more flexible string overrides in wireRelativeTimeStr()

### ISSUE THREAD

**Issue by netcarver** [ryancramerdesign/ProcessWire#780]
Please could you add a way of overriding the strings used in wireRelativeTimeStr() [in functions.php] to allow different contexts for the $useTense option. I have an application where I'd like to override the default "ago" and "from now" strings in just one context, not across the board. Could this function take an array of overrides as an argument?

**Comment by isellsoap** [comment]
@netcarver Can this be closed?
