### ISSUE TITLE
ProcessModule handling of required versions

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#793]
I got this in my modules Forum:
https://processwire.com/talk/topic/8207-cronjob-database-backup/?p=80380

Even if I don't have set any required version $data['requires_versions'] is set.
It produces an output in the Modules Info Tab like 'Requires 0.0.0>=0'

I could fix it if I don't use line breaks in the infoArray like. But this should work too!

**Doesn't work:**
```
    public static function getModuleInfo() {
        $infoArray = array(
            'requires' => array(
                'LazyCron'
            )
        );
```

**Works:**
```
    public static function getModuleInfo() {
        $infoArray = array(
            'requires' => array('LazyCron')
        );
```

**Comment by teppokoivula** [comment]
@ryancramerdesign Just a heads-up: this is apparently the cause for HannaCodeHelper not being installable at the moment for some users. Any chance you could take another look and fix this?

I'd offer to help, but modules.processwire.com is kind of out of bounds for us, so no can do :)

(The workaround you've offered here might work, but I'd rather see the modules directory fixed than the array-format requires param made pretty much useless. For me the whole point is the clarify it offers, both visually and for version control / change tracking purposes, and using a string or one-line array effectively defeats that benefit.)

**Comment by adrianbj** [comment]
I just went to install HannaCodeHelper and this is still an issue. Any chance the priority on this can be upped a little please :)

**Comment by uiii** [comment]
I have the same problem with my module even in PW 3.x. I think this is a quite major problem because the comment in the core `Module.php` file shows an example of 'requires' as multiline array.

**Comment by kixe** [comment]
The problem seems to be fixed in 3.x
