### ISSUE TITLE
$page->viewable() returns true for unpublished page with custom language

### ISSUE THREAD

**Issue by Roope** [ryancramerdesign/ProcessWire#805]
I noticed this behaviour with basic language switcher:
```php
foreach($languages as $lang) {
	if(!$page->viewable($lang)) continue;
	echo $lang == $user->language ? '<li class="active">' : '<li>';
	echo '<a href="'. $page->localUrl($lang) .'">'. $lang->title .'</a>';
	echo '</li>';
}
```
On unpublished page `viewable()` returns false for default language but not with custom languages. I don't know is this intended or not but would expect it to behave same way despite the language.

**Comment by tbba** [comment]
@roope: issue can be closed?

**Comment by Roope** [comment]
Yep, sorry..
