### ISSUE TITLE
Add default support for utf8mb4-based collations

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#839]
I was trying to setup ProcessWire to accept emojis which require utf8mb4 on MySQL to accept saving them (apparently default utf8 is only 3 bytes long, this requires 4). At first, it would only throw MySQL errors and refuse to save anything. I successfully made it happen though on a new test install, so far nothing weird at all is happening, but I think it might be interesting to add support for this by default.

For those interested, I basically did a search in all files (site and wire) and edited when necessary by replacing strings from utf8 to utf8mb4.

In addition to this, I had to change the maximum varchar lengths in all .sql files to 250 (MyISAM seems to support only 1000 bytes on varchar fields). 

![emoji-processwire](https://cloud.githubusercontent.com/assets/171120/5521030/8aeda95c-8962-11e4-9f28-697be652af24.png)

**Comment by ryancramerdesign** [comment]
Bumping this to refresh the date so it appears back in my current list.
