### ISSUE TITLE
small corrections in FieldtypeComments.module

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#841]
in FieldtypeComments.module line 679, text should be changed to:
'4. Enter **/path/to/page:email** to pull the email from an given page ID and field name, replacing "/path/to/page" with correct path and "email" with name of field containing email address.'

in the moment text is:
'4. Enter **/path/to/page:email** to pull the email from an given page ID and field name, replacing "123" with the page ID and "email" with name of field containing email address.'

**Comment by ryancramerdesign** [comment]
Thanks, good catch! I have updated this and it will appear in today's commits.

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
