### ISSUE TITLE
Date picker for date field not showing inside Table 2.5.12

### ISSUE THREAD

**Issue by alexanderpt** [ryancramerdesign/ProcessWire#842]
JS/CSS datepicker files not loading if template has Table with date. If put another date field in template then both working.

**Comment by ryancramerdesign** [comment]
Thanks, I have located the issue. It's specific to InputfieldTable.module, so will post an update to the ProFields board within the next day or so.

**Comment by isellsoap** [comment]
@alexanderpt Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by isellsoap** [comment]
@ryancramerdesign Could you please close this issue? @alexanderpt doesn’t seem to do so.

**Comment by isellsoap** [comment]
@alexanderpt This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
