### ISSUE TITLE
Update CKEditor to latest (4.4.6)

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#843]
I was having issues with the current CKEditor under Safari 8 (pressing Enter brings the cursor back to the start of the field), it seems to be a problem fixed in CKE in 4.4.4, so I just figured I'd update the plugin. 

I made a zip with the new files, I used your build config file to generate the package and it seems to work perfectly right now (not seeing anything weird in console). Hope this helps!

https://dl.dropboxusercontent.com/u/5378779/InputfieldCKEditor_(CKE4.4.6).zip

**Comment by ryancramerdesign** [comment]
Thanks, this has been updated. I was also seeing the same issue in Safari, glad they fixed it! The CKE config that I use when downloading a new version is just their one labeled "full package", that keeps it simple. :)

**Comment by plauclair** [comment]
Glad to be of help! Cheers! 😄
