### ISSUE TITLE
ProcessPageEdit tab prerendering

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#847]
Hi,

I just wanted to hide the settings / children tab on a single site, which should handle all the theme settings of a page. There is just the problem, that the actual tabs are not so easy to remove, because they are not generated from the result of [buildForm()](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L285), but from the internal [$this->tabs](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L173). So hooking isn't working there. Wouldn't it be clearer to generate the tabs after the buildForm(), so the form can be changed to all extends via hooking?

Greetings,
Benjamin

**Comment by apeisa** [comment]
Set $config->advanced = true and you can hide settings tab on template
level. Don't remember if there is similar for children.
4.1.2015 22.19 kirjoitti "Benjamin Milde" <notifications@github.com>:

**Comment by LostKobrakai** [comment]
```php
if($this->page->addable() || $this->page->numChildren) $form->append($this->buildFormChildren()); 
if(!$this->page->template->noSettings && $this->useSettings) $form->append($this->buildFormSettings()); 
```
Nope, it's only for the settings.

**Comment by ryancramerdesign** [comment]
If you set the template used by the page to disallow children, then you
shouldn't have a children tab. This option can be found in Setup >
Templates > your template > Family (tab).

**Comment by LostKobrakai** [comment]
I just don't want it to display for the edtors. 
I have a site, which should hold all the fields for theme related settings. There are subpages to that page which are only there to generate options in different page fields. These should only be managed on the main settings page via page tables. That's why I don't want anyone (except superuser) to see the children / settings / delete tab.
Does this still work if I disallow children?

**Comment by changwuf31** [comment]
+1 for this.
Currently, I'm achieving this via css. It's a dirty fix.
Wish there's a better way for this. 

As for the reason why, I just don't want this to be displayed for editors on pages that does not need it, to simplify the admin pages. The way I see it, for some pages, only superuser needs to access the settings page.

**Comment by LostKobrakai** [comment]
@changwuf31 If you only need the settings tab to be gone, there are already ways to do that.

**Comment by changwuf31** [comment]
I want the delete tab to be hidden too on some pages.
And when there is only Content Tab left, I want that to be hidden too..

**Comment by LostKobrakai** [comment]
You can rename the content tab in the advanced settings of your templates, to something more fitting, but not remove it completely. The delete tab is by default only available if you have the rights to delete this page, which can also be changed in the template settings. 

The only thing currently not available is not showing children to certain roles.

**Comment by changwuf31** [comment]
@ryancramerdesign @LostKobrakai 
My idea is to define setter and getter for "tabs" property on "ProcessPageEdit".
This way, those who need it can just hook "buildForm", and remove the unwanted tabs.

Surely, this is just one way to do it. Not pretty, but works.

**Comment by ryancramerdesign** [comment]
I think the getters/setters you mentioned makes sense, as does a hook for when PageEdit retrieves the tabs. The following methods have been added to ProcessPageEdit on the dev branch:
````````
addTab(id, label); 
removeTab(id); 
___getTabs(); // hookable
````````

**Comment by LostKobrakai** [comment]
Very nice, now it's quite easy to build custom setting pages by just using ProcessPageEdit.

**Comment by changwuf31** [comment]
Superb, thanks Ryan (y)
