### ISSUE TITLE
Session Flashing

### ISSUE THREAD

**Issue by mike-anthony** [ryancramerdesign/ProcessWire#848]
I think it would be really nice to have `$session->flash('key', 'val')`, only valid for the next request.

**Comment by ryancramerdesign** [comment]
What's a good use case for this? Just trying to understand where it might be used and whether it's something that has broad enough applications to warrant core vs. 3rd party module or function.

**Comment by mike-anthony** [comment]
Ah, goodness - I had a good use-case for it, and I simply can't remember what it was. It'll come to me.

**Comment by esrch** [comment]
Hi,

The feature is actually already covered with the Notices class, as mentioned [here](https://processwire.com/talk/topic/970-flashdata/). Though it might be useful to make it more visible with a separate $session->flash() function.

Use cases could be for example:
* After being logged out, a user is redirected to the home page. On the top of the page, a message appears saying that the logout was successful.
* An application that would allow users to receive, view and delete messages. When viewing a message, the user clicks on delete. He is redirected to the list view, with a message at the top of the screen indicating that the message was deleted successfully.

These types of use cases are already used in the PW admin, when you log in ("login successful"), delete a page ("page moved to trash"), etc.
