### ISSUE TITLE
Loosing changes on template save

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#855]
If I change the name of a template at the same time as I delete a field only the field gets deleted, every other change is discarded, even the ones without confirmation like a labelchange. 

I'm on 2.5.13

**Comment by arjenblokzijl** [comment]
I can confirm this. First rename the template, then do other changes.

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this with renaming a template, but I was able to duplicate it with removing fields.  When it detected removed fields, it was firing off a redirect before letting everything else finish saving. I've fixed that. Please let me know if you still run into any other errors with it. Thanks.

**Comment by LostKobrakai** [comment]
Still no template rename and field removing at the same time, but at least now there's a warning. That should be enough.
