### ISSUE TITLE
ModuleConfig doesn't work with InputfieldCheckbox

### ISSUE THREAD

**Issue by mike-anthony** [ryancramerdesign/ProcessWire#858]
If I check one and save, it remains unchecked. However, the field *does save*.

Using PW 2.5.13.

**Comment by somatonic** [comment]
You have to ckeck it.

**Comment by Da-Fecto** [comment]
In which context is this @mike-anthony ? Are you talking about the Inputfield settings or are you referring to the ConfigurableModules which are static ?

I do think there's still [some weirdness](https://github.com/ryancramerdesign/ProcessWire/issues/428
) going on. 


``` php
	$field = $this->modules->get('InputfieldCheckbox');
	$field->attr('name', 'fname');
	$field->attr('autocheck', 1);
	$field->attr('uncheckedValue', 0);
	$field->attr('checkedValue', 1);
	$field->attr('value', $this->fname);

**Comment by mike-anthony** [comment]
I've just moved over to the new [ModuleConfig](https://processwire.com/blog/posts/new-module-configuration-options/).

Even if I force the value, it doesn't seem to work. But I'll try your method.

**Comment by mike-anthony** [comment]
Seems that the value isn't being sent back to the ModuleConfig class. The field (in my case: `$this->experimentEnhancedPathCleaning`) is `NULL`.

**Comment by mike-anthony** [comment]
In my module, [these two fields](https://github.com/mike-anthony/ProcessAdvancedRedirects/blob/master/ProcessAdvancedRedirectsConfig.php#L129-L149) don't fetch the actual, saved value.

**Comment by mike-anthony** [comment]
Just checked the output markup, it seems that the `value` attribute is being set, not the `checked` attribute.

So, this is just an oversight.

**Comment by mike-anthony** [comment]
I must apologise - I didn't realise that `autocheck` really was needed here. That said, I think it should be handled by ModuleConfig automatically. Or, at the very least, should be mentioned in the page discussing ModuleConfig.
