### ISSUE TITLE
empty $data array() returned in wire/core/Modules.php prevents saving modules configuration

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#859]
in 2.5.14 `public static function getModuleConfigInputfields(array $data)` get an empty array, but that shouldn't be that way.

Report here: https://processwire.com/talk/topic/7588-admin-custom-files/?p=84276
Maybe related: https://processwire.com/talk/topic/4865-custom-upload-names/page-4#entry84264

**Comment by Da-Fecto** [comment]
On this commit: https://github.com/ryancramerdesign/ProcessWire/tree/bdc125ae48cf031b7e7cb3e1a7ef19e0f935f176 the bug is introduced.

**Comment by adrianbj** [comment]
Thanks for taking the time to track this down Martijn.

To avoid missing index notices, I modified slightly to:
```
		if(isset($this->configData[$id]) && is_array($this->configData[$id])) {
		    if (count($this->configData[$id])) return $this->configData[$id];
		    return array(); // module has no config data
		}
```

**Comment by Da-Fecto** [comment]
The isset is a weird one Adrian. `$this->configData[$id]` is just an array, so the code reads to me like:
isset(array()). Is that even possible ?

**Comment by adrianbj** [comment]
I have always used it, but that might not make it right :)

You could always use:
```
array_key_exists($id, $this->configData)
```
instead, but I don't see an issue with isset in this case. Here's an interesting read:
http://stackoverflow.com/questions/3210935/difference-between-isset-and-array-key-exists

**Comment by Da-Fecto** [comment]
Thanks for the info & glad it fixes the others issues. 
(Don't know why mentioned the isset thingy :-1: )

**Comment by Da-Fecto** [comment]
Patch fixed [this issue](https://processwire.com/talk/topic/8745-form-builder-2514/#entry84411) as well.

**Comment by Da-Fecto** [comment]
Latest 2.5.14 seems to fix all instances I see/find.
