### ISSUE TITLE
Issue with repeaterfields not saving

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#860]
If I use showIf or requireIf in repeaterfields, the affected fields don't save.

pw version 2.5.13

**Comment by ryancramerdesign** [comment]
Field dependencies aren't supported in repeaters unfortunately. You may want to use PageTable instead, which does have dependency support.

**Comment by NicoKnoll** [comment]
Maybe something for 2.6 or 3.0? Would be really nice I think.

**Comment by LostKobrakai** [comment]
I submitted this more, because I think showIf and requireIf shouldn't break the saving. Even if it's not supported, just ignore it. At least in my opinion.

**Comment by ryancramerdesign** [comment]
I'm not planning to add official support to repeaters–I would rather keep
that to PageTable, as it's within my bandwidth to support it there. But
there is already undocumented partial support from an update from Soma that
I know some people are using, so I also don't want to prevent it either. If
you want to  get the behavior of showIf/requireIf not interfering with
saving, see the `$config->InputfieldWrapper['useDependencies'] = false;`
option, documented in /wire/config.php. This turns off dependencies at the
server side, while still allowing them to work client side. For many cases,
this also has the effect of enabling dependencies to work in repeaters,
from what I understand (I don't use the option myself).
