### ISSUE TITLE
Fieldtype integer min value 0

### ISSUE THREAD

**Issue by NicoKnoll** [ryancramerdesign/ProcessWire#861]
Hey,
I think I found a little bug. If you create an integer inputfield and choose "0" as min value (to disable negative values) and choose "HTML5" method you are still able to use negative values...

Greets,
Nico

**Comment by LostKobrakai** [comment]
Maybe this helps: https://github.com/ryancramerdesign/ProcessWire/issues/512

**Comment by ryancramerdesign** [comment]
The min/max check is handled server side, regardless of whether input type is HTML5 or regular. If you set your min as 0 and attempt to put in a negative value, you should get an error message on the next screen when you save (with the previous value restored). Though let me know if it is letting you store negative values in the database.
