### ISSUE TITLE
Issue with sorting on a subvalue

### ISSUE THREAD

**Issue by esrch** [ryancramerdesign/ProcessWire#863]
Sorting on a subvalue of a FieldtypePage field throws a SQL error. For example, if a "product" template has a "brand" page field, the selector $pages->find("template=product, sort=brand.title") will throw the error "Unknown column '_sort_page_brand_title.title' in 'order clause'". I made an attempt to fix this issue in the pull request #862 .

**Comment by isellsoap** [comment]
@esrch Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by esrch** [comment]
Good point, I hadn't realized that it was open, thanks!
