### ISSUE TITLE
Subfield selectors don't work when including/bootstrapping Processwire in another PHP file

### ISSUE THREAD

**Issue by Hani79** [ryancramerdesign/ProcessWire#868]
Subfield selectors don't seem to work when I include/bootstrap Processwire in another PHP file using 
```
include("user/mydomain.com/index.php"); // bootstrap ProcessWire
```
The following selector does not return the correct pages:
```
$wire->pages->find('parent=1433,user.billing_problem_at="",total>0');
```
(In that case, I'm searching for records with a total > 0 but where the user does not have a billing problem timestamp on their account.)

No records are returned when making that call in a PHP file where Processwire was included.  If I make the same request on a regular page, records are returned.

If I take out "user.billing_problem_at" from the selector on the ProcessWire-included page, records are returned.

**Comment by ryancramerdesign** [comment]
I'm wondering if it might be a matter of access control? Properties from searches on user won't be accessible to a guest user, which would include the bootstrapped context. Have you tried adding `include=all` or `check_access=0` to it? Another alternative would be to set the user / access control context with:
``````
$user = wire('users')->get('your_account_name');
wire('users')->setCurrentUser($user); 
```````

**Comment by Hani79** [comment]
You're right!  Access control was the issue.  But `include=all` and `check_access=0` didn't do the trick for me because the code is running via a cron job.  Using `setCurrentUser()` did the trick.  I didn't even know that method existed!  Thanks, Ryan!
