### ISSUE TITLE
ß to ss, for page name

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#869]
Ryan, could you add ß to the list of character replacements (page name) and let it replace with ss.

This replacement is save to use as wikipedia states: **While the letter "ß" has been used in other languages, today it is only used in German.**

**Comment by tbba** [comment]
+1
This is right now on my of to-do list each time I set up a new website:
I fix that manually (in the settings) and I am glad that this is possible that easy way.
So it is an inconvenience, but at least for me not a big deal.

**Comment by owzim** [comment]
+1
on a related issue, it'd be nice to have the `$sanitizer->pageName` method somehow connected to these particular settings which are currently only part of the `InputfieldPageName.module`

**Comment by somatonic** [comment]
owzim, it's already. look at the code

$sanitizer->pageName($str, Sanitizer::translate);
or
$sanitizer->pageNameTranslate($str);

**Comment by owzim** [comment]
@somatonic cool, I have looked at the code before but somehow oversaw this particular line:
```
$configData = $this->wire('modules')->getModuleConfigData('InputfieldPageName');
```
Good to know.

**Comment by Da-Fecto** [comment]
Thanks Ryan !

**Comment by ryancramerdesign** [comment]
This one was added a few days ago, but I forgot to mention it in this thread. Thanks.
