### ISSUE TITLE
Markup bug in ProcessCommentsManager.module 

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#871]
On line 307 from ProcessCommentsManager.module when **$comment->getField()->useVotes** evaluates to false `</table>` will never be closed. This results is invalid markup and breaking the admin.

**Comment by ryancramerdesign** [comment]
Thanks! I have added this fix.

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
