### ISSUE TITLE
add new translatable string to wire/templates-admin/default.php

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#875]
(version 2.5.15) add following for dynamic phrases:
```
* __("Logs");
```

**Comment by ryancramerdesign** [comment]
Thanks, this has been added.

**Comment by isellsoap** [comment]
@Manfred62 Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Manfred62** [comment]
fixed
