### ISSUE TITLE
wish: Switch on/off SystemNotifications

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#876]
**Here's an other wish (again)**
The XHR requests from SystemNotifications fill easily up the whole console which make debugging in the js console pretty annoying. What I do now is 1.) put Log XMLHttpRequests off (chrome dev) or 2.) de-install the module. But that one throws away the module settings.

I wish there was a on/off switch so that I don't have to de-install it and can show my own XHR requests.

**Comment by Da-Fecto** [comment]
Great !!!

**Comment by owzim** [comment]
Cool, I was annoyed by this as well ;) thanks

**Comment by isellsoap** [comment]
@Da-Fecto Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
