### ISSUE TITLE
List of fields to display in the admin Page List not populated in template settings

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#879]
On  2.5.15 the title says: The values form 'List of fields to display in the admin Page List' are not populated to the field. The values are saved however. But the next time the template is saved, your settings will be overwritten by the blank value.

**Comment by ryancramerdesign** [comment]
Thanks, looks like I had a capitalization error–fixed.

**Comment by Da-Fecto** [comment]
Checked & me Happy again, thanks Ryan.

**Comment by isellsoap** [comment]
@Da-Fecto Can this issue be closed?

**Comment by Da-Fecto** [comment]
I was happy so sure !
