### ISSUE TITLE
Translator Issue when defaultlanguage contains special characters like umlauts

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/ProcessWire#881]
Hey, I have seen a bug where strings for translation (textinputfield titles/labels) are not shown in the edit mask but are completly missing.

To simply replicate this please add a translation string into a site template file like:
```$text = __("Übersicht");```

Now the default language has a string with a special char that needs to be translated to additional languages. 

When you go to translate that file to another language you would assume to see a textinputfield with a title and / or label with that string "Übersicht". But both is missing! There is only an empty textinputfield without any header or label or comment.

This behaves the same with PW 2.5 stable and PW 2.5 dev and with earlier versions (2.4) too.

**Comment by ryancramerdesign** [comment]
Horst, I can't seem to duplicate this one. I added your text translation string to my site/templates/basic-page.php and then went to the translator and saw this (screenshot below). Is it possible that your template file is not UTF-8 or something like that?
![screen shot 2015-02-02 at 5 53 30 am](https://cloud.githubusercontent.com/assets/328272/5999481/2a5b41bc-aaa0-11e4-99be-aa20ff667db3.png)

**Comment by horst-n** [comment]
Ryan, thank you for looking into this. I haven't explored this by myself. I haven't worked with the translator by myself and have no install at hand where this were ready to use for me. I have seen this by a webdeveloper here in town and he has told me that another person also has this issue. 
So, I will check this with him and come back here.

Many thanks.

**Comment by horst-n** [comment]
@ryancramerdesign: it was like you mentioned: the files were saved with the wrong encoding!
