### ISSUE TITLE
Time not showing in datetime field when using current date and no time picker

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#882]
I was helping someone on the forum when we discovered something.

When you:
- create a datetime field,
- choose time formats in Details and Input tabs,
- check the Default to today's date option,
- *don't* use a datetime picker;

The value created doesn't seem to hold the time (only shows YYYY-MM-DD). When you *do* use a datetime picker, the value shows up as it's supposed to.

**Comment by plauclair** [comment]
Looking at the source, in InputDatetime.module (line 92 onwards), $useTime is set to false and must pass if($this->datepicker) to ever be set to true. Is that the intended behaviour?

**Comment by ryancramerdesign** [comment]
Nope that's not the intended behavior. Thanks for letting me know. I have fixed locally and it will appear in today's commits.
