### ISSUE TITLE
ckeditor with image management: error when inserting SINGLE image

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#886]
when inserting a SINGLE image i get this error:
![image](https://cloud.githubusercontent.com/assets/8488586/5935880/b4ecda8a-a6df-11e4-84b1-4eb032aac09b.png)

setup:
1 body field (ckeditor, Markup/HTML with image management)
1 image field:
![image](https://cloud.githubusercontent.com/assets/8488586/5935917/f7e7cb38-a6df-11e4-9707-8e461d1e645c.png)

everything works if
1) i set the maxiumum allowed images to zero OR
2) i set it to "array of items"

but then my templates brake, as i'm using $image->url and not $image->first()->url

if there is a fix on that, i would prefer leaving my templates untouched :)

thank you!

**Comment by BernhardBaumrock** [comment]
ProcessWire 2.5.15 dev

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this to dev.

On Wed, Jan 28, 2015 at 5:29 AM, Bernhard Baumrock <notifications@github.com

**Comment by BernhardBaumrock** [comment]
Wow, that was quick :+1: Thank you!
