### ISSUE TITLE
Sorting something strange with integer

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#888]
I have pages I list sorted by modified date and a integer field (page_nr).

If I use sort=-modified, sort=page_nr it sorts starting by 10 up to 34 and the 1 to 10.
If I use sort=-modified, sort=-page_nr sorting is correct but from 34 down to 1, which I don't need.

**Comment by ryancramerdesign** [comment]
Since '-modified' is the first specified sort, the order is going to depend primarily on what's in those dates. Only when multiple pages have the same exact modified date/time (down to the second) will the page_nr even come into play.
