### ISSUE TITLE
ProcessLogger wrong count

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#890]
On overview it says 3 errors but the log contains 4! :)

**Comment by ryancramerdesign** [comment]
I've submitted an update for this. Accurate total counts aren't completely possible here, at least not while keeping it fast on large log files. But for small log files we can get it more accurate at least. When it's actually displaying each pagination of the log, it parses the lines and removes duplicate or invalid lines last it finds them. So if you click to the last pagination of a log file, you may find the actual total to be different from the estimated. I've added a little tag next to the pagination info headline indicating whether the total number is estimated or actual.
