### ISSUE TITLE
2.5.16 can't edit templates anymore

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#891]
Fatal error: Call to a member function attr() on a non-object in /home/www-data/*/wire/modules/Process/ProcessTemplate/ProcessTemplate.module on line 1003
Error: Call to a member function attr() on a non-object (line 1003 of /home/www-data/*/wire/modules/Process/ProcessTemplate/ProcessTemplate.module) 
This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged. Administrator has been notified.

**Comment by somatonic** [comment]
Ah I see that's the InputfieldIcon not being installed... but I thought a
$field = $this->modules->get("InputfieldIcon");

will install a module if it's not...

**Comment by apeisa** [comment]
That icon module has caused two "why this dev site suddenly stopped working" confusions at our office. Any hope getting running module refresh through system updater because of this?

**Comment by adrianbj** [comment]
Just for cross-linking purposes:
https://github.com/ryancramerdesign/ProcessWire/issues/873

**Comment by apeisa** [comment]
Ah, thanks Adrian! So we were updating our dev branch in bad time in history :)

**Comment by ryancramerdesign** [comment]
Yes I think that was it, but please let me know if anyone continues to see it. Btw, it should not cause a dev site to suddenly stop working–only the field or template edit screen, until a modules refresh. Any other requests to the site would still be successful. If you are seeing the whole site stop, that might be a different issue, so please let me know if so.
