### ISSUE TITLE
Fatal error in PageFinder when trying to add new language 

### ISSUE THREAD

**Issue by anilex** [ryancramerdesign/ProcessWire#893]
```
Notice: Undefined variable: stmt in /<path>/wire/core/PageFinder.php on line 286
Fatal error: Call to a member function errorCode() on a non-object in /<path>/wire/core/PageFinder.php on line 286
```

When I try to add new language.
(latest dev 2.5.17, clean site-language install)

**Comment by isellsoap** [comment]
@anilex Can this issue be closed?

**Comment by isellsoap** [comment]
@ryancramerdesign Could you please close this issue? Thank you!

**Comment by isellsoap** [comment]
@anilex This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.
