### ISSUE TITLE
SQL syntax error in FieldtypeOptions (SelectableOptionManager.php)

### ISSUE THREAD

**Issue by kongondo** [ryancramerdesign/ProcessWire#895]
Issue reported here: https://processwire.com/talk/topic/3768-processwire-dev-branch/?p=86665

It prevents values from being update resulting in the error: 
Option 14 'New York': SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

On line [#548](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Fieldtype/FieldtypeOptions/SelectableOptionManager.php#L548) in SelectableOptionManager.php, there is a missing 'space' at the beginning of the SQL string.

```php
$sql .=	"WHERE fields_id=:fields_id AND option_id=:option_id";
```
This should be:
```php
$sql .=	" WHERE fields_id=:fields_id AND option_id=:option_id";
```
Although that 'space' is in line [#543](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Fieldtype/FieldtypeOptions/SelectableOptionManager.php#L543), that's wrapped in a conditional for multi-language environments so it is not catching for single language environments?

```php
$sql .= ", $name=:$name ";
```
Not sure how the suggested change will affect those in multi-language setups, but am sure you will figure it out :-)

**Comment by ryancramerdesign** [comment]
Thanks for tracking that down kongondo. This is the second time I've fixed
it, somehow I keep managing to remove leading/trailing whitespace from
query lines likes this... starting to wonder if PhpStorm is doing it when
lines get reformatted (running on a new copy that I'm still tweaking the
config).

**Comment by isellsoap** [comment]
@kongondo Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by kongondo** [comment]
Done, thanks.
