### ISSUE TITLE
FieldtypeOptions, Select (Single Value) and Radios (Single Value) error

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#896]
When i choose **"Select (Single Value)"** and **"Radios (Single Value)"** from Details (tab) -> What should be used for input? section getting error 2 times :

```
Notice: Array to string conversion in /{PATH}/wire/modules/Inputfield/InputfieldSelect.module on line 210

Notice: Array to string conversion in /{PATH}/wire/modules/Inputfield/InputfieldSelect.module on line 210
```

**Comment by ryancramerdesign** [comment]
It took me a bit to figure out how to duplicate this one, but finally did. The fix should appear in the latest commit. Thanks.
