### ISSUE TITLE
Can't use Ymd as date input format

### ISSUE THREAD

**Issue by Roope** [ryancramerdesign/ProcessWire#897]
I have bunch of datetime fields that are defined to use 'Ymd' as custom input format.

Entered dates are treated as unformated (unix time) values - eg. 20150202 changes to 19700822 after page save.

I've tried to add 'Ymd' to [InputfieldDatetime.module](https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Fieldtype/FieldtypeDatetime.module#L36) but that doesn't seem to help.

Using PW stable 2.5.3 version.

**Comment by ryancramerdesign** [comment]
I'm not sure how to support this one because Ymd contains no punctuation, and thus is indistinguishable from a unix timestamp. Since FieldtypeDatetime needs to support input of either a timestamp or a formatted string, it has to assume that a string of only digits is a timestamp.

**Comment by Roope** [comment]
Short after posting this I figured this must be the case. So I'll be closing this for now since there is no way to recognize formating on a digits only string. Thanks for your reply!
