### ISSUE TITLE
Backend Page Search (error/access)

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#906]
I got this error sent today

Call to a member function errorCode() on a non-object (line 286 of /wire/core/PageFinder.php)

Not idea why.

The other thing is, why do editor get the old search when they enter /page/search ? and superusers get the lister search? It's also when I enter search term in the topbar and enter.. editor lands on the old page search. Is this intentional and if how can I change that?

**Comment by somatonic** [comment]
Just looking the the ProcessPageSearch, there a check for permission "lister" but there's no "lister" persmission, only "page-lister" for the base lister access. Did you forget to change it?

**Comment by ryancramerdesign** [comment]
You are right, looks like I've got the wrong permission in there. I've fixed and it will be in today's commits. Thanks.
