### ISSUE TITLE
thousands of log entries in modules.txt with recent version

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/ProcessWire#907]
Hi Ryan,

we have encountered that there are with newer dev versions (between 2.5.12 and 2.5.16) one can get very quickly thousands of log entries in the modules.txt.

I use in two modules (Pia and Croppableimages) some tweaking / merging of the config data in the classes init methods with the API call to save the config data:
```wire('modules')->saveModuleConfigData(__CLASS__, $data);```

This forces everytime now a log entry like: ```2015-02-06 09:51:45	?	?	Saved module 'FieldtypeCroppableImage' config data```
or
```2015-02-06 09:51:45	horst	http://croppableimage.kawobi.local/	Saved module 'PageimageAssistant' config data```

Is there any method / flag / setting that we can use to avoid those entries?

**Comment by ryancramerdesign** [comment]
Horst, see /wire/config.php entry for `$config->logs`. You can turn off the modules log by adding this to your /site/config.php: `$config->logs = array();`

**Comment by horst-n** [comment]
Ah, ok. Thanks Ryan.
