### ISSUE TITLE
Reno Theme: fatal error with images

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#911]
Fatal error: Exception: Method Pageimage::first does not exist or is not callable in this context (in /...wire/core/Wire.php line 325) #0 /.../wire/modules/AdminTheme/AdminThemeReno/AdminThemeRenoHelpers.php(85): Wire->__call('first', Array)

I got this error when trying to delete an image from a page. Seems to be specific - I could not duplicate that behavior on other installations. But maybe there is a way to be smarter with the problem instead of a fatal error that makes further editing impossible in that case. (debug is on / PW dev version).

**Comment by tbba** [comment]
That could have to do with the pageTableExtended module and a content block in the table containing a text field managed by CKE which includes an image... :-)

There is no issue with the default theme!

**Comment by ryancramerdesign** [comment]
I think I see what the issue is. AdminThemeReno uses an avatar image, and it looks like it expects it to be a multi-image field. I've fixed it locally and it should appear in today's commits.

**Comment by Renobird** [comment]
Thanks Ryan. I had fixed that locally a while back and forgot about it.

**Comment by tbba** [comment]
Hooray, works! :-)
