### ISSUE TITLE
Min/Max of number fields context sensitive

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#913]
It would be nice, to set min/max settings template specific. 
My current need would be a field to limit / soft cap the number of children of this page, and warn the user if he gets there. But this depends on the content type.

**Comment by esrch** [comment]
I just wanted to mention that this problem can be solved with a hook, for example (in a module):

```php
$this->addHookAfter("InputfieldInteger::getConfigAllowContext", function($event) {
    $a = array("min", "max");
    $event->return = array_merge($event->return, $a);
})
```

I had to do this yesterday for a project (but making "Selectable pages" for InputfieldPage context-dependent).

**Comment by LostKobrakai** [comment]
I've archieved it already with the new ability to have a copy of the core module in the site modules. Just changed the array there.

**Comment by esrch** [comment]
I didn't know that was possible! Thanks for the tip :-)
