### ISSUE TITLE
ProcessPageEdit shows wrong buttons for unpublishable page

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#914]
ProcessPageEdit shows the `publish` and `save + keep unpublished` even if the current page is unpublishable. That's a heck of a lot confusing. I had to triple check my hook on `Page::publishable` and the ProcessPageEdit sourcecode to find out my hook indeed worked, but the module just still shows the wrong buttons.

**Comment by horst-n** [comment]
+1
It does a lot of confusion to not so save users! Would be good to simply not display it for users that do not have page-publish permission.

**Comment by Spica2** [comment]
agree, same issiu here

**Comment by ryancramerdesign** [comment]
Can you describe the steps to duplicate from a blank installation?

**Comment by LostKobrakai** [comment]
I've just tested it in a fresh dev install. I used the blank profile and added a new "basic-page" and leave it unpublished. Then I installed this module and when I edit the page there are both buttons, while the user in fact can't publish the page and the checkbox for publish/unpublish is also hidden.

```
<?php
class Publishable extends WireData implements Module {

	public static function getModuleInfo() {

		return array(
			'title' => 'Publishable', 
			'version' => 1, 
			'summary' => 'Test',
			'singular' => true, 
			'autoload' => true,
			);
	}

	public function init() {
		$this->addHookAfter('Page::publishable', $this, 'checkSoftCapLimits');
	}

	public function checkSoftCapLimits(HookEvent $event){
		$page = $event->object;

		if($page->template->name === "basic-page"){
			$event->return = false;
		}
	}
	
}
```

**Comment by ryancramerdesign** [comment]
Thanks, I think I understand now. I have just pushed an update that should
fix this.

**Comment by yckart** [comment]
Works @ryancramerdesign :+1:
