### ISSUE TITLE
InputfieldCheckbox::render overrides skipLabel

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#916]
There seems currently no way to have a Checkbox show a headerlabel without a description.

**Comment by ryancramerdesign** [comment]
That's correct, if referring to default behavior of admin output. The point is to not show the same label twice, right on top of one another. But if referring to API side, you can specify a separate $inputfield->label and $inputfield->label2, and if they are different then it will show both.

**Comment by LostKobrakai** [comment]
I'm talking about the api side and it doesn't work for me in 2.5.19. This still shows only label2 in the module settings.
```php
		$f2 = wire('modules')->get('InputfieldCheckbox');
		$f2->label = __("Should system templates be shown?");
		$f2->label2 = __("Activate");
		$f2->skipLabel = Inputfield::skipLabelNo;
		$f2->attr('id+name', 'showSystem');
		$f2->attr('value', $showSystem);
		if($showSystem) $f2->attr('checked', "checked");
		$inputfields->add($f2);
```

**Comment by ryancramerdesign** [comment]
Okay I understand, it looks like label2 isn't part of the logic there but
really should be. I have updated locally to correct that so it should
appear in this weeks commits.
