### ISSUE TITLE
[2.5.18] Adding Fieldset* field to template via Actions doesn't add its _END equivalent

### ISSUE THREAD

**Issue by mike-anthony** [ryancramerdesign/ProcessWire#917]
For example, if I add the field **imagery_tab** to the template **home** (via Actions), only **imagery_tab is added** - it should also add **imagery_tab_END**.

**Comment by NicoKnoll** [comment]
If imagery_tab_END is created then this is not a mistake. Because imagery_tab_END is a separate field using a special template.

But I guess it would be nice to get a warning/error if you forget to add "..._END" field.

**Comment by mike-anthony** [comment]
imagery_tab_END *is* created, but it is not automatically added to a template when using the Actions tab for the field. That needs to be fixed, in my opinion.

**Comment by NicoKnoll** [comment]
Ah okay, you used the action field. I think you're right then.

**Comment by ryancramerdesign** [comment]
I have added this so that it also asks you were to put the fieldset_END field within this action. It should appear in this weeks commits.

**Comment by NicoKnoll** [comment]
Nice :+1:

**Comment by mike-anthony** [comment]
Great stuff, thanks Ryan :+1:
