### ISSUE TITLE
404 pages gets no icon

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#918]
I've a specific template for the 404 page and it just won't show the chosen icon.

pw 2.5.18

**Comment by Da-Fecto** [comment]
404 Page is a 'system' page. Those are not handled as normal pages in the tree. The 404 is only shown for the superuser.

**Comment by LostKobrakai** [comment]
yeah, but admin / roles / user seemed to work.

**Comment by ryancramerdesign** [comment]
Not sure about this one, I can't seem to duplicate. I changed the icon on the template used by my 404 page and am seeing that icon in the PageList. Or are you talking about somewhere else?

**Comment by LostKobrakai** [comment]
No, I'm not talking about other places, it's not visible in the PageTree for me. Every other page/template seems to work as mentioned above. Also I'm not aware that any installed 3rd party module would change something in the tree view.

**Comment by gingebaker** [comment]
I ran in the same issue today. I did set the Icon on the specified 404 template (PageID 27). It shows no icon in the page tree.

I nailed it down to an translation issue (multi language support). No bug, a feature...!?
In this particular PW installation I also installed a language pack for default language. This translated also this core file:
wire/modules/Process/ProcessPageList/ProcessPageListRenderJSON.php

Than checked out this file where I found the hint that solved it for me...(Line 40)
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageList/ProcessPageListRenderJSON.php#L40

So if a language Pack overwrites the string "404 Page Not Found", than you cannot set an icon anymore.

perhaps this helps in your case too?

**Comment by isellsoap** [comment]
@LostKobrakai Can this issue be closed? Is this still an issue in latest PW?

**Comment by isellsoap** [comment]
Can you write the exact steps to reproduce the issue? I fear that otherwise this issue won’t get fixed any time soon. Thank you.

**Comment by LostKobrakai** [comment]
gingerbaker did already supply that with a exact location in the code. I think that should be enough.

**Comment by isellsoap** [comment]
So what’s the suggested fix (technically speaking)?

**Comment by LostKobrakai** [comment]
Not matching against a translatable string or any other means of not overwriting the icon if only the title should be changed.

**Comment by isellsoap** [comment]
@ryancramerdesign This issue is reproducible. @gingebaker tracked it down [quite nicely](https://github.com/ryancramerdesign/ProcessWire/issues/918#issuecomment-160151724) and @LostKobrakai has a [suggested fix](https://github.com/ryancramerdesign/ProcessWire/issues/918#issuecomment-250754993) for this.
