### ISSUE TITLE
Add proper umlauts conversion for page name (InputfieldPageName)

### ISSUE THREAD

**Issue by owzim** [ryancramerdesign/ProcessWire#922]
Related to #869
Wrong:
```
ä=a
ö=o
ü=u
```
Correct:
```
ä=ae
ö=oe
ü=ue
```
This is one of the first things I change after every fresh PW installation. It should be default.
Thanks.

**Comment by NicoKnoll** [comment]
Already posted: https://github.com/ryancramerdesign/ProcessWire/issues/41

TL;DR:
There are other languages (like finish) where ä => a is correct. So Ryan decided to use the closest replacement to each letter (which in this case would be a not ae).

**Comment by owzim** [comment]
@NicoKnoll thanks for the info
