### ISSUE TITLE
dev: adminTheme - missing css

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#926]
small mystery bug when editing a page (backend, PW dev) 

Safari complains about a missing file (404 error):
https://...domain.../wire/modules/AdminTheme/AdminThemeDefault/styles/main-classic.css.map

In the page source I only find this:
link type="text/css" href="/wire/modules/AdminTheme/AdminThemeDefault/styles/main-classic.css?v=12a" rel="stylesheet" 

So this is maybe a side effect of some javascript?

**Comment by owzim** [comment]
Chrome tries to find a css.map when the source maps feature is enabled (it's for debugging preprocessed css, like Sass or LESS), perhaps that's the same with Safari?
It's certainly not an issue with PW.

**Comment by tbba** [comment]
Thank you for pointing me to that. Seems to be a Safari related nonsense.

**Comment by mike-anthony** [comment]
Blink/WebKit-related nonsense. :wink:

**Comment by owzim** [comment]
not nonsense.

**Comment by mike-anthony** [comment]
Indeed, not nonsense. Was only correcting the 'Safari' part.

**Comment by owzim** [comment]
:+1: :smile:

**Comment by owzim** [comment]
Perhaps reopen. This should not be happening, since browsers with source map support only look for source maps if there is a special line in the CSS file.
```
/*# sourceMappingURL=main-warm.css.map */
```
This line should be stripped on distribution.

**Comment by tbba** [comment]
ozwim, I agree. Glad you found a solution.
Actually I am still not happy seeing a 404 error notice for something not being a real error in fact. I find that distracting.

**Comment by ryancramerdesign** [comment]
I've always compiled the scss files manually with the compile.sh script in
the same directory. But it looks like PhpStorm has started compiling the
scss files automatically on its own, and that must be where this came from.
I'll figure out how to turn that off so these css.map references stop
appearing.

**Comment by owzim** [comment]
This should be reopened until this is fixed then.
