### ISSUE TITLE
FieldtypeOptions and wrong value with getLanguageValue

### ISSUE THREAD

**Issue by owzim** [ryancramerdesign/ProcessWire#927]
I've installed a fresh `2.5.19` with the multi language profile

I've added an `option` field, with the following values:

English (`default`):
```
1=brown|Brown
2=yellow|Yellow
3=green|Green
```
German (`de`):
```
1=brown|Braun
2=yellow|Gelb
3=green|Grün
```
and added that field to `basic-page`

on `/about/` I've set the option to 1=brown

When I want to retrieve the `title` of the selected option in a certain language, I always get the default, the English version:

```PHP
$p = $this->pages->get('/about/');
$p->getLanguageValue('default', 'options')->title; // Brown
$p->getLanguageValue('de', 'options')->title; // Brown
```

**Comment by ryancramerdesign** [comment]
This is actually not a multi-language Fieldtype in the way you are thinking of. The values it stores do not vary by language. It just keeps one value for all languages (an ID number). So you have to think of this as being the same thing as a Page fieldtype in that sense. The field provides multi-language labels, but not multi-language values. To word it differently, you can't have different selected options per language. So the getLanguageValue/setLanguageValue interface doesn't apply here. That interface is exclusive to fields that actually store different values per language. 

In your example the `->title` access is actually occurring after the `getLanguageValue()` call. So your getLanguageValue() call is doing the correct thing (not that it matters). By the time your `->title` call occurs, the user's language has already been set back to the previous language (as it has to be). Basically think of this as working the same way as a Page fieldtype. 

To achieve the result you want, try this: 
`````````
$user->language = $languages->get('default'); 
echo $page->options->title; // Brown
$user->language = $languages->get('de'); 
echo $page->options->title; // German version of Brown
`````````

**Comment by isellsoap** [comment]
@owzim Can be closed?

**Comment by isellsoap** [comment]
@owzim This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
