### ISSUE TITLE
FilenameArray class to implement Countable interface

### ISSUE THREAD

**Issue by hwmaier** [ryancramerdesign/ProcessWire#929]
It would be beneficial if the FilenameArray class would have a count() method.
Suggested implementation:

```php
class FilenameArray implements IteratorAggregate, Countable {

...

/**
 * Returns the number of items in this FilenameArray.
 *
 * Fulfills Countable interface.
 *
 * @return int
 */
 public function count() {
     return count($this->data);
 }
```

Rationale:
A count method can be used to check if any scripts or stylesheets are configured as shown in the following example:

```php
<?if (count($config->scripts)):?>
    <script type="text/javascript" src="<?=AllInOneMinify::JS($config->scripts?>"></script>
<?endif?>
```

The current implementation of FilenameArray does not implement the Countable interface and count() will return a 1 regardless of the number of elements in the FilenameArray.

Refer to https://processwire.com/talk/topic/9074-filenamearray-class-to-implement-countable-interface/#entry87961

**Comment by ryancramerdesign** [comment]
Makes sense to me. I have added and it will appear in this weeks commits. Thanks.
