### ISSUE TITLE
5.19 & cropimage

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#930]
Does v5.19 breaks @apeisa Image cropping tool? Since installed newly cropped images are saved to the assets folder, but the size is wrong with a factor of 2
So an image configured in the field input:
etalage,600,100,admin-shop (name, width, height, template)
ends up as 1200x200 in the assets folder.

**Comment by ryancramerdesign** [comment]
Not as far as I know, but from what I understand apeisa's
thumbnails/cropimage module doesn't work in PW 2.5 at all? At least I seem
to have read that somewhere, but not tried yet. You may want to look into
using Horst's CroppableImage instead though, as I think that's a fork that
does more and is designed for PW 2.5+. It's pretty much identical when it
comes to the base functionality, but CroppableImage just takes it further.

**Comment by ryancramerdesign** [comment]
I'm on GitHub directly now. The info about the doubled dimensions didn't show up in the email I replied to. That does sound more like core than apeisa's module. I'll take a closer look at this now to see what I can find.

**Comment by junofornow** [comment]
yeah, I always type before I think, so I have to edit my original message
often more than once ;-)

groeten,

Andre
Truespace Bvba, Stijfselrui 28/11, 2000 Antwerpen
+32498110192 - truespace.be - KBO 0873.901.902

2015-02-16 16:09 GMT+01:00 Ryan Cramer <notifications@github.com>:

**Comment by ryancramerdesign** [comment]
I think that I tracked it down. I had the wrong scale value in the ImageSizer class, which was screwing up both CropImage and CroppableImage. I just pushed a fix, so it should work correctly now. I actually tested with CroppableImage since I already had it installed, but I'm assuming it's the same issue that was affecting CropImage.

**Comment by junofornow** [comment]
Perfect, solves it for cropimage too. Thanks for the prompt fix.
