### ISSUE TITLE
Inputfield Dependencies problem on template access settings?

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#933]
When I remove guest from view I get some additional settings below. But when I add back view access to guest and save one field still shows but shouldn't.

![image](https://cloud.githubusercontent.com/assets/370148/6226366/ad248b6c-b694-11e4-809f-cc4245a8c1d7.png)

**Comment by ryancramerdesign** [comment]
That's because your login URL field is populated with a value. If you want it to disappear, you'll need to remove the value from it first.

**Comment by somatonic** [comment]
I see so the show if populated is overwriting the dependencies. I guess it's an issue also with nested rules. 

Anyway but it says it's only available if "Redirect to another url is selected"... Seems confusing.

**Comment by isellsoap** [comment]
@somatonic Should @ryancramerdesign do something or can this issue be closed?
