### ISSUE TITLE
Comments approve link from email doesn't approve comment

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#937]
Not sure what's going on but I'm testing approve of comments.

I recieve email with link to approve. Opening that link doesn't do anything. Is it working for you?

The links looks like this
news/ausland/wirtschaft/sony-setzt-kuenftig-voll-auf-playstation-und-bildsensoren-20150218112430/?field=comments&page_id=122790&code=LqhZbFGGnBJlgpMj6CgN50y_stmVnIxccMIt05PsMgk4xPIgyCiCdUKa7s1qkLjEG9y7opV_RwotPUHfXs8WH7pdTl707lLnrp7g9tAgwJQs2X_9ZbbG13L8RmwqQ_Xl&comment_success=approve

But doesn't do anything.

**Comment by somatonic** [comment]
Ok, found that it's when it's the first comment on page, and I don't render the comments list cause there's no comments yet. But the check for the action is in CommentsList. How could I handle this?

**Comment by ryancramerdesign** [comment]
Your best bet is to still render the CommentsList, but hide it with CSS. Something like this:
```````
$cnt = count($page->comments); 
echo "<div class='comments-cnt$cnt'>" . $page->comments->renderList() . "</div>";
```````
Then in CSS
```````
.comments-cnt0 {
  display: none; 
}
```````

**Comment by somatonic** [comment]
I now display the comments list just with a "no comments yet" message.
