### ISSUE TITLE
"Saving..." then nothing happens

### ISSUE THREAD

**Issue by jacmaes** [ryancramerdesign/ProcessWire#942]
In today's (Feb. 18) dev update, whenever I try the new image editing option,  a "saving..." button immediately appears when the modal loads, then nothing happens, even after waiting for a couple of minutes:
![saving](https://cloud.githubusercontent.com/assets/1206842/6255196/84bc827c-b7ae-11e4-9acc-279d4983b015.png)

On another try, after closing the modal, navigating away from the page, then coming back to it, the image disappeared:

![no-image](https://cloud.githubusercontent.com/assets/1206842/6255227/c98dad90-b7ae-11e4-9ecd-41278d125f55.png)

**Comment by ryancramerdesign** [comment]
Looks like your browser definitely has older CSS/JS files cached. In your
admin, do a Modules > Refresh. If that doesn't do it, clear your browser
cache or quit/re-open. If you still see any errors after that, let me know
what browser you are using (I've done most of my testing in Chrome and
Safari thus far).

**Comment by jacmaes** [comment]
Yep, that was it. I read your recommendation about refreshing the module in the commit, then forgot about it. Sorry to bother you with this.
