### ISSUE TITLE
Lister 1.0.1 doesn't show me the editor anymore

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#944]
![image](https://cloud.githubusercontent.com/assets/370148/6256382/f0b3b5e6-b7b7-11e4-96ba-01a9097fb555.png)

The field is the modified_users_id and created_users_id.
It's just empty and I think it was populated a while ago. I updated meanwhile to  ListerPro 1.0.1 and also Core, maybe that caused an issue? 

I can't think of any relevant other changes I made or something that could interferer.

Also happens on core page search, so not sure where the cause is for this.

Edit: This seems strange as it works on my other local test install. Just on this site there seems an issue and I have no idea where :)

**Comment by somatonic** [comment]
Ok I see now. Heh, yeah I have definately more than 100 users. :)

```
// InputfieldSelector
$numUsers = $this->wire('pages')->count("template=user, include=all"); 
		if($numUsers < 100) { 
			foreach($this->wire('users') as $user) {
				$users[$user->id] = $user->name; 
			}
		}
```

Shouldn't then it have autocmplete search? I remember you mentioned it would switch to when more than a certain amount.

**Comment by somatonic** [comment]
Ok I figured now that it is because of this bug reported here https://github.com/ryancramerdesign/ProcessWire/issues/915

**Comment by somatonic** [comment]
Oook, took me a while to spot it...

InputfieldSelector there's
```
if(!count($users)) {
			$this->systemFields['modified_users_id']['type'] = 'number';
			unset($this->systemFields['modified_users_id']['options']);
			$this->systemFields['created_users_id']['type'] = 'number';
			unset($this->systemFields['created_users_id']['options']);
		}
``` 

it should be "input"
```
if(!count($users)) {
			$this->systemFields['modified_users_id']['input'] = 'number';
			unset($this->systemFields['modified_users_id']['options']);
			$this->systemFields['created_users_id']['input'] = 'number';
			unset($this->systemFields['created_users_id']['options']);
		}
```

**Comment by ryancramerdesign** [comment]
Excellent detective work–thanks! I have updated and it will appear in this weeks commits.
