### ISSUE TITLE
2.5.19 - 2.5.20 Label for InputfieldSubmit visible

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#960]
Before update

![image](https://cloud.githubusercontent.com/assets/370148/6351232/f49a6b06-bc39-11e4-9e52-812a81b55197.png)

After update

![image](https://cloud.githubusercontent.com/assets/370148/6351251/1e460d7a-bc3a-11e4-949a-c0bbe5c55380.png)

Every now and then I have to go hunt for changes like this. Where is that change that show those label's again? I guess that's the price we pay for using Inputfields on front-end. But then form builder suffers from the same.

**Comment by somatonic** [comment]
I had to remove a $submit->label = "Filtern" from my Inputfield form since now the skipLabelBlank is now used.

**Comment by ryancramerdesign** [comment]
I'm not seeing this issue anywhere yet (not in FormBuilder either), but you mentioned you were assigning a label to a submit field, and I think what you actually want is $submit->value = "Filtern" instead? There's no need to assign a label (or description or notes) to a submit field unless you literally want a label to appear with it.

**Comment by somatonic** [comment]
Yeah I figured that the label was there in some of my forms. I don't know what changed but thy werent visible in later 2.5.19 early 2.5.20. So removing them fixed it.
