### ISSUE TITLE
New field actions triggered remotely

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#962]
I have a problem with the new field actions.
I change various things with the field and on saving an alert appears whether I want to remove the field from the xyz template. (I never touched something inside of the tab actions tab, so something there was fired remotely.)
Is there someone else seeing the same behaviors?
Unfortunately I cannot yet say what exactly causes this behavior and whether custom modules are involved (I use the after-save-actions module for example). But maybe the actions area can be better protected already by just renaming variables? Otherwise I need to keep an eye on this. 
PW 2.5.20

**Comment by adrianbj** [comment]
Do you think it might be related to this ?
https://github.com/ryancramerdesign/ProcessWire/issues/947

ie because you have made changes in another browser tab?

**Comment by tbba** [comment]
yes correct, I see, this could be related. I very often have fields templates and pages open in the browser at the same time (mostly each in a safari browser tab) - which is a situation as you describe it too.
