### ISSUE TITLE
Hanna Code (Textformatter) Issue when checking for a field before output, it doesn't work

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#967]
If($page->body) echo $page->body; 

Hanna code won't work as it seems it's formatting the output twice? The hanna code is replaced, but with nothing at all. Took me while to figure what the problem was.

Also

echo $page->body ? $page->body : "";

Same effect.

$page->body;
echo $page->body;

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate here, but maybe it has something to do with what your specific HannaCode is doing. Can you export the code so I can import it? Worth mentioning though is that whenever you access a field like $page->body, it's going to run any assigned textformatters on it. So in your code examples above, yes Hanna Code (and any other text formatters applied) would run twice. But it starts from a non-formatted copy of $page->body on every call, so it shouldn't make any difference unless your code is going in and modifying something about the page. Hanna codes should return/output a value, but not modify anything.

**Comment by isellsoap** [comment]
@somatonic Can this issue be closed?

**Comment by isellsoap** [comment]
@somatonic I close this issue as it seems fixed or hasn’t had any reaction from you for months. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.
