### ISSUE TITLE
File upload lost when click on title after upload

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#971]
Upload a file, then click on its name in the title bar - this opens the file in the same browser window, thereby navigating away from the page - this results in loss of any unsaved changes. Soma's Form Save Reminder saves the day (functionality I think should be in the core), but I think this situation is unique in that the user probably doesn't expect to open the file directly in the same window - they might expect a modal, or a new tab, but not behavior that has potential data loss. Same goes for the View "tab", because it looks like a tab, but isn't!

**Comment by teppokoivula** [comment]
+1 to both parts (and one more "+1" to including something like Form Save Reminder in core -- a must-have module for all my/our sites). Anything that suddenly sends the user out of the edit view should either do it without any possibility of data loss (new tab/modal/whatever) or only after making sure that it's really a safe thing to do :)

**Comment by ryancramerdesign** [comment]
Ouch that link is supposed to have a target=_blank on it. Looks like it
never has! I will update.
