### ISSUE TITLE
open basedir restriction when renaming vhost

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#972]
Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/ ### old vhost name ### /httpdocs/wire/modules/System/SystemNotifications/SystemNotificationsConfig.php) is not within the allowed path(s): (/var/www/vhosts/ ### new vhost name ### /:/tmp/) in /var/www/vhosts/ ### new vhost name ### /httpdocs/wire/core/Modules.php on line 2145

workaround: uninstall and install again

pw 2.5.17

**Comment by BernhardBaumrock** [comment]
sorry, of course this is related to the new systemnotification module... could i have posted this issue directly there somehow?

**Comment by ryancramerdesign** [comment]
I think this might actually be an open basedir configuration error. If using open basedir, you likely need to add the directory that the web files live in (to your open basedir config). Otherwise, I'd expect to see this error pop up a lot more.
