### ISSUE TITLE
wire("users")->get(0); returns random pages.

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#973]
What's going on here?

I get an array back with id's like. 1|2|28|29|30|37|38|40|41|1061|1012|1001|

I noticed this when debugging something where there was a 0 given to the users get().

**Comment by ryancramerdesign** [comment]
Good find Soma. Looks like a cache array was finding it's way out the door there rather than the expected NullPage object. Fixed.
