### ISSUE TITLE
$form->get() does not find nested inputfields

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#975]
The title says it already. More on it in the forum thread:
https://processwire.com/talk/topic/7684-modify-form-object/?p=88926

**Comment by LostKobrakai** [comment]
Just to have this also updated. The error seems not to be specificly insertBefore, but the way it's handled for forms.

**Comment by LostKobrakai** [comment]
@ryancramerdesign could you please take a look at it, as FormBuilder is also affected by this. Every nested field in a form is not formatted in the entires list, because `$form->get($inputfieldKey)` does not find the inputfield, but return `null`.

**Comment by ryancramerdesign** [comment]
Just reading the thread you linked to, but not totally sure I understand. The thread seems to indicate the issue revolved around a fieldset not having a defined name attribute. But it also seems like Soma found a resolution? Or is there a bug here that needs to be fixed? Thanks.

**Comment by LostKobrakai** [comment]
There's no bug in ProcessWire, what I understand now thanks to soma.
But the issue in FormBuilder (which I though to be related) still exists: You're using `$form->get()` in `ProcessFormBuilder::buildListEntries`, but this does not find nested inputfields, so these nested fields aren't formatted for the entries list. It's working for my own lists with `$form->find()`.
