### ISSUE TITLE
Pre-packed CKEditor version does not function correctly on Safari

### ISSUE THREAD

**Issue by CaelanStewart** [ryancramerdesign/ProcessWire#976]
Hi,

There is a serious query selector bug in Safari 7.1+, that Apple have still not fixed (not even in 8.0.3). These versions of Safari use a version of webkit that first introduced this bug. This bug causes the cursor to move to the beginning of a line when the "Return" key is pressed. The expected behaviour would be for it to begin a new paragraph and move the cursor there.

I reference this support ticket from CKEditor:
http://dev.ckeditor.com/ticket/12423

The version this was fixed in is 4.4.5, the version pre-packed with PW is 4.4.3. I fixed this myself (for now) by upgrading the pre-packed version of CKEditor to 4.4.5 (not 4.4.7, as that broke the CKEditor module).

**Comment by ryancramerdesign** [comment]
This one was already fixed a few months back (available on dev branch). I figured it was a bug in CKE, didn't realize it was actually a bug in Safari.

**Comment by isellsoap** [comment]
@CaelanStewart Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!

**Comment by CaelanStewart** [comment]
@isellsoap, yes, the issue was fixed.
