### ISSUE TITLE
"Add New" button does not recognize unpublished parents

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#977]
I can't seem to get the add new page button to recognize unpublished pages. 

I have a structure that require to add child pages to a parent that is unpublished.

**Comment by ryancramerdesign** [comment]
Which add new button, the one in PageList or the one in Lister? I'm guessing PageList, so will test there first.

**Comment by somatonic** [comment]
No in the PageList.

**Comment by somatonic** [comment]
Any news on this yet? Have you tested?

**Comment by isellsoap** [comment]
@somatonic Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
