### ISSUE TITLE
2.5.21 "save + publish" does not publish

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#980]
message is "created page xy using template xy" but page is still unpublished

**Comment by somatonic** [comment]
Works fine here.

**Comment by BernhardBaumrock** [comment]
thanks soma, will check this...

**Comment by somatonic** [comment]
Any more details you can provide would be helpful. Thx

**Comment by BernhardBaumrock** [comment]
sorry for this - don't know where this came from! fresh installation works :)
