### ISSUE TITLE
Selector stopped working

### ISSUE THREAD

**Issue by phlppschrr** [ryancramerdesign/ProcessWire#981]
In my 2.5.8 installation I have this selector for finding all pages where at least one of the image fields is populated:
```$pages->find("parent='/filme', image2|image|images|poster_image!=");```
After upgrading to the latest dev the selector is not working anymore, I only get 1 page, before I had >500 pages.

The queried fields are all single image fields except 'images' which is multiple images.

**Comment by ryancramerdesign** [comment]
I think I tracked this one down and have pushed a fix. Can you confirm it resolves the issue? Also, when matching a count, it's usually preferable to either specify an actual count (like "0" in your case), and/or to use the "count" subfield, i.e. "image.count!=0". But for this particular field the selector you were using is valid, so no need to change it either (at least once it works).

**Comment by phlppschrr** [comment]
Thanks for your fast fix!
I can confirm that the issue is now resolved.
