### ISSUE TITLE
Latest dev: Getting notices relating to PageFinder.php

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#982]
introduced with commit 2a2dc672c6ff250495d248ff0e7d63b35ea309fb
Notice: Undefined variable: blankIsObject in /mypath/wire/core/PageFinder.php on line 752
Notice: Undefined variable: blankIsObject in /mypath/wire/core/PageFinder.php on line 788

**Comment by Da-Fecto** [comment]
Same here.

**Comment by Da-Fecto** [comment]
Thanks
