### ISSUE TITLE
Fatal error in Select image modal

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#983]
Running latest 2.5.21 run into a fatal error for the select image modal (CKEditor)

Notice: Undefined variable: btn in ###/wire/modules/Process/ProcessPageEditImageSelect/ProcessPageEditImageSelect.module on line 410

Fatal error: Call to a member function render() on a non-object in ###/wire/modules/Process/ProcessPageEditImageSelect/ProcessPageEditImageSelect.module on line 410

**Comment by ryancramerdesign** [comment]
Thanks, looks like it just occurs on pages that have no image fields assigned. I just pushed a fix. Usually my IDE flags undefined variables, not sure why it's missed two today (and still doesn't see them). Time for a reboot!

**Comment by Da-Fecto** [comment]
> looks like it just occurs on pages that have no image fields assigned

You must have fixed something else to as I had the error with and without image fields on the template.

**Comment by ryancramerdesign** [comment]
It was working for Adrian and me at least. :) Glad it seems to be resolved over there too.
