### ISSUE TITLE
url sanitize -> umlaut?

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#984]
wanted to save a domain with umlaut to an URL field and got an "check that url is valid" error.

it seems that sanitizer does not allow german umlauts in urls?
https://github.com/ryancramerdesign/ProcessWire/blob/7b9730d43e6eda8bd27841a4811a1b9737bfe903/wire/core/Sanitizer.php#L455

**Comment by plauclair** [comment]
Right now urls need to be ascii characters only. Umlauts are beyond this scope unfortunately.

**Comment by BernhardBaumrock** [comment]
yes, but i think thats a real concern - IDNs are approved since ~2010...
http://en.wikipedia.org/wiki/Internationalized_domain_name

why not edit the current regex or use dns_lookup to accept IDNs?
https://www.safaribooksonline.com/library/view/regular-expressions-cookbook/9781449327453/ch08s15.html
http://stackoverflow.com/questions/14313849/how-to-validate-internationalized-domain-names

**Comment by horst-n** [comment]
I think the answer is given in the SO thread you linked to:

```
By specification, **literally every character in the UTF-8 character set is valid** to use in a IDN domain, but every top level domain authority can define valid characters within the Unicode charset so it will be hard to create and maintain a real regex.

If you want to accept IDN domains in your application **you should internally work with the encoded version**. PHP extension intl brings two functions to en- and decode IDN domain names

echo idn_to_ascii('täst.de');  // =>    xn--tst-qla.de  // After encoding, the domain should pass any traditional regex check
echo idn_to_utf8('xn--tst-qla.de');  // =>  täst.de
```
I think you need to handle IDN's with a wrapper of those two PHP functions to convert them force and back.

**Comment by BernhardBaumrock** [comment]
yes - but shouldn't that be built in? are there any drawbacks with this?

**Comment by teppokoivula** [comment]
We've had problems with this before, so if you ask me, yes -- this definitely needs to be addressed. Such requests still seem  rare, though, so it's unlikely to be addressed with very high priority.

**Comment by plauclair** [comment]
There are some other limitations regarding internationalization and localization, here's a thread mentioning some improvements that could be done. https://processwire.com/talk/topic/8921-true-multilingual-urls/

I might invest some time improving some of these, my biggest fear is that right now there is no full-on testing suite for PW, and I don't have much time to do proper testing of all the parts this might interact with. Making those changes in dev might mean a (few) pretty unstable release(s) until bugs are ironed out… AFAIK multibyte strings in PHP aren't all that straightforward.

**Comment by adrianbj** [comment]
Sounds like today's commit PW 3.0.12 takes care of this:
https://github.com/ryancramerdesign/ProcessWire/commit/1f60e9942ca52cb025c7fffcbf05d6179aa59b1b

**Comment by plauclair** [comment]
@BernhardBaumrock please close this issue. Thanks! :)
