### ISSUE TITLE
[2.5.20] Unable to delete images

### ISSUE THREAD

**Issue by mike-anthony** [ryancramerdesign/ProcessWire#985]
It seems that one of my installations is unable to delete images. I have a field called `book_covers`, and I've set it to show thumbnails in a grid on the admin panel.

If I delete an image from the array and then save, the image comes back.

Have also tried deleting all variations, and then deleting the image, but no go...

**Comment by mike-anthony** [comment]
I'm assuming this has something to do with the Version Control module? No?

**Comment by mike-anthony** [comment]
**Screencast:** http://ge.tt/2QryscB2

**Comment by ryancramerdesign** [comment]
I can't duplicate here, but I am running 2.5.21. You might want to try to
upgrade to that just in case. Seems like there was some image deleting
issue for a few hours in one of the recent dev versions, but I don't
remember how recent that was. But upgrading to the latest would be the
first thing to try.

**Comment by mike-anthony** [comment]
Ah right - that did it. Thought I was already on the latest, but that was another site (too many local installs of PW :wink:)

Turns out I was actually on .19 - hehe!

Thanks Ryan. :+1:
