### ISSUE TITLE
Browser gets blocked when $config->pagefileSecure = true

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#987]
Test scenario:
- /site/config.php: `$config->pagefileSecure = true`
- set up a template with links to some larger files 

If one of the links is clicked, the browser gets blocked. If you click on another link, the browser waits until download of the first file has finished. This is a killer for me, because I'm building an intranet at present...

Solution proposal: in /wire/modules/Process/ProcessPageView.module the secured pagefile gets handled. In line 551 the file is sent to the browser: `wireSendFile($filename, $options); `

Before that line, add `session_write_close();`
Reason: see https://processwire.com/talk/topic/4602-flexible-downloads-using-pages/?p=79128

**Comment by teppokoivula** [comment]
For the record: the use of word "blocked" here confused the heck out of me. Perhaps it's just me, but I thought it meant that an user without access to said template gets *blocked from downloading a secure file*.

After taking a closer look at the linked thread, this sounds like a no-brainer -- definitely worth adding, if there really are no harmful side-effects :)

**Comment by ryancramerdesign** [comment]
Sounds like a good update to me. Just wondering though: why not put it in wireSendFile()? I'm adding it to the top of that function, unless there's a reason to put it in ProcessPageView instead? Seems like it would be just as useful in other situations where wireSendFile is used.

**Comment by isellsoap** [comment]
@processwired Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!
