### ISSUE TITLE
No official 2.5 release

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#997]
Been meaning to mention this for a while. Might be too late to add it now, but it's weird that the last release is still 2.4

https://github.com/ryancramerdesign/ProcessWire/releases

**Comment by ryancramerdesign** [comment]
Actually our official website is processwire.com and you can find official
releases there. :) of course we love and use github for a lot of things but
its not our official site or authority of releases. Good point though, I'll
try to do better with the tags.
