### ISSUE TITLE
New Insert Link tools not working in CKEditor

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#998]
I'm trying out the new Insert Link functionality and the classes and the custom classes, target, and rel options are not taking when I click "Insert Link". I tried turning off ACF but that didn't seem to make a difference.

This is on an install that I did an upgrade on. I'm not sure if this could be a bug or just some setting/module that may be conflicting, but I'm not sure where to look first.

**Comment by LostKobrakai** [comment]
Did you try to refresh the modules and/or restart the browser to force a cache clear?

**Comment by thetuningspoon** [comment]
Did a refresh and tried it out again this morning--everything is a-ok. So, not a bug, although it might be good if there were some way to run the refresh automatically after an update so this issue doesn't come up. Anyway, thanks for the suggestion, LostKobrakai.
